### ISSUE TITLE
Adcolony ClearText error in google play console

### ISSUE THREAD

**Issue by umiringo** [AppLovin/AppLovin-MAX-Unity-Plugin#100]
Hi, team

I tried to integrate adcolony by MAX. But after I uploaded the apk to google play console, it shows error in pre-launch report, which says 
**Cleartext traffic allowed for all domain.**

That is because when I integrate adcolony, it required add clear text for all domains in applovin documents.

I searched about this error, it may cause some nagative effect to my game. Then I checked the document of other mediation platforms.
In Ironsource document, it only require clear text for 127.0.0.1, but when I set clear text in 127.0.01, in applovin test suite, it shows invalid intergration of adcolony, and show no ads.

May I know if I MUST add clear text for all domains if I want to integate adcolony by MAX? or is there any update to solve this issue?

Thank you!

**Comment by thomasmso** [comment]
It's not required anymore - but if you enable test ads for AdColony, it will still show an error. Their team is working to fix that, before we update our documentation.
