### ISSUE TITLE
 Vungle platform advertising issues

### ISSUE THREAD

**Issue by zhang00lei** [AppLovin/AppLovin-MAX-Unity-Plugin#105]
When watching an ad on the vungle platform, the ad was successfully played but no successful event (OnAdReceivedRewardEvent) was received, but everything was normal on other ad platforms.
How to solve this...

**Comment by zhang00lei** [comment]
max sdk version:4.3.12
Vungle version:android_6.10.3.0

**Comment by NanaAmoah** [comment]
Hi @zhang00lei, please note that according to Vungle's docs, the rewarded ad needs to be completed for the `OnAdReceivedRewardEvent` to be fired.
Could you please send us the [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) while playing a Vungle ad so I can investigate further?

**Comment by zhang00lei** [comment]
@NanaAmoah 
Sorry, I haven't pulled ads on the vungle platform for a long time. I will send you the detailed log next time I encounter this problem

**Comment by thomasmso** [comment]
@zhang00lei - Multiple people on our team were not able to reproduce this issue - we suspect it is a temporary issue with Vungle, or you are not getting rewards due to fraud prevention. If it occurs again, you should report it to Vungle as they should have more info. Thanks!

**Comment by zhang00lei** [comment]
OK,thanks
