### ISSUE TITLE
The ad click event did not call back in time

### ISSUE THREAD

**Issue by sundxing** [AppLovin/AppLovin-MAX-Unity-Plugin#107]
Unity will pause after the full-screen ad is displayed, and will not receive the event until UnityPlayerActivity returns to the foreground. We want to get all ad events in time, any solutions?

**Comment by thomasmso** [comment]
Hi. We're actually going to move towards the industry-standard of pausing Unity even on iOS (as right now it's only paused on Android) - that is what is most requested by clients at the moment.

**Comment by sundxing** [comment]
Thanks for your prompt reply @thomasmso, the behavior of pausing Unity on Android is expected, but the ad event can be called back to the child thread in some ways in real time. The result of `UnitySendMessage` is only triggered when UnityPlayerActivity resumes.  I looked through the Unity documentation,  `AndroidJavaProxy` my be a solution. [AndroidJavaProxy-Doc](https://docs.unity3d.com/Manual/AndroidUnityPlayerActivity.html)

**Comment by thomasmso** [comment]
Agreed on the `AndroidJavaProxy` part - we're actually going to be using that for the [ad revenue callback](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#impression-level-user-revenue-api). But as for the other callbacks, we will consider updating it when we receive more requests.

**Comment by sundxing** [comment]
Ok, thanks so much

**Comment by dingmingxin** [comment]
Also expecting more information to be exposed in ad event callbacks 🙏 , such as ad-click-timestamp, load-impression-duration, impression-click-duration.

**Comment by thomasmso** [comment]
As there are numerous feature requests everyday, adding support for passing ad-click timestamp and impression click duration will depend on the requests received. But I figure if we receive enough requests, we'll just go with using `AndroidJavaProxy` and fire these callbacks in realtime.

Load impression duration will have an API in the next release, you will be able to track the load latency of every ad in the waterfall, and for each ad that failed to load - the reason why (from the actual mediated SDK).

**Comment by dingmingxin** [comment]
Thanks for the prompt reply.
Whether using `AndroidJavaProxy` or not, more informations are expected for analyzing.
By the way,  `AndroidJavaProxy ` is a better approach in my opinion.

**Comment by sundxing** [comment]
Hi, sorry to bother you again, another problem, i want to change Android plugin of unity to get ad events timely, but there is no source code here. I checked  my project, and found iOS plugin is integrated through the source code but not the Android plugin, where to get source code of the Android plugin?

**Comment by thomasmso** [comment]
We distribute the Android bridge as a JAR, no plans to update to source since that would require project cleanup for backwards compatibility.

**Comment by hgeg** [comment]
Hello, I know it has been a while, but is there a change or improvement about this issue? `OnAdDisplayedEvent` for both rewarded ads and interstitials are seemingly triggered simultaneously with `OnAdReceivedRewardEvent` or `OnAdHiddenEvent`, right after the ad is disappeared. I read maybe a native android plugin can be a solution. Is there a straightforward way to trigger display events in a timely manner yet? If not is there a workaround you suggest?
