### ISSUE TITLE
Failed to download file from SafeDK server

### ISSUE THREAD

**Issue by anjasnewbie** [AppLovin/AppLovin-MAX-Unity-Plugin#108]
Hello

During build to apk I got error like this
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[SafeDK-ERROR] Failed to download file from SafeDK server, Exception: Failed to download file /Users/jaya/unity/ra/Temp/gradleOut/.safedk/list.enc, Reason: Read timed out
```
I'm able to download package from unity package manager, so I don't think this is related to my internet connection.
any advice how can I troubleshoot this ?
thank you

**Comment by orilentz** [comment]
Hey,

The message suggests it's failing to download the file from here - http://download.safedk.com/android/prod/list.enc

Could you check in the exported Unity project, if you have the file list.enc under the .safedk directory of your project? If not, can you check if the above link is working for you? If so, you can just place the file in the .safedk directory and it should bypass the error.

**Comment by anjasnewbie** [comment]
thank you for your help
now the issue is gone.
thanks

**Comment by gotokanwal** [comment]
I also got this issue . build failed with error
Failed to download file from server
