### ISSUE TITLE
How to get currecy code in maxsdk ?

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#109]
There is a line in the demo project :
```
var countryCode =
                MaxSdk.GetSdkConfiguration()
                    .CountryCode; // "US" for the United States, etc - Note: Do not confuse this with currency code which is "USD" in most cases!
```
you mentioned "in most cases" but there is no documentation on how to find the correct currency code? ( I need it for analytics events)

**Comment by thomasmso** [comment]
It actually will be "USD" in all cases. We'll update the docs and demo apps to reflect that.
