### ISSUE TITLE
Android kill the game on low memory devices after watching ads

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#112]
On a device with a small amount of memory ,sometimes after watching ads, android kills the game. 
(By low memory I mean 2gb of memory)
Then the game restart from scratch, It's probably related to two things : 
1_ I think playable ads use a lot of memory, and probably it's better if Max SDK does not show playable advertisements on low memory devices  ( or have an API to let the developer disable them )
2_ The way you pause the game before showing ads is probably cause this issue, I think one way to fix this is to show games in the notification section of the device during the advertisement ( Because with this approach Android probably doesn't kill it )

**Comment by santoshbagadi** [comment]
Hi @uchar , 
For 1. We are actively working on improving the performance on low memory devices by limiting the type of ads we show on these devices.
For 2. I think showing the ad on top of the game content might make it more resource intensive since Android is trying to keep the game content alive while the ad is being show.

**Comment by uchar** [comment]
for 2, what I mean was running some process as [foreground service](https://developer.android.com/guide/components/foreground-services), so that android doesn't kill them, I don't think it's related to being resource-intensive because you can still pause the unity game loop

**Comment by santoshbagadi** [comment]
We will look into in but for now we are focusing on solving this by improving the they of ads we serve on low memory devices.
