### ISSUE TITLE
Constructor on type 'MaxSdkBase+MediatedNetworkInfo' not found

### ISSUE THREAD

**Issue by sundxing** [AppLovin/AppLovin-MAX-Unity-Plugin#115]
Hi, i got a problem here, when i call `MaxSdk.GetAvailableMediatedNetworks`, got error:
`MissingMethodException: Constructor on type 'MaxSdkBase+MediatedNetworkInfo' not found.
`
I suspect it has something to do with code optimization.

**The code i use:**
```
    MaxSdkCallbacks.OnSdkInitializedEvent += (MaxSdkBase.SdkConfiguration sdkConfiguration) =>
    {
        // AppLovin SDK is initialized, start loading ads
        var networks = MaxSdk.GetAvailableMediatedNetworks();
        ...
    };
```

**Unity version** : 2018.4.36
**AppLovin Max plugin version** : 4.3.12

**Comment by ritamsarmah** [comment]
Hi @sundxing, would you mind sharing the Android and iOS SDK versions you are using, as well as the mediated networks you have installed?

**Comment by sundxing** [comment]
Ok
![Screen Shot 2022-01-07 at 10 38 40 AM](https://user-images.githubusercontent.com/7501153/148483690-4fb9d2fd-99d1-4c40-9839-63f2ccee3585.png)


![Screen Shot 2022-01-07 at 10 38 16 AM](https://user-images.githubusercontent.com/7501153/148482659-5651b251-cfce-4f42-8f2d-5a70b037789c.png)

**Comment by ritamsarmah** [comment]
Thanks @sundxing, we're looking into it and will update on whether we can reproduce the issue

**Comment by ritamsarmah** [comment]
Hi @sundxing, we weren't able to reproduce the issue using the same Unity and plugin versions. Could you try upgrading to Unity Plugin 5.0.1 (as well as any outdated adapters)? The newer plugin includes stability improvements that may relate to this issue with `GetAvailableMediatedNetworks`
