### ISSUE TITLE
Ads not showing on user devices

### ISSUE THREAD

**Issue by alexisdavidson** [AppLovin/AppLovin-MAX-Unity-Plugin#123]
Hi, the SDK and all was successfully implemented and the test ads work as expected on my test device.

However, friends of mine downloaded the game and no ads are showing on their device. When I remove my device from the test devices, I still get the test ads shown so I cannot debug myself and see the logs.

Any idea how to proceed?

Thank you

**Comment by joeapplovin** [comment]
Hi @alexisdavidson - are you able to see live ads via this mediation debugger [feature](https://dash.applovin.com/documentation/mediation/unity/testing-networks/mediation-debugger#testing-with-live-ads)?  You can also enable [test mode](https://dash.applovin.com/documentation/mediation/unity/testing-networks/test-mode#max-test-mode) to see verbose logs from the device.

**Comment by alexisdavidson** [comment]
Hi @joeapplovin even though I paused the test mode of my device / tried to change the GAID, my device still seem to be in test mode. I get the message "Please restart the app and make sure the GAID has not been enabled for test mode..."

**Comment by alexisdavidson** [comment]
My bad, I was manually adding my device for test mode in the code ^^' The live ads seem to be working.
I will do more tests once the app is live on the play store but it looks promising. 

Thank you for the help!
