### ISSUE TITLE
MaxSdkCallbacks has been destroyed but you are still trying to access it

### ISSUE THREAD

**Issue by Marefo** [AppLovin/AppLovin-MAX-Unity-Plugin#124]
On first play mode after start unity everything ok MaxSdkCallbacks spawns, but after exit play mode and on new enter, it doesn't spawn and unity shows
Error: 
```
MissingReferenceException: The object of type 'MaxSdkCallbacks' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.MonoBehaviour.StartCoroutine (System.Collections.IEnumerator routine) (at <a555715ef291462eb190c2c939543f55>:0)
MaxSdkUnityEditor.ExecuteWithDelay (System.Single seconds, System.Action action) (at Assets/MaxSdk/Scripts/MaxSdkUnityEditor.cs:1230)
MaxSdkUnityEditor.InitializeSdk (System.String[] adUnitIds) (at Assets/MaxSdk/Scripts/MaxSdkUnityEditor.cs:75)
AdsController.Start () (at Assets/Scripts/GamePlay/Controllers/AdsController.cs:22)
```
If reload unity, everything repeat.

**Comment by santoshbagadi** [comment]
Hi @Marefo , do you by any chance have an experimental setting in Unity `Enter Play Mode` enabled? Our plugin currently doesn't support that setting and we are still investigation how we can accommodate this settings. In the mean time do you mind disabling that setting and see if that fixes the issue?

**Comment by Marefo** [comment]
Oh, sure. Thanks, it just solved my problem)
