### ISSUE TITLE
Low revenue

### ISSUE THREAD

**Issue by alexisdavidson** [AppLovin/AppLovin-MAX-Unity-Plugin#125]
Hi,
I successfully implemented MAX Mediation in my Android game. I launched the game yesterday on the market and finally could analyze the performance. To my surprise, I am seeing very low revenue. I used to have WAY higher revenue when using Google Ad Mobs along with the same mediation networks.

Any idea what is going on ?

Best regards,

**Comment by joeapplovin** [comment]
Hi @alexisdavidson - if you go to the [revenue reporting](https://dash.applovin.com/documentation/mediation/max/analyze) tab, do you see the difference in revenue concentrated in a particular network?  Also, it'd be helpful to confirm the networks are all [activated](https://dash.applovin.com/documentation/mediation/max/enable-networks) under the status column.

**Comment by alexisdavidson** [comment]
Hi @joeapplovin - the revenue seems to be split between AppLovin Bidding and Facebook Bidding (~10$ ecPM) mostly. There is also AppLovin Exchange that is actually taking most of the impressions but has an extremely low eCPM (~0.50$ eCPM) in comparison to the bidding networks. Is there a way to prioritize the Bidding networks maybe?

I confirm that all networks are activated under the status column.

**Comment by joeapplovin** [comment]
Thanks for the context @alexisdavidson .  Can you please fill out [this form](https://try.applovin.com/mopub-max-integration) with your account information, and someone on our partner support team will work with you to optimize your waterfall?
