### ISSUE TITLE
Max SDK only fetching ads through Mintegral network even if adapter is not installed

### ISSUE THREAD

**Issue by devSyed72** [AppLovin/AppLovin-MAX-Unity-Plugin#126]
I am using latest applovin max sdk for unity in unity 2020, after building, my log shows that max only fetches/loads ads from mintegral network, however i have not added mintegral in project or max dashboard. i have added unity ads,google admob ads only but it only goes for mintegral. i dont want mintegral network. Pleas help

**Comment by santoshbagadi** [comment]
Hi, could you please share the `unityLibrary/build.gradle` file (or your `mainTemplate.gradle` file if you are using Gradle templates) of your exported Android studio project.

Also, could you share more details on how you determine if an ad is from Mintegral or otherwise.

**Comment by devSyed72** [comment]
Hi, thanks for your kind response. I figured it out actually, i was testing
on a test device which had testing mode to mintegral selected, thats why
only mintegral was caching even i didnt add mintegral adapter in project.
Thanks again.
