### ISSUE TITLE
Build error. GAMaxIntegration.cs. The type or namespace name 'MaxSdkBase' could not be found.

### ISSUE THREAD

**Issue by DmitryKotusev** [AppLovin/AppLovin-MAX-Unity-Plugin#129]
Hi, when trying to build on Android on Unity 2021.12.f1 I get the following error almost immediately:

![Снимок экрана 2022-01-29 191925](https://user-images.githubusercontent.com/26222535/151672864-ecd29fdb-df00-42b8-93f3-a5ce2ef2f3af.png)

My settings:

![Снимок экрана 2022-01-29 192246](https://user-images.githubusercontent.com/26222535/151672862-b5469f62-4a07-461a-acac-f7d8967a95e9.png)

![Снимок экрана 2022-01-29 192157](https://user-images.githubusercontent.com/26222535/151672863-bb38c1b0-7e04-48a9-9c4f-a247fd3c0d99.png)

![Снимок экрана 2022-01-29 192313](https://user-images.githubusercontent.com/26222535/151672867-90370376-b40f-4576-8290-5288a3a63611.png)

Don't know what to do actually...

**Comment by chauduyphanvu** [comment]
@DmitryKotusev, have you tried to [force resolve dependencies](https://github.com/googlesamples/unity-jar-resolver#auto-resolution) in the External Dependency Manager?

Vu Chau
AppLovin Team

**Comment by DmitryKotusev** [comment]
@chauduyphanvu, yeap, didn't work. It seems like GAMaxIntegration.cs script doesn't see MaxSdkBase class because of some reason.

**Comment by DmitryKotusev** [comment]
![Снимок экрана 2022-01-30 220333](https://user-images.githubusercontent.com/26222535/151717753-cb3379d6-15f0-4f07-90ac-385767af7a7a.png)

Seems like this is the place where the mistake occurs.

**Comment by chauduyphanvu** [comment]
@chauduyphanvu - thanks for the confirmation. 

Has anything changed in your environment/integration after you upgraded to v5.1.0 (11.1.0)? Could you show your imports/using block in the class with the issue?

**Comment by DmitryKotusev** [comment]
@chauduyphanvu, the version v5.1.0 (11.1.0) was the one I started with. The class above is the class from the library folder.

**Comment by DmitryKotusev** [comment]
And it seems like after updating the project to Unity 2021.1.24f1 the compiler error described above dissappeared.

**Comment by chauduyphanvu** [comment]
@DmitryKotusev - thanks for the update! Well, sounds like you got it resolved. Let us know if you encounter it again.
