### ISSUE TITLE
No visible @interface for 'MAAdView' declares the selector 'initWithAdUnitIdentifier:adFormat:sdk:'

### ISSUE THREAD

**Issue by gevorgyanmp** [AppLovin/AppLovin-MAX-Unity-Plugin#13]
Hi. We have upgrade our AppLovin MAX Unity sdk version to "2.3.3" and ios version to "6.11.5".
After this upgrade we started to get this error in ios Xcode build process.
Unity version - 2018.4.18f1

ARC Semantic Issue Group
~/Libraries/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.m:686:36: 
No visible @interface for 'MAAdView' declares the selector 'initWithAdUnitIdentifier:adFormat:sdk:'

**Comment by mehmetuysal** [comment]
Same problem here with the latest version

**Comment by thomasmso** [comment]
Hey guys, it was a bad push that was live for around 6hrs, we've resolved it in the latest MAX Unity Plugin 2.3.4.
