### ISSUE TITLE
Banner Ad not showing up on device, in test mode.

### ISSUE THREAD

**Issue by NomanAliKhokhar** [AppLovin/AppLovin-MAX-Unity-Plugin#130]
I'm having 2 issues.
1- banner ad not showing up in testing on deices, only the black panel is showing up.
2- API not returing the accurate banner height, due to which banner ad (Balck panel for which is showing up) overlaps the content.

What should I do?

**Comment by santoshbagadi** [comment]
Hi @NomanAliKhokhar ,

1. Are you getting any banner ad loaded/failed to load callbacks. If so, could you please share the full [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) when the banner ad is not showing up.
2. For banner height issue, what API are you using specifically?

**Comment by NomanAliKhokhar** [comment]
"Are you getting any banner ad loaded/failed to load callbacks. If so, could you please share the full verbose logs when the banner ad is not showing up."
[Verbose_Logs.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/7979797/Verbose_Logs.txt)

"For banner height issue, what API are you using specifically"
MaxSdkUtils.GetAdaptiveBannerHeight()
This is the method I use to get the height of the banner.

I thing banner height will resolve by itself once the banner will start working.

**Comment by NomanAliKhokhar** [comment]
I could be possible that Banner might be loaded successfully, but believe me it never showed up, not even once.
It is all-most a week since i'm trying to get banner to work.

I tried with both TESTMODE ENABLED/DISABLED.

but it is remains the same.

Is there any LOG entry in "Verbose_Logs", which confirm that the banner is successfully shown to the user, becasue I never seen one.

**Comment by NomanAliKhokhar** [comment]
I did manage to make the banner ad work.

But I still have some question.

https://user-images.githubusercontent.com/66634108/152198040-29ff0d32-0161-4f94-afae-a48d1bea2d08.mp4


Please have a look at the video.

a- 00:00 to  00:16 sec you can see that the black pannel shows up at the bottom center but no banner ad is showing, I tried multiple times as you can see in the video.
    1- Suppose if there is no fill rate then why black pannel showing up? It should also be disabled.
    2- Becasue if the banner is not avalible and BLACK PANEL showing up, then MaxSdkUtils.GetAdaptiveBannerHeight() will also return the wrong height, due to which the game UI can't be adjusted acurately and BLACK PANEL will overlay the UI.
     ​
​b- Once I enable the TEST Mode from the MEDIATION DUBUGGER restarted the app then banner ad start showing up. Why is that?

So, I'm not sure why the banner ad start working normally, when the test mode is active and not the other way around.

Also tell me when should I know that all ads are working correctly, should I them whith TEST MODE ENABLE ?
Or just add my testing device to the ApplovIn Platform and just test normally?

**Comment by santoshbagadi** [comment]
a-1: The banner background color can be set by calling `MaxSdk.SetBannerBackgroundColor(adUnitId, Color)`. To not show the background, you can simply choose to not call this API or set it to a transparent color.
a-2: Could you please share the height values returned before and after the banner ad is loaded. It should be the same height before and after a banner ad is loded.

b: From the mediation debugger in the recording, `Tracking Authorization Status` is `Not Determined` which means our SDK does not have a way to detect the IDFA of the device. So, enabling test mode from our dashboard wouldn't work but since enabling test mode on Mediation Debugger is done on the client side, you are able to get test ads.

Please check out our [Privacy](https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy) and [Consent Flow](https://dash.applovin.com/documentation/mediation/unity/getting-started/consent-flow) to get more information on how [`App Tracking Transparency`](https://developer.apple.com/documentation/apptrackingtransparency).

**Comment by NomanAliKhokhar** [comment]
a-1: If the BANNER ad is loaded or not loaded MaxSdkUtils.GetAdaptiveBannerHeight() always return 50. and I belive the actual banner is 3 times what MaxSdkUtils.GetAdaptiveBannerHeight() returns. 
I think the banner height also varies on differnt devices, Is that right?

so, How can I get the exact banner height? for multiple devices?

**Comment by santoshbagadi** [comment]
Hi, the `MaxSdkUtils.GetAdaptiveBannerHeight()` returns height in points (not pixels) which might explain why you are seeing that difference. You may need to convert to pixels to use it.

Also, adaptive banners are sized differently based on device, and you can get that height by calling `MaxSdkUtils.GetAdaptiveBannerHeight()` and adjust your UI accordingly. If you wish to have fixed height across all devices, please check out our docs on how you can disable [Adaptive Banners](https://dash.applovin.com/documentation/mediation/unity/getting-started/banners#adaptive-banners).

**Comment by NomanAliKhokhar** [comment]
Thank you so much for your support.
we really appreciate it.

**Comment by jeuxdaily** [comment]
hi
I have a problem in Adobe Air
Interstitial Show Good
But The banner Only show background-color

**Comment by thomasmso** [comment]
@jeuxdaily - Could you file issue [here](https://github.com/AppLovin/AppLovin-MAX-AIR)?

**Comment by jeuxdaily** [comment]
Thank you
Actually follow this example
But the ads banner alone did not appear

**Comment by santoshbagadi** [comment]
@jeuxdaily , do you mind [enabling verbose logs](https://dash.applovin.com/documentation/mediation/adobe-air/getting-started/advanced-settings#enable-verbose-logging) and send us the logs for the session.

**Comment by santoshbagadi** [comment]
@jeuxdaily mind sharing verbose logs so that we can further investigate.

**Comment by jeuxdaily** [comment]
> @jeuxdaily mind sharing verbose logs so that we can further investigate.

how can I share it

can I put my code here

**Comment by santoshbagadi** [comment]
Yeah, you can share it as a file here, or you can just send it to my email: santosh.bagadi@applovin.com

**Comment by seyitbursa** [comment]
Hi @santoshbagadi,

Can you share a script for calculating bottom banner height for multiple devices? I am using the formula px = dp * (Screen.dpi / 160), but it doesn't work for all devices.

**Comment by santoshbagadi** [comment]
@seyitbursa , if you are referring to the adaptive banner height, you can retrieve it using the `MaxSdkUtils. GetAdaptiveBannerHeight()` API. 

For non-adaptive banners, the height would be 50dp on Android and 50 points on iOS.

**Comment by santoshbagadi** [comment]
We have another method to get the screen density (`MaxSdkUtils.GetScreenDensity()`). You can get the pixel values by this with the dp values as below
```
var heightDp = MaxSdkUtils.GetAdaptiveBannerHeight();
var density = MaxSdkUtils.GetScreenDensity();
var heightPx = heightDp * density;
```

**Comment by seyitbursa** [comment]
Hi again @santoshbagadi ,

I added two screenshots from the game. In the first screenshot you can see the real banner with yellow background. In the second one I added a black panel on an overlay canvas(same as the BannerBottom prefab in sdk) with height calculated according to formula you wrote in the previous message. As you can see there is a difference between the real banner size and the calculated one. Do you have any idea about this?

Device : Xiaomi Redmi Note 8 
Density: 2.75
Adaptive Banner Height: 61


![1677576083651](https://user-images.githubusercontent.com/78257045/221825479-aac6fb8f-b798-41ac-bf3b-94251359bb2b.jpg)
![1677576083661](https://user-images.githubusercontent.com/78257045/221825493-2a3c2fd2-476a-4bf9-94bf-aaede4a734c6.jpg)

**Comment by laststare** [comment]
Hello, why i got 68 point in debug apk and 50 point in release apk on calling  MaxSdkUtils.GetAdaptiveBannerHeight() ?
