### ISSUE TITLE
Gradle Built Failed After Adding Mediation Network

### ISSUE THREAD

**Issue by AbdulDS-JP** [AppLovin/AppLovin-MAX-Unity-Plugin#131]
Hey there,  I am using unity 2020.3.25f1 with all default SDK/NDK/JDK and gradle. I am encountering an error on built after i add on mediated network of ADMOB and Unity Ads. Here are the errors. 

![Capture](https://user-images.githubusercontent.com/93519753/151966760-dac1c38e-b140-4135-90d6-b7b1246b488f.PNG)

**Comment by santoshbagadi** [comment]
Hi @AbdulDS-JP , could you please share the full error message from console. It seems like some issue with Gradle/Android build cache. Maybe you could try to clear gradle cache and build again.

**Comment by AbdulDS-JP** [comment]
Thank you, this resolves my error. But now MAXSDK has issue with Game analytics. One of plugin named as appset in Game analytics has conflict with appset in MaxSdk, which produces duplication error. 
FILE NAMES>>
      GAME ANALYTICS (play-services-appset-16.0.1)
      MAX SDK (com.google.android.gms.play-services-appset-16.0.0)
How can i get rid of this?

**Comment by santoshbagadi** [comment]
@AbdulDS-JP , MAX SDK does not have a direct dependency on `play-services-appset` (maybe it is coming from another network SDK?).

Google External Dependency Manager should automatically resolve this (unless GAME ANALYTICS is manually adding the aar, in which case you can delete it and let External Dependency Manager pull in the dependency).
