### ISSUE TITLE
Callbacks not working correctly, only one invocation allowed

### ISSUE THREAD

**Issue by PaXLiCh** [AppLovin/AppLovin-MAX-Unity-Plugin#133]
From demo app, if this called once, invocations works properly
`
            // Attach callbacks
            MaxSdkCallbacks.Rewarded.OnAdLoadedEvent += OnRewardedAdLoadedEvent;
            MaxSdkCallbacks.Rewarded.OnAdLoadFailedEvent += OnRewardedAdLoadFailedEvent;
            MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent += OnRewardedAdFailedToDisplayEvent;
            MaxSdkCallbacks.Rewarded.OnAdDisplayedEvent += OnRewardedAdDisplayedEvent;
            MaxSdkCallbacks.Rewarded.OnAdClickedEvent += OnRewardedAdClickedEvent;
            MaxSdkCallbacks.Rewarded.OnAdHiddenEvent += OnRewardedAdDismissedEvent;
            MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent += OnRewardedAdReceivedRewardEvent;
            MaxSdkCallbacks.Rewarded.OnAdRevenuePaidEvent += OnRewardedAdRevenuePaidEvent;
`
But if add more subscriptions in another class, only first invocation will be called, and second subscribed methods from new class will never be called. It makes some problems for controlling behaviour of ads (for example controller for displaying ads and another place to debug).

**Comment by chauduyphanvu** [comment]
@PaXLiCh, have you tried first unsubscribing from the events before re-subscribing to them?

```cs
MaxSdkCallbacks.RewardedInterstitial.OnAdLoadedEvent -= OnRewardedInterstitialAdLoadedEvent
...
```

Vu Chau
AppLovin Team

**Comment by PaXLiCh** [comment]
Of course no. I just want to subscribe multiple methods to event. All subscriptions needed to work.
