### ISSUE TITLE
Unity Ads causes error 5209 DURING its own playback

### ISSUE THREAD

**Issue by PaXLiCh** [AppLovin/AppLovin-MAX-Unity-Plugin#134]
We trying to show "rewarded ad", but got error during attempt to display and ad playback anyway started after error.
What we found in logs:
Rewarded : load started with `MaxSdk.LoadRewardedAd`
Rewarded : load finished 'Unity Ads', fired `MaxSdkCallbacks.Rewarded.OnAdLoadedEvent`
<after 5 seconds we trying to show ad>
Rewarded : show attempt 'Unity Ads' with `MaxSdk.ShowRewardedAd`
<fullscreen ad playback started, we suspend audio in our app>
<after 5 seconds got event `MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent`>
Rewarded : show 'Unity Ads' failed with error code: -5209, message: Internal Error
At this event we started loading of new rewarded ad, resumed sound, BUT AD STILL PLAYING.
After closing fullscreen ad, event `MaxSdkCallbacks.Rewarded.OnAdHiddenEvent` was not fired

And this may happens periodically.

**Comment by PaXLiCh** [comment]
@chauduyphanvu we trying to get complete logs, not only from our app, what is `Charles sessions`?

**Comment by chauduyphanvu** [comment]
@PaXLiCh - it's a [Charles Proxy](https://www.charlesproxy.com/) session to intercept network traffic. It contains information pertaining to the ads being requested and played.

Feel free to email me at vu.chau@applovin.com.

**Comment by chauduyphanvu** [comment]
We're speaking with Unity about this issue. They are aware of it.

**Comment by chauduyphanvu** [comment]
@PaXLiCh, Unity Ads has confirmed that they have pushed out a fix with the latest SDK (4.0.1). We've released the certified adapters yesterday ([Android](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/60bbae23eb6f670c7b84693bc794506da713ffef) / [iOS](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/commit/8c270fb1f59faf805d65bbdd1be50ae6ea141fbf)). Check it out and let us know if the issue persists. 

Thank you.
