### ISSUE TITLE
[Editor] Error with new Input System

### ISSUE THREAD

**Issue by pixeption** [AppLovin/AppLovin-MAX-Unity-Plugin#135]
The AppLovin SDK currently is using the old Input System which works well for the old/default Input System.
For the project that use new Input System, the ad can be shown but not interactable. This is just a minor bug but quite annoying sometimes.

AppLovin Unity SDK version: 5.1.2
Unity: 2020.3.28f1 (With new Input System)

<img width="1148" alt="Screen Shot 2022-02-12 at 3 22 40 PM" src="https://user-images.githubusercontent.com/10240918/153703539-8ff15872-8193-418d-96fa-d17c8b7a3775.png">
<img width="809" alt="Screen Shot 2022-02-12 at 3 23 02 PM" src="https://user-images.githubusercontent.com/10240918/153703544-6364e2b5-2d97-47e6-a0e7-87024d69f8e3.png">

**Comment by santoshbagadi** [comment]
Hi @pixeption , thank you for reporting the issue. We'll look into the issue and report back here when we have a fix for it.
