### ISSUE TITLE
Error about Interstitial Ads 

### ISSUE THREAD

**Issue by nhchoi98** [AppLovin/AppLovin-MAX-Unity-Plugin#136]
Hello :) 
I'm using latest Plugin (5.1.2) and I got a clip from user which Interstitial Ads doesn't work properly 
The error's that Sound streams but any ads doesn't play and I can't exit interstitial ads panel. 

I have a link of the clip which records the error, So I hope figure out what I can do to fix this problem. 
https://youtu.be/-SrZA2mALmE

Thank you :) 

Best regards,
Nak hyeon Choi.

**Comment by Chocoemon** [comment]
https://youtu.be/-SrZA2mALmE

 This's link of the clip.

**Comment by thomasmso** [comment]
Hi, do you mind sending us our SDK's [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) and the ad response via our [Creative Debugger](https://dash.applovin.com/documentation/mediation/unity/testing-networks/creative-debugger)? Thanks!

**Comment by Chocoemon** [comment]
Ok, I'll check  via verbose logs and Creative Debugger, Thx!
