### ISSUE TITLE
Annoying Interstitials

### ISSUE THREAD

**Issue by ShahHusayn** [AppLovin/AppLovin-MAX-Unity-Plugin#137]
Hi, Applovin Interstitial ads allow user only to skip after more than 5 seconds, even when I have checked the options "Skip during video playback".  Its causing trouble in user experience. Just checking if there  is a way to show non annoying interstitials to user just like they appear in UnityAds & Admob Interstitials.

**Comment by thomasmso** [comment]
Hi, please email partner_support@applovin.com with your concern and someone will address it there.
