### ISSUE TITLE
Vungle SDK Error through AppLovin-Max

### ISSUE THREAD

**Issue by bartutiryakioglu** [AppLovin/AppLovin-MAX-Unity-Plugin#139]
I am getting the below error constantly after I integrated Vungle SDK through Max-Unity-Plugin.

2022/02/15 17:28:01.448 23550 24412 Debug AssetDownloader Response code: 200 com.vungle.warren.downloader.DownloadRequestMediator@fd9e325
2022/02/15 17:28:01.449 23550 24412 Error FileUtility Cannot delete DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=
2022/02/15 17:28:01.449 23550 24412 Error FileUtility java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.GulliversGames.RT/no_backup/vungle_cache/clever_cache/assets/DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.nio.file.Files.delete(Files.java:1126)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1470)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.lang.Thread.run(Thread.java:929)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility Cannot delete DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
2022/02/15 17:28:01.449 23550 24412 Error FileUtility java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.GulliversGames.RT/no_backup/vungle_cache/clever_cache/assets/meta/DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.nio.file.Files.delete(Files.java:1126)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1473)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022/02/15 17:28:01.449 23550 24412 Error FileUtility 	at java.lang.Thread.run(Thread.java:929)

I can't see this error every time but when it throws this error game lags because of too much error throwing. Have you seen this error or is there anything you could tell me to fix this problem? Thanks.

**Comment by thomasmso** [comment]
Hi, Vungle's team acknowledged these logs and they are purely cosmetic. For more context, see here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/132
