### ISSUE TITLE
MaxSdkUnityEditor.LoadInterstitial does not call RequestAdUnit

### ISSUE THREAD

**Issue by JasperChimpWorks** [AppLovin/AppLovin-MAX-Unity-Plugin#14]
Version: 2.3.4
Platform: Editor

Unlike LoadRewardedAd, LoadInterstitial does not call RequestAdUnit. No callbacks are fired in editor and calling ShowInterstitial results in a warning that the interstitial was not requested.

**Comment by thomasmso** [comment]
Hey @JasperChimpWorks, @Lorenzo45 is looking into it and will respond accordingly. Thank you for bringing up your concern.

**Comment by Lorenzo45** [comment]
Yeah I noticed this bug too and fixed it in version 2.4.0 which should be released in the coming weeks. We've also adding more features to enable testing ads and callbacks in the Unity Editor so stay tuned!

**Comment by Lorenzo45** [comment]
The Unity Plugin version 2.4.0 is out! This should fix your problem and also adds fake ads that display in the Unity Editor. Let us know if you have feedback on this new feature!
