### ISSUE TITLE
Android gradle plugin version 3.4.0 issue due to jetifier in applovin aar files

### ISSUE THREAD

**Issue by akarsh-tenjin** [AppLovin/AppLovin-MAX-Unity-Plugin#140]
The unity package `AppLovin-MAX-Unity-Plugin-5.1.3-Android-11.1.3-iOS-11.1.2.unitypackage` and earlier version unity package have an issue with the gradle version.
They require Android gradle plugin version 3.6.4 but the unity 2019.4.x Editor version only have 3.4.0
This is causing an issue. I have to export the android project instead of doing `Build and Run` from unity.
After exporting I had to change the gradle version in Android studio in `Project Structure`. 
The reason for the change of Android gradle plugin version is because the Android aar files for Applovin are using jetifier which is supported in 3.6.4 not in 3.4.0 of Android gradle plugin version.

I suggest to resolve the issue to support low version of Android gradle plugin version 3.4.0

**Comment by santoshbagadi** [comment]
Hi @akarsh-tenjin , you can use `gradleTemplate` to update the Gradle plugin version as shown below. This should allow you to just build and run the project again from within Unity:

- If not yet using a custom base template, enable this: **ProjectSettings > Publishing Settings > Custom Base Gradle Template**
- The template will be located at `Assets/Plugins/Android/baseProjectTemplate.gradle`
- Open the template and change this line: `classpath 'com.android.tools.build:gradle:3.4.0'` to `classpath 'com.android.tools.build:gradle:3.6.4' `

**Comment by akarsh-tenjin** [comment]
Hi @santoshbagadi 

Thank you for the response on the issue.

I followed the instructions and tried it. But it did not change the gradle plugin version in the exported Android Project.
The `build.gradle` in the exported project still contained version `3.4.0`.

I changed the gradle plugin version in the file `mainTemplate.gradle` from `3.4.0` to `3.6.4` and then it also changed the gradle plugin version in the exported Android Project.

I went further to understand why the need to change gradle plugin version. 
The requirement is from the Applovin Android SDK version 9.1.0
https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/8ee9ada4ae021e58939e5f5dec5978e801c0c0ab/InMobi/CHANGELOG.md#9100
> 9.1.0.0
> Certified with InMobi SDK 9.1.0.
> Uses <queries> element which requires min Gradle version 3.5.4.

Is there any way you can downgrade and remove the usage of [queries](https://developer.android.com/guide/topics/manifest/queries-element) element be avoided in the Applovin Android Manifest file. So that we can avoid changing the default setting in the mainTemplate.gradle?

The reason for the above, is that the Unity version `2019.4.x` support Gradle version 5.1.1
<img width="1223" alt="Screenshot 2022-02-25 at 12 00 19" src="https://user-images.githubusercontent.com/91734292/155704095-0fed9d0c-6ea7-4393-b2d6-39db2cc4aaf2.png">

The Gradle version 5.1.1 supports only Gradle plugin version till 3.4.3

The current requirement to push the gradle plugin version to 3.6.4, requires to update Unity Editor version from 2019.4.x to 2020.1
<img width="1242" alt="Screenshot 2022-02-25 at 12 07 04" src="https://user-images.githubusercontent.com/91734292/155704943-b0f0c172-416f-409d-8f09-cf8251c09053.png">

The Gradle version and gradle plugin version [table](https://developer.android.com/studio/releases/gradle-plugin),
<img width="893" alt="Screenshot 2022-02-25 at 12 01 46" src="https://user-images.githubusercontent.com/91734292/155704976-4a80b4ff-3585-4c94-b0dd-9f2f5c1dd419.png">

**Summary**
This would mean that mention 
> Either Unity 5.x.x, or Unity 2017.x.x or later.
is actually false.

It should be Unity 2020.1 the minimum version supported by the Applovin Unity Plugin.

Changing the requirement of minimum gradle plugin version in Applovin Android SDK would lower the minimum version supported by the Applovin Unity Plugin.

**Comment by santoshbagadi** [comment]
@akarsh-tenjin , I've tried to reproduce your issue, but I've been able to successfully update the version on my local build with Unity `2019.4.0f1`. You may have missed an additional step mentioned in `baseProjectTempalte.gradle` file 
```
// To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
```

The requirement also comes from InMobi SDK, so, we don't have a way to update it. You may reach out to the InMobi team if you would want them to remove this requirement. 

As for the min requirement, our base plugin should still work with the min versions mentioned in our doc.

**Comment by akarsh-tenjin** [comment]
> additional step mentioned in baseProjectTempalte.gradle file

On your end you have unchecked the "Gradle Installed with Unity (recommended)" and gave a custom path.
Which custom path did you use. Does it need to point to the Android Studio gradle path?

> The requirement also comes from InMobi SDK, so, we don't have a way to update it. You may reach out to the InMobi team if you would want them to remove this requirement.

Thanks for clarifying on it. I now got the understanding that the above is a requirement from Inmobi Android SDK. I will reach out to them.

**Comment by santoshbagadi** [comment]
> On your end you have unchecked the "Gradle Installed with Unity (recommended)" and gave a custom path.
Which custom path did you use. Does it need to point to the Android Studio gradle path?

Not exactly, I just downloaded the necessary library versions at the Unity's library path using Android SDK download manager. But just pointing to the Android Studio's default SDK path should also work.

**Comment by akarsh-tenjin** [comment]
Thank you it resolve the issue 👍
