### ISSUE TITLE
Google Play Shows Error

### ISSUE THREAD

**Issue by bartutiryakioglu** [AppLovin/AppLovin-MAX-Unity-Plugin#141]
<img width="835" alt="TapjoyWarning" src="https://user-images.githubusercontent.com/86728323/155518114-1cd0c951-0f42-4ea3-8207-c62279347f7b.png">

Google PLAY gave us the above error. What should we do about it? Do we need to care about this issue? Thanks!

**Comment by chauduyphanvu** [comment]
@bartutiryakioglu, since this is referencing Tapjoy's internal classes, could you let the Tapjoy team know? There's unlikely nothing we can do from our standpoint. Thanks.

Vu Chau
AppLovin Team

**Comment by AlexSergPosp** [comment]
We pushed our game to store and got this
![image](https://user-images.githubusercontent.com/12152944/168794298-a0766efb-4005-4f44-92f3-357f4c7c63ff.png)

We got same warnings before we pushed and we not use tapjoy network

**Comment by thomasmso** [comment]
It means you have the Tapjoy adapter installed, but not the SDK. Please remove the adapter.
