### ISSUE TITLE
Ads are failed to display with error. Unity 2021.2. 

### ISSUE THREAD

**Issue by AVOGames** [AppLovin/AppLovin-MAX-Unity-Plugin#142]
Just cloned the plugin, and ran DemoApp. 
I've updated all my AdUnitIds with the real ones.
Ads are loaded, but failed to display with the following error in debug logs:

`2022-02-28 15:31:55.360356+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] DEBUG [ALFullScreenAdTracker] Setting fullscreen ad pending display: 1646055115
2022-02-28 15:31:55.360531+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] INFO [ALMediationService] Showing ad fe4293e93c70d7b3 with delay of 0.000000 seconds...
2022-02-28 15:31:55.360700+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] DEBUG [ALMediationAdapterWrapper] ALAppLovinMediationAdapter: running show_ad...
2022-02-28 15:31:55.360830+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] INFO [ALAppLovinMediationAdapter] Showing interstitial: inter_regular...
2022-02-28 15:31:55.361069+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] ERROR [ALSdk] Developer passed nil instead of ALAd instance - please check object types!
2022-02-28 15:31:55.382835+0200 MaxDemoUnity[27005:1625204] [AppLovinSdk] ERROR [ALSdk] Called with an invalid object type from: (
	0   MaxDemoUnity                        0x0000000104f2c218 +[ALUtils assertValidAd:] + 268
	1   MaxDemoUnity                        0x0000000104e95a90 -[ALInterstitialAd showAd:] + 68
	2   MaxDemoUnity                        0x0000000104efe19c -[ALAppLovinMediationAdapter showInterstitialAdForParameters:andNotify:] + 392
	3   UnityFramework                      0x000000010dcb2f2c __36-[ALMediationAdapterWrapper showAd:]_block_invoke + 128
	4   UnityFramework                      0x000000010dcb30c4 __36-[ALMediationAdapterWrapper showAd:]_block_invoke_3 + 44
	5   UnityFramework                      0x000000010dcb46f0 __55-[ALMediationAdapterWrapper runOperationWithTag:block:]_block_invoke + 168
	6   UnityFramework                      0x000000010dcb4594 -[ALMediationAdapterWrapper runOperationWithTag:block:] + 256
	7   UnityFramework                      0x000000010dcb2e6c -[ALMediationAdapterWrapper showAd:] + 1296
	8   UnityFramework                      0x000000010dbcde38 __49-[ALMediationService showFullscreenAd:andNotify:]_block_invoke + 44
	9   UnityFramework                      0x000000010dbcdd94 -[ALMediationService showFullscreenAd:andNotify:] + 1124
	10  UnityFramework                      0x000000010dbf3d08 __47-[MAFullscreenAdController showAdForPlacement:]_block_invoke_2 + 612
	11  UnityFramework                      0x000000010dbf4630 -[MAFullscreenAdController transitionToState:withTransitionBlock:] + 1760
	12  UnityFramework                      0x000000010dbf3a8c __47-[MAFullscreenAdController showAdForPlacement:]_block_invoke + 100
	13  UnityFramework                      0x000000010dbf3dbc -[MAFullscreenAdController showAlertBeforeShowingAdIfNeeded:showAdBlock:] + 128
	14  UnityFramework                      0x000000010dbf388c -[MAFullscreenAdController showAdForPlacement:] + 1016
	15  UnityFramework                      0x000000010dbf9d04 -[MAInterstitialAd showAdForPlacement:] + 184
	16  UnityFramework                      0x000000010db763b0 -[MAUnityAdManager showInterstitialWithAdUnitIdentifier:placement:] + 88
	17  UnityFramework                      0x000000010db888a0 _MaxShowInterstitial + 220
	18  UnityFramework                      0x000000010e813ff8 MaxSdkiOS__MaxShowInterstitial_m7769E9F8F14D488146F75D1F7DE1FECFF9D9`
	
	
The only changes I made to the project, converted it to 2021.2.13fi and updated the plugin.

**Comment by santoshbagadi** [comment]
Hi @AVOGames , could you please share the full logs with [verbose logs enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) when the issue is happening.

Also, what version of the AppLovin MAX plugin and SDK versions are you using?

**Comment by AVOGames** [comment]
Thanks for the reply. 
Unity 3D version (plugin) 5.3.1
iOS SDK Version: 1.11. 2

Full logs are attached.
[logs.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/8155866/logs.txt)

**Comment by santoshbagadi** [comment]
@AVOGames , this is an issue with the default External Dependency Manager configuration. To fix the issue please open the iOS Resolver Settings (**Assets > External Dependency Manager > iOS Resolver > Settings**) and uncheck Add `use_frameworks! to Podfile` and `Always add the main target to Podfile` settings.

**Comment by AVOGames** [comment]
Big thanks, it's working now.
