### ISSUE TITLE
Some events for rewarded ad are not fired in build, works okay in editor

### ISSUE THREAD

**Issue by allenWTF** [AppLovin/AppLovin-MAX-Unity-Plugin#143]
When I'm trying to test a plugin in editor everything works fine, I receive a log about every event just as expected.
But when I'm trying to test a plugin with test mode inside a build some events are not being fired. Here is what happens:

Sdk initializes correctly and fires an event, then I'm trying to preload a reward ad with ```MaxSdk.LoadRewardedAd(REWARD_AD_UNIT)``` method. I'm not getting any logs although I have listeners with logs for both ```MaxSdkCallbacks.Rewarded.OnAdLoadedEvent``` and ```MaxSdkCallbacks.Rewarded.OnAdLoadFailedEvent``` events. 
Despite all of that, ```MaxSdk.IsRewardedAdReady(REWARD_AD_UNIT)``` returns true and hence I'm trying to show a rewarded ad with ```MaxSdk.ShowRewardedAd(REWARD_AD_UNIT)```. Test rewarded ad shows correctly (but again event is missing, this time it's  ```MaxSdkCallbacks.Rewarded.OnAdDisplayedEvent``` at the start), I close it and ...nothing. No ```MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent```, no ```MaxSdkCallbacks.Rewarded.OnAdHiddenEvent``` events are being fired

Can someone help me, please? Maybe I'm missing something. Thanks in advance!

**Comment by allenWTF** [comment]
It feels like the only event that is fired in build is the one about max sdk being initialized. Here is how I subscribe to all events and initialize SDK

```
        private void Start()
        {
            instance = this;

            MaxSdkCallbacks.OnSdkInitializedEvent += (MaxSdkBase.SdkConfiguration sdkConfiguration) =>
            {
                Log.WriteToScreen("Max Sdk Initialized");

                MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent += OnRewardedAdReceivedRewardEvent;
                MaxSdkCallbacks.Rewarded.OnAdHiddenEvent += OnRewardedAdDismissedEvent;
                MaxSdkCallbacks.Rewarded.OnAdLoadedEvent += OnRewardedAdLoadedEvent;
                MaxSdkCallbacks.Rewarded.OnAdLoadFailedEvent += OnRewardedAdFailedEvent;
                MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent += OnRewardedAdFailedToDisplayEvent;
                MaxSdkCallbacks.Rewarded.OnAdDisplayedEvent += OnRewardedAdDisplayedEvent;
                MaxSdkCallbacks.Rewarded.OnAdClickedEvent += OnRewardedAdClickedEvent;
                MaxSdkCallbacks.Rewarded.OnAdRevenuePaidEvent += OnRewardedAdRevenuePaidEvent;
                
                LoadRewardedAd();
            };

            MaxSdk.SetSdkKey(MAX_SDK_KEY);
            MaxSdk.InitializeSdk();
        }

**Comment by allenWTF** [comment]
> Hi @allenWTF , could you please send us [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of the app while the issue is happening to further investigate.
> 
> Also, is the issue happening only on one platform, or both Android and iOS? Could you also share the Plugin and SDK versions being used.

Hi @santoshbagadi thanks for your answer, I will definetly try to enable verbose logs and send them to you asap
This issue happened on Android, I don't have access to iOS to test this behaviour right now though so it maybe happens there aswell.
Here is the picture of versions that I'm using right now:
![image](https://user-images.githubusercontent.com/22818851/156037961-f81f36c3-906b-4431-a74c-c41ac68e8b60.png)

**Comment by allenWTF** [comment]
I've tried to enable verbose logs but I guess it doesn't work since I don't see any new logs neither in editor or in build via adb logcat.

The only logs that I see in build are about sucessfulll subscribe to rewarded ad events. Here is how they look like:
```Debug [AppLovin MAX] Listener has been added to callback: OnRewardedAdReceivedRewardEvent```
and only one log about event invoke, it's about succesfull initialization of sdk. Here is how it looks:
```Debug [AppLovin MAX] Invoking event: System.Action`2[System.String,MaxSdkBase+AdInfo]. Params: da6e715eab9066a7, [AdInfo adUnitIdentifier: da6e715eab9066a7, adFormat: , networkName: , networkPlacement: , creativeIdentifier: , placement: , revenue: -1, revenuePrecision: ]```

Here is how I'm trying to enable verbose logging:
```
        private void Start()
        {
            instance = this;

            MaxSdkCallbacks.OnSdkInitializedEvent += sdkConfiguration =>
            {
                Log.WriteToScreen("Max Sdk Initialized");
                MaxSdk.SetVerboseLogging(true);

                MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent += OnRewardedAdReceivedRewardEvent;
                MaxSdkCallbacks.Rewarded.OnAdHiddenEvent += OnRewardedAdDismissedEvent;
                MaxSdkCallbacks.Rewarded.OnAdLoadedEvent += OnRewardedAdLoadedEvent;
                MaxSdkCallbacks.Rewarded.OnAdLoadFailedEvent += OnRewardedAdFailedEvent;
                MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent += OnRewardedAdFailedToDisplayEvent;
                MaxSdkCallbacks.Rewarded.OnAdDisplayedEvent += OnRewardedAdDisplayedEvent;
                MaxSdkCallbacks.Rewarded.OnAdClickedEvent += OnRewardedAdClickedEvent;
                MaxSdkCallbacks.Rewarded.OnAdRevenuePaidEvent += OnRewardedAdRevenuePaidEvent;
                
                LoadRewardedAd();
            };

            MaxSdk.SetSdkKey(MAX_SDK_KEY);
            MaxSdk.InitializeSdk();
        }
```

**Comment by santoshbagadi** [comment]
Do you mind checking if you can reproduce it in our demo app in this repo or share a sample project where the issue is reproducible

**Comment by WeeeeeeW** [comment]
[verbose.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/9696282/verbose.txt)
This is the verbose log I got, it only show error on the banner, even though it's not consistant, sometimes it shows sometimes it doesnt.

How ever I got no callback from any of the ad except for ad pain revenue.
I suspect this was the problem but I don't really know how to deal with this

@santoshbagadi  please help
> 2022/10/03 16:23:41.502 6802 6802 Info art Rejecting re-init on previously-failed class java.lang.Class<com.applovin.adview.AppLovinFullscreenActivity$a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.OnBackInvokedCallback" on path: DexPathList[[zip file "/data/app/com.cla.stickmanera.artofwar-2/base.apk"],nativeLibraryDirectories=[/data/app/com.cla.stickmanera.artofwar-2/lib/arm, /data/app/com.cla.stickmanera.artofwar-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art 
> 2022/10/03 16:23:41.502 6802 6802 Info art Rejecting re-init on previously-failed class java.lang.Class<com.applovin.adview.AppLovinFullscreenActivity$a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.OnBackInvokedCallback" on path: DexPathList[[zip file "/data/app/com.cla.stickmanera.artofwar-2/base.apk"],nativeLibraryDirectories=[/data/app/com.cla.stickmanera.artofwar-2/lib/arm, /data/app/com.cla.stickmanera.artofwar-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art 
> 2022/10/03 16:23:41.502 6802 6802 Info art Rejecting re-init on previously-failed class java.lang.Class<com.applovin.adview.AppLovinFullscreenActivity$a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.OnBackInvokedCallback" on path: DexPathList[[zip file "/data/app/com.cla.stickmanera.artofwar-2/base.apk"],nativeLibraryDirectories=[/data/app/com.cla.stickmanera.artofwar-2/lib/arm, /data/app/com.cla.stickmanera.artofwar-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art 
> 2022/10/03 16:23:41.502 6802 6802 Info art Rejecting re-init on previously-failed class java.lang.Class<com.applovin.adview.AppLovinFullscreenActivity$a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.OnBackInvokedCallback" on path: DexPathList[[zip file "/data/app/com.cla.stickmanera.artofwar-2/base.apk"],nativeLibraryDirectories=[/data/app/com.cla.stickmanera.artofwar-2/lib/arm, /data/app/com.cla.stickmanera.artofwar-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o.a(com.applovin.impl.adview.o, android.content.Context) ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.applovin.impl.adview.o$2$1.run() ((null):-1)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.os.Looper.loop() (Looper.java:154)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6176)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:893)
> 2022/10/03 16:23:41.502 6802 6802 Info art   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:783)
> 2022/10/03 16:23:41.502 6802 6802 Info art

**Comment by harryarakkal** [comment]
@WeeeeeeW could you try installing the latest Android SDK and build tools (API level 33)? It looks like you may be using an Android 13 device, but not have the appropriate SDK support. 

Here are the docs for updating that with Unity: https://docs.unity3d.com/Manual/android-sdksetup.html or with Android Studio: https://developer.android.com/studio/intro/update#sdk-manager. Also, could you confirm what device (and Android version) are you seeing this issue on?

**Comment by WeeeeeeW** [comment]
@harryarakkal I'm already upgrade the latest Android SDK with API level 33.
I'm using Nox emulator with Android version 7.1.2. Also I tested on Redmi Note 10s with Android 11 and the problem still persist

**Comment by WeeeeeeW** [comment]
[full-log.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/9702228/full-log.txt)
Here's the full log in case you needed it @harryarakkal

**Comment by WeeeeeeW** [comment]
After hours of investigation I found that the problem have something to do with scene loading, currently I haven't found any cause yet but I'll try

**Comment by allenWTF** [comment]
@WeeeeeeW I wasn't able to resolve that issue at that time. Instead I have downgraded plugin version to 4.3.12 (latest before 5.x.x versions) and it started to work properly with all events being fired up in editor and in builds. Maybe it will be appropriate for your use case aswell.

**Comment by WeeeeeeW** [comment]
@allenWTF do you still have the .unitypackage for 4.3.2?
I downgraded to 5.4.7 but it still happen

**Comment by allenWTF** [comment]
@WeeeeeeW Yeah, [here it is](https://artifacts.applovin.com/unity/com/applovin/applovin-sdk/AppLovin-MAX-Unity-Plugin-4.3.12-Android-10.3.5-iOS-10.3.7.unitypackage)

**Comment by WeeeeeeW** [comment]
> @WeeeeeeW Yeah, [here it is](https://artifacts.applovin.com/unity/com/applovin/applovin-sdk/AppLovin-MAX-Unity-Plugin-4.3.12-Android-10.3.5-iOS-10.3.7.unitypackage)

Thank you, I'll give it a go

**Comment by WeeeeeeW** [comment]
> @WeeeeeeW Yeah, [here it is](https://artifacts.applovin.com/unity/com/applovin/applovin-sdk/AppLovin-MAX-Unity-Plugin-4.3.12-Android-10.3.5-iOS-10.3.7.unitypackage)

Too bad still didn't work in my case

**Comment by santoshbagadi** [comment]
@WeeeeeeW The MaxSdk Plugin is responsible for adding the `MaxSdkCallbacks` object to the scene. If there is a duplicate object with the same name, the callbacks might not work as intended. Do you by any chance have the `MaxSdkCallbacks` object in any of the scenes in your project?

**Comment by WeeeeeeW** [comment]
@santoshbagadi in my case sometimes the `MaxSdkCallbacks` object just not automatically added to the scene

**Comment by santoshbagadi** [comment]
@WeeeeeeW would you be able to share a sample project where this is happening so that we can further investigate. You can also share the project directly to my email: santosh.bagadi@applovin.com

**Comment by WeeeeeeW** [comment]
@santoshbagadi I'll in the future, right now I'm just so busy to make a sample

**Comment by majidkh** [comment]
I had a similar issue, and found out that in my case another function was attempting to load a rewarded ad while the current rewarded ad was playing.

**Comment by griever-gf** [comment]
I had the same issue - no events (except initialization) are fired on Android (but everything works ok in editor).
Unity version - 2021.3.16f1
The only advice that helped me is reverting to old version of SDK (version 4).
But I'm not completely satisficed, because I want to use a newer version.
I'll provide project info to developer's email.
