### ISSUE TITLE
Max Ad Review doesn't enable on iOS

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#144]
I have an issue on iOS devices with Max Ad review, It's fine on android devices with the same project. Did I miss something on iOS? 

Unity settings : 
![image](https://user-images.githubusercontent.com/5172296/156339776-d638b1c0-f58c-4442-a3c4-084d91e1aec3.png)
Max Mediation Debugger on iOS ( seems to have issue ) : 

<img src="https://user-images.githubusercontent.com/5172296/156342507-d6dd222c-9a9b-47f7-91bb-2273152a9e9e.jpg" width="450" >

Same project with MAX Mediation Debugger on Android ( which is fine) : 

<img src="https://user-images.githubusercontent.com/5172296/156341268-719af39b-2711-4724-98cb-07c89eac88ee.jpg" width="300" >

**Comment by santoshbagadi** [comment]
Hi @uchar , did you get any errors in the Unity console while building the iOS app? Also, do you mind checking if there is a file named `AppLovinQualityServiceSetup.rb` in the exported Xcode project?

**Comment by uchar** [comment]
@santoshbagadi yes thanks , I found out that ruby was not installed on my windows machine
