### ISSUE TITLE
Unity Build Failure after importing Facebook module from Applovin Integration Manager

### ISSUE THREAD

**Issue by ShahHusayn** [AppLovin/AppLovin-MAX-Unity-Plugin#145]
Unity Version: 2019.4.17f1
Applovin Max: 5.0.1
Min API Level: 21 (Android 5.0 Lollipop)
Target API: API Level 31
MultiDex Enabled: Yes

I have attached EditorLog, gradleTemplate, LauncherTemplate and mainTemplate files for reference. Kindly let me know what I am doing wrong.

Note: I have made builds before on same configuration using AdMob, InMobi and Unity applovin adapters but build fails if I use Facebook adapter.

Error Logs: 
1. > Configure project :launcher
WARNING: The option setting 'android.bundle.enableUncompressedNativeLibs=false' is experimental and unsupported.
The current default is 'true'.

2. Note: E:\BusRamp\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
An exception has occurred in the compiler (1.8.0-adoptopenjdk). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.

3. CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Unity/Hub/Editor/2019.4.17f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -classpath "D:\gradle-5.6.4\lib\gradle-launcher-5.6.4.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"****
[mainTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/8177766/mainTemplate.txt)
[gradleTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/8177771/gradleTemplate.txt)
[LauncherTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/8177776/LauncherTemplate.txt)
[ErrorLogs.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/8177828/ErrorLogs.txt)

**Comment by chauduyphanvu** [comment]
@ShahHusayn, it's an error with the AdoptOpenJDK as shown in the error logs. Feel free to follow the suggestions in
https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab to resolve the issue. 

Vu Chau
AppLovin Team

**Comment by ShahHusayn** [comment]
@chauduyphanvu Thanks for help following the link fixed my problem.
