### ISSUE TITLE
Facebook Adapter and 320x50 Banner Ads

### ISSUE THREAD

**Issue by ShahHusayn** [AppLovin/AppLovin-MAX-Unity-Plugin#146]
Hello,
I want to show 320x50 banner using Facebook Audience Network but it covers the full screen width. I have seen several apps using 320x50 Facebook banner which doesn't cover the device width. Is there a way to show Facebook banner of specified width using 

Applovin Max or do I have to stick with smart banner?

I am attaching my Facebook banner current output and required output images as well as my initialization code

Here is my banner initialization code:

`        // Banners are automatically sized to 320×50 on phones and 728×90 on tablets
        // You may call the utility method MaxSdkUtils.isTablet() to help with view sizing adjustments
        MaxSdk.CreateBanner(bannerId, MaxSdkBase.BannerPosition.TopCenter);
        MaxSdk.SetBannerExtraParameter(bannerId, "adaptive_banner", "false");
        // Set background or background color for banners to be fully functional
        MaxSdk.SetBannerBackgroundColor(bannerId, new Color(0.0f,0.0f,0.0f,0.0f));`
![RequiredOutput](https://user-images.githubusercontent.com/20114190/156716894-23dabb84-e7f4-40d0-b0f1-89492ced9040.jpg)
![CurentOutput](https://user-images.githubusercontent.com/20114190/156716908-4505988e-85e6-4b00-a690-0b65f21809c5.jpg)

**Comment by santoshbagadi** [comment]
Hi @ShahHusayn , for `TopCenter` and `BottomCenter` positions, banners stretch full width by default. If you would like to set a fixed width, you can do so by calling `MaxSdk.SetBannerWidth(adUnitIdentifier, width)` to your desired width.

**Comment by ShahHusayn** [comment]
@santoshbagadi thanks for your help, I was struggling for a while this helped me.
