### ISSUE TITLE
applovin crash

### ISSUE THREAD

**Issue by maliX0024** [AppLovin/AppLovin-MAX-Unity-Plugin#147]
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime FATAL EXCEPTION: main
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime Process: com.AppLovin.MaxDemoUnity, PID: 13283
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/applovin/mediation/MaxAdFormat;Lcom/applovin/sdk/AppLovinSdk;Landroid/app/Activity;)V in class Lcom/applovin/mediation/ads/MaxAdView; or its super classes (declaration of 'com.applovin.mediation.ads.MaxAdView' appears in /data/app/~~O0UTDSDFt0f51QY0P-3joA==/com.AppLovin.MaxDemoUnity-unsBjjA6t85sLtHgjXspnA==/base.apk!classes2.dex)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager.retrieveAdView(MaxUnityAdManager.java:1327)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager.access$700(MaxUnityAdManager.java:59)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager$4.run(MaxUnityAdManager.java:927)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.applovin.mediation.unity.Utils$1.run(Utils.java:27)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:938)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:236)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8037)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2022/03/04 19:08:08.964 13283 13283 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by santoshbagadi** [comment]
Hi @maliX0024 , it seems like there is a mismatch between our AppLovin Android SDK and the MAX Unity Android plugin versions.

Could you please share the [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) of our SDK and check what version of our SDK is is being used. You should see a log similar to the below with the SDK and plugin versions:

```
========================================
===SDK Versions===
    Version: x.y.z
    Plugin Version: Max-Unity-a.b.c
    Ad Review Version: 
    OM SDK Version: 
    ===Device Info===
```

You can fix this by upgrading to our latest plugin or delete existing dependencies and force resolve the dependencies by running Assets > External Dependency Manager > Android Resolver > Force Resove.

**Comment by maliX0024** [comment]
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== MAX ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK Version - 11.2.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Plugin Version - Max-Unity-4.3.12
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Ad Review Version - 4.3.7
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Unity Version - 2020.3.30f1

**Comment by maliX0024** [comment]
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== MEDIATION DEBUGGER ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== APP INFO ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Dev Build - true
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Test Mode - disabled
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Target SDK - 32
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== MAX ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK Version - 11.2.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Plugin Version - Max-Unity-4.3.12
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Ad Review Version - 4.3.7
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Unity Version - 2020.3.30f1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== PRIVACY ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Age Restricted User - No value set
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Has User Consent - No value set
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk "Do Not Sell" - No value set
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ========== NETWORKS ==========
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ---------- ADCOLONY_NETWORK ----------
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Status  - COMPLETE
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK     - 4.6.5
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Adapter - 4.6.5.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ---------- APPLOVIN_NETWORK ----------
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Status  - COMPLETE
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK     - 11.2.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Adapter - 11.2.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ---------- FACEBOOK_NETWORK ----------
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Status  - COMPLETE
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK     - 6.8.0
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Adapter - 6.8.0.12
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ---------- UNITY_NETWORK ----------
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Status  - COMPLETE
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK     - 4.0.1
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Adapter - 4.0.1.0
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk ---------- VUNGLE_NETWORK ----------
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Status  - COMPLETE
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk SDK     - 6.10.4
2022/03/05 14:15:01.818 2044 2335 Debug AppLovinSdk Adapter - 6.10.4.0

**Comment by maliX0024** [comment]
Same error.... 


2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime FATAL EXCEPTION: main
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime Process: com.carstunt.offline.taycoongames, PID: 2044
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/applovin/mediation/MaxAdFormat;Lcom/applovin/sdk/AppLovinSdk;Landroid/app/Activity;)V in class Lcom/applovin/mediation/ads/MaxAdView; or its super classes (declaration of 'com.applovin.mediation.ads.MaxAdView' appears in /data/app/~~h2rEXnDrEbUmnx8PVBVDvQ==/com.carstunt.offline.taycoongames-0k69zOeFDftZspobL67pKw==/base.apk!classes2.dex)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager.retrieveAdView(MaxUnityAdManager.java:1327)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager.access$700(MaxUnityAdManager.java:59)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.applovin.mediation.unity.MaxUnityAdManager$4.run(MaxUnityAdManager.java:927)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.applovin.mediation.unity.Utils$1.run(Utils.java:27)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:938)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:236)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8037)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2022/03/05 14:14:59.726 2044 2044 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2022/03/05 14:14:59.729 500 500 Error SELinux avc:  denied  { find } for pid=4715 uid=10273 name=tethering scontext=u:r:vendor_systemhelper_app:s0:c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0

**Comment by santoshbagadi** [comment]
@maliX0024  Looks like what I mentioned above was the issue. It could be that External Dependency Manager is resolving to a newer version of our native SDK than what is set in the plugin.

You can fix this by upgrading to our latest plugin or delete existing dependencies and force resolve the dependencies by running `Assets > External Dependency Manager > Android Resolver > Force Resolve`.
