### ISSUE TITLE
After Moving maxsdk to a custom package, Applovin Integration Manager does not recognize it's plugins

### ISSUE THREAD

**Issue by dopaminegamesstudio** [AppLovin/AppLovin-MAX-Unity-Plugin#150]
After I moved MaxSdk to a custom package and add it through unity's package.json. Applovin Integration Manager does not recognize its plugins anymore.
I think the problem is related to the logic of `PluginParentDirectory`.

![image](https://user-images.githubusercontent.com/78404578/158332070-ef1ba334-dcd5-4e6f-9693-8a023324b421.png)
 

![image](https://user-images.githubusercontent.com/78404578/158331391-474b20c8-6d28-4b22-b895-b878364c1d1d.png)

**Comment by uchar** [comment]
@santoshbagadi Do you have any update on this issue? 
We're using the same code for handling video ads in a couple of different projects and because of this issue we can't move them to a separate package and reuse them

**Comment by JonathanLiuApp** [comment]
We've just released plugin [version 8.0.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_8_0_0) which includes UPM support.
