### ISSUE TITLE
Get height of banner 

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#151]
I want to show UI contents exactly on top of the banner, I didn't find any API to get the exact height of the banner.
I found a comment in your examples : 
`// Banners are automatically sized to 320×50 on phones and 728×90 on tablets`

Is it the case for all banners? e.g the Admob adaptive banner?

And suppose that I want to get the height of the banner on a device, is it the right way to do it? 
```     
public float GetBannerHeight()
{
     return (MaxSdkUtils.IsTablet() ? 90 : 50) * (Screen.dpi / 160);
}
```

**Comment by chauduyphanvu** [comment]
@uchar, you can do something like this:

```java
[](https://dash.applovin.com/documentation/mediation/android/getting-started/banners#table-of-contents)@Override
public void onAdLoaded(final MaxAd maxAd)
{
   AppLovinSdkUtils.Size adViewSize = maxAd.getSize();

   int widthDp = adViewSize.getWidth();
   int heightDp = adViewSize.getHeight();
}
```

It works best for Google adaptive banner since its sizes are unpredictable. For non-adaptive banner, the size should be as you requested (like you said).

**Comment by uchar** [comment]
@chauduyphanvu  Is it the java method? How can I use it in the unity, C# plugin?

**Comment by chauduyphanvu** [comment]
@uchar, let us look into adding support for it from C#. Stay tuned!

**Comment by santoshbagadi** [comment]
Hi @uchar , we have an API already to get the adaptive height of the banner, `MaxSdkUtils.GetAdaptiveBannerHeight()`. You can also get the banner position on screen by calling `MaxSdk.GetBannerLayout(adUnitId)`. Please note that the later requires the banner to be visible on screen.

**Comment by uchar** [comment]
@santoshbagadi I tried `MaxSdk.GetBannerLayout`, in the editor it always returns 0 widths and height object .  Is this normal behavior?
Also about `GetAdaptiveBannerHeight`does this also works in case of banner doesn't come from google?

**Comment by uchar** [comment]
Well I just test it on my device, it seems to be working fine, I put the code in case someone else needs it in the future:
```
public class MAXSdkObjectScript : MonoBehaviour
    {
        [HideInInspector] public List<UnityAction> bannerAdjusterActions = new List<UnityAction>();
        [SerializeField] private string bannerAdUnitId;
        [SerializeField] private string maxSdkKey;
    
        private static MAXSdkObjectScript _instance;

        public static MAXSdkObjectScript GetInstance()
        {
            return _instance;
        }


        void Start()
        {
            _instance = this;
            DontDestroyOnLoad(gameObject);
            MaxSdk.SetSdkKey(maxSdkKey);
            MaxSdk.InitializeSdk();
        }

        public void InitializeBannerAds()
        {
            MaxSdk.CreateBanner(bannerAdUnitId, MaxSdkBase.BannerPosition.BottomCenter);
            MaxSdk.SetBannerBackgroundColor(bannerAdUnitId, Color.white);

            MaxSdkCallbacks.Banner.OnAdLoadedEvent += OnBannerAdLoadedEvent;

            ShowBanner();
        }

        public float GetBannerHeight()
        {
            // 160 is value in Canvas Scalar,Refrence Per Pixel unit , Make sure that's 160
            return MaxSdkUtils.GetAdaptiveBannerHeight() * (Screen.dpi / 160);
        }

        private void OnBannerAdLoadedEvent(string adUnitId, MaxSdkBase.AdInfo adInfo)
        {
            foreach (var adjuster in bannerAdjusterActions)
            {
                adjuster.Invoke();
            }
        }

        public void ShowBanner()
        {
             MaxSdk.ShowBanner(bannerAdUnitId);
        }

     
        public void HideBanner()
        {
            MaxSdk.HideBanner(bannerAdUnitId);
        }
      
    }
```

```
 public class BannerAdjuster : MonoBehaviour
    {
        [SerializeField] private float extraMarginOnPhone = 0;
        [SerializeField] private float extraMarginOnTablet = 0;

        private RectTransform _rectTransform;

        private void Start()
        {
            _rectTransform = GetComponent<RectTransform>();
            MAXSdkObjectScript.GetInstance().bannerAdjusterActions.Add(SetYBaseOnBannerHeight);
            SetYBaseOnBannerHeight();
        }

        private void SetYBaseOnBannerHeight()
        {
            var isTablet = MaxSdkUtils.IsTablet();
            var bannerHeight = MAXSdkObjectScript.GetInstance().GetBannerHeight();
            var pos = _rectTransform.anchoredPosition;
            pos.y =  bannerHeight +
                    (isTablet ? extraMarginOnTablet : extraMarginOnPhone) * (Screen.dpi / 160);
            _rectTransform.anchoredPosition = pos;
        }
    }
```

Place `BannerAdjuster` on any component that you want to be on top of the banner ( e.g you can put it on the parent of all your UI elements ) and make sure it has RectTransform

**Comment by santoshbagadi** [comment]
@uchar , when adaptive banners are enabled, the banner height is always set to adaptive height even if the ad is not coming from Google. The inner view from the specific network maybe set to 50, but the actual `MaxAdView`/`MAAdView` are set to be of adaptive height returned by `MaxSdkUtils.GetAdaptiveBannerHeight`

For `MaxSdk.GetBannerLayout` returning 0s in Editor mode, yes, it is expected. We do not yet have support for banner layout on Editor.
