### ISSUE TITLE
AppLovinFullscreenActivity go black and can't close

### ISSUE THREAD

**Issue by sundxing** [AppLovin/AppLovin-MAX-Unity-Plugin#152]
Hi, when I tested the ad, I encountered a black screen ad, which was displayed normally at the beginning, but then turned into a black screen and couldn't be closed, so I had to force kill the application.

**Device** OPPO F1s A1601
**Android Version** 5.1

**The sure part:**

1 This bug can be reproduced on this device, but not others(different android version).
2 The Ad Network is  `AppLovin`

**The debug log:**

```
03-31 12:52:04.843 24660-24660/myapp D/AppLovinSdk: [AppLovinFullscreenActivity] Video completed
03-31 12:52:04.843 24660-24660/myapp D/AppLovinSdk: [AppLovinFullscreenActivity] Showing postitial...
03-31 12:52:04.968 24660-24660/myapp D/AppLovinSdk: [CountdownManager] Ending countdown for PROGRESS_BAR
03-31 12:52:04.979 24660-24660/myapp V/InputMethodManager: START INPUT: com.applovin.impl.adview.d{3dae0d0a VFED..CL .F...... 0,0-720,1280} ic=org.chromium.content.browser.input.AdapterInputConnection@7b7528 tba=android.view.inputmethod.EditorInfo@17334241 controlFlags=#100
03-31 12:52:05.168 24660-24660/myapp D/AppLovinSdk: [AdWebView] Forwarding "javascript:al_onPoststitialShow(0,0);" to ad template
03-31 12:52:05.168 24660-24660/myapp D/WebView: loadUrl=javascript:al_onPoststitialShow(0,0);
03-31 12:52:05.174 24660-24660/myapp D/AppLovinSdk: [AdWebView] : 1: Uncaught ReferenceError: al_onPoststitialShow is not defined
03-31 12:52:08.643 24660-24660/myapp I/AppLovinSdk: [AdWebView] Loaded resource: https://prod-a.applovin.com/interact?clcode=4!v3!51963.1648702283!9_6Upw_POkQUmZD-FsD4hBfHcr-Hz2grkUcBlTvMrVFkO4gJqY3mGesG-M7AWFmm2CAUVJ0jHvN-Al87KocxDCPgVwV-0TSiCro9DfzwiK61Uqhxl91VJDlASzvS7gSAOBGqbzqyXUzEioxG2-VK0exvBsStzU7olqUMOeVVSgD2hcqczuyWo-5L5LnfywR6mO1L6jEANTfgR4Zdx-ybXx-eXLIAQ9rKeKVs_GIDFAV5t3kBG5u-dnQRIzk4G5L-q7hA5ewAZlzJMINfos4y7lVQ4h9Spt5Gw6MtpFbQNYiv7iA1H0dQdX8Pr6sp_yvuGyVFLSQ7xOfHm21fM-VHGu535kwaZmZiSkRZalNY8fAVx-R4f6OSwHS9K_lKy_leTPJCZtbEKOyYAeNFCtQVwZc2KZ-x2tWC6zezqdIrq12xEWtnQ4d5S_bsvWfITp3KnyUEnuGZKCxADeM2KHG-q-59zWA2XX_Z5XxcGiAMrazZrZhgz2vXm1E13oGuS-YfzL2wui7w9pCwUx6jfLZhAN1c2Hwh6TQwJB5Qz3soyc2gvqUb3T0lFOXEgQi6Vn3GYRcvVDQd495Mew8fvHfCjQOiY3gDn4B7gPlaSdusNrBwsrc9-cSBo2pDtfCfb8TvVm8nvPkF1PuvYpWV2YxvP2kBNBxK_Cw0LQCewtz41zLe_RPjxUvbOL5Vce5dUdtNmOb39PnmOa0URkIZtVzesOCFDsWVn71Z2Bz64UJSpUbU3qPOx_3Ji08gj_fxgd7522EdQCNgSfTFYZamNCiuxULjEsFUEbx7tZJfIjsIancM2PgU_OfkxOac4uhKSG12p5Fxnt_vIE848Wd5ajjsTpi-jzUFFN0DNOyG_HF_UEqDAlxEGYnKvuPd7UVeH1IU7d66uBrE9UpGfQ-5LEIcqNXQpy1scThNyqFF8UUYNBRqkSz_bEb64hP3pWRkeaKD2-XbbBw2DOA6PI22siiYc2JoUAQwsgwjunsQ9xgMth5fe6VoXvigoO6dHCrYMV8NSEH7ofexo-ym-B_WWtdVJ7-flgA4uXVPeAIsMo_f93g*&h_p=NaN&v_p=NaN&x_s=unknown
03-31 12:52:08.646 24660-25110/myapp D/libc-netbsd: [getaddrinfo]: mtk hostname=prod-a.applovin.com; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10502; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
03-31 12:52:08.658 24660-25110/myapp D/libc-netbsd: getaddrinfo: prod-a.applovin.com get result from proxy >>
```
**About Max:**

![device-2022-03-31-125040](https://user-images.githubusercontent.com/7501153/160980230-8bf50e01-6bf8-478c-92ee-8c6680cd3ad0.png)

![device-2022-03-31-125109](https://user-images.githubusercontent.com/7501153/160980293-9ad39dc1-360d-4113-a1f4-67286542ab8d.png)

**Comment by tracer8** [comment]
+1 this issue happen all of time. From beginning of this SDK
Anyone fix this?

**Comment by santoshbagadi** [comment]
Hi @tracer8 , are you able to reproduce the issue locally. If so, could you please enable [verbose logs](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#enable-verbose-logging) and share the full logs for the session so that we can further investigate.

**Comment by tracer8** [comment]
> Hi @tracer8 , are you able to reproduce the issue locally. If so, could you please enable [verbose logs](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#enable-verbose-logging) and share the full logs for the session so that we can further investigate.

Below is my video capture. No verbose logs error at all when this issue show up.
You can see:
- Time Count Down Stop
- Black screen
- Still click to go to store on this ad

https://www76.zippyshare.com/v/3kZvx86j/file.html

**Comment by santoshbagadi** [comment]
@tracer8 I'm not able to download the file. Could you please upload the file directly to GitHub. Also, do you mind sending us the full logs when the issue is happening (even if you don't see any errors).

**Comment by tracer8** [comment]
@santoshbagadi Here is video and log.
This errors happen on Mintegral ads.
My configs:
- Android SDK version: 11.5.2
- MAX Version: 5.5.2 
- Unity Version: 2020.3.38f1


https://user-images.githubusercontent.com/15725821/196331248-98666740-aedc-419b-8712-c9537f7065ae.mp4

[BlackScreen Ads Log.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/9806293/BlackScreen.Ads.Log.txt)

**Comment by tracer8** [comment]
Another black screen with time countdown stop can't close, but i can't identify what network.

https://user-images.githubusercontent.com/15725821/196333866-40e7cbd5-07cd-428b-8b23-98f760dd7549.mp4

**Comment by tracer8** [comment]
Another black screen on Vungle use newest version 5.5.3

https://user-images.githubusercontent.com/15725821/196385744-b5577947-6225-4705-86e8-c4636588d1c2.mp4

**Comment by tracer8** [comment]
Bump, anyone?

**Comment by NanaAmoah** [comment]
@tracer8 Since these issues are with Mintegral and Vungle creatives, I'd recommend that you reach out to them directly with the **ad issue report** of the problematic ads. You can generate this using our creative debugger tool (Docs: [iOS](https://dash.applovin.com/documentation/mediation/ios/testing-networks/creative-debugger), [Android](https://dash.applovin.com/documentation/mediation/android/testing-networks/creative-debugger#creative-debugger), [Unity](https://dash.applovin.com/documentation/mediation/unity/testing-networks/creative-debugger)). 

I see in the logs attached that the ad was from [mintegral.com](http://mintegral.com/) DSP serving on AppLovin Exchange. For issues with DSP ads, you can share them with your AM and they would be able to advise on the best solution.

**Comment by Watcher3056** [comment]
+1
Not sure which exactly ad-network create this issue, but it happens on some devices in our project where we using Applovin Max SDK with next ad-netwroks:

![UacImuPS4b](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/53340768/d20099c7-8349-46d3-883a-b0f6e3cfa689)
