### ISSUE TITLE
Chartboost build error

### ISSUE THREAD

**Issue by tin-22** [AppLovin/AppLovin-MAX-Unity-Plugin#153]
Hi,
I have build error when intergrated Chartboost to my project. I have tried using the sample project, upgrade MAX sdk, and use only Chartboost adapter only but still got the same error. Can anyone help?
Unity: 2019.4.36f
MAX: 11.3.2
Chartboost: android_8.4.1.0_ios_8.5.0.3

Execution failed for task ':launcher:preReleaseBuild'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Failed to transform artifact 'com.chartboost.chartboost-sdk-8.4.1.aar (:com.chartboost.chartboost-sdk-8.4.1:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: D:\Projects\MaxDemoApp\Temp\gradleOut\unityLibrary\libs\com.chartboost.chartboost-sdk-8.4.1.aar.
         > Failed to transform 'D:\Projects\MaxDemoApp\Temp\gradleOut\unityLibrary\libs\com.chartboost.chartboost-sdk-8.4.1.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)

**Comment by Str4tos** [comment]
I also have problems with the latest version of Сhartboost.
If exist `android.enableDexingArtifactTransform=false` property in `gradleTemplate.properties` file then I got build error:
```
error processing C:\Users\..\.gradle\caches\transforms-2\files-2.1\f06e25d29edd6a4af32112f8eb487024\jetified-chartboost-sdk-8.4.1-runtime.jar
java.lang.UnsupportedOperationException: This feature requires ASM7
  at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
  at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
  at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
...
```
Also, from the [release notes of Chartboost SDK](https://answers.chartboost.com/en-us/child_article/android-amazon), it can be seen that it requires the minim version of the gradle 
`classpath 'com.android.tools.build:gradle:4.0.2'`   
`gradle.properties distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`.  

Not every version of the Unity version compliance these requirements.

**Comment by thomasmso** [comment]
We're working with Chartboost on laxing the requirement, will keep this thread posted.

**Comment by borisenki** [comment]
The same error on Unity 2021.2.10f1

**Comment by Str4tos** [comment]
### Instructions from Сhartboost support:  
 To solve `java.lang.UnsupportedOperationException: This feature requires ASM7` issue with `android.enableDexingArtifactTransform=false` property you need to upgrade:  
- gradle tools version to: com.android.tools.build:gradle:4.1.0+, 
- gradle version to: gradle-6.5+ 

### How to modify Gradle Tools version and Gradle Wrapper version in Unity: 
1. Modify Gradle Tools version  
Use `Edit->Project Settings->Player->Select Android Card->Build->Custom Base Gradle Template` option to generate a file at `Assets/Plugins/Android/baseProjectTemplate.gradle`.
2. Open the `baseProjectTemplate.gradle` file with a text editor, then modify as below:
```gradle
dependencies {
   classpath 'com.android.tools.build:gradle:4.1.0'
   **BUILD_SCRIPT_DEPS**
}
```
3. Download Gradle Wrapper version 6.5+: https://services.gradle.org/distributions/gradle-6.5-bin.zip
4. Unzip the archive to any location.
5. Use `Unity->Preferences->External Tools` menu and deselect the `Gadle Installed with Unity(recommended)`
6. Select a path to a `.../gradle-6.5` you have downloaded manually.  

The instruction is valid for any versions of Unity, even on 2018.4.
