### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by maliX0024** [AppLovin/AppLovin-MAX-Unity-Plugin#154]
> Failed to list versions for com.applovin.quality:AppLovinQualityServiceGradlePlugin.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
                  > dl.google.com
      > Failed to list versions for com.applovin.quality:AppLovinQualityServiceGradlePlugin.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
                  > jcenter.bintray.com
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

      > Failed to list versions for com.applovin.quality:AppLovinQualityServiceGradlePlugin.
         > Unable to load Maven meta-data from https://artifacts.applovin.com/android/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml.
            > Could not HEAD 'https://artifacts.applovin.com/android/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
               > artifacts.applovin.com
      > Failed to list versions for com.applovin.quality:AppLovinQualityServiceGradlePlugin.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
                  > dl.google.com
      > Failed to list versions for com.applovin.quality:AppLovinQualityServiceGradlePlugin.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.
                  > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <762caba6f98a4d7e9d56f7b5bd6e35d6>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by ura8627** [comment]
Hi, @maliX0024 find any solution?
