### ISSUE TITLE
Unity2019.4.26 Build Stay at the Step("Exporting Android project") 

### ISSUE THREAD

**Issue by runing-five-flower-meat** [AppLovin/AppLovin-MAX-Unity-Plugin#156]
![x3F84oJhXM](https://user-images.githubusercontent.com/64903989/165050603-03ad48aa-e723-42a2-bcf0-e8389562d18d.jpg)

unity 2019.4.26
AppLovin Max Unity Plugin 5.3.1
spectial setting:
Unity\Hub\Editor\2019.4.26f1c1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\GradleTemplates\baseProjectTemplate
![d6YvgSGXdB](https://user-images.githubusercontent.com/64903989/165050645-15e31103-690f-437e-8f9f-e4adecbea5ac.jpg)

![ew2rqV10O1](https://user-images.githubusercontent.com/64903989/165050782-648e3672-7bc5-47c2-bcf0-1ee1a7eafa8f.jpg)

![image](https://user-images.githubusercontent.com/64903989/165052142-4a08b4a8-7e98-4a09-ac79-08401c02bcbb.png)

If I delete the directory "Assets/StreamingAssets" . Build can be Succeed.   otherwise build always stay at step ("Exporting Android project")  . The directory  "Assets/StreamingAssets" size is about 350MB.

after build two hours ,build failed.
![image](https://user-images.githubusercontent.com/64903989/165077754-c5424b59-3912-4d3c-b78b-da64be8f0c94.png)

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Unity/Hub/Editor/2019.4.26f1c1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -classpath "D:\gradle-6.9.2-all\gradle-6.9.2-all\gradle-6.9.2\lib\gradle-launcher-6.9.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > AAPT2 aapt2-3.6.4-6197926-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 4s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
=============================================================================
AppLovin Quality Service Plug-in for Gradle and Android Studio Version 4.3.12
Copyright (c) 2022 AppLovin Ltd. All rights reserved.
=============================================================================
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
[SafeDK] Your project has been updated to support Multi-Dex!
With Multi-Dex support you can use as many methods as you like in your application (no 65K method limit)

> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseResValues
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:MaxMediationGoogle.androidlib:extractDeepLinksRelease
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:javaPreCompileRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:mergeReleaseShaders
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseShaders
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseAssets
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseAssets
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:MaxMediationGoogle.androidlib:parseReleaseLocalResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibResRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:MaxMediationGoogle.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:MaxMediationGoogle.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:MaxMediationGoogle.androidlib:processReleaseManifest
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseRFile
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibCompileRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibRuntimeRelease
> Task :launcher:checkReleaseDuplicateClasses UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders UP-TO-DATE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:processReleaseManifest
> Task :launcher:processReleaseResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
58 actionable tasks: 25 executed, 33 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <98f1d933052f4ea1953718dde49bfee4>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <98f1d933052f4ea1953718dde49bfee4>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <98f1d933052f4ea1953718dde49bfee4>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <f145152621bd4bdf8ad4a76c96b41c9b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by concat1911** [comment]
I have same issues
Unity 2019.4.22f1
Max SDK 5.3.1

This happen when I added Mediated Networks: Facebook, Inmobi and Vungle. If i remove them I can build again.

**Comment by ura8627** [comment]
HI, @concat1911 @runing-five-flower-meat find any solution?
