### ISSUE TITLE
Banner Ads Custom Position

### ISSUE THREAD

**Issue by ShahHusayn** [AppLovin/AppLovin-MAX-Unity-Plugin#159]
Hi, I want to show banner ads at 2 different positions.
1. Inside MainMenu scene I want banner positioned at TopCenter
2. Inside my Gameplay Scene I want banner positioned at TopLeft.

What is the best approach, do I create 2 different banner IDs and initialize it at start of my game? and show respective banners at specified positions. Or should I create only one ID for banner and first initialize it for MainMenu with position TopCenter and then reinitialize it for Gameplay with position TopLeft?

**Comment by thomasmso** [comment]
Hi - we do not support showing multiple banners on the screen with the same Ad Unit ID. Please create a separate Ad Unit ID and use that in our APIs.
