### ISSUE TITLE
Can't build 11.4: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by zenith-jacob** [AppLovin/AppLovin-MAX-Unity-Plugin#161]
I also reported here: https://github.com/googlesamples/unity-jar-resolver/issues/487#issuecomment-1126952956
But I guess it should be reported here.

**Specifications**
- Unity 2020.2.1f1 (but I've seen this reported on StackOverflow on Unity 2021)
- Applovin 11.4 (but please read below)

**The issue**
After 11.4 update two days ago, you can't build Android anymore. Here's the error:

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
.../app/build/intermediates/incremental/mergeDevelopmentDebugResources/merged.dir/values/values.xml:2682: AAPT: error: resource android:attr/lStar not found.
```

One of the mediation adapters (I'm pretty sure it's Facebook Audience Network) is pulling **androidx.core.core-1.7.0** which is causing the error below. With **core-1.6.0** it worked perfectly (3 days ago).

I tried downgrading to the setup that worked (**Applovin SDK** from **11.4** to **10.3** and **FAN** from **6.11.0.1** to **6.10.0.1**) but somehow the resolver is still pulling **Applovin 11.4 aar** (despite the fact that Integration Manager correctly shows that I'm on version **10.3**).

So I guess it may not be FAN, but Applovin causing the issue, but FAN somehow forces Applovin to update to 11.4.
I have auto-update turned off.

Still trying to find a proper workaround.

- Setting minSdkVersion to 31 or anything like that is not an option.
- Overriding build.gradle and forcing android:core:1.6.0 is also not an option

We're talking serious app here and these hack-fixes will cause further issues impossible to track down.

**Comment by MounirAbb** [comment]
i am having the same issue . it doesnt build . i tried several solutions and none worked. can i download old version ?

**Comment by zenith-jacob** [comment]
Temporary solution is to:

- Resolve aars with External Dependency Manager so it pulls everything
- Disable auto-resolution on build in EDM
- Delete androidx.core-1.X.X (possibly 1.7.0)
- Download core-1.6.0 from Maven and manually place the .aar in Plugins/Android (https://mvnrepository.com/artifact/androidx.core/core/1.6.0)
- Put `android.enableDexingArtifactTransform=false` in custom gradleTemplate

**Comment by NikolaySkakun** [comment]
Same here

**Comment by DJYar** [comment]
Same issue on Unity 2019.4.17 with Applovin 11.4

With Applovin 11.4 game won't compile even with latest android SDK (32 in my case). Compiler throws strange errors (e.g. duplicate classes, internal OpenJDK compiler error, etc)

Just core-1.7.0 replacement [as mentioned above](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/161#issuecomment-1127758560) didn't work until I reverted Applovin to previous version (11.3.3)

Issue still persists but at least we can compile workable APKs with core aar swap

**Comment by mofish9** [comment]
Same issue.

**Comment by santoshbagadi** [comment]
Hi, could you please share a sample project where the issue is reproducible, since we are not able to reproduce the issue once we update target SDK version to API 31. 

Note: some times you may have to restart Unity for settings to take effect. You can also make sure that Unity is correctly applying target SDK version to API 31 by exporting the Android project and making sure that the `targetApi` is set to 31.

**Comment by zenith-jacob** [comment]
@santoshbagadi But isn't setting the targetApi to hardcoded 31 preventing the app from being installed on older devices have lower API?

We just always use this (Automatic, Highest Installed)
![image](https://user-images.githubusercontent.com/33549831/169008042-a5b1be9a-153b-4ebc-8d75-79201b0cefe3.png)

**Comment by zenith-jacob** [comment]
> Same issue on Unity 2019.4.17 with Applovin 5.4.0 (11.4)
> 
> With Applovin 11.4 game won't compile even with latest android SDK (32 in my case). Compiler throws strange errors (e.g. duplicate classes, internal OpenJDK compiler error, etc)
> 
> Just core-1.7.0 replacement [as mentioned above](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/161#issuecomment-1127758560) didn't work until I reverted Applovin to previous version (5.3.1 / 11.3.3)
> 
> Issue still persists but at least we can compile workable APKs with core aar swap

These errors you mentioned may be because you still have Automatic Dependency Resolution (In Editor or In Build). I had the same problem and had to disable both: **Auto Resolution** and **Auto Resolution On Build**

You probably got duplicate classes because you manually inserted core-1.6.0 that I mentioned, but in the meantime EDM pulled 1.7.0 again.

![image](https://user-images.githubusercontent.com/33549831/169008456-603750d1-7561-4ca9-8659-7ee2f84c1130.png)

**Comment by santoshbagadi** [comment]
@zenith-jacob [`Target API Level`](https://developer.android.com/guide/topics/manifest/uses-sdk-element#target) does no prevent the app from being installed on older devices. It just means that the app is verified compatible with that API level. The `Minimum API Level` is what controls which OS levels are restricted. So, you should be able to safely update to API level 31.

**Comment by Kerydic** [comment]
> @zenith-jacob [`Target API Level`](https://developer.android.com/guide/topics/manifest/uses-sdk-element#target) does no prevent the app from being installed on older devices. It just means that the app is verified compatible with that API level. The `Minimum API Level` is what controls which OS levels are restricted. So, you should be able to safely update to API level 31.

But set targetAPILevel to 31 means that your app is fully tested on every version between minimumAPILevel and Android31, which may not be sure for old version unity users. I think keep targetAPILevel same with minimumAPILevel is better.

**Comment by blueveno** [comment]
same issue

**Comment by serzit** [comment]
Same issue here, after upgrading to Applovin 11.4 :) Unity Version: 2019.4.29f. Workaround did not helped.

**Comment by serzit** [comment]
Found workaround. Open "mainTemplate.gradle" and add line to dependencies field: 
implementation ('androidx.core:core:1.6.0') {force = true}

**Comment by p0w1nd** [comment]
> Set API level 31 instead of 30 is worked for me

My project uses the latest MAX plugin as of today and still got this error.
I tried changing API level (AndroidTargetSdkVersion) from 30 to 33 (which is the biggest showing in my Player Settings) and it works!

**Comment by ersagunkuruca** [comment]
This is still a problem. I have to deal with lots of different projects on different versions of Unity. The first error I got was this, but after updating target api level to 31 I thought I fixed it. But now I am getting lots of other build errors. Some of them come and go by themselves.

**Comment by cihadturhan-st** [comment]
@ersagunkuruca what is the downgraded version of EDM?

**Comment by ersagunkuruca** [comment]
@cihadturhan-st We were using the version that comes with Firebase SDK(1.2.171 I think), the version that worked was the one that comes with MAX. It's 1.2.164. I only checked this with one project, so it may or may not work for every project. Tip: You have to delete External Dependency Manager before importing the older version. Otherwise the newer one just wants to delete the older one.

**Comment by sontungunity** [comment]
i had fix it , target 30->target 31

**Comment by Nintoryan** [comment]
> 

Thank god, you saved my day
