### ISSUE TITLE
Android build fails after upgrading Applovin Max SDKs

### ISSUE THREAD

**Issue by sarebots** [AppLovin/AppLovin-MAX-Unity-Plugin#162]
I just upgraded my AppLovin Max SDK and the android builds are now failing. I'm using Unity 2019.4.38f1 and AppLovin Max version 5.4.0. I also upgraded the following Mediated networks:

Facebook, Fyber, Admob, IronSource, Mintegral, Unity Ads.

I'm not sure which specific update caused the build process to fail, but the following is the error I get:

`
> Configure project :launcher
============================================================================
AppLovin Quality Service Plug-in for Gradle and Android Studio Version 4.4.4
Copyright (c) 2022 AppLovin Ltd. All rights reserved.
============================================================================
[SafeDK] Your project has been updated to support Multi-Dex!
With Multi-Dex support you can use as many methods as you like in your application (no 65K method limit)

> Task :unityLibrary:unity-android-resources:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:unity-android-resources:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:checkReleaseManifest
> Task :unityLibrary:unity-android-resources:checkReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:checkReleaseManifest
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :unityLibrary:unity-android-resources:processReleaseManifest
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:unity-android-resources:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:unity-android-resources:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:prepareLintJar UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:unity-android-resources:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:unity-android-resources:generateReleaseResValues
> Task :unityLibrary:unity-android-resources:generateReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseResValues
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseResources
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseSources UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseResources
> Task :unityLibrary:unity-android-resources:packageReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseRFile
> Task :unityLibrary:unity-android-resources:generateReleaseRFile
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:unity-android-resources:generateReleaseBuildConfig
> Task :unityLibrary:MaxMediationGoogle.androidlib:prepareLintJar UP-TO-DATE
> Task :unityLibrary:unity-android-resources:prepareLintJar UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseSources
> Task :unityLibrary:unity-android-resources:generateReleaseSources
> Task :unityLibrary:MaxMediationGoogle.androidlib:javaPreCompileRelease
> Task :unityLibrary:unity-android-resources:javaPreCompileRelease
> Task :unityLibrary:unity-android-resources:compileReleaseJavaWithJavac
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:unity-android-resources:bundleLibCompileRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibCompileRelease
> Task :unityLibrary:unity-android-resources:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:MaxMediationGoogle.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:unity-android-resources:mergeReleaseShaders
> Task :unityLibrary:MaxMediationGoogle.androidlib:mergeReleaseShaders
> Task :unityLibrary:unity-android-resources:compileReleaseShaders
> Task :unityLibrary:unity-android-resources:generateReleaseAssets
> Task :unityLibrary:MaxMediationGoogle.androidlib:compileReleaseShaders
> Task :unityLibrary:MaxMediationGoogle.androidlib:generateReleaseAssets
> Task :unityLibrary:unity-android-resources:packageReleaseAssets
> Task :unityLibrary:MaxMediationGoogle.androidlib:packageReleaseAssets
> Task :unityLibrary:unity-android-resources:bundleLibRuntimeRelease
> Task :unityLibrary:unity-android-resources:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:unity-android-resources:bundleLibResRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:bundleLibResRelease
> Task :unityLibrary:unity-android-resources:mergeReleaseJniLibFolders
> Task :unityLibrary:MaxMediationGoogle.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:MaxMediationGoogle.androidlib:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:preReleaseBuild
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest UP-TO-DATE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:generateReleaseSources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJar UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseSources
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:FirebaseApp.androidlib:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:FirebaseApp.androidlib:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:generateReleaseRFile
> Task :unityLibrary:javaPreCompileRelease

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:transformNativeLibsWithStripDebugSymbolForRelease
> Task :launcher:mergeReleaseResources
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :launcher:processReleaseManifest
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:processReleaseResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings
91 actionable tasks: 68 executed, 23 up-to-date

UnityEngine.GUIUtility:ProcessEvent (int,intptr)
`

**Comment by sarebots** [comment]
UPDATE: I tried building after removing all Mediation Network SDKs but it still doesn't work. So I guess the problem lies with AppLovin SDK itself. Also, note that I'm using the following custom base gradle template: 

`// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

allprojects {
    buildscript {
        repositories {**ARTIFACTORYREPOSITORY**
            google()
            jcenter()
        }

        dependencies {
            // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
            // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
            // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
            // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
            classpath 'com.android.tools.build:gradle:3.4.3'
            **BUILD_SCRIPT_DEPS**
        }
    }

    repositories {**ARTIFACTORYREPOSITORY**
        google()
        jcenter()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by sarebots** [comment]
UPDATE 2: Downgrading AppLovin to v5.3.1 fixed the issue.

**Comment by MounirAbb** [comment]
downgrading didnt solve it for me

**Comment by MounirAbb** [comment]
it is the facebook plugin . remove facebook adapter and things work damn .

**Comment by zodiac2k** [comment]
Is the v5.3.1 still available somewhere to download?

**Comment by sarebots** [comment]
> Is the v5.3.1 still available somewhere to download?

I just edited the download url from official AppLovin Max Unity SDK download page: [v5.3.1](https://artifacts.applovin.com/unity/com/applovin/applovin-sdk/AppLovin-MAX-Unity-Plugin-5.3.1-Android-11.3.2-iOS-11.3.2.unitypackage)

**Comment by tuhai993** [comment]
I just met same issue, in my case i fixed it by download Build tool 31 and restart Unity

**Comment by zodiac2k** [comment]
> > Is the v5.3.1 still available somewhere to download?
> 
> I just edited the download url from official AppLovin Max Unity SDK download page: [v5.3.1](https://artifacts.applovin.com/unity/com/applovin/applovin-sdk/AppLovin-MAX-Unity-Plugin-5.3.1-Android-11.3.2-iOS-11.3.2.unitypackage)

Thanks for providing the 5.3.1 link. After switching to the previous version Android builds work again.

**Comment by Lorenzo45** [comment]
Thanks for reporting this issue. We've just released Unity Plugin version 5.4.2 that is backwards compatible with Android SDK versions earlier than 31. Let us know you're still experiencing build issues.

**Comment by LDHrez** [comment]
I tried integrate v5.4.2 and I can't build the apk but downgraded to v5.3.1 all works

**Comment by Lorenzo45** [comment]
Could you share the error you're seeing? You might need to update your Gradle version.
