### ISSUE TITLE
Unity Configurable Enter Play Mode Compatibility is missing!

### ISSUE THREAD

**Issue by ahmetyazir22** [AppLovin/AppLovin-MAX-Unity-Plugin#163]
Hi,

We are using "Configurable Enter Play Mode" in our studio & Max SDK keeps spamming console when "Domain Reloading" is disabled.

- How to produce?
1. Add Max SDK to your Unity Project
2. Follow "Project Settings > Editor >  Enter Play Mode Settings"
3. Set related settings as shown below
![Screen Shot 2022-05-17 at 10 07 44](https://user-images.githubusercontent.com/33584207/168750314-407f39c5-68f7-4bd9-8139-05a0367e9644.png)
4. Enter play mode twice

- What Happens?

First play mode: Everything works as expected.
Second play mode: MissingReferenceExceptions is thrown as some callbacks are not removed from previous play mode. 
![Screen Shot 2022-05-17 at 10 04 13](https://user-images.githubusercontent.com/33584207/168749736-36021c7a-14ec-4bb9-a318-1f0920f26dab.png)

- Expected behavior
No exception should be thrown.

Urls:
https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html
https://docs.unity3d.com/Manual/DomainReloading.html

**Comment by thomasmso** [comment]
Hi @ahmetyazir22 - What Unity version are you on?

**Comment by ahmetyazir22** [comment]
I am on 2020.3.27f. The issue appears on all Unity versions which supports Configurable Enter Play Mode & Domain Reloading disabled.

**Comment by thomasmso** [comment]
Cool, we'll check it out in an upcoming sprint and get back to you. It doesn't seem blocking to me.

**Comment by ahmetyazir22** [comment]
Not blocking, just distracting. Thanks for the quick reply 👍

**Comment by alvarshahanji** [comment]
@ahmetyazir22 thanks for reporting this. It is a known issue: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/pull/58. Fixing this had resulted in another issue. We will update you know when we have a fix.
