### ISSUE TITLE
Can't archive iOS anymore - could not reparse object file in bitcode bundle

### ISSUE THREAD

**Issue by zenith-jacob** [AppLovin/AppLovin-MAX-Unity-Plugin#166]
After upgrading **Applovin SDK to 5.4.2** you can't archive an XCode build anymore for iOS. It produces the below error:
**Android SDK: 11.4.2
iOS SDK: 11.4.1**
Unity: 2020.2.1f1

On 5.4.0 it worked.
Same error happens on Cloud Build

`ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/jakub/Desktop/Zenith/BUILD/LumberMaster_iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: Incompatible Objective-C category definitions. Some category metadata may be lost. '/Users/jakub/Library/Developer/Xcode/DerivedData/Unity-iPhone-aqugkfnqtdliwudaduszezuesdzo/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppLovinSDK/AppLovinSDK.framework/AppLovinSDK(UIColor+ALUtils.o)' and '/Users/jakub/Desktop/Zenith/BUILD/LumberMaster_iOS/Libraries/libiPhone-lib.a(PLCrashReportTextFormatter.o) built with different compilers
ld: warning: method '-viewDidAppear:' in category from /Users/jakub/Library/Developer/Xcode/DerivedData/Unity-iPhone-aqugkfnqtdliwudaduszezuesdzo/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityViewControllerBase+iOS.o overrides method from class in /Users/jakub/Library/Developer/Xcode/DerivedData/Unity-iPhone-aqugkfnqtdliwudaduszezuesdzo/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityViewControllerBase.o
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1316.0.21.2.3_0' Reader: '1300.0.29.30_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.30)' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I guess Applovin plugin was build with a newer version of XCode, but it's not available yet to download, at least not from the app store.
My XCode version is: 13.2.1

**Comment by thomasmso** [comment]
The issue is actually with `UnityViewControllerBase.o` using bitcode that is only compatible with a newer version of Xcode that you have in stalled.

**Comment by konsnos** [comment]
Hey there, was this resolved? Because I'm having the same issue and no Xcode update is available.
