### ISSUE TITLE
AppLovinQualityService ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by dodoan-alt** [AppLovin/AppLovin-MAX-Unity-Plugin#167]
Hello team,

I'm getting this bellow issue while uploading our app into Testflight today

`ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/AppLovinQualityService.framework/AppLovinQualityService: frameInfo, isMainFrame, navigationDelegate, setNavigationDelegate:, typeLabel, userContentController, userScripts, world,The app references non-public selectors in Frameworks/UnityFramework.framework/UnityFramework: applicationWillFinishLaunchingWithOptions:, callWithArguments:, didReceiveRemoteNotification:, evaluateScript:, initWithFrame:configuration:, isMainFrame, isString, loadPlugin, navigationDelegate, navigationType, setNavigationDelegate:, targetFrame, toDouble, toString, userContentController. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/`

I uploaded a build successfully with the same MAX & Unity version yesterday

- MAX Plugin: 5.4.2
- Unity : 2021.3.3
- Xcode: 13.4

Could you take a look?

Thanks in advance!
D.

**Comment by thomasmso** [comment]
Looks like it may be an issue on Apple's end - https://github.com/ionic-team/capacitor/issues/5661

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by dodoan-alt** [comment]
It works.

Thank you!
