### ISSUE TITLE
MaxSdk.IsInterstitialReady returns true but ad is not shown

### ISSUE THREAD

**Issue by kashiftasneempro** [AppLovin/AppLovin-MAX-Unity-Plugin#17]
Hi. Mostly it works fine but sometimes `MaxSdk.IsInterstitialReady("interstitialId");` returns true and when I call `MaxSdk.ShowInterstitial(interstitialId);` ad is not shown. I have registered event `MaxSdkCallbacks.OnInterstitialAdFailedToDisplayEvent` and it does not fire as well.

My code snippets:

`MaxSdkCallbacks.OnSdkInitializedEvent += sharedInstance.OnSdkInitializedEvent;`
`MaxSdk.SetSdkKey("sdk_key");`
`MaxSdk.InitializeSdk();`

`MaxSdkCallbacks.OnInterstitialAdFailedToDisplayEvent += sharedInstance.InterstitialFailedToDisplayEvent;`

`if (MaxSdk.IsInterstitialReady(interstitialId)) {`
   ` MaxSdk.ShowInterstitial(interstitialId);`
`}`

I am also caching Ads at appropriate locations using:

`if (!MaxSdk.IsInterstitialReady(interstitialId)) {`
	`MaxSdk.LoadInterstitial(interstitialId);`
`}`

**Comment by thomasmso** [comment]
Hi @kashiftasneempro - do you mind [turning on our SDK's verbose logging](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) and sending them to thomas.so@applovin.com? I'll take care of you there.
