### ISSUE TITLE
Can banner background be transparent instead of opaque?

### ISSUE THREAD

**Issue by p0w1nd** [AppLovin/AppLovin-MAX-Unity-Plugin#171]
In the documentation, there's this sample code:

```
public void InitializeBannerAds()
{
    // Adaptive banners are sized based on device width for positions that stretch full width (TopCenter and BottomCenter).
    // You may use the utility method `MaxSdkUtils.GetAdaptiveBannerHeight()` to help with view sizing adjustments
    MaxSdk.CreateBanner(bannerAdUnitId, MaxSdkBase.BannerPosition.BottomCenter);
    MaxSdk.SetBannerExtraParameter(bannerAdUnitId, "adaptive_banner", "true");

    // Set background or background color for banners to be fully functional
    MaxSdk.SetBannerBackgroundColor(bannerAdUnitId, <YOUR_BANNER_BACKGROUND_COLOR>);
}
```

I have a few questions:

1. Why need to set a background or background color for banners to be `fully functional`? Is there any special reason? I can't seem to see this requirement in other mediations/networks like ironSource, AdMob,...

2. If setting an `opaque` background such as white:
```
  MaxSdk.SetBannerBackgroundColor(bannerAdUnitId, Color.white);
```
... the bottom part of the game screen looks quite ugly - especially on iOS.

Instead, I do this, which set the background to transparent:
```
MaxSdk.SetBannerBackgroundColor(bannerAdUnitId, new Color(1, 1, 1, 0));
```
... and it looks "beautiful". But, I'm wondering if there's any problem with that? E.g. affects on revenue from AppLovin or other ad networks such as AdMob??

Thanks,

**Comment by thomasmso** [comment]
You should be fine to do that. AdMob used to have a policy where the notch area could not be transparent.
