### ISSUE TITLE
AppMetrica with yandex plugin for Max sdk doesn't build for iOS 

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#177]
I'm using AppMetrica 4.3.0 and Yandex for AppLovin (Yandex version is 4.4.2.3 and max SDK version is 5.4.3) 
But I can't build it for iOS, using ```pod install``` the error is : 
```
[!] CocoaPods could not find compatible versions for pod "YandexMobileMetrica":
  In Podfile:
    AppLovinMediationYandexAdapter (= 4.4.2.3) was resolved to 4.4.2.3, which depends on
      YandexMobileAds (= 4.4.2) was resolved to 4.4.2, which depends on
        YandexMobileAds/Static (= 4.4.2) was resolved to 4.4.2, which depends on
          YandexMobileMetrica (< 4.0.0, >= 3.14.1)

    YandexMobileMetrica (= 4.2.0)
```
I also created this issue in the Yandex GitHub repo too, but it seems you have to fix it: https://github.com/yandexmobile/metrica-plugin-unity/issues/51

**Comment by kobyle69** [comment]
No update yet? 25 days

**Comment by Billy-Hu** [comment]
Hi folks! So sorry for the late response. We were working on a new adapter version 5.1.0.0 and it should be live now. Could you please check out this version? Thank you so much for your patience!

**Comment by uchar** [comment]
Hi @Billy-Hu , Thanks, the build issue seems to be resolved now and it's working fine
