### ISSUE TITLE
5.4.4 does not build on android 

### ISSUE THREAD

**Issue by MounirAbb** [AppLovin/AppLovin-MAX-Unity-Plugin#178]
it doesnt build for android 
> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
============================================================================
AppLovin Quality Service Plug-in for Gradle and Android Studio Version 4.5.9
Copyright (c) 2022 AppLovin Ltd. All rights reserved.
============================================================================
[SafeDK] Your project has been updated to support Multi-Dex!
With Multi-Dex support you can use as many methods as you like in your application (no 65K method limit)

> Task :launcher:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:unity-android-resources:preBuild UP-TO-DATE
> Task :unityLibrary:unity-android-resources:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:unity-android-resources:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:unity-android-resources:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:unity-android-resources:compileReleaseRenderscript NO-SOURCE
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :unityLibrary:unity-android-resources:generateReleaseResValues
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:unity-android-resources:generateReleaseResources
> Task :unityLibrary:unity-android-resources:packageReleaseResources
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:unity-android-resources:extractDeepLinksRelease
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:unity-android-resources:processReleaseManifest
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:unity-android-resources:parseReleaseLocalResources
> Task :unityLibrary:unity-android-resources:generateReleaseRFile
> Task :unityLibrary:unity-android-resources:compileReleaseLibraryResources
> Task :unityLibrary:generateReleaseRFile
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:unity-android-resources:generateReleaseBuildConfig
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:unity-android-resources:javaPreCompileRelease
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE

> Task :launcher:processReleaseManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

> Task :unityLibrary:packageReleaseAssets
> Task :launcher:mergeReleaseResources
> Task :unityLibrary:unity-android-resources:compileReleaseJavaWithJavac

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
29 actionable tasks: 21 executed, 8 up-to-date

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by ura8627** [comment]
Hi @MounirAbb Same Issue. Find Any Solution?

**Comment by MounirAbb** [comment]
> Hi @MounirAbb Same Issue. Find Any Solution?

they didnt solve anything . ill contact support then

**Comment by Kidkiwi** [comment]
Any update?
