### ISSUE TITLE
2.4.8 Editor Prefabs don't work in Unity 2018.3

### ISSUE THREAD

**Issue by hh-mattking** [AppLovin/AppLovin-MAX-Unity-Plugin#18]
Hello,

I've just updated to 2.4.8 and the 4 built in Prefabs for displaying content in the Editor have missing Unity UI related MonoBehaviours. 

I haven't investigated this thoroughly yet, but it seems to be that the Prefabs have been authored in Unity 2019. Previously it seems like the Prefabs were authored in Unity 2018. I'm not completely sure but it looks like the GUIDs for some of the Unity UI MonoBehaviours have changed between 2018 and 2019.

**Repro Steps**
* Create a new Unity project in Unity 2018.3.9f1
* Import `AppLovin-MAX-Unity-Plugin-2.4.8-Android-9.12.5-iOS-6.12.5.unitypackage`
* Browse to `Assets/MaxSdk/Prefabs/Rewarded.prefab`
* Open the prefab and note the missing components
* Some of the specific missing components are `CanvaScaler` and `GraphicRaycaster`.

I'd suggest that all releases be made from the lowest version of Unity that you actively support.

Again, not thoroughly investigated but it does look like the prefabs authored in 2018 work in 2019, just not the other way around.

**Comment by Lorenzo45** [comment]
Thanks for bringing this to our attention! We're investigating and should have a fix out soon.

**Comment by thomasmso** [comment]
We've released a new AppLovin MAX Unity Plugin v2.4.9 which addresses the issue.
