### ISSUE TITLE
When build for android of gradle, always mention "Received status code 403 from server: Forbidden."

### ISSUE THREAD

**Issue by chenqiu1988** [AppLovin/AppLovin-MAX-Unity-Plugin#184]
### MAX Plugin Version

5.4.4

### Unity Version

2019.4.36

### Device/Platform Info

Android 11(Target API Level 30)

### Current Behavior

when I build with gradle. Always mention the error:
What went wrong:
A problem occurred configuring project ':unityLibrary'.
> Could not resolve all artifacts for configuration ':unityLibrary:classpath'.
   > Could not resolve com.android.tools.build:gradle:5.1.1.
     Required by:
         project :unityLibrary
      > Could not resolve com.android.tools.build:gradle:5.1.1.
         > Could not get resource 'https://artifacts.applovin.com/android/com/android/tools/build/gradle/5.1.1/gradle-5.1.1.pom'.
            > Could not GET 'https://artifacts.applovin.com/android/com/android/tools/build/gradle/5.1.1/gradle-5.1.1.pom'. Received status code 403 from server: Forbidden

### Expected Behavior

Expected to build succeed.

### How to Reproduce

Gradle version 5.1.1. 
when I copy the url in chrome, “https://artifacts.applovin.com/android/com/android/tools/build/gradle/5.1.1/gradle-5.1.1.pom”

return：
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>K911FFS0V7B9WJTJ</RequestId>
<HostId>cIum8kBZdiDNx43WpLTtZIaUeD2N4+QO/1Qo/+PV1t88/a4u2vmWz+2OPmBhybl5po8zQ5w7Pvo=</HostId>
</Error>

### Additional Info

How to solve the problem? change vpn, clear cache, not work. thank you.

**Comment by HeejongCho** [comment]
Are you using custom `baseTemplate.gradle` file? Unless you explicitly need it for certain reason, try disabling it.

It seems like when `AppLovinProcessGradleBuildFile` sees `baseTemplate.gradle`, it adds a line `maven { url 'https://artifacts.applovin.com/android' }` to repositories section and that repository is denying our access :(.

**Comment by thomasmso** [comment]
Thanks for raising this - we're investigating

**Comment by thomasmso** [comment]
Can either of you send the 1) full output of `time curl  -v -s -o artifacts.zip https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/applovin-ios-sdk-11.0.0.zip` and 2) `curl ifconfig.me` to thomas.so@applovin.com?

**Comment by thomasmso** [comment]
Fixed in v5.6.0
