### ISSUE TITLE
Empty placement value

### ISSUE THREAD

**Issue by akarsh-tenjin** [AppLovin/AppLovin-MAX-Unity-Plugin#186]
### MAX Plugin Version

5.4.4

### Unity Version

2019.2.21f1

### Device/Platform Info

Android 12

### Current Behavior

Empty placement value when using the method `MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent`

### Expected Behavior

Placement value to be returned from the method `MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent`

### How to Reproduce

1. Integrate applovin max unity package
2. Initialize the applvoin max unity sdk
3. request for a banner ad placement
4. log the values for the method  `MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent`
5. Notice the placement value is empty

### Additional Info

log,

```
"max": {
        "network_name": "Mintegral",
        "ad_unit_id": "5bd49836652e3e72",
        "ad_revenue_currency": "USD",
        "creative_id": "62d086f187143800210a7f8x",
        "country": "ES",
        "network_placement": "1715940",
        "format": "BANNER",
        "placement": "",
        "publisher_revenue_micro": "11.29371",
        "revenue": "1.129371E-5",
        "publisher_revenue_decimal": "0.00001129371",
        "revenue_precision": "exact"
      }
      ```

**Comment by santoshbagadi** [comment]
Just to be sure, when you say the following, you mean interstitial right?

> 3. request for a banner ad placement

To set a placement for interstitial ads, you need to call the `ShowInterstitial` method with the placement ID

`MaxSdk.ShowInterstitial(adUnitId, placement)`.

**Comment by akarsh-tenjin** [comment]
> Just to be sure, when you say the following, you mean interstitial right?
> 
> > 3. request for a banner ad placement
> 
> To set a placement for interstitial ads, you need to call the `ShowInterstitial` method with the placement ID
> 
> `MaxSdk.ShowInterstitial(adUnitId, placement)`.

Sorry I forgot to make code changes when creating the issue. I had a copy-paste error.

The issue was with banner AdFormat.

```
        MaxSdkCallbacks.OnSdkInitializedEvent += (MaxSdkBase.SdkConfiguration sdkConfiguration) =>
        {
            // AppLovin SDK is initialized, start loading ads
        };
        MaxSdk.SetSdkKey(applovinKey);
        MaxSdk.SetUserId("USER_ID");
        MaxSdk.InitializeSdk();
        MaxSdk.CreateBanner(_banner, MaxSdkBase.BannerPosition.TopCenter);
        MaxSdk.SetBannerBackgroundColor(_banner, Color.yellow);
        MaxSdk.ShowBanner(_banner);
        MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent += OnAdRevenuePaidEvent;
```

Hope this helps in the investigation.

**Comment by santoshbagadi** [comment]
@akarsh-tenjin , couple of things 
1. Please make sure to call all Ad APIs within the `OnSdkInitializedEvent` callback as shown below
```        
        MaxSdkCallbacks.OnSdkInitializedEvent += (MaxSdkBase.SdkConfiguration sdkConfiguration) =>
        {
            // AppLovin SDK is initialized, start loading ads
            MaxSdk.CreateBanner(_banner, MaxSdkBase.BannerPosition.TopCenter);
            MaxSdk.SetBannerPlacement(_banner, "your_placement_herer");
            MaxSdk.SetBannerBackgroundColor(_banner, Color.yellow);
            MaxSdk.ShowBanner(_banner);
            MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent += OnAdRevenuePaidEvent;
        };
        MaxSdk.SetSdkKey(applovinKey);
        MaxSdk.SetUserId("USER_ID");
        MaxSdk.InitializeSdk();
```
2. I see that the banner placement is not being set. You can set the banner placement by calling `MaxSdk.SetBannerPlacement(adUnitIdentifier, placement)`.

**Comment by akarsh-tenjin** [comment]
Thank you @santoshbagadi for helping out.
This resolves the issue.
