### ISSUE TITLE
OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed

### ISSUE THREAD

**Issue by sonpro107** [AppLovin/AppLovin-MAX-Unity-Plugin#187]
### MAX Plugin Version

5.4.5

### Unity Version

2021.3.6f1 LTS

### Device/Platform Info

Untiy Editor

### Current Behavior

Exception: OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details.
UnityEditor.Android.PostProcessor.Tasks.CheckUserResources.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <0bc7e9c04c1540528b26863a0cb726ae>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <0bc7e9c04c1540528b26863a0cb726ae>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PrepareForBuild (UnityEditor.BuildOptions options, UnityEditor.BuildTarget target) (at <0bc7e9c04c1540528b26863a0cb726ae>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PrepareForBuild (UnityEditor.BuildOptions options, UnityEditor.BuildTarget target) (at <0bc7e9c04c1540528b26863a0cb726ae>:0)
UnityEditor.PostprocessBuildPlayer.PrepareForBuild (UnityEditor.BuildOptions options, UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target) (at <44a70d1b13cf47e29810e30f45ffae08>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

### Expected Behavior

Error building Player: Exception: OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details.

Build completed with a result of 'Failed' in 52 seconds (51968 ms)
0x00007ff6ec7a930d (Unity) StackWalker::GetCurrentCallstack
0x00007ff6ec7affe9 (Unity) StackWalker::ShowCallstack
0x00007ff6ed71d613 (Unity) GetStacktrace
0x00007ff6eddb223d (Unity) DebugStringToFile
0x00007ff6eb9147e2 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000020f3a0dfc53 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000020f3a0dfb6b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000020f3a0df8b0 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000020f3a0df775 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x000002100b2bdefb (Mono JIT Code) UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
0x000002100b2ba533 (Mono JIT Code) UnityEditor.BuildPlayerWindow:CallBuildMethods (bool,UnityEditor.BuildOptions)
0x0000020f8247c1a3 (Mono JIT Code) UnityEditor.BuildPlayerWindow:GUIBuildButtons (UnityEditor.Modules.IBuildWindowExtension,bool,bool,bool,UnityEditor.Build.BuildPlatform,UnityEditor.Modules.IBuildPostprocessor)
0x0000020f8246c3b3 (Mono JIT Code) UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings ()
0x0000020f6145cd33 (Mono JIT Code) UnityEditor.BuildPlayerWindow:OnGUI ()
0x0000020f5e68e26a (Mono JIT Code) UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect)
0x0000020f5e68e083 (Mono JIT Code) UnityEditor.DockArea:DrawView (UnityEngine.Rect)
0x0000020f5e66f9db (Mono JIT Code) UnityEditor.DockArea:OldOnGUI ()
0x0000020f3a22d03f (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
0x0000020f3a22c13b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
0x0000020f5e96f0eb (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
0x0000020f5e96ef53 (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
0x0000020f5e96ea9b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
0x0000020f5e96e983 (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
0x0000020f39e1b48b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleEvent (UnityEngine.UIElements.EventBase)
0x0000020f39e0e9d8 (Mono JIT Code) UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
0x0000020f5e96d81b (Mono JIT Code) UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x0000020f39e0cbde (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
0x0000020f39e0c6db (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x0000020f39e12aeb (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
0x0000020f39e11013 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:OpenGate ()
0x0000020f39e10f4b (Mono JIT Code) UnityEngine.UIElements.EventDispatcherGate:Dispose ()
0x0000020f39e0c963 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x0000020f39e0c093 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
0x0000020f39e0bf0b (Mono JIT Code) UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
0x0000020f3a1eec7b (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
0x0000020f3a1ee723 (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
0x0000020f3a1ee53f (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
0x0000020f3a1ee45b (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
0x0000020f3a1ee2ad (Mono JIT Code) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
0x0000020f3a1ee366 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr_intptr& (object,intptr,intptr,intptr)
0x00007ffac894e4b4 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffac888e764 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffac888e8fc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff6ec6cdac4 (Unity) scripting_method_invoke
0x00007ff6ec6c8644 (Unity) ScriptingInvocation::Invoke
0x00007ff6ec6c1f65 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff6ec7caeba (Unity) Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent
0x00007ff6ed205e86 (Unity) GUIView::ProcessRetainedMode
0x00007ff6ed74dceb (Unity) GUIView::OnInputEvent
0x00007ff6ed205c9a (Unity) GUIView::ProcessInputEvent
0x00007ff6ed74ec3b (Unity) GUIView::ProcessEventMessages
0x00007ff6ed74880c (Unity) GUIView::GUIViewWndProc
0x00007ffb2f72e858 (USER32) CallWindowProcW
0x00007ffb2f72e299 (USER32) DispatchMessageW
0x00007ff6ed723633 (Unity) MainMessageLoop
0x00007ff6ed72805b (Unity) WinMain
0x00007ff6eeaab42e (Unity) __scrt_common_main_seh
0x00007ffb2f8d7034 (KERNEL32) BaseThreadInitThunk
0x00007ffb2fa42651 (ntdll) RtlUserThreadStart

### How to Reproduce

- build apk unity

**Comment by xxGAGASxx** [comment]
The same issue. Any news ?
