### ISSUE TITLE
[Unity Editor] Inconsistent Asset labels between Windows / non-Windows worktrees

### ISSUE THREAD

**Issue by Pyr3z** [AppLovin/AppLovin-MAX-Unity-Plugin#189]
### MAX Plugin Version

5.4.5

### Unity Version

2020.3.30f1

### Device/Platform Info

Unity Editor

### Current Behavior

- This is a lower priority issue, though I would not call it purely cosmetic because it _has_ taken time out of our devs to fixup git branches and perform unnecessary manual merge conflict resolutions of meta files.

When a developer on **Mac/Linux** commits meta files for MaxSdk files, those meta files contain asset labels containing forward slashes to Git. These look like: `al_max_export_path-MaxSdk/AppLovin/Editor/Dependencies.xml`.

When a developer on **Windows** then pulls these meta files and opens the Editor, the labels auto "fix" themselves to use backslashes. For example: `al_max_export_path-MaxSdk\AppLovin\Editor\Dependencies.xml`.

—and vice versa.

### This creates a certain set of files that are _always_ dirtied for one dev or the other, depending on who committed last.

![MAX Unity  non-windows + windows meta file labels inconsistent](https://user-images.githubusercontent.com/23016109/182448395-e5f624de-e38f-4697-93a2-99ba1bf17c91.png)

### **89 dirtied files**, to be exact:

![MAX Unity  89 files dirtied every time](https://user-images.githubusercontent.com/23016109/182448865-08a871cb-55ba-428f-be53-080986495b79.png)

### Reiteration:

When a developer on **Mac/Linux** commits meta files for MaxSdk files, those meta files contain asset labels containing forward slashes to Git. These look like: `al_max_export_path-MaxSdk/AppLovin/Editor/Dependencies.xml`.

When a developer on **Windows** then pulls these meta files and opens the Editor, the labels auto "fix" themselves to use backslashes—for example: `al_max_export_path-MaxSdk\AppLovin\Editor\Dependencies.xml`.

### Additional Info

I think this should be a relatively easy fix, maybe even less than one line of code: Translate backslashes to forward slashes in asset labels!

**Comment by Fraggle** [comment]
Hello !

I was just going to report a similar issue. It's indeed a bit annoying in heterogenous environnement like ours (macos + windows). We have to constantly be careful about theses files when committing.

I see no answer or activity on this issue, can I help somehow to fix it ?

(the unity plug in is not open source, right ?)

**Comment by santoshbagadi** [comment]
@Fraggle , sorry for the delay here. We'll have a fix for this in an upcoming release.

**Comment by AntonPetrov83** [comment]
Hi! This issue annoys us as well, please fix asap.
