### ISSUE TITLE
Put MAX SDK in an assembly

### ISSUE THREAD

**Issue by JasperChimpWorks** [AppLovin/AppLovin-MAX-Unity-Plugin#19]
Currently (2.4.9) the MAX SDK does not use assembly definitions and gets compiled into the default unity assembly (Assembly-CSharp.dll).

I would like to reference the MAX SDK code from code that lives in one of my own assemblies, but I cannot reference the default assembly. Is it possible to put the MAX SDK code in its own assembly so I can reference it?

Assemblies in Unity: https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by thomasmso** [comment]
Hey @JasperChimpWorks  - We'll look into it and add it to the queue. Will update thread when released. Thank you!

**Comment by thomasmso** [comment]
The fix has been released in AppLovin MAX Unity Plugin v2.4.10.

**Comment by emilkastbjerg** [comment]
Hey @JasperChimpWorks this optimisation was re-released in the latest AppLovin MAX Unity Plugin v2.4.15.
