### ISSUE TITLE
Unable to pass local extras to BannerView

### ISSUE THREAD

**Issue by pm-preety-narvekar** [AppLovin/AppLovin-MAX-Unity-Plugin#192]
### MAX Plugin Version

5.4.5

### Unity Version

2019.4.40f1

### Device/Platform Info

iOS

### Current Behavior

For iOS:
The value in `MaxSdk.SetBannerLocalExtraParameter` API is expected as `object` of type `IntPtr`. If I use below code:
```
string str2 = "def_local_val";
IntPtr ptr2 = Marshal.StringToHGlobalUni(str2);
MaxSdk.SetBannerLocalExtraParameter(bannerAdUnitId, "def_local_key", ptr2);
```
or 
```
string str2 = "def_local_val";
IntPtr ptr2 = (IntPtr)GCHandle.Alloc(str2);
MaxSdk.SetBannerLocalExtraParameter(bannerAdUnitId, "def_local_key", ptr2);
```
it crashes in:
```
void _MaxSetBannerLocalExtraParameter(const char *adUnitIdentifier, const char *key, MAUnityRef value)
```

### Expected Behavior

1. It should not crash.
2. Could you provide an example of passing local extras to all ads, banner, interstitial and rewarded? We can't find it in the document.
3. Could you provide it for iOS and Android both?

### How to Reproduce

Please use below code:
```
MaxSdk.CreateBanner(<bannerAdUnitId>, MaxSdkBase.BannerPosition.BottomCenter);
// set callbacks

string str1 = "def_local_key";
IntPtr ptr1 = Marshal.StringToHGlobalUni(str1);
MaxSdk.SetBannerLocalExtraParameter(bannerAdUnitId, "def_local_key", ptr1);

MaxSdk.ShowBanner(bannerAdUnitId);
```

**Comment by santoshbagadi** [comment]
@pm-preety-narvekar could you provide more details as to what you are trying to use the `SetBannerLocalExtraParameters` for.

Also, could you share the stacktrace and the exception for the crash.

**Comment by pm-preety-narvekar** [comment]
Thanks @santoshbagadi for your quick response.
We have written custom event adapters for mediation through MAX (in android and ios). In those, we need to get few parameters from app developers, where they pass these values in MAX ad view's `localExtras`. 

The API works fine with Android and iOS SDK, but failing for unity.

For the exception, please check the below screenshot. 

<img width="1388" alt="Screenshot 2022-08-12 at 1 30 42 PM" src="https://user-images.githubusercontent.com/47360915/184311326-c20833b5-70c7-4f08-a156-b1f853201b3e.png">

Also, can you provide an example API for setting `SetBannerLocalExtraParameters`?

**Comment by santoshbagadi** [comment]
It looks like the `ptr1` that is created is not being retained. Its reference is being cleared by the time it is passed to our plugin. You'd have to find a way to cache the created `IntPtr` before passing it to AppLovin MAX plugin.

**Comment by pm-preety-narvekar** [comment]
I have made the `IntPtr` as the class level parameter. I think, below code should retain `ptr1`.  Please check my below code in unity:
```
public class Player : MonoBehaviour
{
       string str1 = "abc_local_val";
       IntPtr ptr1 = IntPtr.Zero;

       void Start()
       {
              MaxSdkCallbacks.OnSdkInitializedEvent += sdkConfiguration =>
              {
                     InitializeBannerAds();
              };

              MaxSdk.SetSdkKey(sdkKey);
              MaxSdk.InitializeSdk();
         }
       
       public void InitializeBannerAds()
       {
             MaxSdk.CreateBanner(bannerAdUnitId, MaxSdkBase.BannerPosition.BottomCenter);

             MaxSdkCallbacks.Banner.OnAdLoadedEvent += OnBannerAdLoadedEvent;
             MaxSdkCallbacks.Banner.OnAdLoadFailedEvent += OnBannerAdLoadFailedEvent;

             ptr1 = (IntPtr)GCHandle.Alloc(str1);
             MaxSdk.SetBannerLocalExtraParameter(bannerAdUnitId, "abc_local_key", ptr1);
             MaxSdk.ShowBanner(bannerAdUnitId);
    }
}
``` 
Could you please check or provide the example for `MaxSdk.SetBannerLocalExtraParameter` in both android and iOS? The documentation is also not available for the same.

Thanks!

**Comment by pm-preety-narvekar** [comment]
Hi @santoshbagadi ,
Do you have any update on this, as this is a kind of blocker for us?

Thanks in advance!

**Comment by santoshbagadi** [comment]
The issue is that the created IntPtr is not being retained on the Objective-C side. You'd have to create an `NSString` on the Objective-C side, cache it and then pass it's pointer to our SDK. 

A simple implementation would look like this. 

On the C# side
```
[DllImport("__Internal")]
internal static extern IntPtr _CreateStringIntPtr(string value);

public void InitializeBannerAds()
{
     MaxSdk.CreateBanner(bannerAdUnitId, MaxSdkBase.BannerPosition.BottomCenter);

     MaxSdkCallbacks.Banner.OnAdLoadedEvent += OnBannerAdLoadedEvent;
     MaxSdkCallbacks.Banner.OnAdLoadFailedEvent += OnBannerAdLoadFailedEvent;

     MaxSdk.SetBannerLocalExtraParameter(bannerAdUnitId, "abc_local_key", _CreateStringIntPtr("abc_local_val"));
     MaxSdk.ShowBanner(bannerAdUnitId);
}
```

On the native iOS side
```
#define NSSTRING(_X) ( (_X != NULL) ? [NSString stringWithCString: _X encoding: NSStringEncodingConversionAllowLossy] : nil)

typedef const void *NSStringTypeRef;

NSStringTypeRef _CreateStringIntPtr(char *value)
{
    NSString *stringValue = NSSTRING(value);
    // Cache the stringValue in a dictionary or something
    
    return (__bridge NSStringTypeRef)dictionary;
}
```

**Comment by pm-preety-narvekar** [comment]
Great! Thanks @santoshbagadi for your quick reply. This solves our issue.
