### ISSUE TITLE
[5.4.6] Unable to install on iOS device

### ISSUE THREAD

**Issue by pixeption** [AppLovin/AppLovin-MAX-Unity-Plugin#195]
### MAX Plugin Version

5.4.6

### Unity Version

2020.3.38f1

### Device/Platform Info

iOS 15

### Current Behavior

- Unable to install the build on iOS device with all method (directly, adhoc, firebase app distribution) with below error
`Unable to install "App"` and
`The code signature version is no longer supported`

- Unable to upload to AppStore (even though can built successfully) with the below error
`Invalid Bundle Structure - The binary file 'NonogramLife.app/Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. With error code  `

### How to Reproduce

- Install AppLovin Unity 5.4.6
- Install Facebook Mediation Network

### Additional Info

After checking the change, I notice that `FBAudienceNetwork.xcframework` was added to `dynamicLibrariesToEmbed` in `MaxPostProcessBuildiOS.cs` even though look like it's static.
Remove `FBAudienceNetwork.xcframework` solve the issue in my case.

**Comment by andymads** [comment]
I experienced this issue too. Removing the Facebook adapter fixed it.

**Comment by thomasmso** [comment]
Hi @andymads - We're aware of the issue and are working on a fix.

**Comment by santoshbagadi** [comment]
Hi @pixeption @andymads , we've just released a fix for this in our latest Unity plugin [version 5.4.7](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_4_7).

**Comment by andymads** [comment]
> Hi @pixeption @andymads , we've just released a fix for this in our latest Unity plugin [version 5.4.7](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_4_7).

Thanks guys.
