### ISSUE TITLE
When uploading Vungle adapter from 6.12.0.0 to 6.12.0.1 the build gradle failed

### ISSUE THREAD

**Issue by AnnoyingFreak** [AppLovin/AppLovin-MAX-Unity-Plugin#197]
### MAX Plugin Version

5.4.7

### Unity Version

2020.3.26f1

### Device/Platform Info

Android

### Current Behavior

**When uploading Vungle adapter from 6.12.0.0 to 6.12.0.1 the build gradle fails with the following error**:

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2020.3.26f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2020.3.26f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:collectReleaseDependencies'.
> Could not resolve all task dependencies for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.applovin.mediation:vungle-adapter:6.12.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://jcenter.bintray.com/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - file:/C:/Users/Victor/Documents/Proyectos/FNF Sarvente Hit/Temp/gradleOut/unityLibrary/libs/vungle-adapter-6.12.0.1.jar
       - file:/C:/Users/Victor/Documents/Proyectos/FNF Sarvente Hit/Temp/gradleOut/unityLibrary/libs/vungle-adapter.jar
       - https://maven.google.com/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://artifactory.appodeal.com/artifactory/appodeal/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://artifactory.appodeal.com/appodeal/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - file:/C:/Users/Victor/Documents/Proyectos/FNF Sarvente Hit/Assets/GeneratedLocalRepo/GooglePlayGames/Editor/m2repository/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://artifactory.bidmachine.io/bidmachine/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://artifact.bytedance.com/repository/pangle/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://s3.amazonaws.com/smaato-sdk-releases/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - file:/C:/Users/Victor/.m2/repository/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
       - https://repo.maven.apache.org/maven2/com/applovin/mediation/vungle-adapter/6.12.0.1/vungle-adapter-6.12.0.1.pom
     Required by:
         project :launcher > project :unityLibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
=============================================================================
AppLovin Quality Service Plug-in for Gradle and Android Studio Version 4.5.14
Copyright (c) 2022 AppLovin Ltd. All rights reserved.
=============================================================================
[SafeDK] Your project has been updated to support Multi-Dex!
With Multi-Dex support you can use as many methods as you like in your application (no 65K method limit)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <fc7be335e11c4872b360501993848bfb>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <fc7be335e11c4872b360501993848bfb>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <fc7be335e11c4872b360501993848bfb>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <55729f52d042492e9efc384182ae2feb>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

### Expected Behavior

Build completed with a result of 'Succeeded'

### How to Reproduce

For me it was just upgrading to Vungle adapter 6.12.0.1. Then building for android failed.

**Comment by santoshbagadi** [comment]
Hi @AnnoyingFreak , we are not able to reproduce the issue. There might have been a delay in the maven repo being propagated. Could you please try again and see if you are still seeing the issue.

**Comment by AnnoyingFreak** [comment]
Hi @santoshbagadi and thanks for your time.

I have tried today without no other changes in the project and after a few minutes of tension.. it works!!
Yesterday I build with other networks and the platforms upgrading also... or perhaps it was simply a delay (I tried at least 5 times).

Well, there's no issue anymore.
