### ISSUE TITLE
Failed to load plugin data. Please click retry or restart integration manager

### ISSUE THREAD

**Issue by devendraatxpertaapp** [AppLovin/AppLovin-MAX-Unity-Plugin#200]
### MAX Plugin Version

5.5.1

### Unity Version

2020.3.24f1

### Device/Platform Info

Unity Editor 

### Current Behavior

- not able to see the integration manager in mac os  
- it's working in windows pc

![Window](https://user-images.githubusercontent.com/113201722/192732913-948f2941-f3a4-4dc9-9db6-9de99894b44c.png)

### Expected Behavior

- able to see and edit 

![WIndows Priveiw](https://user-images.githubusercontent.com/113201722/192732964-1aa70775-e32d-4c46-a495-692a2404e19d.png)

### How to Reproduce

-imported plugin in unity editor and open integration manager .

**Comment by santoshbagadi** [comment]
@devendraatxpertaapp is there any chance that the Mac doesn't have an internet connection? Or the Unity app does not have the necessary permissions to make a network request?

Also, are you seeing any related logs in the Unity console?

**Comment by devendraatxpertaapp** [comment]
I did try that but there is no internet issue I tried testing with unity services.
