### ISSUE TITLE
"A Native Collection has not been disposed, resulting in a memory leak" error is thrown during build

### ISSUE THREAD

**Issue by ahmetyazir22** [AppLovin/AppLovin-MAX-Unity-Plugin#201]
### MAX Plugin Version

5.5.1

### Unity Version

2021.3.11f

### Device/Platform Info

Editor build

### Current Behavior

"A Native Collection has not been disposed, resulting in a memory leak" error is thrown while building for iOS. Jenkins builds fail due to this error in our pipeline.
<img width="986" alt="Screen Shot 2022-10-11 at 13 25 34" src="https://user-images.githubusercontent.com/33584207/195067320-f232d5e7-5520-427a-a2c3-96e22d40a428.png">

### Expected Behavior

Builds should succeed without giving any errors.

### How to Reproduce

Unity 2021.3.21f
Applovin Max Plugin 5.5.1
Latest URP, Jobs & Burst packages are installed as default by Unity.

"Menu > Jobs > Leak Detection > On"

**Comment by santoshbagadi** [comment]
Hi @ahmetyazir22 , thank you for reporting the issue. We'll get a fix out in an upcoming release and update here when we released the fix.

**Comment by santoshbagadi** [comment]
@ahmetyazir22 , we have added a fix for this in our latest plugin release [version 5.5.6](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_5_6).
