### ISSUE TITLE
Editor: Interstital and Rewarded Prefab must NOT contains EventSystem

### ISSUE THREAD

**Issue by TheoSabattie** [AppLovin/AppLovin-MAX-Unity-Plugin#203]
### MAX Plugin Version

5.5.3

### Unity Version

2021.3.9f1

### Device/Platform Info

Editor

### Current Behavior

Hello', 

Thanks for your plugin! :)

When we show Interstitial/Rewarded in the Editor, there is a lot of warning because there is **2** EventSystem in the scene.  

### Expected Behavior

We shouldn't see those warnings.

### How to Reproduce

Create a basic UI in you scene (that will add a EventSystem in the scene). 
Show an interstitial or a rewarded. Look your console.

### Additional Info

Resolution:  
Remove Event System from the Rewarded and Interstitial prefab.  
Instantiate prefab, then, check if EventSystem.current is NULL before adding one.

**Comment by JonathanLiuApp** [comment]
Hi @TheoSabattie , thanks for reporting this. We are working on a fix and will update here when a fix is released.

**Comment by JonathanLiuApp** [comment]
Fixed in v5.6.0
