### ISSUE TITLE
MAX Plugin 5.5.4 doesn't build on iOS

### ISSUE THREAD

**Issue by ltk-daniel-zapater** [AppLovin/AppLovin-MAX-Unity-Plugin#204]
### MAX Plugin Version

5.4.4

### Unity Version

2019.4.30f1

### Device/Platform Info

iOS

### Current Behavior

iOS Xcode workspace doesn't build.

### Expected Behavior

Xcode build success.

### How to Reproduce

- Upgrade AppLovin SDK via Integration Manager to Max-Unity-5.5.4, SDK version 11.5.3
- Make an iOS build
- Try to build on Xcode

### Additional Info

The problem seems to be a missing pointer at MAUnityPlugin.mm:394

**Comment by harryarakkal** [comment]
Thanks for bringing this up! I'll check this out

**Comment by santoshbagadi** [comment]
@ltk-daniel-zapater we have just released [v5.5.5](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_5_5) of our plugin that fixes this issue.
