### ISSUE TITLE
iOS Build Issues

### ISSUE THREAD

**Issue by joshua-matchala** [AppLovin/AppLovin-MAX-Unity-Plugin#205]
Since updating to the latest unity sdk version 5.5.5, the project now fails to compile and install pods for ios.

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/75960319/196818803-e6f18e5a-e497-44cf-b611-ddaf24514710.png">

Which results in this error while building:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/75960319/196818912-34498404-f47b-4a51-8559-cc57d638572b.png">

Using unity version 
<img width="181" alt="image" src="https://user-images.githubusercontent.com/75960319/196818948-91cbfe03-c365-4582-b5a7-aa26c8b45bea.png">
Xcode Version
<img width="218" alt="image" src="https://user-images.githubusercontent.com/75960319/196818977-dec9cbca-832e-4555-9f87-9433760686ec.png">

**Comment by santoshbagadi** [comment]
Hi @joshua-matchala , this seems like a CocoaPods issue. Could you please try updating your CocoPods and see if that fixes your issue: https://github.com/CocoaPods/CocoaPods/issues/10604

**Comment by joshua-matchala** [comment]
Sorry forgot to mention. Using the latest version of cocopods as well.

**Comment by santoshbagadi** [comment]
In the thread, they mentioned that if you are on the latest CocoPods version, you can try the following: https://github.com/CocoaPods/CocoaPods/issues/10604#issuecomment-831001475

> If your cocoapod is on latest version and you also did gem update xcodeproj and still face this issue, just uninstall and install the xcodeproj again and it will work like a charm, this is mainly due to permission issue from the gem level and this happens mostly after you upgrade your xcode or iOS sdk version.
> 
> gem uninstall xcodeproj
> gem install xcodeproj

Also, to make sure this is specific to AppLovin, could you try removing AppLovin and see if the issue goes away?

**Comment by matejse** [comment]
We have the same issue after updating to the latest version of MaxSDK

**Comment by santoshbagadi** [comment]
@matejse , as mentioned in the error, it seems like you may have conflicting versions of Facebook SDK. If you are using a Facebook Unity plugin separately, please make sure that both the AppLovin Facebook adapter and Facebook unity plugin are on the same version.

**Comment by matejse** [comment]
@santoshbagadi It helped, thanks 👍
