### ISSUE TITLE
Ad review enable build error Android

### ISSUE THREAD

**Issue by Akelliona** [AppLovin/AppLovin-MAX-Unity-Plugin#206]
### MAX Plugin Version

5.5.5

### Unity Version

2022.2.0b10

### Device/Platform Info

Android

### Current Behavior

With ad review enable such error appears in console

> Error [AppLovin MAX] Failed to add AppLovin Quality Service plugin. Quality Service Plugin Added?: False, Quality Service Repo added?: False, Quality Service dependency added?: False
> UnityEngine.Debug:LogError (object)
> MaxSdkLogger:UserError (string) (at Assets/MaxSdk/Scripts/MaxSdkLogger.cs:55)
> AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:GenerateUpdatedBuildFileLines (System.Collections.Generic.List`1<string>,string,bool) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:422)
> AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:AddQualityServiceBuildScriptLines (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:123)
> AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessGradleProject:OnPostGenerateGradleAndroidProject (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessAndroidGradle.cs:28)
> UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
> 

### Expected Behavior

Project build successfully 

### How to Reproduce

1. Turn on Max enable Ad review in Integration Manager
2. Try to build project for Android device

### Additional Info

gradle file for project

```
plugins {
    // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
    // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
    // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
    // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by santoshbagadi** [comment]
Hi, sorry for the delay here. Could you please share the `build.gradle` files for the root project and `launcher` module of the exported project. 

Also, are you using any custom Gradle template files?

**Comment by joshua-matchala** [comment]
`apply plugin: 'com.android.library'


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'com.google.android.gms.play-services-ads-21.4.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-dynamic-links-21.1.0', ext:'aar')
    implementation(name: 'com.unity3d.ads.unity-ads-4.5.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-crashlytics-18.3.2', ext:'aar')
    implementation(name: 'com.google.android.play.core-common-2.0.2', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-installations-interop-17.1.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-base-18.1.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-viewmodel-2.0.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-config-21.2.0', ext:'aar')
    implementation(name: 'androidx.room.room-runtime-2.2.5', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-tasks-18.0.2', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-measurement-connector-19.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-appset-16.0.1', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-ads-identifier-18.0.0', ext:'aar')
    implementation(name: 'androidx.core.core-1.6.0', ext:'aar')
    implementation(name: 'com.applovin.mediation.google-adapter-21.4.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-livedata-core-2.1.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-auth-api-phone-17.4.0', ext:'aar')
    implementation(name: 'androidx.versionedparcelable.versionedparcelable-1.1.1', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-auth-21.1.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-analytics-21.2.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-safetynet-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.datatransport.transport-backend-cct-3.1.8', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-analytics-unity-10.3.0', ext:'aar')
    implementation(name: 'androidx.cursoradapter.cursoradapter-1.0.0', ext:'aar')
    implementation(name: 'androidx.legacy.legacy-support-core-utils-1.0.0', ext:'aar')
    implementation(name: 'NativeShare', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-crashlytics-unity-10.3.0', ext:'aar')
    implementation(name: 'androidx.coordinatorlayout.coordinatorlayout-1.0.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-dynamic-links-unity-10.3.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-ads-lite-21.4.0', ext:'aar')
    implementation(name: 'androidx.loader.loader-1.0.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-auth-interop-20.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-ads-base-21.4.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-auth-unity-10.3.0', ext:'aar')
    implementation(name: 'androidx.asynclayoutinflater.asynclayoutinflater-1.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-service-2.1.0', ext:'aar')
    implementation(name: 'com.google.android.play.review-2.0.1', ext:'aar')
    implementation(name: 'androidx.print.print-1.0.0', ext:'aar')
    implementation(name: 'androidx.fragment.fragment-1.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-sdk-21.2.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-abt-21.0.2', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-runtime-2.1.0', ext:'aar')
    implementation(name: 'com.applovin.mediation.unityads-adapter-4.5.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-sdk-api-21.2.0', ext:'aar')
    implementation(name: 'androidx.annotation.annotation-experimental-1.1.0', ext:'aar')
    implementation(name: 'androidx.documentfile.documentfile-1.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-base-21.2.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-crashlytics-ndk-18.3.2', ext:'aar')
    implementation(name: 'androidx.startup.startup-runtime-1.0.0', ext:'aar')
    implementation(name: 'androidx.work.work-runtime-2.7.0', ext:'aar')
    implementation(name: 'applovin-max-unity-plugin', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-encoders-json-18.0.0', ext:'aar')
    implementation(name: 'androidx.sqlite.sqlite-framework-2.1.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-basement-18.1.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-livedata-2.1.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-components-17.0.1', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-installations-17.1.0', ext:'aar')
    implementation(name: 'androidx.localbroadcastmanager.localbroadcastmanager-1.0.0', ext:'aar')
    implementation(name: 'com.applovin.mediation.facebook-adapter-6.12.0.1', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-stats-17.0.2', ext:'aar')
    implementation(name: 'androidx.legacy.legacy-support-core-ui-1.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-api-21.2.0', ext:'aar')
    implementation(name: 'com.google.android.datatransport.transport-runtime-3.1.8', ext:'aar')
    implementation(name: 'androidx.slidingpanelayout.slidingpanelayout-1.0.0', ext:'aar')
    implementation(name: 'com.applovin.applovin-sdk-11.6.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-21.2.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-measurement-impl-21.2.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-config-unity-10.3.0', ext:'aar')
    implementation(name: 'com.google.android.datatransport.transport-api-3.0.0', ext:'aar')
    implementation(name: 'LofeltHaptics', ext:'aar')
    implementation(name: 'androidx.viewpager.viewpager-1.0.0', ext:'aar')
    implementation(name: 'androidx.customview.customview-1.0.0', ext:'aar')
    implementation(name: 'androidx.arch.core.core-runtime-2.1.0', ext:'aar')
    implementation(name: 'androidx.drawerlayout.drawerlayout-1.0.0', ext:'aar')
    implementation(name: 'androidx.tracing.tracing-1.0.0', ext:'aar')
    implementation(name: 'androidx.interpolator.interpolator-1.0.0', ext:'aar')
    implementation(name: 'androidx.swiperefreshlayout.swiperefreshlayout-1.0.0', ext:'aar')
    implementation(name: 'com.facebook.android.audience-network-sdk-6.12.0', ext:'aar')
    implementation(name: 'com.google.android.ump.user-messaging-platform-2.0.0', ext:'aar')
    implementation(name: 'androidx.sqlite.sqlite-2.1.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-common-20.2.0', ext:'aar')
    implementation(name: 'androidx.browser.browser-1.4.0', ext:'aar')
    implementation(name: 'com.google.firebase.firebase-app-unity-10.3.0', ext:'aar')
    implementation project('FirebaseApp.androidlib')
    implementation project('MaxMediationGoogle.androidlib')
    implementation project('FirebaseCrashlytics.androidlib')

}

android {
    ndkPath "/Users/josh/Documents/UnityEditors/2022.2.0f1/PlaybackEngines/AndroidPlayer/NDK"

    compileSdkVersion 33
    buildToolsVersion '32.0.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 33
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        versionCode 10
        versionName '0.10.4'
        consumerProguardFiles 'proguard-unity.txt'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }
}

def getSdkDir() {
    Properties local = new Properties()
    local.load(new FileInputStream("${rootDir}/local.properties"))
    return local.getProperty('sdk.dir')
}

def BuildIl2Cpp(String workingDir, String configuration, String architecture, String abi, String[] staticLibraries) {
    def commandLineArgs = []
    commandLineArgs.add("--compile-cpp")
    commandLineArgs.add("--platform=Android")
    commandLineArgs.add("--architecture=" + architecture)
    commandLineArgs.add("--outputpath=" + workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.so")
    commandLineArgs.add("--libil2cpp-static")
    commandLineArgs.add("--baselib-directory=" + workingDir + "/src/main/jniStaticLibs/" + abi)
    commandLineArgs.add("--configuration=" + configuration)
    commandLineArgs.add("--dotnetprofile=unityaot-linux")
    commandLineArgs.add("--profiler-report")
    commandLineArgs.add("--profiler-output-file=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_conv.traceevents")
    commandLineArgs.add("--print-command-line")
    commandLineArgs.add("--data-folder=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput/data")
    commandLineArgs.add("--generatedcppdir=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput")
    commandLineArgs.add("--cachedirectory=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_cache")
    commandLineArgs.add("--tool-chain-path=" + android.ndkDirectory)
    staticLibraries.eachWithIndex {fileName, i->
        commandLineArgs.add("--additional-libraries=" + workingDir + "/src/main/jniStaticLibs/" + abi + "/" + fileName)
    }
    def executableExtension = ""
    if (org.gradle.internal.os.OperatingSystem.current().isWindows())
        executableExtension = ".exe"
    exec {
        executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
        args commandLineArgs
        environment "ANDROID_SDK_ROOT", getSdkDir()
    }
    delete workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.sym.so"
    ant.move(file: workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
}

android {
    task BuildIl2CppTask {
        doLast {
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), 'Release', 'armv7', 'armeabi-v7a', [  ] as String[]);
              BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), 'Release', 'arm64', 'arm64-v8a', [  ] as String[]);
        }
    }
    afterEvaluate {
        if (project(':unityLibrary').tasks.findByName('mergeDebugJniLibFolders'))
            project(':unityLibrary').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':unityLibrary').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':unityLibrary').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }
    sourceSets {
        main {
            jni.srcDirs = ["src/main/Il2CppOutputProject"]
        }
    }
}
`




`apply plugin: 'com.android.application'

dependencies {
    implementation project(':unityLibrary')
    }

android {
    ndkPath "/Users/josh/Documents/UnityEditors/2022.2.0f1/PlaybackEngines/AndroidPlayer/NDK"

    compileSdkVersion 33
    buildToolsVersion '32.0.0'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 33
        applicationId 'com.MatchalaGames.RyahsRhythm'
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        versionCode 10
        versionName '0.10.4'
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    signingConfigs {
        release {
            storeFile file('')
            storePassword ''
            keyAlias ''
            keyPassword ''
        }
    }

    lintOptions {
        abortOnError false
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
            jniDebuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }

    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}
`

@santoshbagadi 

These here?

**Comment by nooralibutt** [comment]
@santoshbagadi I have tried everything. older plugin newer plugin but this error doesn't go away, tried removing, cleaning, reimporting older newer sdk. I think it has problem with newer unity 2022 cz on older unity 2020 and 2018 it works

**Comment by Kidkiwi** [comment]
@nooralibutt that's a good point. I use unity 2022 also

**Comment by joshua-matchala** [comment]
@santoshbagadi this also happens in unity 2022 if you untick the 'ad review' button in integration manager.

**Comment by nooralibutt** [comment]
> @santoshbagadi this also happens in unity 2022 if you untick the 'ad review' button in integration manager.

I tried ticking and unticking both. Same error appears all the time

**Comment by santoshbagadi** [comment]
Hi all, it seems like the issue started specifically with Unity `2022.2.0`. It seems like Unity has significantly changed the how Gradle files are generated. We'll have a fix for it in the next release. 

If you have unchecked the `Enable Ad Review` setting in our Integration Manager and still see the error, you can safely ignore it for now.

If you would like to get rid of the error, you can try adding the following line (shown with a `+` at the start) to the `AppLovinPostProcessGradleProject` file.

```
        public void OnPostGenerateGradleAndroidProject(string path)
        {
#if UNITY_2019_3_OR_NEWER
+            if (!AppLovinSettings.Instance.QualityServiceEnabled) return;
```

**Comment by joshua-matchala** [comment]
Thank you.

@santoshbagadi any idea when the next version will be released?

**Comment by santoshbagadi** [comment]
Our next release is currently planned for the first week of Jan.

**Comment by joshua-matchala** [comment]
@santoshbagadi this is still an issue in the latest version. 5.6.3
<img width="509" alt="image" src="https://user-images.githubusercontent.com/75960319/210903627-3285c8ce-d4b3-4c25-a69d-9490062cbff5.png">

**Comment by santoshbagadi** [comment]
Sorry for the delay here, but we are still working on adding support for Gradle 7.2 which is used in Unity 2022.2+. We should have the fix in the next release.

**Comment by joshua-matchala** [comment]
@santoshbagadi Best guess for a release date? Thanks

**Comment by joshua-matchala** [comment]
@santoshbagadi still no update?

**Comment by santoshbagadi** [comment]
@joshua-matchala , sorry for the delay here. We were running some internal tests. Our latest Unity plugin [version 5.6.5](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_6_5) now fixes this issue.

**Comment by choisin** [comment]
유니티 2022.3.9f 에서 문제가 여전히 발생합니다.
버전 12.4.2
