### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by Kidkiwi** [AppLovin/AppLovin-MAX-Unity-Plugin#207]
### MAX Plugin Version

5.5.6

### Unity Version

2021.3.12f1

### Device/Platform Info

Android

### Current Behavior

Android building throws the below error.

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:processDebugResources'.
> Could not resolve all task dependencies for configuration ':launcher:debugRuntimeClasspath'.
   > Could not resolve com.applovin.mediation:facebook-adapter:[6.12.0.0].
     Required by:
         project :launcher > project :unityLibrary
      > Failed to list versions for com.applovin.mediation:facebook-adapter.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/mediation/facebook-adapter/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/applovin/mediation/facebook-adapter/maven-metadata.xml'.
               > Read timed out
```

### Expected Behavior

Completed android build.

### How to Reproduce

Just building with the applovin sdk, with facebook module enabled.

**Comment by ErkFu** [comment]
same issue，MAX work very well last week， just happen today

**Comment by santoshbagadi** [comment]
Hi All, yes, [`jcenter()` has been shutdown](https://blog.gradle.org/jcenter-shutdown#:~:text=The%20jcenter()%20method%20will,may%20only%20publish%20new%20versions.) for a while and should be removed from all gradle files. As suggested by @kaninhot004 , adding `mavenCentral()` instead will fix the issue.

**Comment by fiinz** [comment]
I've added mavenCentral, but i still get calls to jcenter

**Comment by santoshbagadi** [comment]
@fiinz , If you are still seeing `jcenter` being added, you can update to at least version 1.2.169 of EDM to no longer have it add `jcenter` to the build files.
You can find that here: https://github.com/googlesamples/unity-jar-resolver/blob/ed86be70185e944e4b032de318e6dfdd84ec8ef6/external-dependency-manager-1.2.169.unitypackage

We'll include this version by default in our next release.

**Comment by Kidkiwi** [comment]
I'm using an even later version 1.2.172 and it's still adding Jcenter
somewhere during the build. Any ideas?

**Comment by archengineer** [comment]
Hi,
Even though I have changed jcenter to mavencentral in all gradles in the project, it still gives an error.

Unity version: 2020.3.38f1
External dependency version: 1.2.172

**Comment by fiinz** [comment]
Guys, its the Base Gradle Template. Enable Custom Base Gradle Template and Remove it from there.

**Comment by Kidkiwi** [comment]
I have. There is no jcenter in any of my gradle files before building.

**Comment by Kidkiwi** [comment]
This is now happening on a git branch I have that successfully use to build
android and ios. It now fails with nothing being changed at all.

**Comment by santoshbagadi** [comment]
@Kidkiwi @archengineer , it could be one of the other plugins `jcenter` to the final build. You can try and verify by e[xporting the Android project](https://docs.unity3d.com/Manual/android-export-process.html) and checking if it has `jcenter` in it.

**Comment by archengineer** [comment]
Hi @santoshbagadi, 
As you said even though baseProjectTemplate not selected it is including jcenter, but when I enable "Custom Base Gradle Template" and changed jcenter to mavencentral (See image) it is now working. Thanks to @fiinz.

See images below for my setup @Kidkiwi 

![base-template](https://user-images.githubusercontent.com/5655947/199088841-c6e96a80-1651-4afb-8242-7c0658a5368c.png)
![unity-publish-settings](https://user-images.githubusercontent.com/5655947/199088844-e997aeed-6245-4a4a-8857-77832abd4e08.png)

**Comment by Kidkiwi** [comment]
I waited 24 hours. Changed nothing, and it builds again. Must have been an
outage on some service.
