### ISSUE TITLE
Max SDK as package using Windows Editor

### ISSUE THREAD

**Issue by abogarsukov-braingames** [AppLovin/AppLovin-MAX-Unity-Plugin#209]
### MAX Plugin Version

5.5.7

### Unity Version

2020.3.41

### Device/Platform Info

Unity Editor

### Current Behavior

Moveing Max SDK into UPM package causes removal of mediation files (`MaxSDK/Madiation/*`) and the plugin settings (`MaxSDK/Resources/AppLovinSettings`) from `Assets` folder.

### Expected Behavior

Max SDK can be moved to UPM package as is. Mediation files and the plugin settings should stay in the `Assets`.

### How to Reproduce

Import Max SDK into Unity editor on Windows, then move it into a package. Notice, that mediation files and plugin settings are removed from `Assets`.

### Additional Info

The problem can be solved easily via editing Max SDK scripts;
- Replace forward slashes with back slashes at AppLovinSettings.cs line 24;
- Replace forward slashes with back slashes at AppLovinIntegrationManager.cs lines 135-137.

**Comment by santoshbagadi** [comment]
Hi @abogarsukov-braingames , adding support for UPM is in our pipeline. We'll notify here when we release a plugin with this support.

**Comment by uchar** [comment]
@santoshbagadi  Same as https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/150 and https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/64 
It would be very beneficial if you could do it sooner, We use the same AppLovin logic for different projects and because of this issue we have to duplicate them all across various projects

**Comment by santoshbagadi** [comment]
@uchar , apologies for the delay here, we did not get a chance to prioritize this as we were working on other important tasks. But we have started work on adding support for UPM and we should have a release with UPM support early Q1.

**Comment by MeltdownInteractive** [comment]
Would be great to have this SDK in Package Manager.

**Comment by HanzaRu** [comment]
Please provide a UPM installation, isn't practical to update it manually on each project!

**Comment by uchar** [comment]
> @uchar , apologies for the delay here, we did not get a chance to prioritize this as we were working on other important tasks. But we have started work on adding support for UPM and we should have a release with UPM support early Q1.

@santoshbagadi  Do you have any news on this?

**Comment by abogarsukov-braingames** [comment]
Hey @santoshbagadi, any progress on this?

**Comment by abogarsukov-braingames** [comment]
Any updates? @santoshbagadi it's been more than a year, when can we expect it?

**Comment by uchar** [comment]
@JonathanLiuApp

**Comment by JonathanLiuApp** [comment]
We've just released plugin [version 8.0.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_8_0_0) which includes UPM support.
