### ISSUE TITLE
MaxInitialize resets AppLovinSettings

### ISSUE THREAD

**Issue by JasperChimpWorks** [AppLovin/AppLovin-MAX-Unity-Plugin#21]
We noticed that our applovinsettings get reset on our build machines when they perform a clean build. This causes build failures because the Google Admob IDs go lost.

I investigated the issue and tracked it down to: `AppLovinAutoUpdater.Update()`
This method gets called from the `MaxInitialize()`, but because it's a static constructor, the Unity AssetDatabase doesn't seem to be initialized yet. 
As a consequence, it cannot find `AppLovinSettings` when `AppLovinSettings.Instance` gets called, and as a fallback, it creates a new instance and overwrites the asset.

This only happens if you start your project for the first time, for example after removing the Library folder.

Commenting out `AppLovinAutoUpdater.Update()` resolves the issue, but obviously disables the auto-updater.

**Comment by santoshbagadi** [comment]
@JasperChimpWorks , thank you for reporting this issue! We are investigating and should have a fix soon. We will update this thread once the fix has been released.

**Comment by thomasmso** [comment]
The fix has been released in AppLovin MAX Unity Plugin v2.4.10.
