### ISSUE TITLE
iOS crash: "Passed an object of type other than ALAd" when linking frameworks dynamically

### ISSUE THREAD

**Issue by CJxD** [AppLovin/AppLovin-MAX-Unity-Plugin#211]
Unless I tick 'Link frameworks statically' in iOS Resolver settings (which adds `"use_frameworks! :linkage => :static"` to the Podfile), I get the following error at runtime:

```
[ALDelegateCallbackInvoker] Unable to notify ad delegate about ad being loaded : Passed an object of type other than ALAd: ALAdServerAd.
```

and

```
*** Terminating app due to uncaught exception ‘NSInvalidArgumentException’, reason: ‘Passed an object of type other than ALAd: ALAdServerAd.’
```

This causes ads to load but not get displayed in the best case, and a crash in the worst case. Unfortunately I'm unable to use static frameworks so it's a bit of a blocker.

Details:

Platform : macOS 12.5.1, mac mini M1
Environment : Unity 2020.1.15f1 & Unity 2020.1.16f1, Xcode 13.4.1 & Xcode 14.0 & Xcode 14.1
AppLovin SDK Version : 10.3.7 & 11.5.5
Plugin Version : 4.3.12 & 5.5.8
Device : iPhone 7
Steps to reproduce :

* Open DemoApp
* Add SDK key and ad unit IDs
* Go to External Dependency Manager -> iOS Resolver -> Settings and note that 'Link frameworks statically' is turned off which seems to be the default.
* Build Xcode project
* Update bundle ID and provisioning keys to be able to build the app
* Run app
* Crash

I tried the mitigations in https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/26, but these didn't work. I seem to only be able to prevent this when statically linking.

Furthermore, when it doesn't crash, I was actually seeing "revenue" on the MAX dashboard for my iOS ad unit despite the ad never loading which is concerning!

I've also had linker issues when building with the GoogleAdManager mediation adapter installed - I had to manually add "GoogleMobileAds.xcframework" to the frameworks list in Unity-iPhone with "Do not embed" to make it work.

**Comment by truongntsotanext** [comment]
Hello,
Has this issue been resolved yet? I encountered this problem when building my game on iOS platform. I am using MAX SDK 11.11.4.
I get this error when trying to display Initial Ads.
nspecified - Failed start displaying [ALMediatedFullscreenAd thirdPartyAdPlacementIdentifier=inter_regular, adUnitIdentifier=7f118b884a4f2e38, format=INTER, networkName=AppLovin] : Passed an object of type other than ALAd: ALAdServerAd

And this error when displaying Rewarded Ads.
-5200 - Attempting to display ad with invalid ad type
Please help me!

**Comment by zdrake314** [comment]
We have a [support article](https://support.applovin.com/hc/en-us/articles/20936475608461-Unity-iOS-Podfile-issues) on this issue: https://support.applovin.com/hc/en-us/articles/20936475608461-Unity-iOS-Podfile-issues.

**Comment by ugurinal** [comment]
@mofish9 Hi, I am having the same issue and getting error -5200. Did you find a solution?
