### ISSUE TITLE
AdColony and unity 2021 Error building Player : Exception: OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#212]
### MAX Plugin Version

5.5.8

### Unity Version

2021.3.13

### Device/Platform Info

Android

### Current Behavior

If you follow [guide ](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters?network=ADCOLONY_NETWORK#network-security-configuration-file) on Network security configuration for AdColony in unity 2021 ,after adding Plugins/Android/res/xml/network_security_config.xml  You will get the following build error on android :
``` Error building Player: Exception: OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details. ```
 

### Expected Behavior

Successful Build on android with no errors

### How to Reproduce

1. Install unity 2021.3.13 
2.  Add AdColony 
3. Follow [this guide](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters?network=ADCOLONY_NETWORK#network-security-configuration-file) 
4. Build the project for android and you will get the error.

**Comment by uchar** [comment]
For now, I solved this by creating androidlib :

1. Inside `Assets/Plugins/Android` , create a folder  `somename.androidlib` ( Use whatever name you want but make sure it ends with .androidlib )
2. Inside `Assets/Plugins/Android/somename.androidlib` create `AndroidManifest.xml` with this content : 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.yourcompany.somename">
    <application android:networkSecurityConfig="@xml/network_security_config">
    </application>
</manifest>
```
3. Inside `Assets/Plugins/Android/somename.androidlib` create `project.properties` with this content : 
```
target=android-31
android.library=true
```
4. Inside `Assets/Plugins/Android/somename.androidlib/res/xml` create `network_security_config.xml` with this [content ](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters?network=ADCOLONY_NETWORK#network-security-configuration-file): 
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>

    <!-- For AdColony and Smaato, this permits all cleartext traffic: -->
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
    <!-- End AdColony / Smaato section -->

    <domain-config cleartextTrafficPermitted="true">

        <!-- For Facebook, this permits cleartext traffic to localhost: -->
        <domain includeSubdomains="true">127.0.0.1</domain>
        <!-- End Facebook section -->

    </domain-config>
</network-security-config>
```

**Comment by santoshbagadi** [comment]
@uchar , thank you for the detailed fix! We are already in the process of updating our docs to use something similar to this and will update here once the docs are released.
