### ISSUE TITLE
Win32Exception: The system cannot find the file specified When building for iOS from Windows Unity Editor

### ISSUE THREAD

**Issue by MeltdownInteractive** [AppLovin/AppLovin-MAX-Unity-Plugin#213]
### MAX Plugin Version

5.5.8

### Unity Version

2021.3.12

### Device/Platform Info

iOS

### Current Behavior

I am on Windows 11. 
Whenever I build my iOS project in Unity, I get the following error...

`Win32Exception: The system cannot find the file specified.

System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) (at <9fe598e1f1334abeae4ea9fbbe948c3e>:0)
System.Diagnostics.Process.Start () (at <9fe598e1f1334abeae4ea9fbbe948c3e>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinCommandLine.Run (System.String toolPath, System.String arguments, System.String workingDirectory) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinCommandLine.cs:71)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessiOS.OnPostProcessBuild (UnityEditor.BuildTarget buildTarget, System.String buildPath) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessiOS.cs:89)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`

That code resolves to...

`process.StartInfo.WorkingDirectory = workingDirectory;
            process.StartInfo.FileName = "bash";
            process.StartInfo.Arguments = string.Format("-l -c '\"{0}\" {1} 1> {2} 2> {3}'", toolPath, arguments, stdoutFileName, stderrFileName);
            process.Start();`

And to 

` var rubyVersion = AppLovinCommandLine.Run("ruby", "--version", buildPath);
                if (rubyVersion.ExitCode != 0)
                {
                    MaxSdkLogger.UserError("AppLovin Quality Service installation requires Ruby. Please install Ruby, export it to your system PATH and re-export the project.");
                    return;
                }`

### Expected Behavior

I don't expect to have any errors in the Unity Editor when building my iOS project.

### How to Reproduce

Build an iOS project in the Unity Editor in Windows.

**Comment by santoshbagadi** [comment]
Hi @MeltdownInteractive , iOS builds with AppLovin Ad Review plugin enabled require a MacOS machine to build. So, please try to run the build on a MacOS machine or use [Unity Cloud Build](https://unity.com/products/cloud-build) to create an iOS build.
