### ISSUE TITLE
AppLovinMediationByteDanceAdapter

### ISSUE THREAD

**Issue by PaXLiCh** [AppLovin/AppLovin-MAX-Unity-Plugin#215]
### MAX Plugin Version

latest

### Unity Version

2020.3.40f1

### Device/Platform Info

iOS target 16, Xcode 14.1

### Current Behavior

We enabled Pangle and Facebook Ad, we use latest version of max sdk and mediations,
`<iosPod name="AppLovinMediationByteDanceAdapter" version="4.7.0.8.2" />`
`<iosPod name="AppLovinMediationFacebookAdapter" version="6.12.0.1" />`
and others
but we got error during archiving in Xcode
```XCFrameworkIntermediates/AppLovinMediationByteDanceAdapter/libByteDanceAdapter.a(ALByteDanceMediationAdapter.o) does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/unnati/Library/Developer/Xcode/DerivedData/BrainPuzzle-chbwvweeswlzwpaaoinoodosfdww/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppLovinMediationByteDanceAdapter/libByteDanceAdapter.a' for architecture arm64```
maybe you can add postprocess to disable bitcode for projects?

### Expected Behavior

Just build Xcode projects without any additional changes.

**Comment by thomasmso** [comment]
Bitcode has been deprecated in Xcode 14. Our next SDK release will have it disabled as well.

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
