### ISSUE TITLE
Xcode iOS build error ((ALFacebookMediationAdapter.o)' does not contain bitcode.)

### ISSUE THREAD

**Issue by Vah94** [AppLovin/AppLovin-MAX-Unity-Plugin#217]
### MAX Plugin Version

5.6.1

### Unity Version

2021.3.16f1

### Device/Platform Info

iOS 16.2

### Current Behavior

Xcode project build failed. 

### Expected Behavior

Xcode project build was a success. 

### How to Reproduce

Build a project for the iOS platform. Run on an iOS device.

### Additional Info

Podfile

source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinMediationFacebookAdapter', '6.12.0.1'
  pod 'AppLovinMediationGoogleAdapter', '9.14.0.0'
  pod 'AppLovinMediationIronSourceAdapter', '7.2.6.0.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.4.1.0'
  pod 'AppLovinMediationVungleAdapter', '6.12.1.1'
  pod 'AppLovinSDK', '11.6.0'
  pod 'AppsFlyerFramework', '6.8.1'
  pod 'Firebase/Analytics', '9.6.0'
  pod 'Firebase/Auth', '9.6.0'
  pod 'Firebase/Core', '9.6.0'
  pod 'Firebase/Crashlytics', '9.6.0'
  pod 'Firebase/Database', '9.6.0'
  pod 'Firebase/RemoteConfig', '9.6.0'
  pod 'Firebase/Storage', '9.6.0'
  pod 'FirebaseInstallations'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

**Comment by thomasmso** [comment]
Xcode 14 deprecated bitcode, so none of our artifacts are built with bitcode anymore.

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
