### ISSUE TITLE
Android crash in AppLovinInitProvider

### ISSUE THREAD

**Issue by abogarsukov-braingames** [AppLovin/AppLovin-MAX-Unity-Plugin#219]
### MAX Plugin Version

5.5.7

### Unity Version

2020.3.41

### Device/Platform Info

Android

### Current Behavior

The application crashes with the stack trace attached:
[com.wordfarm.scapes_issue_35ae287802c5c09c4107d29bce1a9af3_ANR_session_63A27889000C00015C50F817D21BC63A_DNE_0_v2_stacktrace.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/10276154/com.wordfarm.scapes_issue_35ae287802c5c09c4107d29bce1a9af3_ANR_session_63A27889000C00015C50F817D21BC63A_DNE_0_v2_stacktrace.txt)

### Expected Behavior

The application doesn't crash.

### How to Reproduce

We're not able to reproduce the issue. This specific crash seems to happen when the app is started from a push notification.

**Comment by avi-cramer** [comment]
@abogarsukov-braingames thank you for the information, we are currently investigating the issue and will update this ticket once we have a fix in place.

**Comment by maximilianbuck** [comment]
@abogarsukov-braingames Ad Review version 4.8.2 has a fix for this issue. Ad Review is separate from our SDK but by default it will pull the newest version when you build. You can check the Mediation Debugger to confirm the Ad Review version that's integrated in your app.
