### ISSUE TITLE
Uncaught exception: NSInvalidArgumentException: Empty ad unit ID specified

### ISSUE THREAD

**Issue by rbyjoswald** [AppLovin/AppLovin-MAX-Unity-Plugin#221]
### MAX Plugin Version

5.6.4

### Unity Version

2020.3.32

### Device/Platform Info

iOS 13.5.1

### Current Behavior

Loading an ad with an empty string as ad unit id causes an app to crash with the following exception:

`Uncaught exception: NSInvalidArgumentException: Empty ad unit ID specified`

### Expected Behavior

Instead of crashing the entire app, just invoke OnAdLoadFailedEvent with the same error message as the exception currently thrown.

### How to Reproduce

Load ad with ad unit id set to ""

**Comment by thomasmso** [comment]
This is expected behaviour, please view this [documentation](https://dash.applovin.com/documentation/mediation/max/get-started-with-max#step-2:-create-an-ad-unit) on how to create an Ad Unit ID.
