### ISSUE TITLE
Specs satisfying the `AppLovinMediationYandexAdapter (= 5.4.0.1)` dependency were found, but they required a higher minimum deployment target

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#222]
### MAX Plugin Version

5.6.5

### Unity Version

2021.3.17

### Device/Platform Info

iOS

### Current Behavior

Recently after upgrading Applovin and its plugins to the latest version, I'm getting the following error after executing `pod install --repo-update` :

```
CocoaPods could not find compatible versions for pod "AppLovinMediationYandexAdapter":
  In Podfile:
    AppLovinMediationYandexAdapter (= 5.4.0.1)
Specs satisfying the `AppLovinMediationYandexAdapter (= 5.4.0.1)` dependency were found, but they required a higher minimum deployment target 
```

### Expected Behavior

Successful iOS build

### How to Reproduce

Enable Yandex mediated network, then try to build for iOS

**Comment by thomasmso** [comment]
The latest Yandex SDK, and thus the adapter, requires the iOS deployment target to be iOS 12 or above.
