### ISSUE TITLE
Could not find mandatory file: com.applovin.mediation.ads.MaxAdView 

### ISSUE THREAD

**Issue by abdollah3d** [AppLovin/AppLovin-MAX-Unity-Plugin#223]
### MAX Plugin Version

5.6.6

### Unity Version

2021.3

### Device/Platform Info

mac

### Current Behavior

Hi
i tried getting a build with different versions of the sdk
i also deleted ExternalDependencyManager and updated to newer version but same error

### How to Reproduce

help

**Comment by santoshbagadi** [comment]
@abdollah3d , do you use any custom Gradle templates? Do you mind trying to force resolve by clicking **Assets > External Dependency Manager > Android Resolver > Force Resolve** and see if that fixes the issue.

**Comment by abdollah3d** [comment]
Im not using custom gradle template ad when i try force resolve it says resolution failed

**Comment by santoshbagadi** [comment]
Do you mind sharing the full error log in the console from External Dependency Manager so that we can further investigate the issue.

**Comment by abdollah3d** [comment]
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
============================================================================
AppLovin Quality Service Plug-in for Gradle and Android Studio Version 4.8.5
Copyright (c) 2022 AppLovin Ltd. All rights reserved.
============================================================================
[SafeDK] Your project has been updated to support Multi-Dex!
With Multi-Dex support you can use as many methods as you like in your application (no 65K method limit)

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:processReleaseManifest UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :launcher:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses UP-TO-DATE
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :launcher:processReleaseResources UP-TO-DATE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibCompileToJarRelease UP-TO-DATE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:compileReleaseSources UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease UP-TO-DATE
> Task :launcher:mergeExtDexRelease UP-TO-DATE
> Task :launcher:mergeDexRelease UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease UP-TO-DATE
> Task :launcher:mergeExtDexRelease UP-TO-DATE
> Task :launcher:mergeDexRelease UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:mergeReleaseJavaResource UP-TO-DATE
> Task :launcher:safedkAdjustInputsRelease

> Task :launcher:safedkInstrumentationRelease FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
40 actionable tasks: 5 executed, 35 up-to-date

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Comment by abdollah3d** [comment]
and when i force resolve heres the log

Gradle failed to fetch dependencies.

Failed to run '/Users/abdollah/Desktop/BallShooter3D/Temp/PlayServicesResolverGradle/gradlew --no-daemon -b "/Users/abdollah/Desktop/BallShooter3D/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=/Users/abdollah/Documents/2021.3.9f1/PlaybackEngines/AndroidPlayer/SDK" "-PTARGET_DIR=/Users/abdollah/Desktop/BallShooter3D/Assets/Plugins/Android" "-PMAVEN_REPOS=" "-PPACKAGES_TO_COPY=com.google.android.instantapps:instantapps:1.1.0;com.google.android.gms:play-services-appset:16.0.2;com.applovin:applovin-sdk:11.6.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"'
stdout:
Unzipping /Users/abdollah/.gradle/wrapper/dists/gradle-5.1.1-bin/90y9l8txxfw1s2o6ctiqeruwn/gradle-5.1.1-bin.zip to /Users/abdollah/.gradle/wrapper/dists/gradle-5.1.1-bin/90y9l8txxfw1s2o6ctiqeruwn

stderr:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

exit code: 1

UnityEngine.Debug:LogError (object)
Google.Logger:Log (string,Google.LogLevel) (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at /Users/drsanta/dev/build/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1069)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey11:<>m__19 (GooglePlayServices.CommandLine/Result) (at /Users/drsanta/dev/build/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:459)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey11/<GradleResolution>c__AnonStorey13:<>m__2C () (at /Users/drsanta/dev/build/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:572)
Google.RunOnMainThread:ExecuteNext () (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12 () (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction (System.Action) (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll () (at /Users/drsanta/dev/build/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)

**Comment by santoshbagadi** [comment]
@abdollah3d , seems like its a Gradle issue that has a fix here: https://answers.unity.com/questions/1496840/gradle-is-failed-to-fetch-dependencies-admob-in-un.html

Could you try it out and see if that fixes your issue.

**Comment by abdollah3d** [comment]
Yes it works now
thanks @santoshbagadi

**Comment by kunalyadav103219** [comment]
1.Add  it in your repository
       maven { url 'https://artifacts.applovin.com/android' }
       maven { url "https://android-sdk.is.com" }
2.  Add this classpath in your dependencies 
    dependencies {
          classpath "com.applovin.quality:AppLovinQualityServiceGradlePlugin:4.9.1"
    }
3.Add this plugins id 
plugins {
   id 'applovin-quality-service'
}
