### ISSUE TITLE
MAUnityAdManager 'init' is unavailable

### ISSUE THREAD

**Issue by pjvslx** [AppLovin/AppLovin-MAX-Unity-Plugin#226]
### MAX Plugin Version

5.6.6

### Unity Version

2020.3.42.f1c1

### Device/Platform Info

XCode 10.1 pod 1.11.3

### Current Behavior

Open XCWorkspace and build with XCode,it happened.

MAUnityAdManager.h:
- (instancetype)init NS_UNAVAILABLE;
MAUnityAdManager.m
+ (MAUnityAdManager *)shared
{
    static dispatch_once_t token;
    static MAUnityAdManager *shared;
    dispatch_once(&token, ^{
        shared = [[MAUnityAdManager alloc] init];
    });
    return shared;
}

### How to Reproduce

Just export Xcode project and build

**Comment by santoshbagadi** [comment]
Hi @pjvslx , could you confirm the Xcode version you are using. We require Xcode version 13.2.1. But for 5.6.6, you might need Xcode 14.0. We're going to fix this to support back to 13.2.1 in our next release. 

Could you also share the full error log you are seeing, if you are still seeing the error after upgrading to the newer Xcode version.
