### ISSUE TITLE
Confronting with advertising filters

### ISSUE THREAD

**Issue by CGreen11** [AppLovin/AppLovin-MAX-Unity-Plugin#229]
A large number of request failure logs have been found in the log system, but access to our log system is network accessible. There may be terminals that use advertisement filtering. At present, by checking these domain names in advance, we will be grateful if there is any way to solve these failures.

The following are some common reasons for request failure:
-1000,Failed to connect to ms.applvn.com/0.0.0.0:443

-1000,Failed to connect to ms.applvn.com/:::443

-1009,Unable to resolve host "ms.applvn.com": No address associated with hostname

1001,failed to connect to localhost/127.0.0.1 (port 443) from /127.0.0.1 (port 55938) after 5000ms

Refer to advertising filtering scheme:
https://github.com/AdguardTeam/AdguardFilters

**Comment by thomasmso** [comment]
Thanks for reporting this @CGreen11 - we'll look into it.

**Comment by CGreen11** [comment]
Adding a log found that it was not a guess. "ping ms.applvn.com" did not have a large number of failures as expected during startup, so the reason for the feedback request failed or the optimization scheme did not have ideas during loadAd. If you have any suggestions, thank you very much
