### ISSUE TITLE
Build Crash on iOS 

### ISSUE THREAD

**Issue by providence94** [AppLovin/AppLovin-MAX-Unity-Plugin#23]
using the latest adapters and sdk version : 2.4.9
ios version 6.12.6
unity version : 2019.3.13f1

our game runs 100% of the time when i run from Xcode on the device connected to the mac

on distributed builds .ipa file shared internally to the team
the game always runs prefectly fine in the FIRST boot.
once we close the game and run the game for the SECOND and subsequent times it gets stuck in our launch screen and crashes
no logs available for this

after so much debugging i tried disabling maxsdk(just commented out the intializesdk code) and the game works fine! 1st boot,2nd time boot ....and so on

please advice.

**Comment by thomasmso** [comment]
Hi @providence94, thanks for reporting this issue. We identified the cause to be Fyber's SDK and pushed out a new Fyber adapter certifying against their latest which fixes it.
