### ISSUE TITLE
Handling user airplane mode (or losing connection before init successful)

### ISSUE THREAD

**Issue by RomainBitard** [AppLovin/AppLovin-MAX-Unity-Plugin#231]
Hey, thanks for the plugin it's awesome and has great features.
I was wondering how we could handle a user switching air plane on at the beginning and then switching it off.
On my game it fail the init and then everything breaks. 
What'd be the best way to handle that ? 
Thanks in advance

**Comment by santoshbagadi** [comment]
Hi @RomainBitard , could you please eloborate on what you mean by:
> On my game it fail the init and then everything breaks.

Do you not get our SDK init callback? Could you please [enable verbose logs](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#enable-verbose-logging) and share the session logs when you see the issue?

**Comment by RomainBitard** [comment]
I implemented a simple 30 secs retry mechanism, I don't know if it's good but it seems to work.
