### ISSUE TITLE
Unity Cloud Build fail with ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by vhnunes** [AppLovin/AppLovin-MAX-Unity-Plugin#232]
### MAX Plugin Version

5.8.0

### Unity Version

2020.3.37

### Device/Platform Info

iOS

### Current Behavior

Xcode 13.2.1, build fails with error

`ld: symbol(s) not found for architecture arm64`

Full xcode log below.
[pandora-admin-king-io-king-io-release-ios-43-king.io-unity-iphone.log](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/10854409/pandora-admin-king-io-king-io-release-ios-43-king.io-unity-iphone.log)

### Expected Behavior

Build success.

### How to Reproduce

1 - Updated AppLovin plugin to from 5.6.1 to 5.8.0

**Comment by santoshbagadi** [comment]
Hi @vhnunes , our latest SDK requires Xcode 14. Please upgrade to Xcode 14 to fix the issue.

**Comment by YuliyF** [comment]
I have Version 14.2 (14C18) and Applovin 5.8.0 and problem with:
AdColony
BidMachine
Pangle
DT Exchange - Fiber
Facebook
AdMob

as:
/AppLovinMediationAdColonyAdapter/libAdColonyAdapter.a(ALAdColonyMediationAdapter.o)' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. f
ile '/Users/hetzner/Library/Developer/Xcode/DerivedData/Unity-iPhone-fjolprfuvhkosrdeauafchzsqzcj/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppLovinMediationAdColonyAdapter/libAdColonyAdapter.a' for architecture arm64

**Comment by vhnunes** [comment]
> I have Version 14.2 (14C18) and Applovin 5.8.0 and problem with:
> AdColony
> BidMachine
> Pangle
> DT Exchange - Fiber
> Facebook
> AdMob
> 
> as:
> /AppLovinMediationAdColonyAdapter/libAdColonyAdapter.a(ALAdColonyMediationAdapter.o)' does not contain bitcode. 
> You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. f
> ile '/Users/hetzner/Library/Developer/Xcode/DerivedData/Unity-iPhone-fjolprfuvhkosrdeauafchzsqzcj/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppLovinMediationAdColonyAdapter/libAdColonyAdapter.a' for architecture arm64

Try to disable bitcode in Xcode. From the max docs, Xcode 14 does not support bitcode anymore.

**Comment by YuliyF** [comment]
'../Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppLovinMediationInMobiAdapter/libInMobiAdapter.a(ALInMobiMediationAdapter.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '.../Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppLovinMediationInMobiAdapter/libInMobiAdapter.a' for architecture arm64
 --
 InMobi and so on

**Comment by vhnunes** [comment]
> Hi @vhnunes , our latest SDK requires Xcode 14. Please upgrade to Xcode 14 to fix the issue.

Hey Santos, after switching to xcode 14, facebook sdk goes mad and is throwing me a signing error. When I fix it, I get you in touch about the build.

`error: Signing for "FBSDKCoreKit-FacebookSDKStrings" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'FBSDKCoreKit-FacebookSDKStrings' from project 'Pods')`

**Comment by vhnunes** [comment]
Fixed the "FBSDKCoreKit-FacebookSDKStrings" problem by updateing facebook sdk to 14.1.

My final success build setup was:

Unity/Xcode -> [Disable bitcode](https://support.unity.com/hc/en-us/articles/207942813-How-can-I-disable-Bitcode-support-)
Xcode -> Upgrade to xcode 14.1
FacebookSDK -> Upgrade to plugin v14.1

**Comment by vhnunes** [comment]
Would be nice if [in the docs](https://dash.applovin.com/documentation/mediation/unity/getting-started/integration) we could have a explicit minimum xcode version🙂
