### ISSUE TITLE
GADApplicationIdentifier is missing in my info.plist

### ISSUE THREAD

**Issue by nooralibutt** [AppLovin/AppLovin-MAX-Unity-Plugin#233]
### MAX Plugin Version

5.8.0

### Unity Version

2018.4.36

### Device/Platform Info

iOS 16

### Current Behavior

I have recently upgraded to 5.8 from 4.8 something and my admob id is being removed somehow every time I build. I do not use admob adapter from MAX plugin, I have directly integrated the admob plugin without mediation.

### Expected Behavior

it should not remove GADApplicationIdentifier from info.plist

### How to Reproduce

just build with admob plugin and max plugin side by side and see admob id will be removed by applovin plugin

**Comment by nooralibutt** [comment]
@santoshbagadi I am using applovin and admob sdks separately. I tried using applovin max and added admob adapter but somehow admob doesn't give good fill when we use other mediations. When we integrate all the plugins ourself admob give good fill. We get good impression rate. So we have integrated admob applovin and unity separate SDKs and managing through our own AdController

**Comment by thomasmso** [comment]
@nooralibutt - We pushed a plugin v5.8.1 which fixes this issue. Please let us know if the issue persists.
