### ISSUE TITLE
MaxSDK  init failed 

### ISSUE THREAD

**Issue by Rhyme1314** [AppLovin/AppLovin-MAX-Unity-Plugin#235]
### MAX Plugin Version

5.8.0

### Unity Version

2021.3.18

### Device/Platform Info

Android10

### Current Behavior

MaxSDK  init failed,This is logcat:
 E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/applovin/sdk/AppLovinCFService$OnCFCompletionCallback;
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/applovin/sdk/AppLovinCFService$OnCFCompletionCallback;

### How to Reproduce

build by AndroidStudio,locat show:
E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/applovin/sdk/AppLovinCFService$OnCFCompletionCallback;
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/applovin/sdk/AppLovinCFService$OnCFCompletionCallback;

**Comment by nohtaray** [comment]
@Rhyme1314 I am also experiencing the same issue.
How did you manage to resolve the problem?

**Comment by Rhyme1314** [comment]
> problem

ProjectSettings > Publishing Settings
Check two options:
Custom Main Gradle Template
Custom Gradle Properties Template

then force resolve
