### ISSUE TITLE
Errors in Xcode from post pod installation

### ISSUE THREAD

**Issue by AnyMindG** [AppLovin/AppLovin-MAX-Unity-Plugin#236]
<img width="257" alt="Screenshot 2023-03-20 at 3 50 16 PM" src="https://user-images.githubusercontent.com/111370321/226312227-1c7f04a7-7077-4ba3-a59a-f5734155203b.png">
<img width="570" alt="Screenshot 2023-03-20 at 3 50 24 PM" src="https://user-images.githubusercontent.com/111370321/226312203-bbff149a-0635-42ee-a825-08198d715d1a.png">

   Hi, so we recently updated the AppLovinMax plugin for Unity to the latest version, i.e 11.8.2 for both Android and iOS. But, we are facing some issues in generating a working iOS build. Please find attached screenshots of the errors generated in Xcode due to AppLoviMax plugin.
We have also unselected use_frameworks! and 'Always add the main target to Podfile' under iOS Resolver Settings, but that does not resolve our issue.
_Originally posted by @AnyMindG in https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/65#issuecomment-1475970137_

**Comment by alvarshahanji** [comment]
@AnyMindG  Our new SDK may not be pulled in in your existing build. Could you first try a clean build?
