### ISSUE TITLE
Unify path separators for cross-platform compatibility

### ISSUE THREAD

**Issue by imurashka** [AppLovin/AppLovin-MAX-Unity-Plugin#237]
### Feature Description

Hello!

The current implementation of AppLovin Max SDK uses "/" as the path separator in various methods, including "UpdateAssetLabelsIfNeeded" and "MovePluginFiles," and possibly other locations. This approach often leads to issues when working simultaneously on macOS and Windows. Specifically, the "MovePluginFiles" method does not work on Windows, and the "UpdateAssetLabelsIfNeeded" method constantly changes asset labels.

Proposed Solution:
To resolve these cross-platform compatibility issues, I suggest standardizing path separators throughout the SDK by replacing instances of "\\" with "/". This can be achieved using a simple string.Replace("\\", "/") operation. Implementing this change will improve the SDK's functionality on both macOS and Windows, reducing user frustration and potential errors.

Benefits:
- Improved cross-platform compatibility: Ensuring the SDK works seamlessly on both macOS and Windows without any issues.
- Reduced errors and frustration: Users will no longer experience problems related to path separators when working with the SDK on different platforms.
- Easier maintenance and support: Unifying path separators will simplify the SDK codebase, making it easier to maintain and support in the future.

**Comment by santoshbagadi** [comment]
Our latest plugin version fixes this issue.
