### ISSUE TITLE
Allow fixed SDK and Adapters versions at the company level across all projects

### ISSUE THREAD

**Issue by imurashka** [AppLovin/AppLovin-MAX-Unity-Plugin#238]
## Problem

We have been actively using the AppLovin MAX SDK for a while now and are currently working on unifying the versions of the SDK and mediation adapters across all our projects. We have a separate repository that serves as a storage for different SDKs, where we fix the versions of all SDKs and then use it as a submodule for all our projects. Each SDK has a structure like a UPM package, so we have to slightly modify those SDKs that don't have a UPM-compatible structure.

Our main goal is to have the ability to fix the same version of SDK and mediation adapters at the company level for all projects. This approach saves us a lot of time in testing and integration, as we have about 10 projects in development concurrently.

## Current Situation

The AppLovin MAX SDK format generally allows converting itself into a UPM package since it supports moving the SDK to a non-default folder. However, we want to fix not only the SDK version but also the versions of all mediation adapters. As far as I understand, even if the SDK is not in the default folder, it will still look for mediation adapters in the `Assets/MAX/` folder when searching for their current versions.

For example, in the `LoadPluginData` method, there is a line: `var mediationPluginParentDirectory = MediationSpecificPluginParentDirectory;`. In turn, `MediationSpecificPluginParentDirectory` checks where the plugin is located and if it is not in the default folder, it will return "Assets".

```csharp
public static string MediationSpecificPluginParentDirectory
{
    get { return IsPluginOutsideAssetsDirectory ? "Assets" : PluginParentDirectory; }
}
```

In this case, it would be more convenient to use `PluginParentDirectory` directly. Moreover, if you try to install a new mediation adapter, Unity will suggest placing it in the SDK folder instead of the default one.

## Proposed Solution
Modify the SDK to allow specifying the parent directory of mediation adapters when the SDK is in a non-default folder. This way, it will be easier to manage the versions of both the SDK and the adapters in a custom setup.

Please advise on how to handle this situation better.

**Comment by uchar** [comment]
This is related to this [issue](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/209) 
Any news on this? I think last time you guys said, you have a plan for it for early Q1

**Comment by imurashka** [comment]
Hello @santoshbagadi! Maybe you have any news about this ticket?

**Comment by santoshbagadi** [comment]
Hi @imurashka , since we added support for Unity Package Manager in our latest plugin version, this issue should be fixed.
