### ISSUE TITLE
Hi @providence94, thanks for reporting this issue. We identified the cause to be Fyber's SDK and pushed out a new Fyber adapter certifying against their latest which fixes it.

### ISSUE THREAD

**Issue by providence94** [AppLovin/AppLovin-MAX-Unity-Plugin#24]
Hi @providence94, thanks for reporting this issue. We identified the cause to be Fyber's SDK and pushed out a new Fyber adapter certifying against their latest which fixes it.

_Originally posted by @thomasmso in https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/23#issuecomment-631683821_

Hi thanks for the really quick response.
In our game we DONT use Fyber though :/

**Comment by thomasmso** [comment]
Hi @providence94 - do you mind sending us an IPA at devsupport@applovin.com? Also please CC your AM in that email.

**Comment by providence94** [comment]
@thomasmso yes let me do that..
a doubt though... do we need to add any of your device ids in our testing devices list or am i missing something ?

**Comment by thomasmso** [comment]
No need - that's only if you want to ensure you get fill for ads.

**Comment by providence94** [comment]
alright let me get on this.
thanks

**Comment by thomasmso** [comment]
@providence94 - We identified the issue and have fixed it in the latest release of our Unity Plugin. Please re-open issue if needed.
