### ISSUE TITLE
Huge number of crash related to fyber

### ISSUE THREAD

**Issue by uchar** [AppLovin/AppLovin-MAX-Unity-Plugin#241]
### MAX Plugin Version

5.8.2

### Unity Version

2021.3.20

### Device/Platform Info

Android

### Current Behavior

Recently, after updating the DT exchange ( fyber ) plugin to the latest version ( 8.2.2 ), we received a very large number of crashes 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5172296/230292297-f1b8bc21-aa70-47c9-9ace-1e2608287aab.png">

### Expected Behavior

No crash!

### How to Reproduce

Install applovin and fyber

**Comment by thomasmso** [comment]
Hi @uchar - this is actually related to Fyber's SDK and the latest AdMob SDK. They notified us earlier today that they remotely disabled the code path that was causing this crash. Please let us know if the crashes continue to occur though.
