### ISSUE TITLE
iOS fails due to DT Exchange adapter

### ISSUE THREAD

**Issue by vg-swift** [AppLovin/AppLovin-MAX-Unity-Plugin#248]
### MAX Plugin Version

5.9.0

### Unity Version

2021.3.20

### Device/Platform Info

iOS

### Current Behavior

Started failing randomly today, no changes in the project, and no changes to the build configuration.

[!] CocoaPods could not find compatible versions for pod "Fyber_Marketplace_SDK":
[2023-04-19T10:59:59Z - Unity]   In Podfile:
[2023-04-19T10:59:59Z - Unity]     AppLovinMediationFyberAdapter (= 8.2.0.0) was resolved to 8.2.0.0, which depends on
[2023-04-19T10:59:59Z - Unity]       Fyber_Marketplace_SDK (= 8.2.0)

### Expected Behavior

Build succeeds

### How to Reproduce

Build in UCB

**Comment by saxahan** [comment]
Same here.
Max plugin v5.9.0

**Comment by applovinAsh** [comment]
Thank you for bringing this to our attention. We are in the process of updating our adapter to support DTExchange 8.2.1 SDK, and we will update you once the adapter is live.

**Comment by applovinAsh** [comment]
The Fyber/ DTExchange adapter has been updated to support 8.2.1 and is live.

**Comment by saxahan** [comment]
I got xcode compile error @applovinAsh 

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PAGPlayer", referenced from:
      objc-class-ref in PAGAdSDK(PAGAppOpenAdExpressView.o)
      objc-class-ref in PAGAdSDK(PAGRewardedVideoDisplayViewController.o)
      objc-class-ref in PAGAdSDK(PAGVideoAdView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressVideoView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressRewardedVideoAdView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressFeedVideoAdView.o)
      __OBJC_$_CATEGORY_PAGPlayer_$_Settings in PAGAdSDK(PAGPlayer+Settings.o)
      ...
     (maybe you meant: _OBJC_CLASS_$_PAGPlayerTimeObserverModel)
  "_OBJC_CLASS_$_PAGPlayerItem", referenced from:
      objc-class-ref in PAGAdSDK(PAGAppOpenAdExpressView.o)
      objc-class-ref in PAGAdSDK(PAGRewardedVideoDisplayViewController.o)
      objc-class-ref in PAGAdSDK(PAGVideoAdView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressVideoView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressRewardedVideoAdView.o)
      objc-class-ref in PAGAdSDK(PAGNativeExpressFeedVideoAdView.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by vg-swift** [comment]
Same here, with same exact error

**Comment by vg-swift** [comment]
The issue seems to fixed now. What caused the issue, was it some kind of stealth update? 
We didn't update any adapters on our end.
