### ISSUE TITLE
AdMob Adapter ANRs

### ISSUE THREAD

**Issue by vg-swift** [AppLovin/AppLovin-MAX-Unity-Plugin#249]
### Feature Description

Based on this article, most of our ANRs come from AdMob
https://www.linkedin.com/posts/hilvoju_admon-mobilegames-programming-activity-7056500812050481152-uGkm?utm_source=share&utm_medium=member_desktop

![image](https://user-images.githubusercontent.com/113506557/234247130-d65f96b4-ba81-4832-90a4-3f2b54639b60.png)

```
The fix is to enable Optimize Initialization and Optimize Ad Loading flags in GMA settings in Admob SDK that offloads the ad init and loading to the background thread to make sure the app is stable. 
The flags are disabled by default, so these flags should be enabled  manually.
```

Could you please add a way to set these flags, and if it's already possible, could you please share how to do this?

Thanks!

**Comment by manelizzard** [comment]
Interested!

**Comment by ab-rdarts** [comment]
Does applovin uses `MobileAds.RaiseAdEventsOnUnityMainThread = true;` for google ads as mentioned here to prevent ants: https://github.com/googleads/googleads-mobile-unity/issues/2854

**Comment by santoshbagadi** [comment]
Hi @ab-rdarts , that API is for AdMob Unity plugin. Our adapters interact with the AdMob SDK natively and we don't call any of their Unity APIs. 

Almost all of our callbacks are already called on Unity main thread. Currently, only the `OnAdRevenuePaidEvent` and `OnAdReviewCreativeIdGeneratedEvent` events are called on a background thread, since they are generally not used to update any game UI.

**Comment by juanblasco** [comment]
> Seems you only need to add these two values to your AndroidManifest.xml. Let us know the results if you try! https://developers.google.com/admob/android/optimize-initialization#update_your_manifest_file

Applovin has it's own manifest, wondering if we should add those values to the Applovin manifest too or just to the main app one.

Anybody ?

**Comment by xy2080** [comment]
> > Seems you only need to add these two values to your AndroidManifest.xml. Let us know the results if you try! https://developers.google.com/admob/android/optimize-initialization#update_your_manifest_file
> 
> Applovin has it's own manifest, wondering if we should add those values to the Applovin manifest too or just to the main app one.
> 
> Anybody ?

The Applovin technician says It should be added to your app's AndroidManifest.xml file

**Comment by cihadturhan** [comment]
Hi, anyone tried this and get better results.
I started to get ANR and crash rates above acceptable levels.
The main exception is the one @ab-rdarts mentioned in google ads repo.

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/26a58306-6dd6-4d66-829d-ff1d6de5d0fe">

I'm going to try creating a build and see if it works.

**Comment by jayesh-w2w** [comment]
I have a question regarding the compatibility of the following meta-data lines in the Android manifest:
`<meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION" android:value="true"/>
<meta-data android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING" android:value="true"/>`
I know that these work with the AdMob Unity plugin, but I'm not sure if they work with Max Mediation. Could someone clarify this?

**Comment by santoshbagadi** [comment]
Hi @jayesh-w2w , our Unity plugin now automatically adds those two flags to the AndroidManifest. These settings are valid for MAX mediation as well.
