### ISSUE TITLE
iOS cloud build Fails with Amazon Mediation compiling with Xcode 14.1.0

### ISSUE THREAD

**Issue by pedro15** [AppLovin/AppLovin-MAX-Unity-Plugin#251]
### MAX Plugin Version

5.9.0

### Unity Version

2021.3.21f1

### Device/Platform Info

iOS

### Current Behavior

When trying to compile with Amazon Mediation, iOS build fails with the following error:

`[error] [2023-04-29T16:34:12.967Z] - 7.3.8.2.7.4 - INFO: ❌  /BUILD_PATH/game_name/Assets/Amazon/Plugins/iOS/AmazonManager.mm:186:22: no visible @interface for 'DTBAdResponse' declares the selector 'keywordsForMopub'`

### Expected Behavior

Compilation success without issues with the result of a working app

### How to Reproduce

Using the Same Unity version and the same MAX Plugin provided in this bug report, 
Then install the following version of Amazon Unity SDK: 1.5.1 and Applovin MAX Mediation SDK: 1.5.1 throught the Amazon SDK Manager, 

Navigate to Assets/Amazon/Mediations/ApplovinMediation/Editor/Dependencies.xml

And be sure that in the iOS pod it looks like this ( default dependency version ):
`<iosPods>
        <iosPod name="AppLovinMediationAmazonAdMarketplaceAdapter" version="~> 4.5" />
  </iosPods>`

iOS resolver settings: https://imgur.com/n4GLvQl
Finally, start compilation using unity cloud build with XCode 14.1.0 and Ruby 2.7.4 and see how it fails.

**Comment by santoshbagadi** [comment]
Hi @pedro15 , this seems to be an issue in the Amazon plugin itself. Please reach out to Amazon with the error so that they can further assist with the issue.
