### ISSUE TITLE
Android Tapjoy build fails 

### ISSUE THREAD

**Issue by AAAYaKo** [AppLovin/AppLovin-MAX-Unity-Plugin#255]
### MAX Plugin Version

5.10.0

### Unity Version

2021.3.25

### Device/Platform Info

PC: Windows 11

### Current Behavior

Trying to build an application(target: Android), process crashes on gradle.
With other mediations we haven't problems.
Error message:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':unityLibrary:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-auth:16+.
     Required by:
         project :unityLibrary
      > Failed to list versions for com.google.android.gms:play-services-auth.
         > Unable to load Maven meta-data from https://sdk.tapjoy.com/com/google/android/gms/play-services-auth/maven-metadata.xml.
            > Could not get resource 'https://sdk.tapjoy.com/com/google/android/gms/play-services-auth/maven-metadata.xml'.
               > Could not GET 'https://sdk.tapjoy.com/com/google/android/gms/play-services-auth/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

### How to Reproduce

Build unity project with added Tapjoy network for android.

**Comment by santoshbagadi** [comment]
Hi @AAAYaKo , we are not able to reproduce the issue and the issue doesn't seem to be from Tapjoy adapter. TapJoy SDK does not have a dependency on `play-services-auth` library. So, it seems to be coming from some other library.

**Comment by AAAYaKo** [comment]
Yes, I was able to build the project today too, maybe there were problems with Tapjoy's repository server.
