### ISSUE TITLE
Error getting value for key: IABTCF_gdprApplies

### ISSUE THREAD

**Issue by majidkh** [AppLovin/AppLovin-MAX-Unity-Plugin#257]
I see a lot of Errors after initializing the AppLovin Max on Unity and I use Google User Messaging Platform.

Using 11.9.0 Plugin for Unity, any idea how to solve this?

`2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk [SharedPreferencesManager] Error getting value for key: IABTCF_gdprApplies
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:329)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.c.e.a(SourceFile:234)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.t(SourceFile:796)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.h(SourceFile:717)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.a(SourceFile:202)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:242)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:28)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl$1.run(SourceFile:179)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.e.z.run(SourceFile:30)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.lang.Thread.run(Thread.java:1012)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk [SharedPreferencesManager] Error getting value for key: IABTCF_gdprApplies
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.c.e.a(SourceFile:177)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.t(SourceFile:797)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.h(SourceFile:717)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.q.a(SourceFile:202)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:242)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:28)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl$1.run(SourceFile:179)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at com.applovin.impl.sdk.e.z.run(SourceFile:30)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/05/23 12:16:38.391 12958 13246 Error AppLovinSdk 	at java.lang.Thread.run(Thread.java:1012)
`

**Comment by thomasmso** [comment]
Hi @majidkh - these errors can be ignored. They should already be removed, unless you have our SDK's verbose logging enabled.

**Comment by thomasmso** [comment]
@majidkh - Amazon has a very unique integration as required by their team. You can refer to the docs here: https://dash.applovin.com/documentation/mediation/unity/mediation-adapters/amazon.

**Comment by majidkh** [comment]
@thomasmso 

The above still appears even when I disable verbose logging:

I see below in the logcat

```
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk ===SDK Settings===
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk SDK Key: XXXX
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk Mediation Provider: admob
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk TG: 4
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk AEI: 100
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk MEI: 7
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk Test Mode On: false
2023/07/16 09:29:25.827 10446 10771 Debug AppLovinSdk Verbose Logging On: false
```

.
.
.

`2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk [SharedPreferencesManager] Error getting value for key: IABTCF_gdprApplies
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.c.e.a(SourceFile:255)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.t(SourceFile:799)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.h(SourceFile:722)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.a(SourceFile:200)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:31)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl$1.run(SourceFile:178)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.e.ac.run(SourceFile:30)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.lang.Thread.run(Thread.java:1012)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk [SharedPreferencesManager] Error getting value for key: IABTCF_gdprApplies
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:329)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.c.e.a(SourceFile:234)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.t(SourceFile:801)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.h(SourceFile:722)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.a(SourceFile:200)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:31)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl$1.run(SourceFile:178)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.e.ac.run(SourceFile:30)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.lang.Thread.run(Thread.java:1012)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk [SharedPreferencesManager] Error getting value for key: IABTCF_gdprApplies
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:345)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.c.e.a(SourceFile:177)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.t(SourceFile:802)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.h(SourceFile:722)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.p.a(SourceFile:200)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl.a(SourceFile:31)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.EventServiceImpl$1.run(SourceFile:178)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at com.applovin.impl.sdk.e.ac.run(SourceFile:30)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/07/16 09:29:53.060 10446 10771 Error AppLovinSdk 	at java.lang.Thread.run(Thread.java:1012)
`
