### ISSUE TITLE
Close button overlaps iOS status bar & notch and is not clickable

### ISSUE THREAD

**Issue by rbyjoswald** [AppLovin/AppLovin-MAX-Unity-Plugin#261]
### MAX Plugin Version

5.6.4

### Unity Version

2021.3.19f1

### Device/Platform Info

iOS (15 & 16)

### Current Behavior

For some ads the close-button is drawn at the same position as the iOS status bar is. The close-button thus looks visually glitched and cannot be clicked. Also it may be cropped by the physical notch that's typically at the same height. In short:

The close-ad button is cropped by the notch, overdrawn by the status-bar & not clickable.

Users can therefore become stuck with no other way to leave than close the app.

### Expected Behavior

Close-ad button must never violate the Screen.safeArea and always remain clickable.

### How to Reproduce

Only on iOS. Invoke MaxSdk.ShowRewardedAd or ShowInterstitial. Our mediation networks are the following:

Chartboost, Facebook, Google AdMob, Google Ad Manager, ironSource, Pangle, Unity Ads.

I do not know which network the faulty ads are coming from.

### Additional Info

![IMG_0136](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/20922523/40cedc86-f1ad-4604-9f0d-8837ce9ea990)

**Comment by Lorenzo45** [comment]
Hi @rbyjoswald 

Thanks for reaching out. You can check the [Creative Debugger](https://dash.applovin.com/documentation/mediation/ios/testing-networks/creative-debugger) or device logs to see which network the ad is from.

Based on the screenshot and other reports we've received, I believe this ad is from AdMob so you'll have to report this issue to Google for them to resolve.

**Comment by rbyjoswald** [comment]
Hello. Thanks for the answers. I feel like you, as the providers of the MAX SDK might have more leverage talking to AdMob than me as a single app-developer. Can you do a quick inquire with them? Would be greatly appreciated.
