### ISSUE TITLE
Error -4205 Attempting to show ad from <network_X> which does not match selected ad network <network_y>

### ISSUE THREAD

**Issue by oseq** [AppLovin/AppLovin-MAX-Unity-Plugin#264]
### MAX Plugin Version

5.10.1

### Unity Version

2021.3.10

### Device/Platform Info

Android (multiple versions and devices)

### Current Behavior

While loading rewarded ad SDK sometimes produces error -4205 _Attempting to show ad from <network_X> which does not match selected ad network <network_y>_ for example:
 _[MaxRewarded] Attemntping to show ad from <UNITY_NETWORK>which does not match selected ad network <APPLOVIN_NETWORK>._

This error does not yield an error callback so the app behaves as if the ad is showing and it isn't.

### Expected Behavior

Should display ad properly or callback an error

### How to Reproduce

This most often happens when you try to trigger the first rewarded ad in the session. You can also trigger it with Applovin Debug with one selected network.

In our app we have 4 connected networks:
-Applovin (Bidding)
-Google Admob
-ironSource
-Unity Ads

### Additional Info
Logcat:
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/9092974/fd017d5b-75ef-4efe-8e8c-da20e426ad25)
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/9092974/6432d1a7-c6ac-4fba-90d0-b29f2103be9d)
You can also trigger this bug with Debugger
![Screenshot_20230615_232453_games mousetrap cardsup](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/9092974/e69413c8-8bfd-46bf-ac7e-7ce931207fb0)

**Comment by santoshbagadi** [comment]
Hi @oseq , the error means that a test ad was loaded earlier and the same ad unit ID is being used to show a new ad with test mode then disabled. 

We do send an ad display failed error callback. You can listen to this even by registering to `MaxSdkCallbacks.OnAdDisplayFailedEvent`. 

Are you by any chance loading ads in the mediation debugger before trying to show them here?

**Comment by oseq** [comment]
We recorded this bug also for users without debug mode, but it only happened 2 times during QA. 

In fact, after reporting the bug, analyzing the logs, we discovered the OnAdDisplayFailedEvent callback and handled it, so even if such a problem occurs, it should not crash the application.

**Comment by santoshbagadi** [comment]
If you see the issue happen without debug/test ads loaded before, please send us the logs so that we can investigate further.
