### ISSUE TITLE
[Feature] Does Applovin Max support Google UMP?

### ISSUE THREAD

**Issue by CodeMasterYi** [AppLovin/AppLovin-MAX-Unity-Plugin#269]
### Feature Description

As the title, does Applovin Max support Google UMP?

[Obtain consent with the User Messaging Platform.](https://developers.google.com/interactive-media-ads/ump)

**Comment by ShahHusayn** [comment]
Any progress? Does Applovin Max support Google UMP? How do we show Google verified consent using Applovin @prod-applovin-ops @santoshbagadi @JonathanLiuApp @JaniceCaoApplovin

**Comment by thomasmso** [comment]
Hi all - we're releasing a new Unity Plugin mid/late Sept which will be able to support Google UMP. I will notify this thread when that release occurs. Until then, please make sure to set our GDPR user consent APIs per our docs [here](https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#consent-and-age-related-flags-in-gdpr-and-other-regions).

**Comment by santoshbagadi** [comment]
Hi, we currently do not include Google's CMP via our Plugin. You would need to integrate the UMP flow (or any [Google Certified CMP](https://support.google.com/admanager/answer/13554116#zippy=%2Cgoogle-certified-cmps)) separely and show it before before initalizing our SDK.

**Comment by CodeMasterYi** [comment]
> Hi all - we're releasing a new Unity Plugin mid/late Sept which will be able to support Google UMP. I will notify this thread when that release occurs. Until then, please make sure to set our GDPR user consent APIs per our docs [here](https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#consent-and-age-related-flags-in-gdpr-and-other-regions).

Sounds great! Long for future release.

**Comment by umairmanz** [comment]
> Hi all - we're releasing a new Unity Plugin mid/late Sept which will be able to support Google UMP. I will notify this thread when that release occurs. Until then, please make sure to set our GDPR user consent APIs per our docs [here](https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#consent-and-age-related-flags-in-gdpr-and-other-regions).

Any exact time frame for this update?

**Comment by thomasmso** [comment]
The release has been delayed to mid/late October.

**Comment by thomasmso** [comment]
@ShahHusayn - It will likely be released this weekend. I'll keep this thread posted.

**Comment by ShahHusayn** [comment]
eagerly waiting 🍡

**Comment by ShahHusayn** [comment]
Well the weekend has passed already? When's the new release coming? Containing UMP support?

**Comment by thomasmso** [comment]
Hey @ShahHusayn - It should be this week. We're finalizing some changes/documentation and doing final assessments of beta tests.

**Comment by ShahHusayn** [comment]
@thomasmso waiting for the update lol, now it seems quite funny how you guys are delaying and making excuses. Pathetic!

**Comment by thomasmso** [comment]
Hey @ShahHusayn - I understand the frustration, but we want to ensure that no stones are left unturned when deploying this feature, and are in the final phases of analyzing an immense amount of data.

**Comment by dolearndouble** [comment]
Waiting, looking forward to seeing the download link and documentation link for this ump plugin here.

**Comment by CodeMasterYi** [comment]
I'll keep waiting until google's deadline.

**Comment by umairmanz** [comment]
Any update ???

**Comment by santoshbagadi** [comment]
We've just released plugin [version 6.0.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_0_0) which includes support for Google UMP.

**Comment by harunayyildizhadi** [comment]
Is it possible to have custom popups somehow instead of this ugly one?
<img width="407" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/98486802/c2ec37b6-e080-4e8b-9adb-2155e5b45f06">

**Comment by CodeMasterYi** [comment]
I think x.0.0 must be an alpha or beta release. waiting for more actions.
