### ISSUE TITLE
Very difficult to close ads (Vungle adapter)!

### ISSUE THREAD

**Issue by N0lex** [AppLovin/AppLovin-MAX-Unity-Plugin#27]
Hi!

On older devices, it’s very difficult to close some ads (from Vungle)!
Other adapters works fine (UnityAds, AppLovin).

- Platform: iOS
- Environment: Unity 2019.2.12, Xcode 11.4.1
- Plugin Version: Max-Unity-2.4.6
- Devices: iPad Mini 2, iPhone 5s
- Vungle adapter: 6.5.3 (latest version)

**Video:** https://www.youtube.com/watch?v=oI0_O3n6_6A

P.S. Old Android devices have the same problem.

Please fix!

**Comment by thomasmso** [comment]
Hi @N0lex, we have no control over how Vungle shows their ads - do you mind bringing up the issue to them?

**Comment by N0lex** [comment]
@thomasmso Sorry, but I downloaded your SDK (AppLovin MAX) and it uses this adapter. In my opinion, you should provide a working system and help solve such problems.
