### ISSUE TITLE
com.applovin.mediation.unity.MaxUnityAdManager$3.onSdkInitialized  - Crash 

### ISSUE THREAD

**Issue by connectinno** [AppLovin/AppLovin-MAX-Unity-Plugin#270]
### MAX Plugin Version

5.10.1

### Unity Version

2021.3.2f1

### Device/Platform Info

Android 10 & Android 12

### Current Behavior

Crash when Applovin SDK is started on Android phones. Devices ( Samsung, Huawei, Xaomi). 
The sample crash report from HUAWEI MRX-W09: 

```
Caused by java.lang.NoSuchMethodError: No interface method isTestModeEnabled()Z in class Lcom/applovin/sdk/AppLovinSdkConfiguration; or its super classes (declaration of 'com.applovin.sdk.AppLovinSdkConfiguration' appears in /data/app/com.Connectinno.Games.Collect3D-sZsEUx58etRi2FKlKIN6ug==/base.apk!classes4.dex)
       at com.applovin.mediation.unity.MaxUnityAdManager$3.onSdkInitialized(MaxUnityAdManager.java:258)
       at com.applovin.impl.sdk.p$5.run(SourceFile:897)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```
[crash_session_64AF9D7403E4000154BBFB901FDD0FC0_DNE_0_v2_stacktrace.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/12038982/crash_session_64AF9D7403E4000154BBFB901FDD0FC0_DNE_0_v2_stacktrace.txt)

### How to Reproduce

Starting adjust SDK at Sandbox Mode: 

AdjustConfig adjustConfig = null; 
adjustConfig = new AdjustConfig(Adjustoken, AdjustEnvironment.Sandbox, true);
adjustConfig.setLogLevel(AdjustLogLevel.Verbose);

adjustConfig.setAppSecret(1, "xx", "xx", "xx", "xx");
adjustConfig.setSendInBackground(true);
Adjust.start(adjustConfig);

**Comment by thomasmso** [comment]
@connectinno - You probably have a mismatched Unity Plugin and AppLovin SDK versions. Please ensure you are on the latest: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_10_1.

**Comment by connectinno** [comment]
Actually we're using the latest Unity Applovin SDK. 


<img width="826" alt="Screenshot 2023-07-13 at 23 02 19" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/108933317/46becc2b-f71f-41a6-bad9-f5c5a996a621">

**Comment by santoshbagadi** [comment]
@connectinno was the plugin updated recently? It feels like there is a stale version of our Android Unity plugin `.aar` file in the project. Do you mind trying a [clean build of the project](https://docs.unity3d.com/2022.1/Documentation/Manual/incremental-build-pipeline.html#creating-non-incremental-builds) and see if that fixes the issue.

If that doesn't work, there might be an issue where the import didn't happen correctly. You'd have to delete the `Assets/MaxSdk` folder and re-import our plugin.
