### ISSUE TITLE
Bitcode related linker error in ALMAX SDK through unity application

### ISSUE THREAD

**Issue by preety8906** [AppLovin/AppLovin-MAX-Unity-Plugin#274]
### MAX Plugin Version

5.10.1, 5.11.2

### Unity Version

2019.4.40f1

### Device/Platform Info

iOS

### Current Behavior

Observed bitcode related linker error when exported the unity project for device in `Xcode 14.3`
Error logs:
```
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/abc/Documents/Unity/TestALMAX/iOS/1/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: '/Users/abc/Library/Developer/Xcode/DerivedData/Unity-iPhone-gbsnbxiigdliqpdmmwmvaypjbpea/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppLovinSDK/AppLovinSDK.framework/AppLovinSDK(ALVASTContext.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/preety/Library/Developer/Xcode/DerivedData/Unity-iPhone-gbsnbxiigdliqpdmmwmvaypjbpea/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/AppLovinSDK/AppLovinSDK.framework/AppLovinSDK' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Behavior

The exported project should build successfully.

### How to Reproduce

1. Create empty project with `Unity 2019.4.40f1`.
2. Import ALMAX unity package `AppLovin-MAX-Unity-Plugin-5.10.1-Android-11.10.1-iOS-11.10.1.unitypackage`.
3. Build the project for iOS for device.
4. Open exported xcworkspace project. The podfile looks like: 
```
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinSDK', '11.10.1'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

```
5. Build it for device target.

**Note:** Similar steps followed for latest MAX unity plugin `AppLovin-MAX-Unity-Plugin-5.11.2-Android-11.11.2-iOS-11.11.2.unitypackage` and same issue is observed.

### Additional Info

When tried by manually enabling/disabling enable bitcode flag in xcode project for both `Unity-iPhone` project and target, it worked.

**Comment by santoshbagadi** [comment]
Xcode 14 deprecated bitcode, so none of our artifacts are built with bitcode anymore. Please disable bitcode to fix the issue. (Here is a guide on how bitcode can be disabled from Unity: https://support.unity.com/hc/en-us/articles/207942813-How-can-I-disable-Bitcode-support-)

https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
