### ISSUE TITLE
OMSDK_Smaato (no such file, not in dyld cache)

### ISSUE THREAD

**Issue by dreamcodestudio** [AppLovin/AppLovin-MAX-Unity-Plugin#282]
### MAX Plugin Version

5.11.3

### Unity Version

2020.3.34f1

### Device/Platform Info

iOS 16.6

### Current Behavior

Application crashes on ad loading

Error message:
```
OMSDK_Smaato.framework/OMSDK_Smaato' (no such file, not in dyld cache)
```

### Expected Behavior

XCode build should works fine without such problems

### How to Reproduce

1. Install `AppLovin v5.11.3` + `Facebook SDK v16.0.2` in Unity project
2. Install `Smaato iOS v22.3.0.0` network from AppLovin `Integration Manager`
3. Use static framework linkage in `iOS Resolver`
4. Build Xcode project

### Additional Info

iOS Resolver Settings

<img src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/7010398/5e1d238a-9bc0-426e-92ea-30716a2a1f23" height="500">

**Comment by JonathanLiuApp** [comment]
Please try unchecking `Add use_frameworks! to Podfile` and `Always add the main target to Podfile`.

**Comment by dreamcodestudio** [comment]
> Please try unchecking `Add use_frameworks! to Podfile` and `Always add the main target to Podfile`.

It's not help us, because after Apply current settings FB crashed, (they link on swift frameworks)

Log:
`
 *** Terminating app due to uncaught exception 'FBFinalClassViolationException', reason: 'FBAdSettings is a final class and cannot be subclassed. FBAdSettings'
 `

**Comment by JonathanLiuApp** [comment]
If you need to keep the settings checked, you would have to add the `OMSDK_Smaato` framework to the embedded frameworks list to the main target to fix this startup crash.

**Comment by dreamcodestudio** [comment]
All modern Unity third-party SDK works fine with Swift framework and we expect it from parthers networks

**Comment by santoshbagadi** [comment]
We've updated our plugin (v6.4.3) to be able to work with the default EDM settings.
