### ISSUE TITLE
Error with Admob on Android build - Android Resource Linking failed

### ISSUE THREAD

**Issue by TrongHieu90** [AppLovin/AppLovin-MAX-Unity-Plugin#288]
### MAX Plugin Version

5.11.4

### Unity Version

2021.3.30f1

### Device/Platform Info

Android

### Current Behavior

Cannot build Android with Admob as an adnetwork in max sdk version 5.11.4. The key for admob is already provided.
If I remove the admob, the build works normally. Try adding other adnetworks doesn't show any issue

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/20443445/9f5df221-6f17-4937-90f6-8c861a312094)

### Expected Behavior

Should be able to build for android

### How to Reproduce

Install AppLovin / Max sdk for Unity
Install Admob in list of adnetworks
Build for Android
Error occurs.

### Additional Info

`Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Note: /Users/hieudev/Programming/Unity/WizardMaster/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/hieudev/.gradle/caches/transforms-2/files-2.1/4c88d5603e715df48977ba1b1270bad4/jetified-applovin-sdk-11.11.3/AndroidManifest.xml:25:13-65: AAPT: error: unexpected element <property> found in <manifest><application>.`

**Comment by TrongHieu90** [comment]
Able to build admob finally. Upgrade gradle t0 6.9.3 and custom gradle plugin to 4.2.1

(Latest version of Admob with 5.11.4 max sdk requires gradle plugin of 4.2.0 plus)

**Comment by ygrinevich** [comment]
Same issue for me. Seems like a breaking issue for Unity 2021.3 LTS users. Any chance to get it workinking out of the box without custom gradle version for Unity 2021.3?

**Comment by santoshbagadi** [comment]
Unfortunately, no. Android Gradle Plugin version 4.2.1 (or newer) is required to fix the issue.

**Comment by ygrinevich** [comment]
Do you know the max version for AdMod, AdManager that will be working with Gradle 6.11 + Gradle Plugin 4.0.1?

**Comment by santoshbagadi** [comment]
AdMob/GAM adapter version 22.3.0.0 or lower should work with older AGP versions.

**Comment by juanblasco** [comment]
Is this a valid approach on Unity?
![Captura de pantalla 2023-10-24 a las 10 54 11](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/135637089/365b712e-9fe0-417a-a203-8dedb50a685b)

**Comment by juanblasco** [comment]
Also, if the problem is the gradle, wouldn't be a possible workaround to use another gradle version?

**Comment by santoshbagadi** [comment]
Yes, either upgrading the Android Gradle Plugin to 4.2.1 (or newer) or downgrading the AdMob adapter should fix the issue.
