### ISSUE TITLE
Applovin MAX Android Build Issue. "2 files found with path 'META-INF/kotlinx_coroutines_core.version' from inputs"

### ISSUE THREAD

**Issue by muneebattamindravel** [AppLovin/AppLovin-MAX-Unity-Plugin#289]
### MAX Plugin Version

5.11.3

### Unity Version

2022.3.1f1

### Device/Platform Info

Android

### Current Behavior

1. I simply added the Applovin MAX plugin "AppLovin-MAX-Unity-Plugin-5.11.3-Android-11.11.3-iOS-11.11.3.unitypackage"

2. Opened the Integration Manager and added the SDK Key

3. Built for Android

I get the following error:

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx_coroutines_core.version' from inputs:
      - /Users/muneebattakhan/Mindravel/Projects/MaxMdeiation/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar
      - /Users/muneebattakhan/Mindravel/Projects/MaxMdeiation/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/org.jetbrains.kotlinx.kotlinx-coroutines-core-1.7.1.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Expected Behavior

The APK should be build without any issue.

### How to Reproduce

1. I simply added the Applovin MAX plugin "AppLovin-MAX-Unity-Plugin-5.11.3-Android-11.11.3-iOS-11.11.3.unitypackage"

2. Opened the Integration Manager and added the SDK Key

3. Built for Android

**Comment by marnelle1** [comment]
1. Go to build settings -> publishing settings -> Check Custom Gradle Launcher Template
2. Open launcherTemplate.gradle and type `packaging {
        resources {
            pickFirst += "META-INF/kotlinx_coroutines_core.version"
        }
    }` under **android {**

But I get another error now:
`[SafeDK-ERROR] Android variants not detected.
Please make sure you place the directive:
apply plugin: 'applovin'
after you apply the Android plugin in your build.gradle file`

**Comment by muneebattamindravel** [comment]
I was able to get the build working by doing the following (but not sure if this is the correct approach). 

I did this on a mac:
1. Goto project's root folder -> Library -> Bee -> Android -> Prj -> IL2CPP -> Gradle
2. Delete all gradle related files in this folder

![Screenshot 2023-10-04 at 9 11 12 PM](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/30898560/bf02f7d0-9f94-4d15-8e0d-2f699e0b223e)

3. Then go to unityLibrary and the launcher folders and open "build.gradle" files. 

4. In both of these files, in the packagingOptions add the following line: 
"exclude 'META-INF/kotlinx_coroutines_core.version'"

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/30898560/b151a19d-20ac-4779-b295-d9647fbad9cf)

Doing this, started created my Android builds and build working fine on device. 

However, this issue should be resolved at the plugin level.

**Comment by NanaAmoah** [comment]
Hi @muneebattamindravel and @marnelle1 this seems to be an issue with the latest Google AdMob SDK. Are you using v22.4.0.0 of the AdMob adapter? If you are, could you try using v22.3.0.0 instead to see if this resolves the issue?

**Comment by marnelle1** [comment]
Hi @NanaAmoah ! Thanks for feedback. How can I downgrade the admob version?
<img width="728" alt="image" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/10241150/87f38f8b-1342-4e60-9f68-12ca949505de">

**Comment by marnelle1** [comment]
@NanaAmoah I tried to delete admob and it builds fine, but I need admob anyway

**Comment by santoshbagadi** [comment]
You can downgrade the adapter by updating the iOS version in the `MaxSdk/Mediation/Google/Editor/Dependencies.xml` file to `22.3.0.0`.

**Comment by marnelle1** [comment]
> You can downgrade the adapter by updating the iOS version in the `MaxSdk/Mediation/Google/Editor/Dependencies.xml` file to `22.3.0.0`.

Thanks! That works great

**Comment by farmme-tienld** [comment]
@NanaAmoah Excuse me, this issue is not resolved. I'm using Unity 2022.3.11f1, AppLovin Intergration Manager 5.11.3. After install Facebook (android_6.16.0.2_ios_6.14.0.0), I meet this issue.

**Comment by NanaAmoah** [comment]
Hi @farmme-tienld, are you using AdMob in your app? Can you share a screenshot of your Unity integration manager and the build.gradle file in your exported Android project?

**Comment by adizhavo** [comment]
this issue still persists - any help / update on the thread pls

**Comment by NanaAmoah** [comment]
Hi @adizhavo  Can you share a screenshot of your Unity integration manager and the build.gradle file in your exported Android project?

**Comment by sanchez-v-klab** [comment]
Same problem with Unity 2023.2.20 after update to last version of Admob adapter.
