### ISSUE TITLE
The MaxSdkCallback.ForwardEvent is bulky and produces allocations. 

### ISSUE THREAD

**Issue by romanmbraingames** [AppLovin/AppLovin-MAX-Unity-Plugin#294]
### MAX Plugin Version

5.11.3

### Unity Version

2021.3.28f

### Device/Platform Info

Checked in Unity Editor and Android Device (Motorola ellis)

### Current Behavior

Currently, the MaxSdkCallbacks.ForwardEvent allocates around 200KB every OnBannerAdLoadedEvent, OnBannerAdClickedEvent (i.e. every that contains AdInfo). 

It looks like the current implementation of the method is not efficient enough for a usage.

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/130351695/284cf895-2928-4fa9-9a91-b43d893d115b)

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/130351695/7f4008df-6dca-4229-84a5-c8173d7e90c0)

On our side we did a several in-place changes above the current implementation to address this problem on our side but it will be nice to cover this on the side of the SDK.

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/130351695/80d2d153-4ce7-46e8-a740-d0f254aabaeb)

List of changes:
- Replace var eventProps = Json.Deserialize(eventPropsStr); MaxSdkUtils.GetStringFromDictionary(eventProps, "name", ""); with `[Serializable] class EventPropsName { public string name; }; JsonUtility.FromJson<EventPropsName>(eventProps).name` to receive an event name (but the recommended way is to pass it from native part as the separate parameter)
- Replace JSON with a JsonUtility.FromJson<T> with a proper dtos based on the event name.
- Don't serialize large volume of the data that may be unused (for example waterfallInfo of the AdInfo). In out case we serialize it lazily on demand.

### How to Reproduce

It's easy to reproduce, just integrate Ads banner and launch an application. Every time when you are receiving an event with adInfo inside you will notice the spike of the CPU and memory allocations.

**Comment by santoshbagadi** [comment]
Hi @romanmbraingames , thank you for raising the issue. We're already working on a way to reduce the amount of serialize/deserialize calls. Will update here once the fix is released.

**Comment by maximilianbuck** [comment]
Hi @romanmbraingames , we made changes to move serialize/deserialize to a background thread and released them in version 6.4.1 of our Unity Plugin.
