### ISSUE TITLE
[FR] Does Applovin for iOS includes "AdServices.framework"?

### ISSUE THREAD

**Issue by CodeMasterYi** [AppLovin/AppLovin-MAX-Unity-Plugin#297]
### Feature Description

As the title, I want to check if Applovin SDK for iOS includes `AdServices.framework`?
If yes, how can I check it?

**Comment by santoshbagadi** [comment]
@CodeMasterYi , no, our [SDK does not include `AdServices`](https://github.com/CocoaPods/Specs/blob/37c608f0061c7ba9294d2b5da1c40b5c8c8b1d69/Specs/9/c/c/AppLovinSDK/11.11.4/AppLovinSDK.podspec.json#L20-L35). You may check the list of frameworks we use in our [CocoaPods pod](https://cocoapods.org/pods/AppLovinSDK).
