### ISSUE TITLE
Gradle was unable to resolve dependencies between Applovin MAX and the Google Mobile Ads Unity plugin

### ISSUE THREAD

**Issue by ratushnyi** [AppLovin/AppLovin-MAX-Unity-Plugin#301]
### MAX Plugin Version

5.11.5

### Unity Version

2021.3.32

### Device/Platform Info

Android, IL2CPP

### Current Behavior

I tried to add Google Mobile Ads Unity Plugin (https://github.com/googleads/googleads-mobile-unity) and got that trouble on build Gradle:

BuildLog
>FAILURE: Build failed with an exception.
>
>* What went wrong:
[10554](https://github.com/app-craft/unity-ci/actions/runs/6788072822/job/18452280662#step:24:10555)
Execution failed for task ':launcher:processReleaseResources'.
[10555](https://github.com/app-craft/unity-ci/actions/runs/6788072822/job/18452280662#step:24:10556)
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[10556](https://github.com/app-craft/unity-ci/actions/runs/6788072822/job/18452280662#step:24:10557)
   > Android resource linking failed
[10557](https://github.com/app-craft/unity-ci/actions/runs/6788072822/job/18452280662#step:24:10558)
     /Users/ci/Development/actions-runner/_work/unity-ci/unity-ci/sample/Library/Bee/Android/Prj/IL2CPP/Gradle/launcher/build/intermediates/merged_manifests/release/AndroidManifest.xml:396: AAPT: error: unexpected element \<property> found in \<manifest>\<application>.

AndroidManifest.xml
>394 \<activity android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:exported="false" android:name="com.google.android.gms.ads.OutOfContextTestingActivity"/>
>395
>396 \<property android:name="android.adservices.AD_SERVICES_CONFIG" android:resource="@xml/gma_ad_services_config"/>
>397
>398 \<receiver android:exported="true" android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            \<intent-filter>
                \<action android:name="com.google.android.c2dm.intent.RECEIVE"/>
           \</intent-filter>
        \</receiver>

I also tried to remove Applovin MAX and build in done successfully.
I also changed verisions of Google AdMob and Google AdManaget networks, but it not depend on that trouble.
If i completely removed Google AdMob and Google AdManaget networks i got next failed reason:

BuildLog
>Could not load custom lint check jar file /Users/ci/.gradle/caches/transforms-2/files-2.1/292574117b23b00d7b8a1d174e7b5c45/jetified-material-1.2.1/jars/lint.jar
>[43287](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43288)
>java.lang.NoClassDefFoundError: com/android/tools/lint/client/api/Vendor
>[43288](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43289)
>	at androidx.compose.material.lint.MaterialIssueRegistry.<init>(MaterialIssueRegistry.kt:34)
>[43289](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43290)
>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>[43290](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43291)
>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>	///
>Could not load custom lint check jar file /Users/ci/.gradle/caches/transforms-2/files-2.1/bb326097aeb5f6dfced251179bf2a480/jetified-animation-1.1.1/jars/lint.jar
>[43419](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43420)
>java.lang.NoClassDefFoundError: com/android/tools/lint/client/api/Vendor
>[43420](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43421)
>	at androidx.compose.animation.lint.AnimationIssueRegistry.<init>(AnimationIssueRegistry.kt:35)
>[43421](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43422)
>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>[43422](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43423)
>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>	///
>FAILURE: Build failed with an exception.
>[43704](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43705)
>
>[43705](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43706)
>* What went wrong:
>[43706](https://github.com/app-craft/unity-ci/actions/runs/6773123120/job/18407255038#step:24:43707)
>Execution failed for task ':launcher:dexBuilderRelease'.

The Google Mobile Ads Unity Plugin is required to display the new Android consent flow (GDPR)(https://developers.google.com/admob/android/privacy), it should be implemented in the EU region from December and I'm hoping someone can help me with this problem.  Thanks!

### Expected Behavior

I got working build with new GDPR for Android, with Google Mobile Ads Unity Plugin or not and Applovin Max with Google AdMob and Google AdManager networks.

### How to Reproduce

Add in one project Google Mobile Ads Unity Plugin and Applovin Max 5.11.5 or lower and build Android with IL2CPP.

**Comment by JonathanLiuApp** [comment]
You should be able to fix the issue you are having by following the solution in this thread: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/286#issuecomment-1789323614.
