### ISSUE TITLE
Gradle compilation error about "<property>" in manifest with Max 6.0.0 & Google Adapter (Admob & Google Ad Manager)

### ISSUE THREAD

**Issue by Allpo** [AppLovin/AppLovin-MAX-Unity-Plugin#304]
### MAX Plugin Version

6.0.0

### Unity Version

2021.3.32

### Device/Platform Info

Android

### Current Behavior

- I tested this on my repository holder all my ads related stuff AND on an empty repository where I only installed Max Plugin.
- Everything works fine if there is only Max Plugin
- Everything works fine if I add : DT Exchange, Facebook, InMobi, IronSource, Liftoff Monetize, Mintegral, Pangle, Unity ads all at one
- I can't compile if I add Admob or Google Ad Manager, either solo, both of them or on top of all the other adapters

### Expected Behavior

I should get my APK

### How to Reproduce

- Add Max SDK to an empty project
- Add Admob adapter
- Try to compile for Android

### Additional Info

Compilation Stacktrace
`
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Note: /Users/kevinchailloux/Documents/gitlab/test_ads-kit/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/kevinchailloux/Documents/gitlab/test_ads-kit/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build/intermediates/library_manifest/debug/AndroidManifest.xml:61:13-47: AAPT: error: unexpected element <property> found in <manifest><application>.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
`

**Comment by JonathanLiuApp** [comment]
You should be able to solve your issue by following the fix in this thread: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/286
