### ISSUE TITLE
Google UMP popup gets shown on every start

### ISSUE THREAD

**Issue by misterHallodri** [AppLovin/AppLovin-MAX-Unity-Plugin#308]
### MAX Plugin Version

6.0.0

### Unity Version

2021.3.31f1

### Device/Platform Info

Android, iOS

### Current Behavior

I've implemented the Google UMP based on the documentation: https://dash.applovin.com/documentation/mediation/unity/getting-started/terms-and-privacy-policy-flow#google-ump-automation

But it is opened on every app start, even if the user has given consent. 

### Expected Behavior

I would expect the popup to only show once

### How to Reproduce

Implement based on documentation: https://dash.applovin.com/documentation/mediation/unity/getting-started/terms-and-privacy-policy-flow#google-ump-automation

And observe that popup is shown every time

**Comment by AntonPetrov83** [comment]
@misterHallodri Are you sure the test flag "Debug User Geography" is not enabled?

**Comment by misterHallodri** [comment]
> @misterHallodri Are you sure the test flag "Debug User Geography" is not enabled?

that was it... I must have forgotten do disable it before making a build, thank you!

**Comment by owenc4a4** [comment]
@misterHallodri 
could you reopen this issue?
I'm living outside GDRP region, so I must set "the Debug UserGeography" to GDRP to test the Google UMP flow.
Without any description, I do not know that whether popup shows every start is a feature or a bug.

I think many people will be confused with it.
It's better to do something about it from Applovin.

**Comment by thomasmso** [comment]
@owenc4a4 - We're going to update the next version of our SDK such that the popup will only show once, which matches what real users may experience.

**Comment by rzer** [comment]
@thomasmso  will it be working with old users? Who were installed the app before GDPR version of app?

**Comment by santoshbagadi** [comment]
Yes, the CMP prompt will be shown to users in GDPR region who don't have a valid TCF string yet.
