### ISSUE TITLE
Google UMP WebView displays Android bars along the edges of the screen

### ISSUE THREAD

**Issue by AntonPetrov83** [AppLovin/AppLovin-MAX-Unity-Plugin#309]
### MAX Plugin Version

6.0.1

### Unity Version

2020.3.43f1

### Device/Platform Info

Android

### Current Behavior

The consent dialog is surrounded by bars what looks ugly.

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/1997978/abbe2660-8e03-4526-9162-e41788a385ef)

### Expected Behavior

Just a dialog over the game without bars around.

### How to Reproduce

Enabled Consent Flow for Andriod + Configure Google AdMob messages.

**Comment by santoshbagadi** [comment]
The UMP webview is coming from the UMP SDK, and we cannot change it's appearance on our end. You'd need to reach out to UMP team at Google to have this fixed.
