### ISSUE TITLE
iOS build doesn't start after updating MaxSdk to 2.4.12

### ISSUE THREAD

**Issue by revolt3r** [AppLovin/AppLovin-MAX-Unity-Plugin#31]
![image](https://user-images.githubusercontent.com/11783754/83352368-295c2200-a34b-11ea-9697-32c06124f255.png)

**Comment by revolt3r** [comment]
It's a crash on start
Unity 2019.3.14f
External Dependency Manager 1.2.155

**Comment by thomasmso** [comment]
Hi @revolt3r - thanks for reporting this issue, we released a new Unity Plugin v2.4.13 which addresses this issue. Alternatively, you can remove the `use_frameworks!` line in the generated `Podfile` and re-run the CocoaPods installation process via `pod install --repo-update`. Please let us know if you encounter any further issues. Thanks!

**Comment by revolt3r** [comment]
Thanks, I updated to v2.4.13, but now I get the following error when trying to show a rewarded ad:
Attempted to display a non-incentivized ad using ALIncentivizedInterstitialAd

I do get the callback that Rewarded Ad was loaded and I double-checked the configuration of the ad unit. It seems to work well on Android.

I submitted a Zendesk request (5022).

**Comment by thomasmso** [comment]
@revolt3r - Interesting, it seems unrelated to this issue, but they'll take care of you on Zendesk instead. Do [enable and send our SDK's verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) enabled for the support team to help debug though.
