### ISSUE TITLE
Allow only Google UMP flow without AppLovin's "Terms of Service and Privacy Policy prompt"

### ISSUE THREAD

**Issue by AntonPetrov83** [AppLovin/AppLovin-MAX-Unity-Plugin#310]
### Feature Description

Is it possible to enable only Google UMP consent for GDPR-regions without enabling the AppLovin's "Terms of Service and Privacy Policy prompt" ???

From the documentation:

> Regional Compliance Check: If the user is not age-restricted under COPPA, AppLovin determines whether the user is located in a GDPR region. If the user is in a GDPR region, the MAX SDK presents Google UMP. If the user is not in a GDPR region, MAX SDK presents the user with a Terms of Service and Privacy Policy prompt. This step ensures that users are informed about data collection and usage and have the option to consent or decline.

**Comment by gulliversgames** [comment]
This is definitely needed.
We implemented our own "Terms of Service and Privacy Policy" prompt in our game on a native good-looking popup. In previous ApplovinSDK versions, there was an option to use it in platform-specific. However in 12.0.0 version, that option gone and all apps (with Google UMP flow) are forced to use most-disgusting-popup-ever on Android to show their TS/PP as below:

![Screenshot_20231127-192838_Wordjong_Puzzle](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/54326194/318f533d-85f7-4571-a453-cb2cc6a00489)

**Comment by santoshbagadi** [comment]
We use the Android native System pop up. It looks like your app has a very old Android Support Library which is causing it to show the old Android popup. Updating to newer AndroidX jetpack libraries should give you a more material style popup. 

The CMP flow provided by us is optional, and you may use your own CMP flow to gather consent. Just make sure that our SDK is initialized after the CMP flow finishes. Our SDK will be able to get the TCF string from the disk written by the CMP and pass it along to the mediation providers as described in this doc: https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#tcf-v2-consent

We are going to discuss internally on providing just the CMP flow, and will leave this ticket open to update on the progress.

**Comment by bartutiryakioglu** [comment]
We tried updating our support libraries but Applovin SDK's dependencies conflict with the new ones as you can see from the below picture. We are using 12.0.0 version and we tried to resolve dependencies through EDM4U in an empty project. It would be really good if we could separate platforms for this feature. 
<img width="603" alt="Screenshot_2023-11-28_at_13 39 05" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/86728323/544333f1-3c0d-432e-bd97-0e0ab79b8cd4">

**Comment by bartutiryakioglu** [comment]
@santoshbagadi we have other libraries which external dependency manager resolves and we can not use external dependency manager with main gradle template. Is there any other option for this problem. You suggested us to use new androidx jetpack but Applovin SDK forces us to use the legacy one.

**Comment by santoshbagadi** [comment]
Our SDK doesn't have any dependencies that require legacy support libraries. It seems like it is a bug in the External Dependency Manager that resolves to older support libraries. 

Here are the only two dependencies of our library, which only use AndroidX libraries. 
- https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier/17.1.0
- https://mvnrepository.com/artifact/com.google.android.gms/play-services-appset/16.0.0

**Comment by plotlessplot** [comment]
+1 for using Google UMP to obtain consent without also having to trigger AppLovin's "Terms of Service and Privacy Policy" prompt. We'd like to keep using our own UI for that but also trigger the CMP message via MAX (for ease of implementation).

I would also like to know how is localization handled for the "Terms of Service and Privacy Policy" prompt. We currently translate our own T&C/PP popup to 6 different languages and I'd like to know if the prompt will be localized if we use MAX's Consent Flow to simplify the Google UMP implementation.

**Comment by pfay-fc** [comment]
Similarly, it would be nice if we could also use our own iOS App Tracking Transparency flow while making use of Applovin's out-of-the-box Google UMP support.

**Comment by wojciech-juszczynski** [comment]
> We are going to discuss internally on providing just the CMP flow, and will leave this ticket open to update on the progress.

@santoshbagadi any updates on that?

**Comment by santoshbagadi** [comment]
After careful consideration, we've decided not to proceed with this feature. We believe that accommodating such customizations would introduce significant complexities. 

Our SDK would still be able to get the consent from CMPs if you decide to implement your own custom solution. You'd just need to make sure that the user completes the flow before initializing our SDK.

**Comment by bartutiryakioglu** [comment]
> We use the Android native System pop up. It looks like your app has a very old Android Support Library which is causing it to show the old Android popup. Updating to newer AndroidX jetpack libraries should give you a more material style popup.
> 
> The CMP flow provided by us is optional, and you may use your own CMP flow to gather consent. Just make sure that our SDK is initialized after the CMP flow finishes. Our SDK will be able to get the TCF string from the disk written by the CMP and pass it along to the mediation providers as described in this doc: https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#tcf-v2-consent
> 
> We are going to discuss internally on providing just the CMP flow, and will leave this ticket open to update on the progress.

I would like to ask something related to that problem. When we call permission request from Unity.Notifications plugin, popup comes with the new Android UI as you can see from the below picture. However, when we call ump or privacy policy from Applovin's plugin, popup comes with the old UI. Are you sure that this is not related to how you call that popup?

![Permission](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/86728323/36a7b7ab-bd38-4009-bfc8-834002402413)

**Comment by santoshbagadi** [comment]
The permissions dialog doesn't rely on the Application's theme. This comes from the Android OS itself (instead of the application's theme).

**Comment by bartutiryakioglu** [comment]
> The permissions dialog doesn't rely on the Application's theme. This comes from the Android OS itself (instead of the application's theme).

Do you have any idea why would the theme is different for the first pic @gulliversgames uploaded and the last pic I upload?

**Comment by 3cky** [comment]
For anyone interested, we did manage to apply our own style (for some extent) to Applovin's ToS & PP prompt using custom theme for AlertDialog:

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/894050/0d877bdc-0aa9-45c9-bce9-97769f3ac2a6)

styles.xml:

```
<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="Theme.Game.Default" parent="Theme.AppCompat.NoActionBar">
        <item name="android:alertDialogStyle">@style/Theme.Dialog.Alert</item>
        <item name="android:alertDialogTheme">@style/Theme.Dialog.Alert</item>
        ...
    </style>

   <style name="Theme.Dialog.Alert" parent="Theme.Dialog">
        <item name="android:windowTitleStyle">@style/Theme.Dialog.Alert.Title</item>
        <item name="android:buttonBarPositiveButtonStyle">@style/Theme.Dialog.Alert.PositiveButtonStyle</item>
    </style>

    <style name="Theme.Dialog.Alert.Title" parent="TextAppearance.AppCompat.Title">
        <item name="android:background">@android:color/transparent</item>
    </style>

    <style name="Theme.Dialog.Alert.PositiveButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
        <item name="android:textColor">#61f916</item>
    </style>

    <style name="Theme.Dialog" parent="@style/Theme.AppCompat.Dialog">
        <item name="android:windowBackground">@drawable/dialog_bg</item>
        ...
    </style>
    ...
</resources>
```

**Comment by gulliversgames** [comment]
thanks @3cky we'll definitely try it

**Comment by fedoit** [comment]
Hmm i just changed the theme in the Assets/Plugins/Android/Manifest.xml to the new one:

<application>
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/Theme.AppCompat"
...

**Comment by fedoit** [comment]
<application>
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/Theme.AppCompat"

**Comment by MadScientist11** [comment]
Is there any way to utilize your function of detecting if user is in a GDPR region or not without initializing SDK? Then, we would be able to implement our custom flow

**Comment by santoshbagadi** [comment]
@MadScientist11  Our SDK requires to be initialized to get the user's region. You'd need to rely on the UMP provider of your choice to provide the user's region.

**Comment by kekchpek** [comment]
@santoshbagadi Does next pipeline work good for MaxSDK? 
1) Disable `MAX Terms and Privacy Policy Flow`
2) Initialize applovin SDK
3) Check if user in the GDPR region with `MaxSdk.GetSdkConfiguration().ConsentFlowUserGeography`
4) If it is GDPR region - Show CMP with `MaxSdk.CmpService.ShowCmpForExistingUser(...)`
5) If it is not GDPR region - Show custom popup with terms&privacy.
6) Ask ATT for iOS

I'm especially worried about last point with ATT because the `Tracking Authorization Status` doesn't become `Authorized` until I restart the app.
And should I pass some data to the MAX SDK about user accepted my custom terms&policy popup?

**Comment by kekchpek** [comment]
And why `MAX Terms and Privacy Policy Flow` does not show Terms&Privacy in GDPR regions? Because, as I know, Google UPM and Terms&Privacy are completely different popups and Terms&Privacy should be shown anyway. Doesn't matter is it GDPR region or not.
![Screenshot 2024-10-30 at 18 24 14](https://github.com/user-attachments/assets/d281f16c-39e2-4784-8f63-35d1832a2f1b)

**Comment by santoshbagadi** [comment]
The pipeline provided has a few issues. 
1. `MaxSdk.CmpService.ShowCmpForExistingUser(...)` would show the CMP alert even if the user has already accepted/rejected the consent. The API is provided so that users who have already completed the flow to update their consent.
2. When MAX SDK is initialized, all the mediated SDKs would also be initialized without the user completing the consent. Any custom consent flows, should be completed before the MAX SDK is initialized, so that all the ad SDKs have user's consent state available on init. 

> And why MAX Terms and Privacy Policy Flow does not show Terms&Privacy in GDPR regions? Because, as I know, Google UPM and Terms&Privacy are completely different popups and Terms&Privacy should be shown anyway. Doesn't matter is it GDPR region or not.

We are working on adding the ability to show the `Terms / Privacy Policy Flow` in GDPR region as well. We'll update here once that feature is released.

**Comment by santoshbagadi** [comment]
No, that API is to be used along with our Terms and Privacy Policy flow and not the custom flow. `MaxSdk.CmpService.ShowCmpForExistingUser(...)` would not work when called before initializing our SDK.

The custom flow I'm referencing here, is a flow that you may have built or another third party CMP solution that you use.

**Comment by cdr9042** [comment]
> Our SDK would still be able to get the consent from CMPs if you decide to implement your own custom solution.

The only other possible solution is using Google Admob's CMP, but it conflict with MAX SDK if I use MAX to Admob Mediation. Other solutions I can find on internet are all costly premium features or overly complicated. Why don't MAX expose the functions to check if users are from GDPR region, check if consent has been obtained... like [Admob provided in their SDK](https://developers.google.com/admob/unity/privacy)?

**Comment by santoshbagadi** [comment]
As long as you use the same SDK version as the AdMob mediation adapter version, you shouldn't have any issues with using Google's solution. 

As for checking if consent has been obtained, we do have APIs to get that info. You can use [`MaxSdkUtils.GetTcfConsentStatus(vendorId)`](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/0b6143238d956f818b9937e554662368b8294cc2/DemoApp/Assets/MaxSdk/Scripts/MaxSdkUtils.cs#L352-L363) and [`MaxSdkUtils.GetAdditionalConsentStatus(atpId)`](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/0b6143238d956f818b9937e554662368b8294cc2/DemoApp/Assets/MaxSdk/Scripts/MaxSdkUtils.cs#L383-L397) to get consent state.

**Comment by sallyliu022** [comment]
> And why `MAX Terms and Privacy Policy Flow` does not show Terms&Privacy in GDPR regions? Because, as I know, Google UPM and Terms&Privacy are completely different popups and Terms&Privacy should be shown anyway. Doesn't matter is it GDPR region or not. ![Screenshot 2024-10-30 at 18 24 14](https://private-user-images.githubusercontent.com/18449140/381642291-d281f16c-39e2-4784-8f63-35d1832a2f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDYxOTMsIm5iZiI6MTczNjMwNTg5MywicGF0aCI6Ii8xODQ0OTE0MC8zODE2NDIyOTEtZDI4MWYxNmMtMzllMi00Nzg0LThmNjMtMzVkMTgzMmEyZjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDAzMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjVkY2Y2NjhkZjczNzVhMDMzN2RkYzBkMjczNmY0MjMyYTBmYjUzZWMzMGMyYmFjODk0NmE2ZjBkMzA5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hG07MblZFFQlNSp2iLhd4Su0mPfQAPoBrvUaPMGCGsY)

same issue here, do you have any new progress about this?

**Comment by wootaejeon** [comment]
Hi @kekchpek @sallyliu022, our latest plugin version 8.1.0 now includes the option to also show Terms & Privacy Policy prompt in GDPR regions. Please refer to our updated docs: https://developers.applovin.com/en/max/unity/overview/terms-and-privacy-policy-flow#enabling-max-terms-and-privacy-policy-flow
