### ISSUE TITLE
Android build failed. Error: Undefined reference to `_MaxGetTcfConsentStatus'

### ISSUE THREAD

**Issue by ilnarmirkhaev** [AppLovin/AppLovin-MAX-Unity-Plugin#311]
### MAX Plugin Version

6.1.0

### Unity Version

2022.1.23f1

### Device/Platform Info

Android

### Current Behavior

Getting BuildFailedException when trying to build for Android. Getting a bunch of messages like this:

>D:/BuildAgents/Agent6/BuildAgent/work/5f5d0f1470e2a90f/Library/Bee/artifacts/Android/il2cppOutput/cpp/MaxSdk.Scripts.cpp:17747: error: undefined reference to '_MaxGetTcfConsentStatus'
> 
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> [5879/5891 147s] Link_Android_arm64 Library/Bee/artifacts/Android/d8kzr/libil2cpp.so

The only error I'm getting is "**error: undefined reference to '_MaxGetTcfConsentStatus'**"

As I understood from google the problem is in these lines in MaxSdkUtils.cs
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/56744129/5506f795-5935-400f-b7d9-e4084db49fc0)

### How to Reproduce

Add some networks in IntegrationManager, resolve dependencies, try to build for Android

**Comment by santoshbagadi** [comment]
@ilnarmirkhaev sorry for the inconvenience here. We'll push a fix for this sometime today. 

In the meantime, you may fix the issue by wrapping the lines with `#if UNITY_IOS` as shown below. 

```
#if UNITY_IOS
    [DllImport("__Internal")]
    private static extern int _MaxGetTcfConsentStatus(int vendorIdentifier);
#endif
```

**Comment by kocburak** [comment]
Seriously??.. Does not even a single soul test it before shipping ?

**Comment by santoshbagadi** [comment]
It was a last minute addition before the release that caused this one to slip through. Apologies again for any inconvenience. 

We've pushed a new plugin [version 6.1.1](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_1_1) that should fix this issue.
