### ISSUE TITLE
Immediately after launching the app on iOS, it crashes with the error "Library not loaded: @rpath/IASDKCore.framework/IASDKCore".

### ISSUE THREAD

**Issue by marchenterprise** [AppLovin/AppLovin-MAX-Unity-Plugin#313]
### MAX Plugin Version

6.1.1 (Android 12.1.0 & iOS 12.1.0)

### Unity Version

Unity 2022.3.14f1

### Device/Platform Info

iPhone 15/iOS 17.1.2

### Current Behavior

Create a new empty 3D project and install AppLovin MAX SDK 6.1.1. I additionally installed DT Exchange android_8.2.4.0_ios_8.2.5.0 on Mediated Networks from AppLovin Integration Manager.
After building with Unity Editor, it crashes with the error "Library not loaded: @rpath/IASDKCore.framework/IASDKCore" immediately after installing and starting it on an iOS device with Xcode.

### How to Reproduce

AppLovinQualityService top: AppLovinQualityService Client Version: 7.0.3
AppLovinQualityService top: AppLovinQualityService Device ID: 927FB886-EDC2-4324-BDFC-A8A7AACFA8FE
Error loading /var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework (139):  dlopen(/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/IASDKCore.framework/IASDKCore
  Referenced from: <4C76A1CC-E47A-3056-A542-3201C9520F26> /private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file)
Error loading /var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework (139):  dlopen(/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/IASDKCore.framework/IASDKCore
  Referenced from: <4C76A1CC-E47A-3056-A542-3201C9520F26> /private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/UnityFramework.framework/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/Frameworks/IASDKCore.framework/IASDKCore' (no such file), '/private/var/containers/Bundle/Application/D5311C6F-7F86-466C-935D-60CB81F777C3/TestAppLovin.app/Frameworks/IASDKCore.framework/IASDKCore' (no such file)

**Comment by junerain89** [comment]
> I also have problems with IASDKCore.framework. It always gives me a headache when I try building unity for iOS. Usually XCode gives me "Command CodeSign failed with a nonzero code" or "The signature of IASDKCore cannot be verified".
> 
> One of the logs contained this:
> 
> > The following build commands failed: CodeSign /Users/.../Library/Developer/Xcode/DerivedData/Unity-iPhone/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/app_name.app/Frameworks/IASDKCore.framework/Versions/A (in target 'Unity-iPhone' from project 'Unity-iPhone')
> 
> About 2 months ago I made the error go away by **downgrading** DT Exchange network version from 8.2.4.0 to 8.1.4.0 for iOS (Android doesn't happen to have any issues with it). But I recently had to update Unity to 2022.3.10 and AppLovin plugin to 6.1.1 and 12.1.0 for mobile. The error with DT occured again for previously working 8.1.4 version, and upgrading it didn't help this time as I tried both 8.2.5 and 8.1.9 versions. **BUT removing the DT Exchange network for iOS completely solves the issue**. So for now our iOS game doesn't have this network, which is bad.
> 
> We tried installing/updating CocoaPods, clearing DerivedData folder, updating Xcode to 15 version. The problem is within IASDKCore.framework and DT Exchange network.
> 
> My iOS resolver settings look like this: ![image](https://private-user-images.githubusercontent.com/56744129/288799202-86525f3e-7cde-40bc-a21f-4b49abcb83af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MTEyMTIsIm5iZiI6MTcwMjYxMDkxMiwicGF0aCI6Ii81Njc0NDEyOS8yODg3OTkyMDItODY1MjVmM2UtN2NkZS00MGJjLWEyMWYtNGI0OWFiY2I4M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAzMjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4N2I4YmVkNzhhODU5MjMxNzczNWVlNmUwZTg2MWMxYjBmMTdjNjMwMWIwMTVjZjAxOTAxNjY4Y2IwYmM1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-GrHJmWEMjQjq6Hx_RvnCkIvQbEg5sAntCDjH4bJ8M)
> 
> And here is my Podfile:
> 
> ```
> source 'https://cdn.cocoapods.org/'
> 
> platform :ios, '13.0'
> 
> target 'UnityFramework' do
>   pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.4'
>   pod 'AppLovinMediationByteDanceAdapter', '5.6.0.7.0'
>   pod 'AppLovinMediationGoogleAdapter', '10.12.0.0'
>   pod 'AppLovinMediationInMobiAdapter', '10.5.8.1'
>   pod 'AppLovinMediationIronSourceAdapter', '7.5.0.0.0'
>   pod 'AppLovinMediationMintegralAdapter', '7.4.7.0.0'
>   pod 'AppLovinMediationMyTargetAdapter', '5.19.0.0'
>   pod 'AppLovinMediationUnityAdsAdapter', '4.9.1.0'
>   pod 'AppLovinMediationVungleAdapter', '7.1.0.0'
>   pod 'AppLovinSDK', '12.1.0'
>   pod 'AppsFlyer-AdRevenue', '6.9.1'
>   pod 'AppsFlyerFramework', '6.12.2'
>   pod 'Firebase/Analytics', '8.11.0'
>   pod 'Firebase/Core', '8.11.0'
>   pod 'PurchaseConnector', '6.12.2'
> end
> ```
> 
> Someone please fix this :(

Pls use version 8.2.4.0. And Drag IASDKCore from Pods to Unity-Iphone. 
<img width="272" alt="Screenshot 2023-12-15 at 10 30 22" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/71481750/7ac0f174-62d9-4fd0-9b17-b457759c1725">
Then, add it here and make it "Embed & Sign".
<img width="1327" alt="Screenshot 2023-12-15 at 10 32 46" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/71481750/0ccb9798-7704-41be-bf96-b9483536b3d0">
Done! Hope this help.
By the way, I also want to inform you that IASDKCore has a problem in version 8.2.5.0. You will not be able to build it because IASDKCore cannot validate. This error : "A sealed resource is missing or invalid".

**Comment by JonathanLiuApp** [comment]
IASDKCore does seem to have an issue with 8.2.5.0 and downgrading to 8.2.4.0 should fix it as @junerain89 stated. But as long as your iOS resolver settings in the EDM are correct, the IASDKCore.xcframework should be embedded automatically. We will look into the issue, but for now please use version 8.2.4.0.

**Comment by zenith-jacob** [comment]
Any idea guys how to make this through PostBuild script?
It's not as simple as: 
` project.AddFileToEmbedFrameworks(mainTargetGuid, frameworkPath);`
What actually happens when we drag & drop this file onto Unity-Iphone?

**Comment by AntonPetrov83** [comment]
Does manualy calling `pod install` before doing Xcode build helps?

**Comment by junerain89** [comment]
> Does manualy calling `pod install` before doing Xcode build helps?

No. "pod install" doesn't help in this case.

**Comment by junerain89** [comment]
I have seen the latest version 8.2.5.1. You can build with this latest version but you still have to use the method I instructed above.

**Comment by JonathanLiuApp** [comment]
As @junerain89 stated, the latest version 8.2.5.1 fixed the issue. IASDKCore will still need to be embedded, but that should be done automatically if you are using our recommended External Dependency Manager settings.
