### ISSUE TITLE
Google UMP is not displaying in Unity-Android App

### ISSUE THREAD

**Issue by Saadbutt3** [AppLovin/AppLovin-MAX-Unity-Plugin#320]
### MAX Plugin Version

6.1.1

### Unity Version

2020.3.37f1

### Device/Platform Info

Android

### Current Behavior

> #
![1](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/22549934/afc3498e-ee73-47f8-80a5-9658cbf65a00)
![2](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/22549934/b907f8de-fbe3-4306-afd3-90295ba67f01)
![3](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/22549934/1a4586fb-9eee-4365-93e4-bd1daefd76b6)

*These are the settings I am working with . On anAndroid Device "no Goggle cmp" Pop up notification   on app launch
* On IOS Device with same project  "Google cmp" displays on app launch 
                 

*These are mdediation debugger screenshoots below

![4 (1)](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/22549934/2bba8ccb-9b20-499c-a5af-73e8166f7bb8)
![5](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/22549934/bb7720be-a641-4e54-a154-39ef207e12a5)

### Expected Behavior

Google cmp should shows up on app start/launch on an android device as well

### How to Reproduce

Just build the project and check android unity-app start/lauch.

**Comment by santoshbagadi** [comment]
Please make sure that the app is running in debug mode. The `Debug User Geography` setting only works when running in debug mode.

**Comment by Saadbutt3** [comment]
Thanks  @santoshbagadi  mate its working now
