### ISSUE TITLE
Corrupted UI on Google CMP popup

### ISSUE THREAD

**Issue by abogarsukov-braingames** [AppLovin/AppLovin-MAX-Unity-Plugin#321]
### MAX Plugin Version

6.1.2

### Unity Version

2021.3.28

### Device/Platform Info

Android

### Current Behavior

Usually the consent popup is displayed normally, but sometimes it has corrupted UI (see the attachment).

### Expected Behavior

The consent popup always has normal layout.

### How to Reproduce

We were able to catch this after several app reinstall.

### Additional Info

![1703172126643](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/68687154/7e1af6a5-c9a8-4207-846c-d33375a83342)

**Comment by santoshbagadi** [comment]
Google has recently rolled out a server side fix that should fix this issue. Please note that the issue may still be  seen on slow connections.
