### ISSUE TITLE
SetHasUserConsent and SetIsAgeRestrictedUser usage after 12.0.0

### ISSUE THREAD

**Issue by AntonPetrov83** [AppLovin/AppLovin-MAX-Unity-Plugin#323]
### Feature Description

Hi!

Is it still required to call `SetHasUserConsent` and `SetIsAgeRestrictedUser` if I use Google-certified CMP which sets IAB TCF strings?

**Comment by thomasmso** [comment]
@AntonPetrov83 - If you are using underlying Android/iOS SDKs v12.0.0 or higher, then no. Else, yes. You can read more about it here: https://dash.applovin.com/documentation/mediation/unity/getting-started/privacy#tcf-v2-consent.
