### ISSUE TITLE
Superold PlayServicesResolver Part Of Every Update

### ISSUE THREAD

**Issue by rbyjoswald** [AppLovin/AppLovin-MAX-Unity-Plugin#327]
### MAX Plugin Version

6.1.2

### Unity Version

2022.3.16f1

### Device/Platform Info

Editor

### Current Behavior

When updating or installing the latest Applovin Max SDK the package always contains a superold folder PlayServicesResolver with a file play-services-resolver_v1.2.137.0.txt.
Note that this is on top of the proper latest version of ExternalDependencyManager which is correctly part of the package.

### Expected Behavior

Package should not include the outdated file play-services-resolver_v1.2.137.0.txt

### How to Reproduce

Just import the latest SDK and obvserve on the import-screen that this file is part of the imported package.

**Comment by santoshbagadi** [comment]
Hi @rbyjoswald , this is part of the External Dependency Manager (EDM) package: https://github.com/googlesamples/unity-jar-resolver/tree/master/exploded/Assets

EDM needs it for its version resolution of its own packages. So, this is expected.

**Comment by rbyjoswald** [comment]
Sorry for reopening this. The latest apploving max unity plugin (AppLovin-MAX-Unity-Plugin-8.2.2-Android-13.2.0-iOS-13.2.0.unitypackage) includes the EDM 1.2.182. But on top the .unitypackage also still includes "PlayServicesResolver/Editor/play-services-resolver_v1.2.137.0.txt". You see that file at the very bottom of the import preview window in Unity when you import AppLovin-MAX-Unity-Plugin-8.2.2-Android-13.2.0-iOS-13.2.0.unitypackage.
Why is a .txt file that is old and does not correspond to the EDM in the package part of the .unitypackage?
Once you import the unitypackage the EDM immediately asks you with a popup to remove that .txt file suggesting it is redundant / not used.

**Comment by santoshbagadi** [comment]
This is a requirement by External Dependency Manager. EDM would automatically remove these files after importing. 

As mentioned in the previous comment, you can verify the exploded EDM package to verify.
