### ISSUE TITLE
[GoogleCmpAdapter] Failed to request consent info with error

### ISSUE THREAD

**Issue by dreamcodestudio** [AppLovin/AppLovin-MAX-Unity-Plugin#328]
### MAX Plugin Version

6.1.0

### Unity Version

2020.3.34f1

### Device/Platform Info

Android 13, Samsung A52

### Current Behavior

AppLovin logging:
```
[GoogleCmpAdapter] Initializing with SDK Version: null, consentStatus: 0, consentFormAvailable: false
[GoogleCmpAdapter] Failed to request consent info with error: com.google.android.ump.FormError@c740bed
```

Debugger Info:
<img src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/7010398/180e3a6f-4bd6-4371-b81a-ce6dcf70535d" width="300">

### Expected Behavior

For GDPR users, showing Google Consent form

### How to Reproduce

Implementing instructions by documentation:
https://dash.applovin.com/documentation/mediation/unity/getting-started/terms-and-privacy-policy-flow

### Additional Info

Reproduced in `VPN` mode or `Debug User Geography` = GDPR

**Comment by ertugrulerdogan** [comment]
We also have the same problem.

**Comment by osamaraza24** [comment]
we are also facing the same problem if anyone has a fix kindly mention it here

**Comment by santoshbagadi** [comment]
Would you mind [enabling verbose logs](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#enable-verbose-logging) and sharing the logs for the full session where you are seeing the issue

**Comment by osamaraza24** [comment]
2024-01-10 22:49:32.588 1691-2473/? I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.tiltingpoint.bigwolf.narcosfactory/com.applovin.mediation.MaxDebuggerActivity} from uid 10666
2024-01-10 22:49:33.032 16806-17230/? D/AppLovinSdk: [GoogleCmpAdapter] Initializing with SDK Version: null, consentStatus: 0, consentFormAvailable: false
2024-01-10 22:49:33.036 16806-17230/? D/AppLovinSdk: [MediationDebuggerListAdapter] 
    ========== MEDIATION DEBUGGER ==========
    ========== APP INFO ==========
    Dev Build - false
    Test Mode - disabled
    Target SDK - 33
    ========== MAX ==========
    SDK Version - 12.1.0
    Plugin Version - Max-Unity-6.1.2
    Ad Review Version - 5.0.7
    Unity Version - 2022.3.13f1
    ========== PRIVACY ==========
    Age Restricted User - true
    Has User Consent - false
    "Do Not Sell" - false
    Consent Flow Enabled - true
    Privacy Policy - https://bigwolf.com/privacy-policy/
    Terms of Service - https://bigwolf.com/terms-of-use/
    ========== CMP (CONSENT MANAGEMENT PLATFORM) ==========
    CMP Name - No value set
    CMP SDK ID - No value set
    CMP SDK Version - No value set
    IABTCF_gdprApplies - No value set
    IABTCF_TCString - No value set
    IABTCF_AddtlConsent - No value set
    ========== NETWORK CONSENT STATUSES ==========
    Amazon Ad Marketplace - false
    Amazon Publisher Services - false
    AppLovin - false
    BidMachine - false
    Chartboost - false
    Criteo Bidding - false
    DT Exchange - false
    Facebook - false
    Google Ad Manager - false
    Google AdMob - false
    HyprMX - false
    InMobi - false
    ironSource - false
    Liftoff Monetize - false
    LINE - false
    Maio - false
    Mintegral - false
    MobileFuse - false
    myTarget - false
    Nend - false
    Ogury - false
    Pangle - false
    Smaato - false
    Unity Ads - false
    Verve - false
    Yandex - false

**Comment by osamaraza24** [comment]
is this helpful? @santoshbagadi

**Comment by osamaraza24** [comment]
![Uploading Screenshot 2024-01-11 031834.png…]()

**Comment by osamaraza24** [comment]
![Screenshot 2024-01-11 031834](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/692bafef-6ea6-4adf-bb37-6dca12ec838c)

**Comment by osamaraza24** [comment]
I have created a message on the AdMob dashboard and updated GDPR settings,but only see default popup on game 
![WhatsApp Image 2024-01-09 at 20 22 20_3e5703f4](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/754d7d73-9dcb-476a-9dac-cfc9ac6df28d)

**Comment by osamaraza24** [comment]
![Screenshot_20240105-221700 (1)](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/fbe981c4-2d18-47c1-83f1-b6fe69765198)
this message appears on max debugger ,what is an exact issue we need to fixed?

**Comment by osamaraza24** [comment]
![Screenshot 2024-01-11 031834](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/8141fae8-3fad-49c0-a71f-ca0f5daab479)
session logs

**Comment by osamaraza24** [comment]
![Screenshot 2024-01-11 031834](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/049f92f6-6c0a-4641-a0ce-97a1cba0e4ec)

**Comment by santoshbagadi** [comment]
How are you testing the CMP flow. Are you using VPN or the Debug Geography setting in the Integration Manager to test?

We'd need full verbose logs to investigate further. You can send them to santosh.bagadi@applovin.com

**Comment by osamaraza24** [comment]
Using VPN UK region ,I tested with set test geographic location to gdpr but
same issue happened

**Comment by santoshbagadi** [comment]
Do you mind trying to VPN to another region in EU (like FR). We've seen issues with VPN to UK not being detected by Google UMP SDK.

**Comment by ducloc96** [comment]
I also have the same problem. I set Debug User Geography = GDPR to test but CMP not show

**Comment by santoshbagadi** [comment]
The debug geography setting only works in debug builds. Please make sure you are exporting a debug build to check

**Comment by ducloc96** [comment]
Do you mean development build in unity?
![Screenshot 2024-01-11 100843](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/28078872/c6145647-9401-42ce-a73b-ff2cfce48ee8)

**Comment by santoshbagadi** [comment]
Yes, development build on Unity.

**Comment by ertugrulerdogan** [comment]
We managed to solve our issue. In our case it was caused by wrong AdMob appId configuration. Consent flow start to work as excepted after updating appIds with correct ones.

**Comment by dreamcodestudio** [comment]
> We managed to solve our issue. In our case it was caused by wrong AdMob appId configuration. Consent flow start to work as excepted after updating appIds with correct ones.

You updated Admob ids config in `Google admin panel` or `AppLovin > Integration Manager` ?

Because in our case we not use separate AdMob network via AppLovin adapter.

**Comment by ertugrulerdogan** [comment]
> You updated Admob ids config in `Google admin panel` or `AppLovin > Integration Manager` ?

Updated ids in the Applovin Integration Manager.

**Comment by dreamcodestudio** [comment]
@santoshbagadi Can we use `Google UMP` without integration `AdMob` like Mediated Network?

**Comment by osamaraza24** [comment]
I can not access FR, i switched to Germany but same problem @santoshbagadi

**Comment by dreamcodestudio** [comment]
after add `AdMob AppLovin` in Integration Manager network:
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/7010398/9ab7e610-ebc9-40f0-a47f-80c73f7eec67)

It's worked

But it's strange requirements, can you specify it in Unity documentation

**Comment by dreamcodestudio** [comment]
> > after add `AdMob AppLovin` in Integration Manager network: ![image](https://private-user-images.githubusercontent.com/7010398/295941725-9ab7e610-ebc9-40f0-a47f-80c73f7eec67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODUzODcsIm5iZiI6MTcwNDk4NTA4NywicGF0aCI6Ii83MDEwMzk4LzI5NTk0MTcyNS05YWI3ZTYxMC1lYmM5LTQwZjAtYTQ3Zi04MGM3M2Y3ZWVjNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTQ1ODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1YjAyOTgyOTgwOTA1MGJkNTdmNGQyMjU3ZTg0MWYxNTA3ODBiZTI3MmY4NTUwNDE0NDI5YzcyZDQ5ZGQ1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pHwnxC0hec31IJ5b_hvAV-20gxWlaO6QgXAqk1iUuEM)
> > It's worked
> > But it's strange requirements, can you specify it in Unity documentation
> 
> I have integrated Admob with the same latest as you mentioned but, I am not using Google Ad Manager, this should be an issue and how you are testing on the device ?, means I have not set the GDPR value on Debug User Geography. testing with VPN UK or Germany region, how did you test on the device or what location on VPN?

in last test i integrated only `AdMob` (without Google Ad Manager).
`VPN` = off
`Debug User Geography` = GDPR
`Unity Development Build` = true

**Comment by osamaraza24** [comment]
It worked for me on FR VPN only but it appears two time

**Comment by osamaraza24** [comment]
It worked for me on FR VPN only but it appears two time, I have enabled with applovin integration manager
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/36219797/f278c5ca-4af9-420d-92bb-9884ea90d393)
and added this code 
`                if (sdkConfiguration.ConsentFlowUserGeography == MaxSdkBase.ConsentFlowUserGeography.Gdpr)
                {
                    MaxSdk.CmpService.ShowCmpForExistingUser((error) =>
                    {
                        if (error != null)
                        {
                            Debugger.LogProduction("AdsManager", "MaxSdkCallbacks.OnSdkInitializedEvent", "Error", error);
                        }
                    });
                }`
is this appear two time because i called for existing users @santoshbagadi

**Comment by santoshbagadi** [comment]
Yes, the `MaxSdk.CmpService.ShowCmpForExistingUser()` should be called when a user requests to reset their consent. You'd need a button in your app's setting and when the user clicks it, you'd need to call this method to re-sow the CMP prompt

**Comment by PalliativeX** [comment]
In my case I cleared the game data after the install out of habit, which seems to clear some prefs required for the CMP (but that's only by default for non-GDPR, without VPN).
The main issue was the setup of Admob Consent window (I was provided the Admob App key), which didn't show the CMP window with GDPR debug mode or German VPN. When I used my own setup, the issue resolved.
![Снимок экрана 2024-02-02 102757](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/43545329/8807592e-2bef-4549-b57e-d9b34ca3c28f)
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/43545329/6d854a18-54df-4053-8600-8e074a831d31)

Speaking about Applovin setup, I enabled MAX Terms and Privacy Policy flow, provided a Privacy Policy link and added AdMob to mediated networks (not sure that it will work without using it).
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/43545329/b0620b5a-58cd-4773-b3b5-01c7348398de)
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/43545329/01629eae-b067-46f8-a1ba-fa5a7629928d)
