### ISSUE TITLE
Move MaxSdk to Plugins folder

### ISSUE THREAD

**Issue by revolt3r** [AppLovin/AppLovin-MAX-Unity-Plugin#33]
Would you please consider moving MaxSdk to the Assets/Plugins folder?
Or at least allow us to move it manually, right now some paths are hardcoded, so the plugin breaks you move it to a different folder.

**Comment by Lorenzo45** [comment]
Thanks for the suggestion! We'll certainly consider moving it if there's enough demand for it. Supporting multiple locations could introduce issues in future updates so we don't believe that's the best path forward.

**Comment by santoshbagadi** [comment]
@revolt3r we have added support with the ability to move our plugin to a different folder under the `Assets` directory a while back (plugin version 3.2.0). So, closing this ticket, please let us know if you run into any issues with this.

**Comment by revolt3r** [comment]
Almost!
![image](https://user-images.githubusercontent.com/11783754/141442346-830742b4-909a-4c82-bf41-a7e663a28773.png)

**Comment by revolt3r** [comment]
You could try AssetDatabase.FindAssets by type instead of path to fix that

**Comment by santoshbagadi** [comment]
Ah, I think you might need to update the Google adapter. What version of Google adapter are you on?

We don't use path, but we tag our assets with a label (we use the path you see as the tag) and use that to find the asset. The `AppLovinSettings.asset` should also be tagged with something like `al_max_export_path-MaxSdk/Resources/AppLovinSettings.asset`. Could you please double check if it is, if not there might be an issue somewhere.

**Comment by revolt3r** [comment]
You're right, I found the issue -> the slashes are reversed
![image](https://user-images.githubusercontent.com/11783754/141448810-86c7ce8f-5906-4b29-8d73-b18922b85992.png)

**Comment by santoshbagadi** [comment]
Looks like an issue with path separator being different on Windows. Could you please try replacing 
```
var guids = AssetDatabase.FindAssets("l:al_max_export_path-" + AppLovinSettingsExportPath);
```
with 
```
var guids = AssetDatabase.FindAssets("l:al_max_export_path-" + AppLovinSettingsExportPath.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar));
```

in `MaxMediationGoogleUtils` and see if that fixes it. If so, we can include the change in our next rlease.

**Comment by revolt3r** [comment]
That fixed it indeed, thanks.
Looking forward to the update!

**Comment by santoshbagadi** [comment]
Great! Thank you for testing the change. We'll include it in the next release.
