### ISSUE TITLE
UnityWebRequest issue

### ISSUE THREAD

**Issue by jedai7** [AppLovin/AppLovin-MAX-Unity-Plugin#331]
### MAX Plugin Version

6.0.1

### Unity Version

2021.3.24

### Device/Platform Info

iOs

### Current Behavior

In our project we have applovin 6.0.1(update for google ump) and google adapter. Also we use unitywebrequest to our server for user identification and we have problems, our webrequest doenst work after updating. If we downgrage applovin to 5.4.5. Unitywebrequest dont work at all, we didnt see even in charles

### How to Reproduce

i dont know((

**Comment by JonathanLiuApp** [comment]
Hi @jedai7, could you try to see if you can reproduce this in an empty Unity project with our plugin installed?

**Comment by jedai7** [comment]
@JonathanLiuApp hi, yes. I found why. Your plugin broke http, only https. But we can't move your server to https.

**Comment by santoshbagadi** [comment]
@jedai7 you may use the [InsecureHttpOption.AlwaysAllowed](https://docs.unity3d.com/ScriptReference/InsecureHttpOption.html) option to allow plain text HTTP.
