### ISSUE TITLE
iOS crashing after use ogury

### ISSUE THREAD

**Issue by jedai7** [AppLovin/AppLovin-MAX-Unity-Plugin#332]
### MAX Plugin Version

6.1.1

### Unity Version

2021.3.24

### Device/Platform Info

all ios devices

### Current Behavior

This is our current mediation networks.
![telegram-cloud-photo-size-2-5274054715631588976-y](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/155758157/165ac731-f9bf-4e89-9d31-0e10e76450e9)
After install ogury ios build crashing
crashing with error 
Error loading /var/containers/Bundle/Application/B7D68A1F-F540-423E-AC38-E35F864CCCAE/CryptoTycoon.app/Frameworks/UnityFramework.framework/UnityFramework (139):

### How to Reproduce

Install ogury mediation adapter

**Comment by jedai7** [comment]
Error loading /var/containers/Bundle/Application/A4F9925C-A766-4D29-8A7B-E9E005AED2B8/CryptoTycoon.app/Frameworks/UnityFramework.framework/UnityFramework (139):  dlopen(/var/containers/Bundle/Application/A4F9925C-A766-4D29-8A7B-E9E005AED2B8/CryptoTycoon.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/OMSDK_Ogury.framework/OMSDK_Ogury
  Referenced from: <DF87ED62-1F9E-3552-A532-026E30E5E781> /private/var/containers/Bundle/Application/A4F9925C-A766-4D29-8A7B-E9E005AED2B8/CryptoTycoon.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/OMSDK_Ogury.framework/OMSDK_Ogury' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OMSDK_Ogury.framework/OMSDK_Ogury' (errno=2), '/private/var/containers/Bundle/Application/A4F9925C-A766-4D29-8A7B-E9E005AED2B8/CryptoTycoon.app/Frameworks/OMSDK_Ogury.framework/OMSDK_Ogury' (errno=2), '/private/var/containers/Bundle/Application/A4F9925C-A766-4D29-8A7B-E9E005AED2B8/CryptoTyco<…>

**Comment by JonathanLiuApp** [comment]
Hello, could you check whether you have the correct External Dependency Manager settings by following our integration docs: https://dash.applovin.com/documentation/mediation/unity/getting-started/integration#external-dependency-manager

**Comment by JonathanLiuApp** [comment]
To fix the issue, you can manually embed OMSDK_Ogury.xcframework to your target.
