### ISSUE TITLE
IAB tcfV2 missing critical methods

### ISSUE THREAD

**Issue by agrobost** [AppLovin/AppLovin-MAX-Unity-Plugin#334]
### Feature Description

We currently use **GetTcfConsentStatus(int vendorID)** method in your SDK and appreciate its functionality. To enhance compliance with IAB's Transparency and Consent Framework, especially under GDPR, we suggest adding two critical methods:

- **public bool IsPurposeAccepted(int purposeID)**
- **public bool IsSpecialFeatureAccepted(int specialFeatureID)**

These methods will greatly aid in accurately managing user consents for specific purposes and features, ensuring both legal compliance and user trust. We believe their integration would be a significant improvement to your SDK and beneficial to all developers using your services.

Thank you for your attention. We look forward to a swift and effective resolution.

Best regards,

**Comment by wootaejeon** [comment]
Hi @agrobost, we are looking into adding public APIs on our next SDK release for purpose and special feature consents. We'll let you know when these features go live.

**Comment by agrobost** [comment]
Dear AppLovin Team,

Following our previous suggestion regarding the addition of **IsPurposeAccepted(int purposeID)** and **IsSpecialFeatureAccepted(int specialFeatureID)** methods to your SDK to enhance compliance with the IAB's Transparency, we would like to highlight the importance of adding several additional methods to further enhance the management of user consents:

- **public string GetTCFString()** - This method would provide a standardized mechanism to retrieve the user's current consent state in a format that can be easily shared with other systems or partners, ensuring consistent consent interpretation across the ecosystem.

- **public bool IsSpecialPurposeAccepted(int specialPurposeID)**

- **public bool IsFeatureAccepted(int featureID)**

Thank you for considering our suggestions. 

Best regards

**Comment by wootaejeon** [comment]
@agrobost Thanks for your suggestions. We will consider them for a future release and follow up with relevant updates.

**Comment by wootaejeon** [comment]
@agrobost Unity plugin version 6.2.0 is now live with the following methods:
`public static bool? GetPurposeConsentStatus(int purposeId)`
`public static bool? GetSpecialFeatureOptInStatus(int specialFeatureId)`
