### ISSUE TITLE
app-ads.txt "Text file contains non-ASCII characters" error

### ISSUE THREAD

**Issue by wojciech-juszczynski** [AppLovin/AppLovin-MAX-Unity-Plugin#357]
### MAX Plugin Version

6.4.1 / 12.4.1 iOS

### Unity Version

2022.3.14f

### Device/Platform Info

iOS

### Current Behavior

app-ads.txt "Unable to parse app-ads.txt file at <website>. Text file contains non-ASCII characters" error in Mediation Debugger. 
On Android application with MAX - there is no such error (the same app-ads.txt is used for both apps).

### How to Reproduce

1. Open Mediation Debugger
2. Tap on app-ads.txt section

**Comment by wootaejeon** [comment]
Hi @wojciech-juszczynski, could you share the URL to your app-ads.txt file so we can further assist with the issue?

**Comment by wojciech-juszczynski** [comment]
Hey @wootaejeon sent via email

**Comment by wootaejeon** [comment]
@wojciech-juszczynski On row 1049 on your app-ads.txt file, there are some non-ASCII characters `â€` at the end. Could you remove these and see if the issue persists?

**Comment by wojciech-juszczynski** [comment]
@wootaejeon Thanks, will do. Why Android is not throwing the same error?
