### ISSUE TITLE
Fail to build iOS build after update to 6.4.2 from 6.1.2

### ISSUE THREAD

**Issue by kekchpek** [AppLovin/AppLovin-MAX-Unity-Plugin#360]
### MAX Plugin Version

6.4.2

### Unity Version

2022.3.18f1

### Device/Platform Info

iOS

### Current Behavior

When I build an iOS build in XCode, I get errors:
 - Multiple commands produce '.../Frameworks/FBAEMKit.framework'
 - Multiple commands produce '.../Frameworks/FBSDKCoreKit.framework'
 - Multiple commands produce '.../Frameworks/FBSDKCoreKit_Basics.framework'
 - Multiple commands produce '.../Frameworks/FBSDKGamingServicesKit.framework'
 - Multiple commands produce '.../Frameworks/FBSDKLoginKit.framework'
 - Multiple commands produce '.../Frameworks/FBSDKShareKit.framework'

### Expected Behavior

iOS build in XCode should be cooked well.

### How to Reproduce

Just make the XCode project build in Unity, and try to build&run the cooked project in XCode.

### Additional Info

I noticed, that `AppLovinPostProcessiOS` has been significantly changed, when I update the AppLovin plugin to 6.4.2. As I understand, it makes some manipulations with the dependencies, that are specified in the errors above. Also these framewokrs are specified as Pod dependencies in FacebookSDK `*Dependencies.xml` file for google-jar-relover(aka External Dependency Manager). Probably this cause a some kind of conflict between AppLovin and Facebook SDKs. I hadn't dived deep into it, but maybe this info can be useful.

**Comment by JonathanLiuApp** [comment]
Hello, this should be fixed in plugin version 6.4.3. Could you try updating your plugin version and see if that helps the issue?

**Comment by santoshbagadi** [comment]
@kekchpek if you have custom settings for Facebook to be added to main target, you may have to remove it as mentioned here: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/355#issuecomment-2051817075

The other option would be to remove the Facebook frameworks from this list in our plugin here: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/07378eee00a848f360c83ac372ef82acb796b552/DemoApp/Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessiOS.cs#L65-L70

We'll include a fix in the next SDK release that only embeds dynamic libraries only if they are not in the main target as well.

**Comment by Barky** [comment]
Same issue here. Unity plugin version 6.4.3 and iOS plugin version 12.4.1.

**Comment by santoshbagadi** [comment]
Our latest plugin version [6.6.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_6_0) now takes `Unity-iPhone` Pods when embedding dynamic libraries.
