### ISSUE TITLE
Can not make a standalone windows build

### ISSUE THREAD

**Issue by hoainam1593** [AppLovin/AppLovin-MAX-Unity-Plugin#364]
### MAX Plugin Version

6.4.3

### Unity Version

2022.3.17

### Device/Platform Info

not applicable

### Current Behavior

when I make a standalone windows build, I get a syntax error:
Assets\MaxSdk\Scripts\MaxSdkUnityEditor.cs(1401,26): error CS0117: 'MaxEventExecutor' does not contain a definition for 'Instance'

### How to Reproduce

- create an empty project
- import max sdk
- make a standalone windows build

**Comment by santoshbagadi** [comment]
Hi @hoainam1593 , thank you for raising the issue. We are going to release a for this in an upcoming release. 

In the mean time you can apply the fix by updating [this line](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/07378eee00a848f360c83ac372ef82acb796b552/DemoApp/Assets/MaxSdk/Scripts/MaxEventExecutor.cs#L47) in `Assets/MaxSdk/Scripts/MaxEventExecutor.cs` to `#if UNITY_EDITOR || !(UNITY_ANDROID || UNITY_IPHONE || UNITY_IOS)`.

**Comment by cemtuver-applovin** [comment]
Hi @hoainam1593, we have released a version of our [Unity plugin (6.4.4)](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_4_4) which addresses this issue. Could you please try updating your MAX Unity Plugin?
