### ISSUE TITLE
Yandex SKAdNetwork IDs

### ISSUE THREAD

**Issue by soqman** [AppLovin/AppLovin-MAX-Unity-Plugin#370]
### MAX Plugin Version

6.4.4

### Unity Version

2022.3.21f

### Device/Platform Info

ios 17.4.1 iPhone 13 mini 13

### Current Behavior

Yandex adapter 7.0.0.0

INCOMPLETE in mediation debugger.

SKAdNetwork identifiers are missing or outdated

bd757ywx3.skadnetwork

### Expected Behavior

Yandex adapter COMPLETED INTEGRATION

### How to Reproduce

iOS:
MAX: 6.4.4
Yandex adapter 7.0.0.0

**Comment by santoshbagadi** [comment]
Thank you for reporting the issue, the ID is being flagged incorrectly, and we'll have a server side fix for this shortly. 

We'll update here once we have a fix.

**Comment by soqman** [comment]
![IMG_9254](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/17062360/ad3b91a8-a790-4a99-ae26-000f1427ddd1)

please check also the following IDs for Smaato

**Comment by santoshbagadi** [comment]
We've pushed a fixed for this and the error should no longer exist.
