### ISSUE TITLE
Recieving Rewarded Ad placement name Empty string in call back

### ISSUE THREAD

**Issue by umairmanz** [AppLovin/AppLovin-MAX-Unity-Plugin#382]
### MAX Plugin Version

6.5.2

### Unity Version

2021.3.34f1

### Device/Platform Info

Editor

### Current Behavior

I call RewardedAd with a placement name parameter and expect to receive it in Rewarded Ad onRecieve call back but I receive an empty string in "MaxSdkBase.AdInfo.Placement". I used this to distinguish various Rewarded video Rewards in my scene. 

Log : Debug [AppLovin MAX] Invoking event: OnRewardedAdHiddenEvent. Params: 2c721d2f8073e83f, [AdInfo adUnitIdentifier: 2c721d2f80******, adFormat: , networkName: , networkPlacement: , creativeIdentifier: , placement: , revenue: -1, revenuePrecision: , latency: 0, dspName: ]

Following is calling mechanism and registered call back funtion.

 MaxSdk.ShowRewardedAd(applovin_RewardedVideo_Id, placement);

private void OnRewardedAdReceivedRewardEvent(string adUnitId, MaxSdk.Reward reward, MaxSdkBase.AdInfo adInfo)

### Expected Behavior

I received earlier this placement name successfully but now I receive only an empty string. I am expecting to receive my placement name in the call back function which I passed as a parameter on calling Rewarded Video.

### How to Reproduce

It happens all the time now on updates to the latest Max version.

**Comment by santoshbagadi** [comment]
Hi @umairmanz this is not a regression and was not supported in Unity Editor. But we'll add support for it in an upcoming release.

**Comment by OzanDost** [comment]
+1 It'd be great to be able to recieve placement id in the editor. At least for testing.

**Comment by santoshbagadi** [comment]
Our latest plugin version [6.6.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_6_0) now has support for passing placement ID in editor callbacks.
