### ISSUE TITLE
iOS - Crash with AL SDK 6.5.2 in ALDCMPNetworksTableViewController

### ISSUE THREAD

**Issue by ltk-daniel-zapater** [AppLovin/AppLovin-MAX-Unity-Plugin#383]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.22f1

### Device/Platform Info

iOS

### Current Behavior

App crashes with the following stack trace (similar stack traces attached below):

      Crashed: com.apple.main-thread
      SIGABRT ABORT 0x00000001e4a86974
0  libsystem_kernel.dylib         0xa974 __pthread_kill + 8
1  libsystem_pthread.dylib        0x60ec pthread_kill + 268
2  libsystem_c.dylib              0x75b80 abort + 180
3  libswiftCore.dylib             0x3a6690 swift::fatalError(unsigned int, char const*, ...) + 134
4  libswiftCore.dylib             0x3a66b0 swift::warningv(unsigned int, char const*, char*) + 30
5  libswiftCore.dylib             0x3a6874 swift::swift_abortRetainUnowned(void const*) + 32
6  libswiftCore.dylib             0x405550 swift_unknownObjectUnownedTakeStrong + 74
7  AppLovinSDK                    0x185584 -[ALDCMPNetworksTableViewController .cxx_destruct] + 864
8  UnityFramework                 0x195ef44 specialized UnityAdsAdViewAdapterDelegate.bannerViewDidError(_:error:) + 97692
9  UnityFramework                 0x195ecf8 @objc UnityAdsAdViewAdapterDelegate.bannerViewDidError(_:error:) + 97104
10 UnityFramework                 0x1f9698c __64-[UADSBannerLoadModuleDelegateWrapper bannerViewDidError:error:]_block_invoke + 3116
11 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
13 libdispatch.dylib              0x125a4 _dispatch_main_queue_drain + 988
14 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
15 CoreFoundation                 0x3751c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
16 CoreFoundation                 0x34218 __CFRunLoopRun + 1996
17 CoreFoundation                 0x33968 CFRunLoopRunSpecific + 608
18 GraphicsServices               0x34e0 GSEventRunModal + 164
19 UIKitCore                      0x22aedc -[UIApplication _run] + 888
20 UIKitCore                      0x22a518 UIApplicationMain + 340
21 UnityFramework                 0x190af20 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 96 (main.mm:96)

### Expected Behavior

App does not crash

### How to Reproduce

Cannot reproduce

### Additional Info

We have noticed the crash in Firebase Crashlytics after releasing 6.5.2 to prod. It's affecting 2% of app sessions. Attached similar stack traces.

As, according to the stack traces, it seems to always happen after an ad from Unity fails to load:
- Will it stop happening by pausing Unity Ads in the AL console?
- Will it be fixed by upgrading Unity ads adapter from 4.11.3.1 to the recently available 4.11.3.2?

[ALDCMPNetworksTableViewController Crashes.zip](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/15454755/ALDCMPNetworksTableViewController.Crashes.zip)

**Comment by thomasmso** [comment]
Hi, this issue has been fixed in UnityAds adapter version v4.11.3.2. Thanks for bringing it to our attention.
