### ISSUE TITLE
Can not build Android after upgrading Target SDK version to 34

### ISSUE THREAD

**Issue by bartutiryakioglu** [AppLovin/AppLovin-MAX-Unity-Plugin#387]
### MAX Plugin Version

6.5.2

### Unity Version

2021.3.29f1

### Device/Platform Info

Android

### Current Behavior

After upgrading Target SDK version to 34, my gradle builds started failing with **launcher:processReleaseResources** task and with **AAPT2 aapt2-7.0.3-7396180-osx Daemon #0: Unexpected error during link, attempting to stop daemon..** error.

### How to Reproduce

Upgrade target SDK version to 34 and gradle build is gonna fail

### Additional Info

I've also Firebase, Facebook and Appsflyer in my project with their latest versions.

**Comment by itkdo** [comment]
@bartutiryakioglu we solved this problem by migrating to unity 2022 with resetting greadle files

**Comment by heyChenfu** [comment]
@bartutiryakioglu Same problem, have you find solution at last?

**Comment by gulliversgames** [comment]
> @bartutiryakioglu Same problem, have you find solution at last?

https://github.com/firebase/firebase-unity-sdk/issues/1035#issuecomment-2149471713
this might work for you
