### ISSUE TITLE
Creating Banner Load Time

### ISSUE THREAD

**Issue by justin-tsai** [AppLovin/AppLovin-MAX-Unity-Plugin#39]
Is it normal that the time to create a banner is around 30-40 seconds? In comparison, interstitial and rewarded ads take around 3-5 seconds to load on the same device and network.

**Comment by applovinjosh** [comment]
Hey @justin-tsai,
That sounds like there is an issue somewhere with your banners.  Can you try enabling verbose logging and emailing me at josh.gleeson at applovin dot com?  [Here's instructions](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) for verbose logging.  I can help you debug from there.

**Comment by thomasmso** [comment]
Hey @justin-tsai - I'm going to close this issue as we've resolved it via email. Thank you.
