### ISSUE TITLE
Applovin Admob Mediation Problem

### ISSUE THREAD

**Issue by HakanErenAlice** [AppLovin/AppLovin-MAX-Unity-Plugin#392]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.16

### Device/Platform Info

IOS

### Current Behavior

ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
ld: Undefined symbols:
  _GADAdLoaderAdTypeNative, referenced from:
      ___73-[ALGoogleMediationAdapter loadAdViewAdForParameters:adFormat:andNotify:]_block_invoke in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
      ___64-[ALGoogleMediationAdapter loadNativeAdForParameters:andNotify:]_block_invoke in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _GADAdSizeBanner, referenced from:
      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _GADAdSizeLeaderboard, referenced from:
      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _GADAdSizeMediumRectangle, referenced from:
      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth, referenced from:
      ___75-[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:]_block_invoke in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
      +[ALGoogleMediationAdapter currentOrientationAchoredAdaptiveBannerSizeWithWidth:] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _GADGetStringFromVersionNumber, referenced from:
      -[ALGoogleMediationAdapter SDKVersion] in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADAdLoader, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADAppOpenAd, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADBannerView, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADExtras, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADInterstitialAd, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADMediaView, referenced from:
       in libGoogleAdapter.a[3](ALGoogleNativeAdDelegate.o)
  _OBJC_CLASS_$_GADMobileAds, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADNativeAdImageAdLoaderOptions, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADNativeAdView, referenced from:
       in libGoogleAdapter.a[7](ALGoogleNativeAd.o)
  _OBJC_CLASS_$_GADNativeAdViewAdOptions, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADQueryInfo, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADRequest, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADRewardedAd, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
  _OBJC_CLASS_$_GADRewardedInterstitialAd, referenced from:
       in libGoogleAdapter.a[10](ALGoogleMediationAdapter.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Hello, I use 4 different mediations. liftoff, fb, mintegral and admob. When admob is turned off, I build without any problems. When admob is opened, I enter the key and build, I get this error. There was no such problem before. I tried several different versions of Unity and the result is the same.

### How to Reproduce

<img width="1088" alt="Ekran Resmi 2024-06-05 14 27 11" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/153733730/2389828a-8ebf-48f8-8d51-c352eec06ae3">

**Comment by JonathanLiuApp** [comment]
@HakanErenAlice Unfortunately, I was unable to reproduce the error. Are you able to reproduce this with our demo app?

**Comment by HakanErenAlice** [comment]
Solved

**Comment by Wudderda** [comment]
Were you able to solve this problem? I am having the same issue

**Comment by evgeny44** [comment]
Has anyone resolved it?

**Comment by kogodm** [comment]
Has anyone resolved it? same error on : maxsdk 6.6.3

**Comment by kogodm** [comment]
> Has anyone resolved it? same error on : maxsdk 6.6.3

stlll on 7.0.0

**Comment by evgeny44** [comment]
The issue is with google mobile ads xframework missing from "link binary with library" in build phases in unity iphone target

**Comment by Tamsiree** [comment]
I am having the same issue, Has anyone resolved it?

**Comment by evgeny44** [comment]
> I am having the same issue, Has anyone resolved it?

Yes man. This happens, because you install pods with use_frameworks! This forces pods to be dynamic frameworks. And googlemobileads is a static framework. So to resolve this:

After pod install, navigate to your main target (which is Unit-iPhone) go to General tab,scroll down to Libraries, Frameworks and manually drag and drop there GoogleMobileAds.xcframework (embed & sign) from Pods project. Or update your Podfile to do that automatically on post_integrate hook.

**Comment by Tamsiree** [comment]
> > I am having the same issue, Has anyone resolved it?
> 
> Yes man. This happens, because you install pods with use_frameworks! This forces pods to be dynamic frameworks. And googlemobileads is a static framework. So to resolve this:
> 
> After pod install, navigate to your main target (which is Unit-iPhone) go to General tab,scroll down to Libraries, Frameworks and manually drag and drop there GoogleMobileAds.xcframework (embed & sign) from Pods project. Or update your Podfile to do that automatically on post_integrate hook.

thank you~

**Comment by alexwzebr** [comment]
for me, this worked:
pod update
pod install
add GoogleMobileAds.xcframework to Build Phases -> Link binary with library
