### ISSUE TITLE
Can't build ios after install Facebook mediation network

### ISSUE THREAD

**Issue by hoainam1593** [AppLovin/AppLovin-MAX-Unity-Plugin#394]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.17

### Device/Platform Info

not applicable

### Current Behavior

after install Facebook mediation, build ios will get the error:
Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_FBAudienceNetwork in FBAudienceNetwork[270](FBAudienceNetwork.o)

### How to Reproduce

- create unity project
- import applovin unity sdk
- go to applovin integration manager -> install facebook mediation network
- build ios will get the error build as described above

**Comment by JonathanLiuApp** [comment]
Hi @hoainam1593, could you try updating Xcode to 15.4 and see if that fixes your issue?

**Comment by hoainam1593** [comment]
thanks @JonathanLiuApp , I've built successfully with xocde 15.4

**Comment by krzysztofturek-ops** [comment]
I have the same problem..
Xcode: 16.3
AppLovinMax: 8.5.1
Facebook 6.21.0


> ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3.0', '-lz'
> ld: warning: Could not find or use auto-linked library 'swiftWebKit': library 'swiftWebKit' not found
> ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation1': library 'swift_DarwinFoundation1' not found
> ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation2': library 'swift_DarwinFoundation2' not found
> ld: warning: Could not find or use auto-linked library 'swift_DarwinFoundation3': library 'swift_DarwinFoundation3' not found
> ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
> ld: warning: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
> ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
> ld: warning: Could not parse or use implicit file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
> Undefined symbols for architecture arm64:
>   "_swift_coroFrameAlloc", referenced from:
>       ___swift_coroFrameAllocStub in FBAudienceNetwork[18](FBANVideoViewSwift.o)
>       ___swift_coroFrameAllocStub in FBAudienceNetwork[18](FBANVideoViewSwift.o)
> ld: symbol(s) not found for architecture arm64
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Revan1993** [comment]
Same here

**Comment by krzysztofturek-ops** [comment]
Ok, I found the solution. You need Xcode 26.0.0 at least
