### ISSUE TITLE
Crash in MaxDebugger after click on reason problem of integration MobileFuse (1.7.5)

### ISSUE THREAD

**Issue by maxim-narchuk-cleverside** [AppLovin/AppLovin-MAX-Unity-Plugin#398]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.17f

### Device/Platform Info

iOS 16.1.2, iPhone 11

### Current Behavior

When trying to find out details in the debugger (tap here), the app crashes.
crashlog

![image](https://github.com/user-attachments/assets/00ddd3ca-3c89-4a88-9258-c44205430de0)

### Expected Behavior

No crash, more information on MobileFuse integration issue is displayed

### How to Reproduce

1. Launch app
2. Open MaxDebugger
3. Select on MobileFuse (version 1.7.5)
4. Select on reason problem (see attach)

[crashlog.pdf](https://github.com/user-attachments/files/16192002/crashlog.pdf)

**Comment by applovinAsh** [comment]
@maxim-narchuk-cleverside - We are looking into the issue and will update you once more information is available.

**Comment by applovinAsh** [comment]
@maxim-narchuk-cleverside - this issue has been fixed in Unity 6.6.0.
