### ISSUE TITLE
Error codes meaning

### ISSUE THREAD

**Issue by Heaven31415** [AppLovin/AppLovin-MAX-Unity-Plugin#4]
Hi.

In the demo implementation of this plugin you can find that some callbacks are returning error codes when something bad happens, however I don't see how can I convert those codes into meaningful information.

Where can I find more information about error codes returned by callbacks?

**Comment by thomasmso** [comment]
We don't currently expose the error code definitions in Unity, but will do so in a future release. In the meantime, it is safe to re-try the ad request after some delay as pointed out in our [docs](https://dash.applovin.com/documentation/mediation/unity/getting-started).

**Comment by Heaven31415** [comment]
Hi. Thanks for quick response. 

Would you mind telling me about error code -5001? I'm getting this error code constantly in some bizarre situations when trying to load rewarded videos on both iOS and Android devices. After getting this error, I'm sending another response to load more ads, however I'm not seeing any responses.

**Comment by thomasmso** [comment]
That's actually a pretty generic error where none of the mediated networks were able to load an ad. I suggest sending us your logs capturing the error to devsupport@applovin.com and we'll be able to assist you further.

**Comment by Heaven31415** [comment]
Thanks, I tried to look at the documentation link you gave here, however I'm instantly asked to create an account, which I cannot do, because I'm working for a company and I doesn't have access to their applovin account. 

I don't really understand why do I have to create an account to see documentation?

**Comment by thomasmso** [comment]
You should ask the company to provide you with an account.
