### ISSUE TITLE
Applovin Interstitial never ends

### ISSUE THREAD

**Issue by Mecze** [AppLovin/AppLovin-MAX-Unity-Plugin#402]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.8f1

### Device/Platform Info

Android 13 nubia X729J

### Current Behavior

We show interstitials as "Initial Interstitial" when de app cold boots.

In one of these ads, a video plays, after that I get a playable that never ends, and an "x" to close it is never shown. I have been here for 30 minutes already!

This can happen on any interstitial.

### Expected Behavior

We show interstitials as "Initial Interstitial" when de app cold boots.

An Interstitial show, and whitin 30 seconds tops, the user should be back on our app.

### How to Reproduce

I dont really know how to reproduce it, but here is the debug thrown by the Plugin.
We just launch an Interstitial when de app opens.

2024/07/23 13:08:44.035 26674 27161 Info Unity Debug [AppLovin MAX] Invoking event: OnInterstitialDisplayedEvent. Params: 30482b23*****, [AdInfo adUnitIdentifier: 30482b*****, adFormat: INTER, networkName: AppLovin, networkPlacement: *****, creativeIdentifier: 42325152, placement: InterstitialStaticBingo, revenue: 0,0290401248931885, revenuePrecision: exact, latency: 1812, dspName: ]

Also I see this error on Logcat a lot:
2024/07/23 13:22:41.388 26674 27048 Error Utils exception in get absolute parent (input param is com.applovin.impl.adview.b{f695875 VFED..CL. .F...... 0,0-2480,1116 aid=1073741824}' , error : android.view.ViewRootImpl cannot be cast to android.view.View

 It is an AppLovin Ad (We do have mediation networks, but this one is served by AppLovin)

I attach a screenshot.

### Additional Info

![image](https://github.com/user-attachments/assets/3db6fb79-c30b-4256-8540-3a30138e49be)

**Comment by Mecze** [comment]
This behaviour happens with ALL PLAYABLES

**Comment by Mecze** [comment]
Still testing, it also happens with rewardeds, any "skip" button is and other context items while in viewing the ad (like a potential time bar) are gone!

**Comment by santoshbagadi** [comment]
Hi @Mecze , are you using our Ad Review plugin? We've recently had an issue with Ad Review plugin version 5.4.1 that might be causing this issue. Could you please try rebuilding the project and see if that fixes the issue?

**Comment by Mecze** [comment]
We do have the "Enable MAX Ad Review" check enabled in the integration settings
Here are those settings:

![image](https://github.com/user-attachments/assets/5369a47a-441e-46ff-a7fc-f071ba707f0a)

I have rebuilt it several times, still happening.
Also, in further testing: it does not happen on other devices than nubia X729J (RedMagic 8 pro)

**Comment by Flunty** [comment]
Rebuild it one more time

**Comment by santoshbagadi** [comment]
Could you please share the Ad Review version which can be found in the [Mediation debugger](https://developers.applovin.com/en/unity/testing-networks/mediation-debugger/).

**Comment by Mecze** [comment]
Versión is 5.4.1
I reopened the game (a day later) and the problem is gone for now. I really don't know what happened. I'll report back if it happens again

**Comment by santoshbagadi** [comment]
AdReview version 5.4.1 had an issue and was fixed in 5.4.2. Our plugin uses the latest version by default, so, building the app again may have fixed the issue. 

I'm going to close the issue, please re-open it if you are still facing the issue.

**Comment by Mecze** [comment]
Thank you! 
I'll check it out
