### ISSUE TITLE
Stuck while installing mediation

### ISSUE THREAD

**Issue by HiepEldest** [AppLovin/AppLovin-MAX-Unity-Plugin#403]
### MAX Plugin Version

6.6.1

### Unity Version

2022.3.38

### Device/Platform Info

Unity Editor on M1 MacOS 14.5 

### Current Behavior

Stuck in install mediation screen
![Screenshot 2024-07-25 at 9 48 33 PM](https://github.com/user-attachments/assets/5cb7ec57-88d0-46ff-bcfb-4b0c5adf7cdb)

### How to Reproduce

install mediations

**Comment by JonathanLiuApp** [comment]
@HiepEldest Sometimes when importing files the Unity popup will get stuck there - especially if multiple items are imported one after the other. This popup should go away if you import another item or do a script reload.

**Comment by HiepEldest** [comment]
hi @JonathanLiuApp I can't cancel or install anything else or close Unity. I must force quit Unity, very inconvenient
