### ISSUE TITLE
Ad review build error Android Unity 2021.3.41f1

### ISSUE THREAD

**Issue by pspgit** [AppLovin/AppLovin-MAX-Unity-Plugin#405]
### MAX Plugin Version

6.6.1

### Unity Version

2021.3.41

### Device/Platform Info

Android

### Current Behavior

With ad review enabled, error appears during Android build

>  [AppLovin MAX] Failed to add AppLovin Quality Service plugin. Quality Service Plugin Added?: False, Quality Service Repo added?: False, Quality Service dependency added?: False

### Expected Behavior

Gradle postprocess completes without error.

### How to Reproduce

1. Turn on "Enable Max Ad Review" in Integration Manager
2. Build project for Android

### Additional Info

The issue is the same as described for Unity 2022: 
- https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/206

Unity has updated Gradle to 7.5.1 and now this error is happening in Unity 2021.3.41.

> Android: Updated Gradle version to 7.5.1 (from 6.7.1), AGP version to 7.4.2 (from 4.2.2) and JDK to 11 (from 1.8).
> source: https://unity.com/releases/editor/whats-new/2021.3.41#notes

**Comment by santoshbagadi** [comment]
Hi @pspgit , thank you for raising the issue. We are aware of the issue and have a fix in the works. We'll have the fix out in the next release (will most likely be released this weekend).

**Comment by kocburak** [comment]
Hi,
I found a fix toa solution. In the AppLovinProcessGradleBuildFile.cs, AppLovinPostProcessAndroid.cs and AppLovinPostProcessAndroidGradle.cs files there are check for "UNITY_2022_3_OR_NEWER". Change them with " UNITY_2022_3_OR_NEWER || UNITY_2021_3_41"

**Comment by JonathanLiuApp** [comment]
We've added a fix for this in our latest plugin release [version 6.6.2](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_6_2).
