### ISSUE TITLE
Problem in AndroidManifest.xml (screenOrientation = portrait)

### ISSUE THREAD

**Issue by N0lex** [AppLovin/AppLovin-MAX-Unity-Plugin#41]
Hi!

I found problem in your AndroidManifest.xml (com.applovin.applovin-sdk-9.13.0.aar).

**Code:**

`<activity android:configChanges="keyboardHidden|orientation|screenSize" android:name="com.applovin.mediation.MaxDebuggerMultiAdActivity" android:screenOrientation="portrait" android:theme="@style/com.applovin.mediation.MaxDebuggerActivity.Theme"/>`

My game uses only landscape orientation.
Why are you adding portrait orientation?

**Max SDK 2.4.15 (lasted version).**

**Fixed com.applovin.applovin-sdk-9.13.0.aar:** [com.applovin.applovin-sdk-9.13.0.zip](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/4873037/com.applovin.applovin-sdk-9.13.0.zip)

**Screenshots (from Google Play Console):**

![photo_2020-07-04_17-51-49](https://user-images.githubusercontent.com/20575677/86515056-11cafa00-be1f-11ea-8ce8-a15b1fbd272d.jpg)
![photo_2020-07-04_12-48-53](https://user-images.githubusercontent.com/20575677/86515057-12fc2700-be1f-11ea-8b14-2848e3d77a21.jpg)

**Comment by thomasmso** [comment]
Thanks for reporting this @N0lex, we're investigating and will notify the thread when a solution has been reached.

**Comment by N0lex** [comment]
**com.applovin.applovin-sdk-9.13.1.aar** - ### Same problem!

@thomasmso When will you do your work?

Thanks!

**Comment by thomasmso** [comment]
Hey @N0lex, we have a fix scheduled in the next release. The ETA for it will be around next week.

**Comment by thomasmso** [comment]
This has been fixed in our latest Android SDK 9.13.2 which the latest Unity Plugin bundles.
