### ISSUE TITLE
AppLovin Max Banner related automatic ad direction(click) issue

### ISSUE THREAD

**Issue by fuatcoskun** [AppLovin/AppLovin-MAX-Unity-Plugin#410]
### MAX Plugin Version

6.5.2

### Unity Version

2022.3.21f1

### Device/Platform Info

Android

### Current Behavior

After integrating banners, we face weird automatic ad direction issue on some devices which is explaining unexpected user churns. We initialize banners after Max SDK is initialized as we did for interstitials and rewardeds : 

```
public void InitializeBanners()
{
    MaxSdkCallbacks.Banner.OnAdLoadedEvent                      += OnBannerLoadedEvent;
    MaxSdkCallbacks.Banner.OnAdLoadFailedEvent                  += OnBannerLoadFailedEvent;
    MaxSdkCallbacks.Banner.OnAdClickedEvent                     += OnBannerClickedEvent;
    MaxSdkCallbacks.Banner.OnAdCollapsedEvent                   += OnBannerCollapsedEvent;
    MaxSdkCallbacks.Banner.OnAdExpandedEvent                    += OnBannerExpandedEvent;
    MaxSdkCallbacks.Banner.OnAdReviewCreativeIdGeneratedEvent   += OnAdReviewCreativeIdGeneratedEvent;
    MaxSdkCallbacks.Banner.OnAdRevenuePaidEvent                 += OnBannerAdRevenuePaidEvent;
    
    MaxSdk.CreateBanner(Constants.BannerTopCenterAdUnitId, MaxSdkBase.BannerPosition.TopCenter);
    MaxSdk.CreateBanner(Constants.BannerBottomCenterAdUnitId, MaxSdkBase.BannerPosition.BottomCenter);
    
    MaxSdk.SetBannerWidth(Constants.BannerTopCenterAdUnitId, GetBannerWidth());
    MaxSdk.SetBannerWidth(nConstants.BannerBottomCenterAdUnitId, GetBannerWidth());

    MaxSdk.SetBannerExtraParameter(Constants.BannerTopCenterAdUnitId, "ad_refresh_seconds", "5");
    MaxSdk.SetBannerExtraParameter(Constants.BannerBottomCenterAdUnitId, "ad_refresh_seconds", "5");
}
```

In our player log, we saw that app goes to pause state with no reason and we see it on the device that AliExpress app is launched. 3-4 seconds before that, OnAdLoadedEvent and OnAdRevenuePaidEvent are invoked we suspect as the reason. Following logs show the timing : 

```
[20240812 11:15:47.572] --> OnBannerLoadedEvent : XXX-TopAdUnit-YYY
[20240812 11:15:47.594] --> OnAdReviewCreativeIdGeneratedEvent : XXX-TopAdUnit-YYY
[20240812 11:15:48.438] --> OnBannerAdRevenuePaidEvent : XXX-TopAdUnit-YYY
[20240812 11:15:48.551] --> OnBannerLoadedEvent : XXX-BottomAdUnit-YYY
[20240812 11:15:48.568] --> OnAdReviewCreativeIdGeneratedEvent : XXX-BottomAdUnit-YYY
[20240812 11:15:49.713] --> OnBannerAdRevenuePaidEvent : XXX-BottomAdUnit-YYY
[20240812 11:15:52.472] --> [AppState] IN BACKGROUND 
```

In the adb logcat logs, we saw that our app is launching an activity via an intent as follows : 

**08-12 11:15:52.281** 18307 21170 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=https://www.aliexpress.com/... flg=0x10000000 cmp=com.alibaba.aliexpresshd/com.aliexpress.module.navigation.HttpDispatcherActivity} from uid 11588 from pid 2496 callingPackage **com.our.app**

You can see that timing match perfectly and we are %100 sure that no callbacks are triggered from Max SDK.
An we don't call 
```
MaxSdk.ShowBanner("XXX-TopAdUnit-YYY") 
MaxSdk.ShowBanner("XXX-BottomAdUnit-YYY")
```
in this scenario. We think that this ad direction is triggered inside the SDK or somehow from the ad itself maybe.
Do you have an idea about what is going on here? We will have to remove the integration completely if we can not prevent that behavior.

### Expected Behavior

We expect no ad direction without showing a banner ad and also without getting an ad click callback.

### How to Reproduce

All the details are explained in the "Current Behavior" part. You most probably won't be able to reproduce it but all you should do is : 
- Initialize banners as shown above.
- Wait for banner ad loaded and revenue paid callbacks called.
- After a random time, an intent will be fired and app will be paused to launch the app coming from and invisible ad or the store page if it is not installed on the device.

**Comment by fuatcoskun** [comment]
Ok @tiandrew, we saw that click action in the auto redirect report analyze dashboard and it is coming Liftoff Monetize only. We will disable the ad network for now. 
On the other side, do you have a plan to make a development to prevent such actions?

**Comment by tiandrew** [comment]
Hey @fuatcoskun, yes we monitor all network auto-redirects internally and reach out to respective offending partners when detected as well. Please feel free to let me know if this domain from LiftOff or any other partners are detected again.

**Comment by tiandrew** [comment]
Hey @fuatcoskun, `aliexpress.com` has been blocked for Liftoff internally, you should be able to unblock them now.
