### ISSUE TITLE
Configured CMP networks: Missing networks

### ISSUE THREAD

**Issue by bedirhanblt54** [AppLovin/AppLovin-MAX-Unity-Plugin#424]
### MAX Plugin Version

6.6.3

### Unity Version

2022.3.17f1

### Device/Platform Info

android, ios

### Current Behavior

Hello,

I am encountering the “Configured CMP networks: Missing networks” error and I couldn’t resolve it, so I am reaching out for your help.

Could you please guide me step by step on what actions I should take and how I can fix this error? Additionally, I wasn’t getting this error before, and I haven’t made any changes; I noticed it during testing.

The mediated networks I am using are:

DT Exchange, Facebook, Google AdMob, InMobi, Liftoff, Mintegral, Pangle, Unity Ads, Verve.

### How to Reproduce

I enabled the “Enable MAX Terms and Privacy Flow” setting from the AppLovin Integration Manager console, then I added the Privacy and Terms links. After that, I enabled the Override Default Usage Description setting. These are all the settings I configured on Unity.

### Reproducible in the demo app?

Not Tested

### Additional Info

![1](https://github.com/user-attachments/assets/5d94c0ed-c9c1-4078-9731-83588ebbd917)
![2](https://github.com/user-attachments/assets/d33daa9d-54fb-4ecf-92ae-6cb738f12b39)

**Comment by santoshbagadi** [comment]
Hi @bedirhanblt54  Please refer to the [Customize Ad Partners List](https://developers.applovin.com/en/max/unity/overview/terms-and-privacy-policy-flow#customize-ad-partners-list) section of our guide for instructions on updating the networks list for Google's UMP. Make sure that Liftoff is added to the list of ad partners.

**Comment by bedirhanblt54** [comment]
> Hi @bedirhanblt54 Please refer to the [Customize Ad Partners List](https://developers.applovin.com/en/max/unity/overview/terms-and-privacy-policy-flow#customize-ad-partners-list) section of our guide for instructions on updating the networks list for Google's UMP. Make sure that Liftoff is added to the list of ad partners.

Thank you for the response. I have already ensured that Liftoff is added to the list of ad partners. However, I am still encountering the same issue.
