### ISSUE TITLE
Unity Max SDK ad position issue

### ISSUE THREAD

**Issue by niggvard** [AppLovin/AppLovin-MAX-Unity-Plugin#425]
### MAX Plugin Version

6.3.0

### Unity Version

2022.3.18f1

### Device/Platform Info

Redmi Note 9

### Current Behavior

In my game, I am using Max SDK. During ad display, I see a gap at the top where the camera is located.

### Expected Behavior

I want to make sure that even on devices with a camera at the top, the ad is displayed in full screen.

### How to Reproduce

This issue occurs with some interstitial and rewarded ads.

### Reproducible in the demo app?

Not Tested

**Comment by niggvard** [comment]
![screenshot](https://github.com/user-attachments/assets/3103f2a5-a566-42c0-8a29-4431ef4668d9)

**Comment by santoshbagadi** [comment]
Some networks don't show content in the safe ares. In this case, the ad seems to be coming from AdMob (you can confirm using our [Creative Debugger](https://developers.applovin.com/en/max/unity/testing-networks/creative-debugger/)). 

You'd need to reach out to the network to have them fix the issue.
