### ISSUE TITLE
Amazon SKAdNetwork Id

### ISSUE THREAD

**Issue by ab-rdarts** [AppLovin/AppLovin-MAX-Unity-Plugin#426]
### MAX Plugin Version

6.6.3

### Unity Version

2022.3.40f1

### Device/Platform Info

iOS

### Current Behavior

SKAdNetwork identifiers are missing or outdated

yrqqpx2mcb.skadnetwork

### Expected Behavior

Amazon adapter COMPLETED INTEGRATION

### How to Reproduce

Just build application with integrated amazon adapter

### Reproducible in the demo app?

Not Tested

**Comment by thomasmso** [comment]
You need to re-export your project and our Unity Plugin will automatically install the latest SKAdNetwork IDs for the project.

**Comment by ab-rdarts** [comment]
@thomasmso I still see the same problem after full reexport and build app

**Comment by santoshbagadi** [comment]
Could you confirm if you have the `Add Amazon Publisher Services SKAdNetworkIDs` setting under `Other Settings` in our Integration Manager enabled.

**Comment by ab-rdarts** [comment]
@santoshbagadi thanx. It was really disabled. Now it works in right way
