### ISSUE TITLE
 NSPrivacyAccessedAPIType Issue

### ISSUE THREAD

**Issue by R9sungpil** [AppLovin/AppLovin-MAX-Unity-Plugin#431]
### MAX Plugin Version

iOS 11.11.3

### Unity Version

2021.3.28f1

### Mintegral SDK Version 

android_16.5.11.0_ios_7.5.7.0.0

### Device/Platform Info

ios 

### Current Behavior

When building an iOS project using the AppLovin plugin in Unity, I received the following warning from Apple:

ITMS-91105: Invalid API category declaration - The PrivacyInfo.xcprivacy file at the “Frameworks/UnityFramework.framework/MTGSDK.bundle/PrivacyInfo.xcprivacy” path contains “NSUserDefaults” as the value for a NSPrivacyAccessedAPIType key, which is invalid.

It seems to be an issue with the Mintegral SDK. How can I resolve this?

### How to Reproduce

The issue occurs during the App Store review after submitting the iOS build created in Unity.

### Reproducible in the demo app?

Not Tested

**Comment by alvarshahanji** [comment]
@R9sungpil could you use latest Mintegral adapter with Mintegral SDK(7.7.2.0.1). Looks like they have fixed it in their latest SDKs. Thanks!
