### ISSUE TITLE
IOS Build fails. Unity 2022.3.49. IOS Plugin 13.0.0

### ISSUE THREAD

**Issue by TrueRaider** [AppLovin/AppLovin-MAX-Unity-Plugin#434]
### MAX Plugin Version

7.0.0

### Unity Version

2022.3.49f1

### Device/Platform Info

Mac Silicon

### Current Behavior

After update to 7.0.0 and ios 13.0.0, build return error in UnityFramework linking.

### How to Reproduce

Simple. Install unity 2022.3.49f1
Installed mediators:
DT Exchange
Google AdMob
IronSource
Liftoff Monetize
Mintegral
UnityAds
VK ad Network

### Reproducible in the demo app?

Not Tested

**Comment by santoshbagadi** [comment]
@TrueRaider could you please share the full error message you are seeing?

**Comment by TrueRaider** [comment]
Strange Things! Without errors now!
