### ISSUE TITLE
After seeing a specific AdMob Reward ad format, the app doesn't return to the foreground.

### ISSUE THREAD

**Issue by prodongi** [AppLovin/AppLovin-MAX-Unity-Plugin#436]
### MAX Plugin Version

13.0.0

### Unity Version

2022.3.36f1

### Device/Platform Info

Android

### Current Behavior

There is an issue with the ads that automatically redirect to Google Play while watching reward-based ads.

The game does not return to the Foreground after reaching the OnRewardedAdHiddenEvent event.

It need to click anywhere on the screen to return to the foreground.

### How to Reproduce

https://github.com/user-attachments/assets/df36b50c-5513-4aad-8af6-92585633140e

### Reproducible in the demo app?

No

**Comment by applovinAsh** [comment]
@prodongi, is this behavior only happening with Google Ads, or are you seeing it from other networks as well? If you see this happening from AppLovin ads, can you provide the creative debugger log so we can investigate? To enable the creative debugger log, see here: https://developers.applovin.com/en/max/unity/testing-networks/creative-debugger/

**Comment by prodongi** [comment]
Thank you.
This only happens with Google Ads.
Debug log attached.
[MaxDebug.log](https://github.com/user-attachments/files/17388122/MaxDebug.log)

**Comment by applovinAsh** [comment]
@prodongi as this is only happening with Google Ads, please contact them regarding the issue.

**Comment by prodongi** [comment]
Ok, thank you.
