### ISSUE TITLE
Facebook & Ironsource iOS Undefined symbols

### ISSUE THREAD

**Issue by justin-tsai** [AppLovin/AppLovin-MAX-Unity-Plugin#437]
### MAX Plugin Version

7.0.0

### Unity Version

2022.3.10f1

### Device/Platform Info

iOS 

### Current Behavior

When I build a clean project with latest Facebook and IronSource, I get the following errors

Undefined symbols:

Linker command failed with exit code 1 (use -v to see invocation)

Surrounding logs:

ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked library 'libAppVerificationLibrary': library 'libAppVerificationLibrary' not found
ld: warning: Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_FBAudienceNetwork in FBAudienceNetwork[415](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swiftXPC_$_IronSource in IronSource[arm64][616](AbTestMapFile.o)

### Expected Behavior

Build to succeed

### How to Reproduce

Open demo project targetting iOS
Install latest Facebook and Ironsource.
Build to a folder
Open .workspace file in XCode
Try building to a device and the build fails with undefined symbols 

### Reproducible in the demo app?

Yes

**Comment by alvarshahanji** [comment]
@justin-tsai which Xcode version are you using?

**Comment by alvarshahanji** [comment]
@justin-tsai this is an issue we observed on older Xcode versions and version 15.4 or above should not have the issue.
