### ISSUE TITLE
SDK reports that Brazil is a GDPR member but CMP does not open the GDPR window

### ISSUE THREAD

**Issue by gashukov** [AppLovin/AppLovin-MAX-Unity-Plugin#438]
### MAX Plugin Version

6.6.3

### Unity Version

2022.3.31f1

### Device/Platform Info

all devices

### Current Behavior

`MaxSdk.GetSdkConfiguration().ConsentFlowUserGeography` returns `MaxSdkBase.ConsentFlowUserGeography.Gdpr` for Brazilian users, but CMP does not open GDPR window.

It affects 99% of all Brazilian users, we see this in analytics.

### How to Reproduce

I was able to reproduce this using a Brazilian VPN via Planet VPN on a BlueStacks emulator.

### Reproducible in the demo app?

Not Tested

### Additional Info

> [AppLovinSdk] 
> ========================================
> =====AppLovin SDK=====
> ===SDK Versions===
> Version: 12.6.1
> Plugin Version: Max-Unity-6.6.3
> Ad Review Version: 5.4.5
> OM SDK Version: 1.4.12-Applovin
> ===Device Info===
> OS: 9 (P - API 28)
> GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
> App Set ID: <Enable verbose logging to see the App Set ID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
> Model: NE2211
> Locale: ru_RU
> Emulator: false
> Tablet: true
> ===App Info===
> Application ID: [i deleted it]
> Target SDK: 34
> ExoPlayer Version: 2015001
> ===SDK Settings===
> SDK Key: [i deleted it]
> Mediation Provider: max
> TG: 58
> MD: [i deleted it]
> Test Mode On: false
> Verbose Logging On: false
> ===Privacy States===
> Please review AppLovin MAX documentation to be compliant with regional privacy policies.
> 
> Age Restricted User - No value set
> Has User Consent - No value set
> "Do Not Sell" - No value set
> ===MAX Terms Flow===
> Enabled: true
> Flow Type: MAX Terms and Privacy Policy Flow
> Consent Flow Geography: GDPR
> Privacy Policy URI: [i deleted it]
> Terms of Service URI: [i deleted it]
> ===CMP (CONSENT MANAGEMENT PLATFORM)===
> 
> CMP Name - Google LLC CMP
> CMP SDK ID - 300
> CMP SDK Version - No value set
> IABTCF_gdprApplies - 0
> IABTCF_TCString - No value set
> IABTCF_AddtlConsent - No value set
> ========================================
>

**Comment by applovinAsh** [comment]
@gashukov - For Brazil, while it is intended to align with GDPR requirements, Google currently does not display the consent flow there. However, if you’d like to enable the CMP flow in Brazil, you can do so through the AdMob dashboard by enabling it for all regions
