### ISSUE TITLE
Unity6000 Max8.0.0 UPM

### ISSUE THREAD

**Issue by Tamsiree** [AppLovin/AppLovin-MAX-Unity-Plugin#439]
### MAX Plugin Version

8.0.0

### Unity Version

Unity 6 (6000.0.23f1)

### Device/Platform Info

Unity Editor

### Current Behavior

Update Max SDK to UPM package
![image](https://github.com/user-attachments/assets/61324484-8028-48c7-83bf-0aa583e7ee1d)

### How to Reproduce

Update Max SDK to UPM package

### Reproducible in the demo app?

Not Tested

**Comment by JonathanLiuApp** [comment]
Could you check if there are any extra or hidden files in the `Assets/MaxSdk` folder? There may be a .DS_Store file that is causing the error.

**Comment by Tamsiree** [comment]
> Could you check if there are any extra or hidden files in the `Assets/MaxSdk` folder? There may be a .DS_Store file that is causing the error.

In the `Assets/MaxSdk` folder, there are no `.DS_Store` files, only AppLovinSettings files, and when I delete the `Assets/MaxSdk` folder, Click `Applovin` -> `Integration Manager` and the `Assets/MaxSdk` folder is created again, and the same error exists.

**Comment by JonathanLiuApp** [comment]
Thank you for reporting this issue. We will have a fix for it in the next release.

**Comment by santoshbagadi** [comment]
A fix for this is included in our plugin [version 8.0.1](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_8_0_1).
