### ISSUE TITLE
Alot iOS crash

### ISSUE THREAD

**Issue by DimasSup** [AppLovin/AppLovin-MAX-Unity-Plugin#444]
### MAX Plugin Version

13.0.0

### Unity Version

2022.3.36f1

### Device/Platform Info

iOS 

### Crashes/ANRs per Day

> 1000

### Percentage of Users Affected

> 2%

### First Occurrence of Crash/ANR

oct 10, after updating from sdk 12+ to sdk 13

### Exception and Stack Trace

Fatal Exception: NSGenericException
Task created in a session that has been invalidated
0
CoreFoundation
__exceptionPreprocess
1
libobjc.A.dylib
objc_exception_throw
2
CFNetwork
CFHostCreateWithName
3
AppLovinQualityService
(Missing UUID acb7cd55a0f43a9eabe2f63c3de775c4)
4
UnityFramework
NotificationService.sendNotification(urlString:key:attempt:)
5
UnityFramework
closure #1 in NotificationService.sendStoredTpats()
6
UnityFramework
closure #1 in Persistence.readStoredTpats(callback:)
7
UnityFramework
thunk for @escaping @callee_guaranteed @Sendable () -> ()
8
libdispatch.dylib
_dispatch_call_block_and_release
9
libdispatch.dylib
_dispatch_client_callout
10
libdispatch.dylib
_dispatch_lane_serial_drain$VARIANT$mp
11
libdispatch.dylib
_dispatch_lane_invoke$VARIANT$mp
12
libdispatch.dylib
_dispatch_root_queue_drain_deferred_wlh
13
libdispatch.dylib
_dispatch_workloop_worker_thread
14
libsystem_pthread.dylib
_pthread_wqthread
15
libsystem_pthread.dylib
start_wqthread

### How to Reproduce

Can't make same conditions for check

### Reproducible in the demo app?

No

### Additional Info

![image](https://github.com/user-attachments/assets/89a37abb-4e10-4647-a145-ff5170bf643d)
this one on ios 18.0+ only  ![image](https://github.com/user-attachments/assets/051bdc68-83a8-487c-8894-feedde3676f4)

**Comment by DimasSup** [comment]
one more ios 18.0 crash
![image](https://github.com/user-attachments/assets/22ae5a4e-e8c1-42d6-babc-cb3b69bb4771)

**Comment by NanaAmoah** [comment]
@DimasSup This issue is caused by Liftoff/Vungle's SDK. They released a fix in v7.4.2 of their SDK which we certified in [adapter v7.4.2.0](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/blob/master/Vungle/CHANGELOG.md). I'd recommend updating to the latest version to resolve the issue.
