### ISSUE TITLE
Android Gradle build failed with Chartboost

### ISSUE THREAD

**Issue by HiepEldest** [AppLovin/AppLovin-MAX-Unity-Plugin#448]
### MAX Plugin Version

8.1.0

### Unity Version

2022.3.38f1

### Device/Platform Info

Android

### Current Behavior

`FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.chartboost:chartboost-sdk:9.8.0.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all files for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not find com.chartboost:chartboost-sdk:9.8.0.
     Required by:
         project :unityLibrary > com.applovin.mediation:chartboost-adapter:9.8.0.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.`

### How to Reproduce

Using version 8.1.0 with Chartboost mediation

### Reproducible in the demo app?

No

**Comment by NanaAmoah** [comment]
Hi @HiepEldest, it looks like Chartboost rolled back their SDK. We’ll push a new adapter that is built against 9.7.0 to fix the issue.

**Comment by sydorenko-kyrylo** [comment]
@NanaAmoah When is it gonna happened aprox?

**Comment by NanaAmoah** [comment]
Hi @HiepEldest @sydorenko-kyrylo, we've released Chartboost Adapter 9.8.0.1 with the SDK downgraded to their previous version 9.7.0.

You can find the changes here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/132a940cd9fa5de670e24b7c05de5688247da03b
