### ISSUE TITLE
It appears some ads aren’t displaying correctly on the iPhone 16 Pro Max, preventing customers from pressing the X button.

### ISSUE THREAD

**Issue by cman-lf** [AppLovin/AppLovin-MAX-Unity-Plugin#449]
### MAX Plugin Version

8.0.1

### Unity Version

2022.3.51f

### Device/Platform Info

iPhone 16 Pro Max

### Current Behavior

After watching the advertisement, the X button area overlaps with the clock and cannot be touched.

### Expected Behavior

After watching the advertisement, the X button should be functioning properly when touched.

### How to Reproduce

This issue occurs on the iPhone 16 Pro Max when watching all types of video advertisements.

### Reproducible in the demo app?

No

### Additional Info

![image](https://github.com/user-attachments/assets/4ab12571-8b83-4502-b21f-e30306a9dcc8)

**Comment by alvarshahanji** [comment]
@cman-lf Can you get the [creative debugger](https://developers.applovin.com/en/max/unity/testing-networks/creative-debugger/) details for the ad? Then you can reach out to the ad network showing the ad directly. Thanks!
