### ISSUE TITLE
Long response times for loading invalid/disabled ad units

### ISSUE THREAD

**Issue by abogarsukov-braingames** [AppLovin/AppLovin-MAX-Unity-Plugin#452]
### MAX Plugin Version

7.0.0

### Unity Version

2022.3.44

### Device/Platform Info

Android

### Current Behavior

It takes MAX ~300 seconds (HTTP timeout?) to return error code -5603 for ad units removed from MAX dashboard. We did most of the testing on Android. 

### Expected Behavior

It seems to be an easy case to check. So we expect the requests to return within a few seconds with good connection.

### How to Reproduce

In out case first load attempt of a deleted ad unit consistently returns after ~300s with stable connection on Android device.

### Reproducible in the demo app?

Not Tested

### Additional Info

MAX logs:
```
[Log] [16:53:12.0170][Unity] Debug [AppLovin MAX] Invoking event: OnAppOpenAdLoadFailedEvent. Params: e945ed614be25cec, [ErrorInfo code: InvalidAdUnitId, message: Ad Unit ID e945ed614be25cec is invalid or disabled.
Make sure to use an Ad Unit ID from the MAX dashboard that is enabled and configured for the current application.
For more information, see https://developers.applovin.com/en/getting-started#step-2-create-an-ad-unit
Note: New ad units cannot load ads until 30-60 minutes after they are created, latency: 305466, adLoadFailureInfo: ]
```

**Comment by santoshbagadi** [comment]
Hi @abogarsukov-braingames , our SDK has some internal retry logic to fetch ads again on failures, but for the invalid ad unit case, we should be failing immediately in debug builds. Are you running these tests on a release build?

**Comment by abogarsukov-braingames** [comment]
@santoshbagadi I'm not sure what exactly you mean by debug/release builds. We don't enable Development Build option in Unity settings for testing.
