### ISSUE TITLE
Gradle failed to fetch dependencies

### ISSUE THREAD

**Issue by MehdiMashmool** [AppLovin/AppLovin-MAX-Unity-Plugin#454]
### MAX Plugin Version

8.0.1

### Unity Version

2022.3.13f1

### Device/Platform Info

Android

### Current Behavior

Gradle failed to fetch dependencies

### Expected Behavior

Resolve Success

### How to Reproduce

Install:
- Max v 8.0.1
- Google Play Games SDK v0.11.0.1
- Google Admob v 9.1.0
- Mediators in image below

![data](https://github.com/user-attachments/assets/a712f353-ead8-447c-89ee-53a93f8ffbc0)

### Reproducible in the demo app?

Not Tested

### Additional Info

**Stack:**

Resolution attempt 1: packages [androidx.appcompat:appcompat:1.0.0, com.google.android.gms:play-services-base:18.4.0, com.google.firebase:firebase-analytics-unity:12.0.0@srcaar, com.applovin.mediation:mintegral-adapter:16.8.81.0, com.google.android.ump:user-messaging-platform:2.2.0, com.google.android.gms:play-services-ads-identifier:18.1.0, com.applovin.mediation:bytedance-adapter:6.3.0.4.0, com.google.games:gpgs-plugin-support:0.11.01, androidx.browser:browser:1.0.0, androidx.constraintlayout:constraintlayout:2.1.4, androidx.legacy:legacy-support-v4:1.0.0, com.google.firebase:firebase-app-unity:12.0.0@srcaar, com.google.firebase:firebase-analytics:22.0.0, com.google.android.gms:play-services-ads:23.0.0, com.google.firebase:firebase-common:21.0.0, com.google.android.gms:play-services-appset:16.0.2, com.applovin.mediation:fyber-adapter:8.3.3.0, com.facebook.android:facebook-applinks:[16.0,17], androidx.activity:activity-compose:1.3.1, com.google.firebase:firebase-crashlytics-ndk:19.0.0, com.google.android.instantapps:instantapps:1.1.0, androidx.cardview:cardview:1.0.0, com.applovin:applovin-sdk:13.0.1, com.android.billingclient:billing:6.2.1, com.squareup.picasso:picasso:2.71828, com.applovin.mediation:facebook-adapter:[6.18.0.1], com.parse.bolts:bolts-android:1.4.0, com.facebook.android:facebook-core:[16.0,17], com.facebook.android:facebook-login:[16.0,17], com.applovin.mediation:inmobi-adapter:10.8.0.0, com.google.firebase:firebase-firestore-unity:12.0.0@srcaar, com.google.firebase:firebase-config:22.0.0, com.facebook.android:facebook-gamingservices:[16.0,17], com.google.firebase:firebase-firestore:25.0.0, com.google.firebase:firebase-config-unity:12.0.0@srcaar, com.applovin.mediation:smaato-adapter:22.7.1.1, com.google.firebase:firebase-crashlytics-unity:12.0.0@srcaar, com.facebook.android:facebook-share:[16.0,17], com.applovin.mediation:chartboost-adapter:9.8.1.0, androidx.recyclerview:recyclerview:1.2.1]
com.applovin:applovin-sdk conflicting due to package(s):
- com.applovin.mediation:bytedance-adapter:6.3.0.4.0/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:facebook-adapter:[6.18.0.1]/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:fyber-adapter:8.3.3.0/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:inmobi-adapter:10.8.0.0/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:mintegral-adapter:16.8.81.0/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin.mediation:smaato-adapter:22.7.1.1/com.applovin:applovin-sdk:[13.0.0,+]
- com.applovin:applovin-sdk:13.0.1
com.google.android.gms:play-services-ads-base conflicting due to package(s):
- com.google.android.gms:play-services-ads:23.0.0/com.google.android.gms:play-services-ads-base:[23.0.0]
- com.google.android.gms:play-services-ads:23.0.0/com.google.android.gms:play-services-ads-lite:[23.0.0]/com.google.android.gms:play-services-ads-base:[23.0.0]
com.google.android.gms:play-services-ads-identifier conflicting due to package(s):
- com.applovin.mediation:bytedance-adapter:6.3.0.4.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.chartboost:chartboost-sdk:9.8.1/com.google.android.gms:play-services-ads-identifier:18.0.1
- com.applovin.mediation:facebook-adapter:[6.18.0.1]/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:fyber-adapter:8.3.3.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:inmobi-adapter:10.8.0.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:inmobi-adapter:10.8.0.0/com.inmobi.monetization:inmobi-ads-kotlin:10.8.0/com.google.android.gms:play-services-ads-identifier:18.0.1
- com.applovin.mediation:mintegral-adapter:16.8.81.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin.mediation:smaato-adapter:22.7.1.1/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.applovin:applovin-sdk:13.0.1/com.google.android.gms:play-services-ads-identifier:17.1.0
- com.google.android.gms:play-services-ads-identifier:18.1.0
- com.google.android.gms:play-services-ads:23.0.0/com.google.android.gms:play-services-ads-identifier:18.0.0
- com.google.firebase:firebase-analytics:22.0.0/com.google.android.gms:play-services-measurement-api:22.0.0/com.google.android.gms:play-services-ads-identifier:18.0.0
- com.google.firebase:firebase-analytics:22.0.0/com.google.android.gms:play-services-measurement-sdk:22.0.0/com.google.android.gms:play-services-measurement-impl:[22.0.0]/com.google.android.gms:play-services-ads-identifier:18.0.0
- com.google.firebase:firebase-analytics:22.0.0/com.google.android.gms:play-services-measurement:22.0.0/com.google.android.gms:play-services-ads-identifier:18.0.0
- com.google.firebase:firebase-analytics:22.0.0/com.google.android.gms:play-services-measurement:22.0.0/com.google.android.gms:play-services-measurement-impl:[22.0.0]/com.google.android.gms:play-services-ads-identifier:18.0.0
com.google.android.gms:play-services-appset conflicting due to package(s):
- com.applovin.mediation:bytedance-adapter:6.3.0.4.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.chartboost:chartboost-sdk:9.8.1/com.google.android.gms:play-services-appset:16.0.2
- com.applovin.mediation:facebook-adapter:[6.18.0.1]/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:fyber-adapter:8.3.3.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:inmobi-adapter:10.8.0.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:inmobi-adapter:10.8.0.0/com.inmobi.monetization:inmobi-ads-kotlin:10.8.0/com.google.android.gms:play-services-appset:16.0.2
- com.applovin.mediation:mintegral-adapter:16.8.81.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin.mediation:smaato-adapter:22.7.1.1/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0
- com.applovin:applovin-sdk:13.0.1/com.google.android.gms:play-services-appset:16.0.0
- com.google.android.gms:play-services-ads:23.0.0/com.google.android.gms:play-services-appset:16.0.1
- com.google.android.gms:play-services-appset:16.0.2
com.google.android.gms:play-services-base conflicting due to package(s):
- com.android.billingclient:billing:6.2.1/com.google.android.gms:play-services-base:18.3.0
- com.android.billingclient:billing:6.2.1/com.google.android.gms:play-services-location:19.0.0/com.google.android.gms:play-services-base:18.0.0
- com.applovin.mediation:bytedance-adapter:6.3.0.4.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0/com.google.android.gms:play-services-base:18.0.1
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.applovin:applovin-sdk:[13.0.0,+]/com.google.android.gms:play-services-appset:16.0.0/com.google.android.gms:play-services-base:18.0.1
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.chartboost:chartboost-sdk:9.8.1/com.google.android.gms:play-services-appset:16.0.2/com.google.android.gms:play-services-base:18.0.1
- com.applovin.mediation:chartboost-adapter:9.8.1.0/com.chartboost:chartboost-sdk:9.8.1/com.google.android.gms:play-services-auth:20.7.0/c<message truncated>

**Comment by alvarshahanji** [comment]
Could you try Assets > External Dependency Manager > Android Resolver > Force Resolve and then rebuild the project?
