### ISSUE TITLE
Signal 5 (SIGTRAP) 

### ISSUE THREAD

**Issue by hoangthph09747** [AppLovin/AppLovin-MAX-Unity-Plugin#455]
### MAX Plugin Version

8.0.1

### Unity Version

2022.3.20

### Device/Platform Info

Android

### Current Behavior

Before watching rewarded ads sometimes
After watching rewarded ads

### Expected Behavior

Not crashing the game

### How to Reproduce

Add Applovin interstitial, rewarded
Try to watch rewarded or show inter

### Reproducible in the demo app?

No

### Additional Info

[Bug.txt](https://github.com/user-attachments/files/17957818/Bug.txt)

**Comment by applovinAsh** [comment]
@hoangthph09747, Can you provide the following information:
1. How often this is happening? 
2. The percentage of users it is affecting
3.  Devices affected 
4. SDK versions 

If you could also provide the full, unfiltered verbose logs from the start of a session, that would be helpful. To enable verbose logs, please see here: https://developers.applovin.com/en/max/faq/how-to-enable-verbose-logging-in-the-applovin-sdk.

**Comment by hoangthph09747** [comment]
I think problem callback after watching rewarded ads.Somehow they have a problem .So I push them in mainthread.Then Crash rate decreased
Code for anyone similar problems



using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using System.Threading.Tasks;

public class UnityMainThreadDispatcher : MonoBehaviour
{

    private static readonly Queue<Action> _executionQueue = new Queue<Action>();
    public static UnityMainThreadDispatcher Instance { get; private set; }

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }
    }

    public void Update()
    {
        lock (_executionQueue)
        {
            while (_executionQueue.Count > 0)
            {
                _executionQueue.Dequeue().Invoke();
            }
        }
    }

    public void Enqueue(Action action)
    {
       // Debug.Log("UnityMainThreadDispatcher "+action);
        lock (_executionQueue)
        {
            _executionQueue.Enqueue(action);
        }
    }

    public Task EnqueueAsync(Action action)
    {
        var tcs = new TaskCompletionSource<bool>();

        void WrappedAction()
        {
            try
            {
                action();
                tcs.SetResult(true);
            }
            catch (Exception ex)
            {
                tcs.SetException(ex);
            }
        }

        lock (_executionQueue)
        {
            _executionQueue.Enqueue(WrappedAction);
        }

        return tcs.Task;
    }
}
