### ISSUE TITLE
iOS crash Il2CppExceptionWrapper

### ISSUE THREAD

**Issue by lastdan** [AppLovin/AppLovin-MAX-Unity-Plugin#459]
### MAX Plugin Version

6.6.3

### Unity Version

6000.0.30

### Device/Platform Info

iOS 186-18

### Crashes/ANRs per Day

150

### Percentage of Users Affected

1

### First Occurrence of Crash/ANR

don't know

### Exception and Stack Trace

Fatal Exception: Il2CppExceptionWrapper

com.apple.main-thread
0  UnityFramework                 0x39b803c type metadata accessor for PrivacyStateStorage + 959424
1  UnityFramework                 0x39db1d8 specialized UnityAdsServiceProvider.init(skdSettingsStorage:timeReader:telephonyProvider:sendSDKInitializerMetrics:) + 1103196
2  UnityFramework                 0x39d5a58 ServiceProviderObjCBridge.init(_:) + 1080796
3  UnityFramework                 0x39d61f0 @objc ServiceProviderObjCBridge.init(_:) + 1082740
4  CoreFoundation                 0x2fe24 __invoking___ + 148
5  CoreFoundation                 0x2ee6c -[NSInvocation invoke] + 428
6  UnityFramework                 0x3869d4c +[NSInvocation(Category) uads_invokeWithReturnedUsingMethod:classType:target:args:] + 192
7  UnityFramework                 0x3897a94 +[UADSProxyReflection getInstanceUsingMethod:classMethod:args:] + 1808
8  UnityFramework                 0x389b430 +[UADSServiceProviderProxy newWithDeviceInfoProvider:] + 16556
9  UnityFramework                 0x3899d70 -[UADSServiceProvider init] + 10732
10 UnityFramework                 0x389b358 -[UADSServiceProviderContainer init] + 16340
11 UnityFramework                 0x389b300 __46+[UADSServiceProviderContainer sharedInstance]_block_invoke + 16252
12 libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
13 libdispatch.dylib              0x57f4 _dispatch_once_callout + 32
14 UnityFramework                 0x389b2ec +[UADSServiceProviderContainer sharedInstance] + 16232
15 UnityFramework                 0x38ce16c +[UnityServices serviceProvider] + 1264
16 UnityFramework                 0x38ce398 +[UnityServices setDebugMode:] + 1820
17 UnityFramework                 0x3376cf4 -[ALUnityAdsMediationAdapter initializeWithParameters:completionHandler:] + 4474678516
18 AppLovinSDK                    0x172074 __93-[ALMediationAdapterWrapper initializeWithAdapterInitializationParameters:completionHandler:]_block_invoke + 144
19 AppLovinSDK                    0x175064 __67-[ALMediationAdapterWrapper runOperationWithTag:forAdFormat:block:]_block_invoke + 152
20 Foundation                     0x5b70c __NSINDEXSET_IS_CALLING_OUT_TO_A_BOOL_BLOCK__ + 24
21 Foundation                     0x4af68 -[NSBlockOperation main] + 104
22 Foundation                     0x4ae88 __NSOPERATION_IS_INVOKING_MAIN__ + 16
23 Foundation                     0x492e0 -[NSOperation start] + 648
24 Foundation                     0x80750 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
25 Foundation                     0x80380 __NSOQSchedule_f + 172
26 libdispatch.dylib              0x13394 _dispatch_block_async_invoke2 + 148
27 libdispatch.dylib              0x3fa8 _dispatch_client_callout + 20
28 libdispatch.dylib              0x12a34 _dispatch_main_queue_drain + 984
29 libdispatch.dylib              0x1264c _dispatch_main_queue_callback_4CF + 44
30 CoreFoundation                 0x79bbc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
31 CoreFoundation                 0x761b0 __CFRunLoopRun + 1996
32 CoreFoundation                 0xc8274 CFRunLoopRunSpecific + 588
33 GraphicsServices               0x14c0 GSEventRunModal + 164
34 UIKitCore                      0x3ee77c -[UIApplication _run] + 816
35 UIKitCore                      0x14e64 UIApplicationMain + 340
36 UnityFramework                 0x3339630 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 102 (main.mm:102)

### How to Reproduce

no repro

### Reproducible in the demo app?

Not Tested

### Additional Info

mediated networks: facebook, GoogleAdMob, ironSource, liftoff monetize, unityads

**Comment by applovinAsh** [comment]
This looks to be coming from the UnityAds SDK. Please report the issue to Unity.
