### ISSUE TITLE
High percentage of ANR errors

### ISSUE THREAD

**Issue by maniaks1** [AppLovin/AppLovin-MAX-Unity-Plugin#46]
Greetings.
After switching to the Max SDK, the ANR error rate has significantly increased in our application.

Unity version: 2018.4.16
Max SDK version: 2.4.16

Integrated ad networks:
UnityAds: iOS 3.4.6.5 / Android 3.4.6.3
Facebook Audience Network: iOS 5.10.1.0 / Android 5.11.0.0
AdMob: iOS 7.62.0.4 / Android 19.3.0.0
AdColony: iOS 4.1.5.4 / Android 4.2.2
Applovin: iOS 6.13.1 / Android 9.13.1

![overview](https://user-images.githubusercontent.com/30645175/90028515-6f762000-dcc2-11ea-9478-56a658ac3d24.png)

-- ANR 1
![anr1](https://user-images.githubusercontent.com/30645175/90028560-7dc43c00-dcc2-11ea-9ec0-8d67c105e1be.png)

-- ANR 2
![anr2](https://user-images.githubusercontent.com/30645175/90028569-80269600-dcc2-11ea-8704-43ab1cfab2b3.png)

-- ANR 3
![anr3](https://user-images.githubusercontent.com/30645175/90028571-80bf2c80-dcc2-11ea-94e5-f77ed37054bf.png)

-- ANR 4
![anr4](https://user-images.githubusercontent.com/30645175/90028572-8157c300-dcc2-11ea-82ab-bd02dc592755.png)

-- ANR 5
![anr5](https://user-images.githubusercontent.com/30645175/90028576-81f05980-dcc2-11ea-826a-2aa4025c23c6.png)

* The graphs show an increase in the percentage of ANR with these errors after the release of the client. Before that, there were no errors (the fact that on the charts before July 15th most likely beta testing) or their number was not significant.

I attach the error stacktraces below. There are other errors that contributed to the increase in the ANR percentage, but they are less noticeable.
[anr1.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5063597/anr1.txt)
[anr2.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5063598/anr2.txt)
[anr3.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5063599/anr3.txt)
[anr4.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5063600/anr4.txt)
[anr5.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5063601/anr5.txt)

**Comment by Lorenzo45** [comment]
Hey @maniaks1, thanks for all the detailed reports!

These are all OS-level issues that are largely out of our control and some ANRs are to be expected when loading and displaying ads from 5 ad networks in your app. Would you be able to share what you were using before MAX for comparison?

The first ANR is happening during the SCREEN_OFF intent broadcast which means the device has been put to sleep and won't affect the in-game experience. The other ANRs are happening on Android OS versions from 5+ years ago so they are likely older devices that are more prone to performance issues.

That being said, we're always looking for ways to reduce ANRs and hopefully we can improve this over time with more research and development.

Hope this helps, let me know if you have any other questions or concerns!

**Comment by maniaks1** [comment]
Before MaxSDK, we used IronSource with the same set of adapters (UnityAds, Facebook Audience Network, AdMob, AdColony).

**Comment by thomasmso** [comment]
Hi @maniaks1 - We pushed out ANR fixes over the weekend. Please make sure that you're on our latest Unity Plugin v4.2.1 which bundles our Android SDK 10.2.1 and they should be gone.
