### ISSUE TITLE
PackageManagerResolver threw an exception after upgrade to 3.0.1

### ISSUE THREAD

**Issue by ha-quang-vu** [AppLovin/AppLovin-MAX-Unity-Plugin#48]
Hi,

After upgrade to 3.0.1 my project having a ton of errors like

> System.TypeInitializationException: The type initializer for 'Google.PackageManagerResolver' threw an exception. ---> System.MissingMethodException: void Google.EditorMeasurement.set_DataUsageUrl(string)
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Google.PackageMigrator..cctor () [0x00000] in Z:\tmp\tmp.htfnx8Kcq8\third_party\unity\unity_jar_resolver\source\PackageManagerResolver\src\PackageMigrator.cs:597 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:118)

> System.MissingMethodException: void Google.EditorMeasurement.set_DataUsageUrl(string)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:118)

> MissingMethodException: void Google.EditorMeasurement.set_DataUsageUrl(string)
Rethrow as TypeInitializationException: The type initializer for 'Google.PackageManagerResolver' threw an exception.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Activator.CreateInstance (System.Type type) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.AssetPostprocessingInternal.GetMeshProcessorsHashString () (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:354)
UnityEditor.AssetPostprocessingInternal:GetMeshProcessorsHashString() (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:381)

I tried to "Delete Resolved Libraries" or "Force Resolve" but It seem not working.

**Environment**
Unity 2019.5.15f1
Installing SDK: Unity Firebase SDK, Adjust SDK ...
Android

**Comment by santoshbagadi** [comment]
Hi @ha-quang-vu , sorry for the delayed response. It seems like the Google External Dependency Manager installation may have been corrupted. Please try the solution suggested [here](https://github.com/firebase/quickstart-unity/issues/622#issuecomment-607020512), if you are still facing the issue:

> Seems like `Firebase.Editor.dll` cannot find `Google.EditorMeasurement`, which is a new class in the new version of External Dependency Manager (EDM), which was renamed from Play Services Resolver.
>
> If you are unable to build, here is what you can do:
>
> 1. Find the folders named `ExternalDependencyManager` and `PlayServicesResolver` under your Assets folder. Remove them.
> 2. Download the latest [EDM](https://github.com/googlesamples/unity-jar-resolver/raw/master/external-dependency-manager-latest.unitypackage) and import it.
> 3. Wait a bit
> i. If you are building for Android, when you switch platform to Android, you should see AndroidResolver window kick-in. If not, check your settings under `Assets > External Dependency Manager > Android Resolver > Settings` and see if `Enable Auto-Resolution` is on. Or you can force resolution using `Assets > External Dependency Manager > Android Resolver > Force Resolve`
> ii. If you are building for iOS, make sure that iOS Resolver is enabled by checking settings under `Assets > External Dependency Manager > iOS Resolver > Setting`. `Podfile Generation` should be checked.
