### ISSUE TITLE
Can't close interstitial ad

### ISSUE THREAD

**Issue by desouse** [AppLovin/AppLovin-MAX-Unity-Plugin#49]
The ad doesn't allow me to close it.
Log:
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Format: INTER
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Ad Id: 20379349167774732
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Zone Id: inter_regular
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Source: DECODED_AD_TOKEN_JSON
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Ad Class: AdServerAd
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    DSP Name: liftoff.io
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    ========================================
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Fullscreen Ad Properties
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    Target: DEFAULT
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    close_style: INVISIBLE
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    close_delay_graphic: 10000s
08-18 16:22:32.439    17406    17406    D    AppLovinSdk    ========================================

close_delay_graphic: 10000s - looks like I have to wait for almost 3 hours to close it.
[adsBug.zip](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/5094441/adsBug.zip)

**Comment by thomasmso** [comment]
Hi @desouse - Do you mind sending us our full SDK logs so we can inspect other properties of the ad?

**Comment by alvarshahanji** [comment]
Hi @desouse, thank you for reporting this issue. We have resolved the issue.
