### ISSUE TITLE
Android reward ads OnRewardedAdHiddenEvent and OnRewardedAdReceivedRewardEvent not executed

### ISSUE THREAD

**Issue by dongltRabiloo** [AppLovin/AppLovin-MAX-Unity-Plugin#50]
I'm implementing MAX sdk to my game and having troubles with reward ads.
The ads working fine on iOs but in Android, declared onHidden and onRecevied event never being call.

Im using:
 - Unity: 2019.4.1f1
 - Applovin unity MAX sdk: 3.0.2

Here's some sample code https://drive.google.com/file/d/1TSnLyAvcOze8QIYjV1YRQL4rRt9kJPBR

The scenario is some event trigger (click button load in above code) and user can choose to watch reward ad or not.
After 10 sec or player cancel, the dialog will disapear and everything back to normal
If the player watch ads then call MAX sdk to show and wait for sdk callback event (which never does on android)

Does it right to use sdk like in sample code, or any thing i have done wrong? It work fine in iOs.

**Comment by thomasmso** [comment]
Hi, did you try using [test ads](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) for testing? `OnRewardedAdReceivedRewardEvent` may not be called if using test ads or if closing ads early.

**Comment by dongltRabiloo** [comment]
no i'm not enable test mode, not just OnRewardedAdReceivedRewardEvent, the OnRewardedAdHiddenEvent also not being called.

**Comment by thomasmso** [comment]
Do you mind sending our SDK's [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) over to devsupport@applovin.com?

**Comment by dongltRabiloo** [comment]
sorry, we mess up our ad unit id. Loading reward with `InterstitialAdUnitId` causing it to show like an reward video but callback to the `OnInterstitialDismissedEvent` instead.
Thanks for the support!!
