### ISSUE TITLE
Can not build for iOS

### ISSUE THREAD

**Issue by ikitae** [AppLovin/AppLovin-MAX-Unity-Plugin#52]
Unity plugin : 3.0.2
iOS SDK : 6.13.5 
------------------------------
MAUnityAdManager.m : 143
Property 'appTrackingTransparencyStatus' not found on object of type 'ALSdkConfiguration *'

**Comment by thomasmso** [comment]
Hi @ikitae, thanks for reporting this. We'll work to fix your issue right now.

**Comment by thomasmso** [comment]
Hi @ikitae, could you manually download and import the Unity Plugin [here](https://bintray.com/applovin/Unity/download_file?file_path=AppLovin-MAX-Unity-Plugin-3.0.2-Android-9.13.5-iOS-6.13.5.unitypackage)? Thanks!

**Comment by ikitae** [comment]
Thank you @thomasmso, but it doesn't work.

Assets/MaxSdk/Scripts/Editor/MaxPostProcessBuildiOS.cs(24,64): error CS1061: 'AppLovinSettings' does not contain a definition for 'ConsentFlowEnabled' and no accessible extension method 'ConsentFlowEnabled' accepting a first argument of type 'AppLovinSettings' could be found (are you missing a using directive or an assembly reference?)

**Comment by thomasmso** [comment]
Could you delete `MaxSdk/Scripts/Editor/MaxPostProcessBuildiOS.cs` and its `.meta` file and try again?

**Comment by ikitae** [comment]
@thomasmso Its work correctly. Thank you for your quick support.
