### ISSUE TITLE
Incomplete integration of non-existing adapter (Android)

### ISSUE THREAD

**Issue by maxshayne** [AppLovin/AppLovin-MAX-Unity-Plugin#54]
Hi.

We using Max Plugin Unity version 3.1.2 and Android version 9.14.1 with several mediation adapters.

![1](https://user-images.githubusercontent.com/16781629/93475286-a1fae480-f922-11ea-9b71-22dc3c9b3c0e.jpg)

This message appears on application start with builded debug APK (we don't know yet, if it's exists in release version).
And mediation debugger shows that Fyber Integration is incomplete.

![3](https://user-images.githubusercontent.com/16781629/93477735-952bc000-f925-11ea-8cf0-119e616a05f0.jpg) ![4](https://user-images.githubusercontent.com/16781629/93477746-978e1a00-f925-11ea-9af9-d4934f79ff70.jpg)

But we don't have Fyber adapter in our project, so this might be a bug of sdk initialization, or we might miss some install steps or smth.

Any suggestions would be useful

**Comment by thomasmso** [comment]
Could you run Gradle's `androidDependencies` task to see if one of your other dependencies may have been inadvertedly pulling down their SDK? We're checking against the `com.fyber.inneractive.sdk.external.InneractiveAdManager` class so you can also press Shift two times and enter that class name to see that it does exist in your workspace.
