### ISSUE TITLE
Failed to set up AppLovinQualityService [Unity, iOS, plugin v.3.1.2]

### ISSUE THREAD

**Issue by ivfurt** [AppLovin/AppLovin-MAX-Unity-Plugin#55]
Hi!
After building a project for iOS, this error appears in the console:
```
Failed to set up AppLovin Quality Service for your project with error: 
invalid date
AppLovinQualityService setup FAILED


UnityEngine.Debug:LogError(Object)
AppLovinPostProcessiOS:OnPostProcessBuild(BuildTarget, String) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessiOS.cs:100)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
```

The checkbox for "Enable MAX Ad Review" is enabled in the Integration manager. The Applovin SDK KEY entered is correct and is equal to the key from https://dash.applovin.com/o/account#keys.
What can be wrong?

Thanks!

**Comment by thomasmso** [comment]
Hi @ivfurt - Do you mind sending this inquiry to devsupport@applovin.com and attach the Unity console logs during your build? The team can better assist you there.
