### ISSUE TITLE
MREC can't play video

### ISSUE THREAD

**Issue by ikitae** [AppLovin/AppLovin-MAX-Unity-Plugin#56]
Hi, 
MREC native can not play video ads. 
And we want change font color. 

MAX Unity plugin : 3.1.3
MAX Android sdk : 9.14.3
Mediated Network : Admob native

-- Log --
W/TextureView: A TextureView or a subclass can only be used with hardware acceleration enabled.

![mrec_video](https://user-images.githubusercontent.com/1313942/93978204-9beb8480-fdb6-11ea-86a0-151327dea9f7.jpeg)

**Comment by thomasmso** [comment]
Hi @ikitae - Could you reach out to your account manager first? He will be able to direct you to our solutions engineering team specifically for MAX.
