### ISSUE TITLE
Android build. Using proguard

### ISSUE THREAD

**Issue by YuliyF** [AppLovin/AppLovin-MAX-Unity-Plugin#59]
In case i used the poguard function in Unity which libraries does I have to add in proguard-user file for an Applovin? I have such mediated as: AdColony, Chartboost, Facebook, AdMobe, HyprMX, InMobi, ironSource, MyTarget, Tapjoy and Vungle

**Comment by santoshbagadi** [comment]
@YuliyF you don't need to add any ProGuard rules to the `proguard-user` file for AL MAX SDKs or adapters. Our SDK and adapters package the necessary rules in the `.aar`.

Please let us know if you face any issues after enabling ProGuard.

**Comment by gagbaghdas** [comment]
Hello. I have issues. No any callback is being called after enabling ProGuard. @santoshbagadi

**Comment by santoshbagadi** [comment]
@gagbaghdas do you mind sharing your ProGuard rules file and a sample project (or an APK if possible) where the issue is reproducible to santosh.bagadi@applovin.com
