### ISSUE TITLE
Input dispatching timeout () com.applovin.adview.ApplovinFullScreenActivity

### ISSUE THREAD

**Issue by AbdulRehmanUnity** [AppLovin/AppLovin-MAX-Unity-Plugin#60]
Input dispatching timeout () com.applovin.adview.ApplovinFullScreenActivity cause ANR or crashes.
<img width="1143" alt="Screenshot 2021-05-17 at 6 02 35 PM" src="https://user-images.githubusercontent.com/62423838/118493805-f0bf7f00-b73a-11eb-98fb-e89870e1558d.png">

**Comment by thomasmso** [comment]
Hi @AbdulRehmanUnity - we should have a fix enabled from the backend sometime this week.

**Comment by Junaid2K** [comment]
Hey @thomasmso, any update on this? Still happening mate.

**Comment by thomasmso** [comment]
Hey @AbdulRehmanUnity / @Junaid2K - as long as you're on our latest Unity Plugin v4.2.1, the ANRs will be fixed as we've pushed some fixes over the weekend.
