### ISSUE TITLE
Unity errors: code:1002 , code:1008. How to fix them?

### ISSUE THREAD

**Issue by vailshnast** [AppLovin/AppLovin-MAX-Unity-Plugin#61]
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk [AppLovinSdk] 
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk **************************************************
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk NO FILL received:
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk ..ID: ""
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk ..FORMAT: "REWARDED"
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk ..SDK KEY: ""
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk ..PACKAGE NAME: "com.AppLovin.MaxDemoUnity"
2021.05.30 21:16:26.665 30468 30562 Error AppLovinSdk ..Reason: [{"code":1002,"msg":"App info must include app ID"},{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]

**Comment by thomasmso** [comment]
Please double-check that your app is defined in our dashboard, and that you are using the correct Ad Unit ID and SDK key combination for your app.

**Comment by muhamaad-ali-grocerkey** [comment]
I am facing same issue. I have double checked everything. Actually my colleague double checked too but issue still persists.

**Comment by richashukla23** [comment]
@vailshnast  @muhamaad-ali-grocerkey Thanks for the update. 

Can you please share with use [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) as well as the email associated with your AppLovin account?

**Comment by muhamaad-ali-grocerkey** [comment]
How would I get verbose logs? I don’t know how

Email assosiated is ***@***.*** ***@***.***>

I have already opened a thread using my original email: ***@***.*** ***@***.***> with request number 7954

There is a video attached to that thread as well

**Comment by muhamaad-ali-grocerkey** [comment]
Hi @richashukla23 email associated with account is nooralibutt@gmail.com

Let me run the app again share logs with you.

**Comment by richashukla23** [comment]
@muhamaad-ali-grocerkey Thanks for sharing the logs and the account email.

Looking at the logs I see ad unit 43c97a7ad7422a29 getting no fill as account associated with nooralibutt@gmail.com is not having this ad unit set up currently.

So, you will have to make sure the dashboard --> MAX --> Manage --> Ad Units section has this ad unit added and associated with hello.scary.stranger.neighbor.home.

Please try that and let me know if that fixes your issue.

**Comment by muhamaad-ali-grocerkey** [comment]
@richashukla23 That is another issue, my AppLovin Dashboard Ad-Unit section has been crashed. I have been complaining about this for couple of days and no one is fixing it. I even sent them a video of crash.


https://user-images.githubusercontent.com/85221118/122503391-c569d180-d011-11eb-823c-9c2da134b374.mp4

I am attaching crash video as well for your reference.

As far as ad units are concerned, believe me I have triple checked everything. I checked package ID which is same as adunit id, I have checked ad unit id. I am even receiving TestAds successfully but I don't get ads on any other device. I think there is something wrong with Ad Unit ID or something

Logs are saying one thing and I think issue is something else.

**Comment by thomasmso** [comment]
@muhamaad-ali-grocerkey - Where did you send your email to? And what was the title of the email? Also, we'll continue investigating.

**Comment by muhamaad-ali-grocerkey** [comment]
Here is the screenshot of Email conversation:

<img width="1078" alt="Screenshot 2021-06-18 at 9 26 04 AM" src="https://user-images.githubusercontent.com/85221118/122506206-47a8c480-d017-11eb-8a2f-fcc0cd222c98.png">

**Comment by alvarshahanji** [comment]
This is the ticket @muhamaad-ali-grocerkey is referring to : https://applovin.zendesk.com/agent/tickets/7954

The asana for UI team can be found in the ticket as well.

**Comment by muhamaad-ali-grocerkey** [comment]
@alvarshahanji any update on bug fix??? We are waiting for you guys to fix the bug so we could integrate AppLovin and update our app.

**Comment by richashukla23** [comment]
@muhamaad-ali-grocerkey Thanks for following up. The fix is in progress. I will update you as soon as its done.

**Comment by richashukla23** [comment]
@muhamaad-ali-grocerkey I wanted to let you know that the issue with your ad unit page has been fixed. Can you please try at your end and also try creating the ad units we recommended in previous messages.

**Comment by muhamaad-ali-grocerkey** [comment]
@richashukla23 how can I delete ad Units? I guess someone from AppLovin team added ad units for testing purposes and forgot to delete them

**Comment by richashukla23** [comment]
There is no way to delete ad units but you can pause it and it will be hidden by default.
To pause it, hover over the green circle under Status and click the pause button that appears.

**Comment by chuongdp** [comment]
@richashukla23 Hi, I am already associated my ad banner unit (75ba4fbc346380e7) with iOS platform's bundle id, but I still meet "NO FILL received" include code 1002 and 1008 also. Please let me know how to fix this, thanks!
p/s: All Android ad units work fine!

**Comment by richashukla23** [comment]
Can you please share with us verbose logs
<https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK->
and
also confirm the email associated with your AppLovin account? Do rewarded
and interstitial ads look good on iOS?

**Comment by chuongdp** [comment]
@richashukla23 Those ad unit id is belong to another my Applovin account.
All banner, interstitial and reward ads return code 1002, 1008 in return data and error code 204.
All of my unit ads are associated with my app's bundle id.
I found the solution in here: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/65#issuecomment-860838055

**Comment by richashukla23** [comment]
@chuongdp Thanks for confirming the resolution of your issue. If you still have any other questions, feel free to reach out.
