### ISSUE TITLE
Meta files have platform-specific path characters

### ISSUE THREAD

**Issue by Ferbdi** [AppLovin/AppLovin-MAX-Unity-Plugin#63]
Unity 2018.4.32.f1. Meta files contain slash symbols (for Windows developers). But for me as a Mac user, slash is reversed. These files are displayed as changes in git. Here are some examples:
<img width="641" alt="Снимок экрана 2021-06-09 в 18 00 17" src="https://user-images.githubusercontent.com/38311240/121350476-90dc8280-c94c-11eb-84c6-a706062d5605.png">
<img width="377" alt="Снимок экрана 2021-06-09 в 18 00 39" src="https://user-images.githubusercontent.com/38311240/121350517-9b971780-c94c-11eb-8efb-d3c004f6e636.png">
<img width="726" alt="Снимок экрана 2021-06-09 в 18 01 05" src="https://user-images.githubusercontent.com/38311240/121350571-abaef700-c94c-11eb-8ac2-3bf50bff429b.png">

**Comment by santoshbagadi** [comment]
Hi @Ferbdi , our plugin auto-generates these labels with the the platform specific path. Having both labels shouldn't cause any issues and you can safely commit those changes to your VCS.

Please let us know if you see any errors/issues with using our Integration Manager.

**Comment by yasirkula** [comment]
@santoshbagadi Can you use '/' path separator on all platforms? Changing [this line](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/bad1684b8a9f4ae4ca42c24cbddb51a546bffe8c/DemoApp/Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinIntegrationManager.cs#L643) as follows will do that:

`var exportPathLabel = "al_max_export_path-" + assetPath.Replace(pluginParentDir, "").Replace('\\', '/');`

You'll also need to replace [this line](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/bad1684b8a9f4ae4ca42c24cbddb51a546bffe8c/DemoApp/Assets/MaxSdk/Scripts/MaxSdkUtils.cs#L368) as follows:

`var assetGuids = AssetDatabase.FindAssets("l:al_max_export_path-" + exportPath.Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar));`

This'll resolve a lot of headache for us and possibly other users who use both Windows and Mac.

**Comment by santoshbagadi** [comment]
Hi @yasirkula , we do have plans to do this as well. We just want to make sure we don't break backwards compatibility. We'll update here when we change to using the new path labels.

**Comment by santoshbagadi** [comment]
We have just released a fix for this issue in [v5.5.3](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_5_3) of our plugin.
