### ISSUE TITLE
After upgrade from 10.2.1 Building the app with firebase fails.

### ISSUE THREAD

**Issue by mStratSatoshi** [AppLovin/AppLovin-MAX-Unity-Plugin#66]
Hello,
We are experiencing the following issue using Unity 2020.3.12 and firebase 8.0.0. We also encountered the same using Unity 2020.3.4 and firebase 7.1.0.

We have been using the plugin alongside with firebase for quite some time with no problem. But after the 10.2.1 version we get the following exception when we try to build for Android.
 
Note: C:\************************\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzb found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzc found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzd found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zze found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzf found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzh found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzm found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzo found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzp found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzq found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzr found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzs found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and jetified-com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  
  Go to the documentation to learn how to Fix dependency resolution errors.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Any help would be greatly appreciated

**Comment by mStratSatoshi** [comment]
Never mind, This seems to be related entirely to firebase. Sorry for that.

**Comment by jacattrongnlh** [comment]
@mStratSatoshi  I ran into this issue, how did you fix it?

**Comment by AsifNaeem1** [comment]
Ran into in same issue. Any solution?
