### ISSUE TITLE
Out Of Memory Issuse

### ISSUE THREAD

**Issue by thejovialman** [AppLovin/AppLovin-MAX-Unity-Plugin#69]
Hi Dev Teams,

We recently using MAX Mediation (ver 4.3.1 for Unity) instead of IronSource, And We meet a lot of crash and ANR issues (ThrowOutOfMemoryError),  Please fix this error soon.  Thank you

 Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2019.4.8f1 (60781d942082)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'HUAWEI/RNE-L22/HWRNE:7.0/HUAWEIRNE-L22/C636B110:user/release-keys'
    Revision: '0'
    ABI: 'arm64'
    Timestamp: 2021-07-02 14:33:14+0700
    pid: 26119, tid: 26197, name: UnityMain  >>> com.smash.superr.bros.world <<<
    uid: 10540
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
        x0  0000000000000000  x1  0000000000006655  x2  0000000000000006  x3  0000000000000008
        x4  0000000000000193  x5  0000007a73477170  x6  347047737a000000  x7  0000007a73477034
        x8  0000000000000083  x9  ffffffffffffffdf  x10 0000000000000000  x11 0000000000000001
        x12 ffffffffffffffff  x13 0000000000000001  x14 0000000000000000  x15 0000000000000000
        x16 0000007a734b9ec8  x17 0000007a73462ce8  x18 00000000eec0c74c  x19 0000007a41eaf4f8
        x20 0000000000000006  x21 0000007a41eaf450  x22 000000000000000b  x23 0000000000000244
        x24 ffffffffffffffff  x25 0000007a6f834770  x26 0000007a6f7be438  x27 0000007a41eadd51
        x28 0000007a6f78448b  x29 0000007a41eadc80
        sp  0000007a41eadc60  lr  0000007a73460190  pc  0000007a73462cf0
    
    backtrace:
          #00 pc 000000000006bcf0  /system/lib64/libc.so (tgkill+8) (BuildId: 194b1177ee6e437e953b2519dca16c58)
          #01 pc 000000000006918c  /system/lib64/libc.so (pthread_kill+64) (BuildId: 194b1177ee6e437e953b2519dca16c58)
          #02 pc 0000000000023e68  /system/lib64/libc.so (raise+24) (BuildId: 194b1177ee6e437e953b2519dca16c58)
          #03 pc 000000000001c8ec  /system/lib64/libc.so (abort+52) (BuildId: 194b1177ee6e437e953b2519dca16c58)
          #04 pc 000000000042e5f8  /system/lib64/libart.so (art::Runtime::PreZygoteFork()) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #05 pc 00000000000e5424  /system/lib64/libart.so (art::LogMessage::LogLine(char const*, unsigned int, art::LogSeverity, char const*)) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #06 pc 0000000000451df8  /system/lib64/libart.so (art::Thread::AssertNoPendingExceptionForNewException(char const*) const+908) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #07 pc 000000000044a8d8  /system/lib64/libart.so (art::Thread::ThrowOutOfMemoryError(char const*)+336) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #08 pc 000000000034d468  /system/lib64/libart.so (art::JNI::EnsureLocalCapacityInternal(art::ScopedObjectAccess&, int, char const*)+260) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #09 pc 0000000000327a20  /system/lib64/libart.so (art::JNI::PushLocalFrame(_JNIEnv*, int)+584) (BuildId: 2b1b71da1992a9f589e264b00e3fa2ee)
          #10 pc 0000000001072d10  /data/app/com.smash.superr.bros.world-2/lib/arm64/libunity.so (BuildId: 4acdef76d5b595b2c83a0beee0711ab58a148228)
    
        at libc.tgkill(tgkill:8)
        at libc.pthread_kill(pthread_kill:64)
        at libc.raise(raise:24)
        at libc.abort(abort:52)
        at libart.art::Runtime::PreZygoteFork()(PreZygoteFork:0)
        at libart.art::LogMessage::LogLine(char const*, unsigned int, art::LogSeverity, char const*)(LogLine:0)
        at libart.art::Thread::AssertNoPendingExceptionForNewException(char const*) const(AssertNoPendingExceptionForNewException:908)
        at libart.art::Thread::ThrowOutOfMemoryError(char const*)(ThrowOutOfMemoryError:336)
        at libart.art::JNI::EnsureLocalCapacityInternal(art::ScopedObjectAccess&, int, char const*)(EnsureLocalCapacityInternal:260)
        at libart.art::JNI::PushLocalFrame(_JNIEnv*, int)(PushLocalFrame:584)
        at libunity.0x1072d10(Native Method)

**Comment by thomasmso** [comment]
@thejovialman - What ad formats are you running in your app?

**Comment by thejovialman** [comment]
We use Inter Ad and Reward Ad

**Comment by thejovialman** [comment]
I ask many colleges of other project, They also get very very high crash and ANR rate. It's affect a lot to our game organic install. This is an urgent and serious error. Hope team fix it soon.

**Comment by thomasmso** [comment]
What is the top crash(es)/ANR(s) you're experiencing? And how often?

**Comment by thomasmso** [comment]
Also, what date did the ANRs begin to increase?
