### ISSUE TITLE
Vertical ad for Portrait game runs in Landscape mode.

### ISSUE THREAD

**Issue by Deroido** [AppLovin/AppLovin-MAX-Unity-Plugin#72]
Hello. I've been a long MAX user. 'Rewarded videos' mostly work flawless.
But recently I've integrated 'Interstitials' and immediately got an issue.

Unity game is in Portrait mode only. The interstitial ad itself is also vertical. But to show it the screen rotates to landscape. It's almost 100% persistent.

Is this common? Using the latest MAX and mediators versions.

![image](https://user-images.githubusercontent.com/201954/127616953-4cc4e530-bce2-4fe3-9608-727252f430e4.png)

Wrong oriented ads are from Applovin themselves. 

![image](https://user-images.githubusercontent.com/201954/127617448-ac28e889-9ffc-44e2-ba2d-e9a087351d32.png)

**Comment by thomasmso** [comment]
Hi,

Is your app with this behaviour live where we can test? If not, please provide our SDK's [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK) so we can look further.

**Comment by Deroido** [comment]
In production we have only Rewarded Ads version.
Interstitial one exists in 'apk' mode. Can I send it to you directly?

**Comment by thomasmso** [comment]
Thank you for testing it on the few recent versions of our AppLovin MAX SDK. Please feel free to send the APK to thomas.so@applovin.com.

**Comment by Deroido** [comment]
I've sent an email with the build and more explanations. Please confirm.

**Comment by Deroido** [comment]
here's an example of verbose info for an ad that changed screen orientation
It can be seen that 
AppLovinSdk Target: ACTIVITY_PORTRAIT
but the ad still spoils user experience with those rotations.

![image](https://user-images.githubusercontent.com/201954/127739051-63cb34f9-d75c-4881-9efe-c1d9e8bbad77.png)

**Comment by Deroido** [comment]
It happens only on Tablets.
for example Samsung Galaxy Tab.

applovin, inmoby and adcolony are affected.
