### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by eatsports** [AppLovin/AppLovin-MAX-Unity-Plugin#74]
**Versions:
Unity - 2019.4.24
MAX SDK - 4.3.4
MAX iOS - 10.3.4
Mediations enabled - Facebook, IronSource, Unity**

Hello, i cant seem to build the game on iOS
It fails with this error

 In file included from Libraries/MaxSdk/AppLovin/Plugins/iOS/MAUnityPlugin.mm:9:
 Libraries/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.h:7:9: fatal error: 'AppLovinSDK/AppLovinSDK.h' file not found
#import <AppLovinSDK/AppLovinSDK.h>

**Comment by thomasmso** [comment]
You can downgrade to an older version of the FAN adapter (link [here](https://applovin-mobile-artifacts.s3.amazonaws.com/unity/com/applovin/mediation/facebook-adapter/AppLovin-Facebook-Adapters-Android-6.5.0.0-iOS-6.4.1.0.unitypackage)).

This is due to a change Facebook did to the naming of their basics package (FBSDKCoreKit/Basics to FBSDKCoreKit_Basics). The Facebook Audience Network SDK pod right now still references the old version ([see their current podspec here](https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.5.0/FBAudienceNetwork.podspec.json)).

This isn't something we can fix from our side but when Facebook updates their podspec or releases a new version of their SDK that is compatible, we will certify against that.

**Comment by eatsports** [comment]
@thomasmso Hey, thanks, that did fix the cocoapods issue, however the build still fails with the same error:

/Libraries/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.h:7:9: fatal error: 'AppLovinSDK/AppLovinSDK.h' file not found
 #import <AppLovinSDK/AppLovinSDK.h>

**Comment by thomasmso** [comment]
Please update to the External Dependency Manager to minimum version 1.2.164.

Open the iOS Resolver Settings (Assets > External Dependency Manager > iOS Resolver > Settings) and make sure you uncheck Add use_frameworks! to Podfile and Always add the main target to Podfile as in the attached screenshot.

Alternatively, update the Podfile manually as in the Context section above then run pod install --repo-update to make sure the Podfile changes are applied to the project.

**Comment by Syjgin** [comment]
@RogueRocketGames we have the same issue, but I can not understand, how you have fixed it? I already tried to replace FBSDKCoreKit/Basics to FBSDKCoreKit_Basics, but that has no effect

**Comment by santoshbagadi** [comment]
@Syjgin The issue was with opening/using the `Unity-iPhone.xcodeproj` instead of the `Unity-iPhone.xcworkspace` that is generated by External Dependency Manager.

**Comment by ilyichzc** [comment]
> @Syjgin The issue was with opening/using the `Unity-iPhone.xcodeproj` instead of the `Unity-iPhone.xcworkspace` that is generated by External Dependency Manager.

Can u describe more? I tried both variants Unity-iPhone.xcodeproj / Unity-iPhone.xcworkspace, and still dont have success.

**Comment by santoshbagadi** [comment]
Could you share the exact errors you are seeing. Looks like there are multiple issues going on on this thread, so not really sure what the exact issue you are seeing.

**Comment by ilyichzc** [comment]
[35m[33m▸[0m [39;1mCompiling[0m MAUnityPlugin.mm[0m
[ DEBUG    ] [01:34:23]: ▸ [35m[31m❌  [0m/Volumes/Jenkins/workspace/MCN_iOS/McnUnity3d/app_ios/Libraries/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.h:7:9: [31m'AppLovinSDK/AppLovinSDK.h' file not found[0m
[ DEBUG    ] [01:34:23]: ▸ [35m#import <AppLovinSDK/AppLovinSDK.h>[0m
[ DEBUG    ] [01:34:23]: ▸ [35m[36m                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[ DEBUG    ] [01:34:23]: ▸ [35m** ARCHIVE FAILED **[0m

**Comment by santoshbagadi** [comment]
It looks like CocoaPods install failed or it is not pulling the AppLovin SDK. Can you please check that the `pod 'AppLovinSDK'` is in the `Podfile` of the exported project and try to run `pod install --repo-update` on the exported project to make sure the Podfile changes are applied to the project.


If that doesn't work do you mind sending the exported iOS project to santosh.bagadi@applovin.com

**Comment by yohan910800** [comment]
I tried everything mentioned above but I still have the 'AppLovinSDK/AppLovinSDK.h' file not found error.

**Comment by anulagarwal** [comment]
I am having the same issue as @yohan910800. I tried various things - none work

**Comment by yohan910800** [comment]
I finally solved my problem 

-I moved to my build folder
-I uninstalled cocoapod 1.8.4
-I installed brew
-with brew I installed cocoapod
-I deleted the workspace file in my build folder
-I runed install --repo-update
-and finally I built it and it worked !

**Comment by rbyjoswald** [comment]
MAUnityAdManager.h:7:9: 'AppLovinSDK/AppLovinSDK.h' file not found

Unity - 2021.3.19f1
Max SDK - Latest

This build-breaking error just started to pop up 4 days ago. No changes were made to anything related to the Applovin SDK or any of the mediation plugins on our side. We're using Unity Build Automation, and afaik there's no way to trigger cocoapods update ourselves. Tried all the suggestions in this thread to no avail. Updated the Max SDK and all mediation plugins to their latest available versions without success.
We are able to get the builds working again by removing the Facebook Mediation adapter.
Is there a way to make it work in a Cloud Build environment without removing that adapter completely?
