### ISSUE TITLE
Cropped banners on iOS

### ISSUE THREAD

**Issue by Deroido** [AppLovin/AppLovin-MAX-Unity-Plugin#76]
Hello.
Recently we've released Android app with banners. Mostly working fine.

The next is iOS release. and immediately I've noticed broken banners. It's harder to catch good banner than broken one.

code example 
![image](https://user-images.githubusercontent.com/201954/134010552-c5f258de-f188-4813-995f-9155f0982ee8.png)
(yeah I know the last line does nothing. not yet implemented in MAX)

banners look cropped vertically or horizontally. 

![image](https://user-images.githubusercontent.com/201954/134010689-2ce8b2a0-7b06-4087-81a7-e3e6d1d61f50.png)

------
![image](https://user-images.githubusercontent.com/201954/134010716-9aa003b6-aec2-4033-9327-40908bbb06a9.png)
------

expected full screen width there.

using those types 
![image](https://user-images.githubusercontent.com/201954/134010924-2bfd5da0-9f0e-4cb0-b1ba-b44c6adf49fa.png)

please could you suggest anything?

**Comment by thomasmso** [comment]
This was brought to our attention internally by your account manager so closing this.

**Comment by AnuragXansr** [comment]
Any update on this issue

**Comment by thomasmso** [comment]
@AnuragXansr - If you are having issues, please feel free to raise it here: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/new/choose
