### ISSUE TITLE
App crash after build "use_frameworks!"

### ISSUE THREAD

**Issue by tahirduran** [AppLovin/AppLovin-MAX-Unity-Plugin#77]
Hi,
Application crash on the black screen after build.
When I uncheck `Add use_frameworks! to Podfile` and `Always add the main target to Podfile` in iOS Resolver Settings, the problem is solved.

But Facebook SDK doesn't work with these settings. Automatically adds `use_frameworks!` to the Podfile and it doesn't work without this line.

Is there a method to run the AppLovin plugin with `use_frameworks!`?

**Comment by thomasmso** [comment]
Unfortunately not at this moment, this is a byproduct of how different frameworks (Facebook in this case) modifies the generated `Podfile`.

**Comment by tahirduran** [comment]
Thanks for the quick reply.  Is there a method to run AppLovin with Facebook Sdk. I haven't had this problem before.  But now I have the same problem even if I use old versions.

**Comment by Last8Exile** [comment]
Any workaround? I have the same problem.
use_frameworks! forced by Facebook SDK and removing use_frameworks! breaks build. (not found swift libs)
Leaving use_frameworks! makes app crash at start before unity's logo. (it woks fine without AppLovin SDK)

**Comment by tahirduran** [comment]
It can be solved using old version of Facebook SDK. 
I was able to build with Facebook SDK 7.19.2 without this error.

**Comment by santoshbagadi** [comment]
@Last8Exile could you please share the specific versions of Facebook and AppLovin MAX plugins you are using and the build error you are seeing when building without `use_frameworks!`
