### ISSUE TITLE
Handling the case of a lost internet connection

### ISSUE THREAD

**Issue by Heaven31415** [AppLovin/AppLovin-MAX-Unity-Plugin#8]
Hi. 

I'm using your plugin with the obvious assumption that the user needs to have a working internet connection for ads to function properly. 

I'm wondering how should I handle the case of a lost internet connection during gameplay. 

1. Should I check for internet connection before every interstitial and rewarded ad request?
2. Will I get any kind of information about lost internet connectiom from OnInterstitialLoadFailed and OnRewardedAdLoadFailed events?

**Comment by christophercong** [comment]
Hello,

1. No need to. Our SDK is aware of the internet connection status and will handle disconnects and reconnects accordingly.
2. The plugin will return those events on lost internet connections and we recommend re-trying the ad load request after some delay. In a future release, we will provide more info about the event error codes.

**Comment by Heaven31415** [comment]
Thanks for quick response.
