### ISSUE TITLE
Xcode 13 bitcode cannot be reparsed for ad provider lib

### ISSUE THREAD

**Issue by pfay-fc** [AppLovin/AppLovin-MAX-Unity-Plugin#85]
Hi, I'm integrating MAX, I'm on unity plugin version 4.3.10, Android 10.3.4, iOS 10.3.6, Unity 2019.4.21f1, Xcode 12.5

I had a build that was working, but now I can't build on iOS after adding a few more ad providers.

Specifically, I added Fyber, IronSource, UnityAds, and Vungle.

Now I get this error during linking:
```
❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1300.0.29.3.0_0' Reader: '1205.0.22.9_0')', using libLTO version 'LLVM version 12.0.5, (clang-1205.0.22.9)' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe that error is caused because some package was built using xcode 13 (I am on 12.5, and applovin docs say 12.5 is recommended). Here's an [unrelated project's notes on the same error](https://forums.expo.dev/t/eas-ios-build-fail-could-not-reparse-object-file-in-bitcode-bundle-invalid-bitcode-version/57103).

Looking at my podfile install changes from the previous successful build, here are the newly introduced pods:
```
Installing AppLovinMediationFyberAdapter (7.9.0.0)
Installing AppLovinMediationIronSourceAdapter (7.1.11.1.0)
Installing AppLovinMediationUnityAdsAdapter (3.7.5.1)
Installing AppLovinMediationVungleAdapter (6.10.3.0)
Installing Fyber_Marketplace_SDK (7.9.0)
Installing IronSourceSDK (7.1.11.1)
Installing UnityAds (3.7.5)
Installing VungleSDK-iOS (6.10.3)
```

I believe some artifact in one or more of these pods was built erroneously on xcode 13 (or perhaps the wrong version of one of these is being targeted). It could be one of the AppLovin adapters or one of the ad libraries itself.

**Comment by thomasmso** [comment]
Hi @pfay-fc - a lot of mediated SDKs are being compiled with Xcode 13 now, hence your error. Unfortunately there's nothing we can do here. The AppLovin MAX iOS SDK is still compiled with Xcode 12 though.

**Comment by pfay-fc** [comment]
Upgrading to Xcode 13 resolves this as expected.
