### ISSUE TITLE
Banner height does not return safe area?

### ISSUE THREAD

**Issue by revolt3r** [AppLovin/AppLovin-MAX-Unity-Plugin#88]
Documentation doesn't really explain how to use BannerHeight and adjust our UI around that.

Should we move UI by banner height + safe area? Would be cool to have this explained better in the documentation.

Is this the correct way to convert height to pixels? (based on AdMob documentation)
```
public float GetHeightInPixels(float width = -1.0f)
        {
            var heightInUnits = MaxSdkUtils.GetAdaptiveBannerHeight(width);
            return heightInUnits * Mathf.RoundToInt(Screen.dpi / 160);
        }
```

**Comment by santoshbagadi** [comment]
Hi @revolt3r, you can use `MaxSdk.GetBannerLayout(adUnitIdentifier)` to get the absolute position of the banner on screen and adjust your game UI accordingly.

Please note that the banner needs to be displayed on screen to get the actual position on screen.

**Comment by revolt3r** [comment]
Got it, thanks.

In which units is the layout rect returned, is it the same points as MaxSdkUtils.GetAdaptiveBannerHeight()?

**Comment by santoshbagadi** [comment]
Yes, they are both in `dp` on Android.

**Comment by revolt3r** [comment]
Thanks!
