### ISSUE TITLE
The integrated Max SDK is stuck

### ISSUE THREAD

**Issue by GoldWilling** [AppLovin/AppLovin-MAX-Unity-Plugin#89]
An abnormal phenomenon is reported. I use the max unity plugin (4.3.12) integrated advertising SDK. When I use the ipad Mini to test the advertising, I select the applovin advertiser. The incentive video has been loaded successfully. Click from the app to play the advertising. At this time, the app will get stuck. This phenomenon only occurs on this ipad Mini.

Check code, which occurs in MAUnityAdManager.m:

- (void)showRewardedAdWithAdUnitIdentifier:(NSString *)adUnitIdentifier placement:(NSString *)placement
{
    MARewardedAd *rewardedAd = [self retrieveRewardedAdForAdUnitIdentifier: adUnitIdentifier];
    [rewardedAd showAdForPlacement: placement];
}

Version used:

1. MAX Unity Plugin 4.3.12

2. Xcode 12.5

3. Unity2018.4.36

IPad version: ipad Mini (5th generation), ios14.5.

**Comment by christophercong** [comment]
Hello,

Is your app with this behavior live where we can test? If not, please provide our [SDK's verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK) so we can look into it further.
