### ISSUE TITLE
SetHasUserConsent and SetIsAgeRestrictedUser usage

### ISSUE THREAD

**Issue by Heaven31415** [AppLovin/AppLovin-MAX-Unity-Plugin#9]
Hi. 

I just want to clarify something about **SetHasUserConsent** and **SetIsAgeRestrictedUser** usage.

Should I call those methods on **every** game run (before / during max initialization) to tell your SDK about information sharing consent and age restriction?

I'm asking because I'm maintaining some old scripts which are only calling those methods on first game run (and when consent and age restriction changes), which seems to be a bug (those methods aren't called again when you for example enter game second time).

**Comment by christophercong** [comment]
Hello,

No need to call those methods on **every** game run (except for the first run obviously) if the consent or age restriction information has **not** changed. The SDK does persist the changes to those information.

You have the recommended way of using those APIs :).
