### ISSUE TITLE
The current plugin version is incompatible with the Admob Adapter

### ISSUE THREAD

**Issue by revolt3r** [AppLovin/AppLovin-MAX-Unity-Plugin#90]
This error happens randomly during the build. Most of the times there is no error and the build works, and sometimes it crashes on start after this error.
I'm assuming it might be something related to the order of execution. You can find my versions below

![image](https://user-images.githubusercontent.com/11783754/143841378-2acc3821-1569-435d-8edf-68399c47d8c0.png)

![image](https://user-images.githubusercontent.com/11783754/143841492-b3def2e7-4873-465e-b87d-e861799f6757.png)

**Comment by santoshbagadi** [comment]
Hi @revolt3r , it looks like our plugin is somehow not able to find the `AppLovinSettings.asset` file which we try to find using the asset label. This might change when the plugin folder has changed, and the project needs to be re-compiled for us to add the new labels.

Do you see this error after changing the plugin folder? Do you mind sharing the contents of `AppLovinSettings.asset.meta` file to make sure that the label is being added correctly.

**Comment by revolt3r** [comment]
@santoshbagadi, I applied this change and moved it to Plugins folder. Even though it worked on Windows, it seems that this change breaks it on MacOs instead

 https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/33#issuecomment-967290736

**Comment by santoshbagadi** [comment]
It looks like once the project is opened in MacOS, it has not recompiled for us to add the new label with the platform specific path separator. Once the new label is added and is checked into your VCS, you should be able to smoothly transition between MacOS and Windows without any issues.

We use the [`InitializeOnLoadAttribute`](https://docs.unity3d.com/ScriptReference/InitializeOnLoadAttribute.html) to apply the necessary labels. You can get the Unity project to recompile by making a small change to your scripts once it is open in MacOS. Please let me know if you still see the issue after the new labels are added to the project.

**Comment by revolt3r** [comment]
@santoshbagadi I moved the folder back for now and it seems to have fixed the issue. Thanks!
