### ISSUE TITLE
AppLovin crash 

### ISSUE THREAD

**Issue by thangnt93** [AppLovin/AppLovin-MAX-Unity-Plugin#91]
Hi! 
Crash log in firebase 
Platform: Android
android 10.3.5

Log:
Caused by java.util.concurrent.RejectedExecutionException
Task com.mbridge.msdk.foundation.same.net.j$1@5819fc6 rejected from java.util.concurrent.ThreadPoolExecutor@48ac639[Running, pool size = 30, active threads = 30, queued tasks = 60, completed tasks = 16]

java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2086)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1394)
com.mbridge.msdk.foundation.same.net.j.a (RequestQueue.java:71)
com.mbridge.msdk.foundation.same.net.n.a (VolleyManager.java:26)
com.mbridge.msdk.foundation.same.net.h.b.b (CommonAsyncHttpRequest.java:226)
com.mbridge.msdk.foundation.same.net.h.b.c (CommonAsyncHttpRequest.java:162)
com.mbridge.msdk.foundation.same.report.d.a (ReportUtil.java:730)
com.mbridge.msdk.system.a$1.onActivityStopped (MBridgeSDKImpl.java:92)
android.app.Application.dispatchActivityStopped (Application.java:515)
android.app.Activity.onStop (Activity.java:2648)
com.unity3d.player.UnityPlayerActivity.onStop (UnityPlayerActivity.java:78)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1476)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by thomasmso** [comment]
This crash is from Mintegral's SDK, could you make sure you're on the latest adapter v15.7.61.0?

**Comment by thangnt93** [comment]
> This crash is from Mintegral's SDK, could you make sure you're on the latest adapter v15.7.61.0?

Yes. I'm using that version

**Comment by thomasmso** [comment]
We'll notify Mintegral team to release a new SDK with a fix.

**Comment by thangnt93** [comment]
> 

thank you!

**Comment by thangnt93** [comment]
![Capture](https://user-images.githubusercontent.com/13900319/144697449-893b9497-1c52-41aa-bd46-859ff9c74d6f.PNG)
my google console show error

**Comment by thomasmso** [comment]
We'll report to the Mintegral team as well, ty

**Comment by KimihideIiizumi** [comment]
Hi.
Our team has also stopped updating the Mintegral version since this happened.
Has this issue been resolved?
