### ISSUE TITLE
Close button stoped working if lock and unlock device

### ISSUE THREAD

**Issue by vizgl** [AppLovin/AppLovin-MAX-Unity-Plugin#93]
Using ApplovinMax 4.3.12 with networks: FAN, Admob, IronSource, UnityAds.

Close button stoped working when I lock and unlock device while ad showing. Got same behaviour on inter and rewarded ads.
Tested on Admob, Applovin ads.
Not tested on others.

Tested device: Motorola g10(XT2127-2)
Mode: landscape
Unity version: 2020.3.24

P.S. also received ANRs on android with the same trace log from bugsnag.
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 7. Wait queue head age: 5092.6ms.)

ERROR  Error Occurred
21s before |   | STATEUnityPlayerActivity#onSaveInstanceState()previousonStop()
21s before |   | STATEUnityPlayerActivity#onStop()previousonResume()
21s before |   | STATEAppLovinFullscreenActivity#onResume()previousonStart()
21s before |   | STATEAppLovinFullscreenActivity#onStart()previousonCreate()
21s before |   | STATEAppLovinFullscreenActivity#onCreate()hasBundlefalsepreviousonPause()
21s before |   | STATEUnityPlayerActivity#onPause()previousonResume()
21s before |   | LOGLogmessage[InterstitialAd] Show, Mediation: AppLovin

For example on this screenshot both close buttons don't work
![Screenshot_20211205-022558](https://user-images.githubusercontent.com/15825145/144728832-43eee83c-7f54-49fd-8d6d-7ddc9a613320.png)
:

**Comment by vizgl** [comment]
The problem is in the android home bar on the right side (white rect). Home bar is overlapping close buttons and players can't close  ads.

**Comment by thomasmso** [comment]
The screenshot shows our close button visible on the screen. Do you mind taking a photo of the device/ad? Also, to confirm, what device are you on?

**Comment by vizgl** [comment]
> The screenshot shows our close button visible on the screen. Do you mind taking a photo of the device/ad? Also, to confirm, what device are you on?

Close button is visible but Home bar is overlaping it. At this case, home bar will catch all input and clsoe button will not working.
![image](https://user-images.githubusercontent.com/15825145/144750296-72e35b91-776c-408b-8a8c-3e2de2594b8d.png)

My game is for landscape mode, but if I hide game or lock phone, then home bar moved from bottom position to right side.
So this bug is related to the android os, not for max
