### ISSUE TITLE
IOS/Audience network - Link error

### ISSUE THREAD

**Issue by paradizIscool** [AppLovin/AppLovin-MAX-Unity-Plugin#94]
Hi,

I have an issue with AudienceNetwork.

ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
ld: warning: Could not find or use auto-linked framework 'DataDetection'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork)
     

Use demo app, update applovin sdk, set ids, add AudienceNetwork with the manager.

project.AddBuildProperty(mainTargetGuid, "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES", "YES");
is being called

xcode 12.5
unity 2020.3.23
Mac os 11.6.
![Capture d’écran 2021-12-09 à 12 15 05](https://user-images.githubusercontent.com/11227595/145386527-184066de-4b56-4b8f-aca8-49143401d610.png)

Best regards,
Lionel

**Comment by santoshbagadi** [comment]
Hi @paradizIscool , the latest [Facebook Audience Network SDK (6.9.0+) requires Xcode 13](https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/changelog) to build apps. Please update to the latest Xcode to fix the issue.

**Comment by paradizIscool** [comment]
Thanks

**Comment by beingSherlock** [comment]
Ld /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -L/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos -L/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Libraries -L/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Libraries/Plugins/iOS/Firebase -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/FirebaseCore -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/FirebaseCoreDiagnostics -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/FirebaseInstallations -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/GoogleDataTransport -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/GoogleUtilities -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/nanopb -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/FBAudienceNetwork/Static -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/FirebaseAnalytics/Frameworks -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/GoogleAppMeasurement/Frameworks -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/GoogleUserMessagingPlatform/Frameworks/Release -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/IronSourceAdMobAdapter/ISAdMobAdapter -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/IronSourceFacebookAdapter/ISFacebookAdapter -F/Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Pods/IronSourceSDK/IronSource -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FBAudienceNetwork -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/GoogleMobileAds -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/ISAdMobAdapter -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/ISFacebookAdapter -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/IronSource -F/Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/UserMessagingPlatform -filelist /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lc++ -lsqlite3 -lxml2 -lz -framework AVFoundation -framework AdSupport -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework CoreImage -framework CoreLocation -framework CoreMedia -framework CoreTelephony -framework CoreVideo -framework FBAudienceNetwork -framework FBLPromises -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstallations -framework Foundation -framework GoogleAppMeasurement -framework GoogleDataTransport -framework GoogleMobileAds -framework GoogleUtilities -framework ISAdMobAdapter -framework ISFacebookAdapter -framework IronSource -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UserMessagingPlatform -framework WebKit -framework nanopb -weak_framework AdSupport -weak_framework CFNetwork -weak_framework CoreMotion -weak_framework CoreTelephony -weak_framework JavaScriptCore -weak_framework LocalAuthentication -weak_framework SafariServices -weak_framework SystemConfiguration -weak_framework VideoToolbox -weak_framework WebKit -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Metal -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Libraries/baselib.a -lFirebaseCppAnalytics -lFirebaseCppApp -framework GameKit -framework StoreKit -weak_framework GameController -framework Pods_UnityFramework -Xlinker -dependency_info -Xlinker /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/sapteshchaubal/Library/Developer/Xcode/DerivedData/Unity-iPhone-ecydgufgxmiensdiyqliwbqysoeu/Build/Products/ReleaseForRunning-iphoneos/UnityFramework.framework/UnityFramework

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/sapteshchaubal/CosmicSentry/CosmicSentry_iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftCoreAudio'
ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftAVFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCoreMedia'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftsimd'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftAVFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftAVFoundation_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftAVFoundation_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCoreMIDI", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMIDI_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftsimd", referenced from:
      __swift_FORCE_LOAD_$_swiftsimd_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftsimd_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreImage_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftFoundation_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_FBAudienceNetwork)
  "_swift_getInitializedObjCClass", referenced from:
      static FBAudienceNetwork.FBAdFont.sfuiTextRegular(withSize: CoreGraphics.CGFloat) -> __C.UIFont in FBAudienceNetwork(FBAudienceNetwork.o)
      static FBAudienceNetwork.FBAdFont.sfuiDisplaySemibold(withSize: CoreGraphics.CGFloat) -> __C.UIFont in FBAudienceNetwork(FBAudienceNetwork.o)
      type metadata accessor for FBAudienceNetwork.FBAdFont in FBAudienceNetwork(FBAudienceNetwork.o)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_FBAudienceNetwork)
  "_swift_once", referenced from:
      FBAudienceNetwork.FBAdFont.fontSizeTiny.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.fontSizeExtraSmall.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.fontSizeSmall.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.fontSizeMedium.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.fontSizeLarge.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.fontSizeExtraLarge.unsafeMutableAddressor : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
  "__swift_FORCE_LOAD_$_swiftCoreAudio", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreAudio_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreAudio_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_FBAudienceNetwork)
  "_swift_getObjectType", referenced from:
      FBAudienceNetwork.FBAdFont.init() -> FBAudienceNetwork.FBAdFont in FBAudienceNetwork(FBAudienceNetwork.o)
      FBAudienceNetwork.FBAdFont.__deallocating_deinit in FBAudienceNetwork(FBAudienceNetwork.o)
  "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
      __swift_FORCE_LOAD_$_swiftUIKit_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_FBAudienceNetwork)
  "value witness table for Builtin.UnknownObject", referenced from:
      full type metadata for FBAudienceNetwork.FBAdFont in FBAudienceNetwork(FBAudienceNetwork.o)
  "_swift_getObjCClassMetadata", referenced from:
      @objc static FBAudienceNetwork.FBAdFont.sfuiTextRegular(withSize: CoreGraphics.CGFloat) -> __C.UIFont in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.sfuiDisplaySemibold(withSize: CoreGraphics.CGFloat) -> __C.UIFont in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.fontSizeTiny.getter : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.fontSizeExtraSmall.getter : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.fontSizeSmall.getter : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.fontSizeMedium.getter : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      @objc static FBAudienceNetwork.FBAdFont.fontSizeLarge.getter : CoreGraphics.CGFloat in FBAudienceNetwork(FBAudienceNetwork.o)
      ...
  "__swift_FORCE_LOAD_$_swiftCoreMedia", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMedia_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMedia_$_FBAudienceNetwork)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Using Xcode Latest version, ironsource latest version, have tried adding dummy swift file into project also have added search entries into search library
