### ISSUE TITLE
IOS/Audience network - Runtime error

### ISSUE THREAD

**Issue by paradizIscool** [AppLovin/AppLovin-MAX-Unity-Plugin#95]
Hi,

I have an issue with Ogury Presage, at launch.

/var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Ogury.framework/OMSDK_Ogury
  Referenced from: /private/var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
2021-12-09 17:34:11.800666+0100 MaxDemoUnity[2643:1253365] Error loading /var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Ogury.framework/OMSDK_Ogury
  Referenced from: /private/var/containers/Bundle/Application/A9CC60C3-533F-49A8-8418-0C5EC5357F55/MaxDemoUnity.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
  
Use demo app, update applovin sdk, set ids, add Ogury with the manager.

Seems there is no particular post process for this one

xcode 13.1
unity 2020.3.23
Mac os 11.6.

Best regards,
Lionel

**Comment by thomasmso** [comment]
Hi - thanks for bringing this to our attention. Do you mind updating the appropriate path to `dynamicLibraryPathsToEmbed ` in `MaxPostProcessBuildiOS.cs`? We'll update our next plugin accordingly. Let me know if that works, thank you!

**Comment by paradizIscool** [comment]
It's working with

`dynamicLibraryPathsToEmbed.Add(Path.Combine("Pods/", "OguryAds/OguryAds/OMSDK_Ogury.xcframework/"));`

thanks
